# -*- coding: utf-8 -*-
# Ibn Kathir: (1) el relato de Ibn Abbas sobre los reyes que cambiaron la Torá y el Evangelio (57:27);
# (2) casos en que cita a un compañero o a sus discípulos, incluso con cadena auténtica, y él opina lo contrario.
# [[k:...]] naranja = frase clave; [[a:...]] azul = matiz o lo que juega en contra.
import v1cards_data
from hcards_data import HCARDS
v1 = {c['id']: c for c in v1cards_data.V1CARDS}; hc = {c['id']: c for c in HCARDS}
K = "https://quran.ksu.edu.sa/tafseer/katheer/"
KSU = "quran.ksu.edu.sa (Universidad Rey Saúd)"
T1 = "Otra armonización posible"
T2 = "Ibn Kathir cita y opina distinto"
KCARDS = [
 dict(id="K01", tag=T1, chip="Tipo: relato de Ibn Abbas (mawquf)", specs=["K01a", "K01b"],
  title="Ibn Abbas: «hubo reyes después de Jesús que cambiaron la Torá y el Evangelio, y había entre ellos creyentes que leían la Torá y el Evangelio»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 57:27 (relato de al-Nasaʾi e Ibn Jarir); y Sunan al-Nasaʾi 5400, con sus calificaciones",
  ar_ref="تفسير ابن كثير، الحديد ٢٧؛ سنن النسائي ٥٤٠٠", site=KSU + " y hadithunlocked.com", url=K + "sura57-aya27.html",
  es=["Dijeron Ibn Jarir y Abu ʿAbd al-Rahman al-Nasaʾi —la redacción es de este—: Nos informó al-Husayn ibn Hurayth: nos contó al-Fadl ibn Musa, de Sufyan ibn Saʿid, de ʿAtaʾ ibn al-Saʾib, de Saʿid ibn Jubayr, de Ibn Abbas —Dios esté complacido con ambos—, que dijo: «[[k:Hubo reyes después de Jesús]] —la paz sea con él— [[k:que cambiaron la Torá y el Evangelio]], [[k:y había entre ellos creyentes que leían la Torá y el Evangelio]]. Se dijo a sus reyes: “No encontramos insulto más duro que el que nos lanzan estos: leen «Quienes no juzgan según lo que Dios reveló, esos son los incrédulos» (5:44) y estos versículos, además de lo que nos reprochan de nuestros actos en su lectura. Llámalos, que lean como leemos nosotros y crean como creemos nosotros”. Los llamó, los reunió y les dio a elegir entre la muerte [[k:o dejar de leer la Torá y el Evangelio, salvo lo que habían cambiado de ellos]]. Dijeron: “¿Qué queréis con eso? Dejadnos”. Un grupo dijo: “Construidnos una columna, subidnos a ella y dadnos algo con que subir la comida y la bebida, y no volveremos a vosotros”. Otro dijo: “Dejadnos recorrer la tierra, vagar y beber como beben las fieras; si nos encontráis en vuestra tierra, matadnos”. Y otro dijo: “Construidnos casas en los desiertos; cavaremos pozos y cultivaremos legumbres, y no volveremos a vosotros ni pasaremos junto a vosotros”. Y no había tribu que no tuviera un pariente entre ellos. Así lo hicieron, y Dios reveló: «Y el monacato lo inventaron ellos; no se lo prescribimos, sino buscando la complacencia de Dios, y no lo observaron como debían» (57:27). Los otros dijeron: “Hagamos devoción como fulano, recorramos la tierra como fulano, tomemos casas como fulano”, siguiendo en su politeísmo, sin saber de la fe de aquellos a quienes imitaban. Cuando fue enviado el Profeta ﷺ y quedaban pocos de ellos, bajó un hombre de su ermita, vino un errante de su viaje y el del monasterio de su monasterio, y creyeron en él. Y Dios dijo: «Vosotros que creéis, temed a Dios y creed en Su Mensajero; os dará doble parte de Su misericordia» (57:28): doble recompensa, por su fe en Jesús, hijo de María, en la Torá y el Evangelio, y por su fe en Muhammad ﷺ. «Y os dará una luz con la que caminéis»: el Corán. «Para que sepa la Gente del Libro» —los que se asemejan a vosotros— «que no tienen poder sobre nada del favor de Dios…» (57:29)». [[a:Este relato tiene algo de extraño]], y la explicación de estos dos últimos versículos vendrá de otro modo; y Dios sabe más.",
      "[al-Nasaʾi 5400] Hubo reyes después de Jesús, hijo de María —la bendición y la paz sean con él—, [[k:que cambiaron la Torá y el Evangelio]], [[k:y había entre ellos creyentes que leían la Torá]]. Se dijo a sus reyes: «No encontramos insulto más duro que el que nos lanzan estos: leen “Quienes no juzgan según lo que Dios reveló, esos son los incrédulos” y estos versículos, además de lo que nos reprochan de nuestros actos en su lectura. Llámalos, que lean como leemos nosotros y crean como creemos nosotros». Los llamó, los reunió…",
      "Calificaciones de los especialistas: [[a:débil (ʿAli Zaʾi)]]; [[k:su cadena es auténtica, como dicho del compañero (al-Albani)]]."],
  prueba="Otra forma de armonizar las dos narraciones de Ibn Abbas. Aquí el cambio lo hacen unos reyes concretos, después de Jesús, en sus ejemplares, mientras había creyentes que seguían leyendo la Torá y el Evangelio; el rey les exige dejar de leerlos «salvo lo que habían cambiado de ellos». Es una alteración parcial, de un grupo, en ciertas copias, con el texto auténtico conservado por otros. Encaja con «cambiaron parte de los libros de Dios» (Bujari 7523, V02) y con «nadie elimina el texto de un libro de Dios»: nadie lo hace desaparecer del todo.",
  ojo="Tres cautelas. Ibn Kathir dice de este relato que «tiene algo de extraño» (en azul). Las calificaciones están divididas: al-Albani, «cadena auténtica, como dicho de Ibn Abbas»; ʿAli Zaʾi, «débil». Y aquí sí se habla de un cambio en el texto hecho por esos reyes: no lo uses para decir que Ibn Abbas solo hablaba de interpretación, sino de un cambio parcial, de un grupo, con ejemplares auténticos en manos de creyentes."),

 dict(id="K02", tag=T2, chip="Tipo: Ibn Abbas (con cadena de al-Bujari) frente a la mayoría", specs=["K02"],
  title="El homicida y el arrepentimiento (4:93): Ibn Abbas, por al-Bujari, dice que no; Ibn Kathir sigue a la mayoría",
  ref="Ibn Kathir, Tafsir, sobre el Corán 4:93", ar_ref="تفسير ابن كثير، النساء ٩٣", site=KSU, url=K + "sura4-aya93.html",
  es=["Ibn Abbas —Dios esté complacido con ambos— [[k:sostenía que no hay arrepentimiento para quien mata a un creyente a propósito]]. Dijo al-Bujari: Nos contó Adam: nos contó Shuʿba: nos contó Mughira ibn al-Nuʿman: oí a Ibn Jubayr decir: La gente de Kufa discrepó sobre ella; viajé a ver a Ibn Abbas, le pregunté, y dijo: Este versículo, «Quien mate a un creyente a propósito, su recompensa es el Infierno, eternamente», fue revelado y [[k:es lo último que se reveló, y nada lo abrogó]].",
      "[[k:Y lo que sostiene la mayoría de los antepasados de la comunidad y de los posteriores es que el homicida tiene arrepentimiento]] entre él y su Señor: si se arrepiente, vuelve a Dios, se humilla y obra bien, Dios cambia sus malas obras por buenas, compensa al asesinado por la injusticia y lo deja satisfecho en su reclamación. Dijo Dios: «Y los que no invocan a otro dios junto a Dios, ni matan a la persona que Dios ha prohibido salvo con derecho, ni fornican… salvo quien se arrepienta, crea y obre bien: a esos Dios les cambiará sus malas obras por buenas» (25:68–70). Y esta es una noticia que no se puede abrogar. [[k:Y aplicarla a los politeístas, y aplicar este versículo a los creyentes, va contra el sentido aparente]] y necesita una prueba; y Dios sabe más."],
  prueba="Ibn Kathir trae la opinión de Ibn Abbas con la cadena de al-Bujari («es lo último que se reveló, y nada lo abrogó») y se queda con lo contrario, la opinión de la mayoría: el homicida sí tiene arrepentimiento. Incluso rechaza cómo armonizaba Ibn Abbas los versículos: «va contra el sentido aparente».",
  ojo="«Aplicarla a los politeístas» es la lectura de Ibn Abbas de 25:68, que Ibn Kathir recoge en la misma página («fue revelado sobre la gente del politeísmo»)."),

 dict(id="K03", tag=T2, chip="Tipo: Ibn Abbas y sus discípulos frente a al-Hasan", specs=["K03"],
  title="Adán, Eva y «ʿAbd al-Harith» (7:190): lo recibieron de Ibn Abbas sus discípulos… «nosotros seguimos a al-Hasan al-Basri»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 7:189–190", ar_ref="تفسير ابن كثير، الأعراف ١٨٩–١٩٠", site=KSU, url=K + "sura7-aya190.html",
  es=["[[k:Y recibieron este relato de Ibn Abbas un grupo de sus discípulos]], como Mujahid, Saʿid ibn Jubayr e ʿIkrima; y de la segunda generación, Qatada, al-Suddi y no pocos de los antepasados, un grupo de los posteriores y, de los comentaristas tardíos, grupos incontables. Y parece —y Dios sabe más— que [[k:su origen está tomado de la Gente del Libro]], porque Ibn Abbas lo transmitió de Ubayy ibn Kaʿb, como lo transmitió Ibn Abi Hatim:",
      "…Y este relato, ¿es del segundo tipo [lo que sabemos que es falso] o del tercero [lo que ni se cree ni se desmiente]? Hay que verlo. Quien lo transmitió de entre los compañeros o los seguidores lo consideraba del tercer tipo; [[k:en cambio, nosotros seguimos la opinión de al-Hasan al-Basri]] —Dios tenga misericordia de él— en esto, y Dios sabe más: [[k:que lo que se quiere decir en este pasaje no es Adán y Eva]], sino los politeístas de su descendencia; por eso dijo Dios: «Dios está muy por encima de lo que asocian»."],
  prueba="Ibn Kathir reconoce que la interpretación de Ibn Abbas (Adán y Eva llaman a su hijo «ʿAbd al-Harith») la recibieron sus discípulos y «grupos incontables» de comentaristas. Y aun así: «nosotros seguimos la opinión de al-Hasan al-Basri». Cita a Ibn Abbas y a toda su escuela, y opina lo contrario.",
  ojo="Su razón es que cree que el relato viene de la Gente del Libro. Pero es una valoración suya: no niega que Ibn Abbas lo dijera."),

 dict(id="K04", tag=T2, chip="Tipo: cadena «auténtica» y aun así rechazada", specs=["K04"],
  title="El hijo sacrificado (37:107): «esto es auténtico hasta Ibn Masʿud» que es Isaac… y concluye que es Ismael, «lo correcto y lo seguro»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 37:101–113", ar_ref="تفسير ابن كثير، الصافات ١٠١–١١٣", site=KSU, url=K + "sura37-aya107.html",
  es=["Shuʿba transmitió, de Abu Ishaq, de Abu al-Ahwas: Un hombre presumió ante Ibn Masʿud diciendo: «Soy fulano, hijo de fulano, hijo de los nobles ancianos». ʿAbd Allah le dijo: «Ese es José, hijo de Jacob, hijo de Isaac, el sacrificado de Dios, hijo de Abraham, el amigo de Dios». [[k:Y esto es auténtico hasta Ibn Masʿud]]; [[k:y así transmitió ʿIkrima, de Ibn Abbas, que era Isaac]].",
      "[[k:Y todas estas opiniones —y Dios sabe más— están tomadas de Kaʿb al-Ahbar]]: cuando se hizo musulmán en tiempos de Umar, se puso a contarle a Umar cosas de sus libros, y a veces Umar le escuchaba; así que la gente se permitió escuchar lo que tenía y transmitieron de él lo malo y lo bueno. [[a:Y esta comunidad —y Dios sabe más— no necesita ni una letra de lo que él tenía]].",
      "[Mención de los relatos que dicen que es Ismael —la paz sea con él—, [[k:que es lo correcto y lo seguro]]]. [[k:Ya se ha mencionado la transmisión de Ibn Abbas de que es Isaac]]. Y Saʿid ibn Jubayr, ʿAmir al-Shaʿbi, Yusuf ibn Mihran, Mujahid, ʿAtaʾ y otros dijeron, de Ibn Abbas: es Ismael —la paz sea con él—."],
  prueba="Es exactamente el caso: Ibn Kathir verifica la cadena («esto es auténtico hasta Ibn Masʿud»), anota que una transmisión de Ibn Abbas dice lo mismo, y aun así concluye lo contrario: el sacrificado es Ismael, «lo correcto y lo seguro». Que dé por auténtica una atribución no significa que la comparta; y que no la comparta no significa que la atribución sea falsa.",
  ojo="De Ibn Abbas hay dos transmisiones (Isaac e Ismael), e Ibn Kathir se queda con una. La frase «esta comunidad no necesita ni una letra de lo que él tenía» (en azul) es sobre los relatos de Kaʿb al-Ahbar: no la saques de contexto, pero tenla presente."),

 dict(id="K05", tag=T2, chip="Tipo: Ibn Abbas y otros compañeros frente a la mayoría", specs=["K05"],
  title="El matrimonio temporal (4:24): «se ha transmitido de Ibn Abbas y de un grupo de compañeros»… «pero la mayoría sostiene lo contrario»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 4:24", ar_ref="تفسير ابن كثير، النساء ٢٤", site=KSU, url=K + "sura4-aya24.html",
  es=["[[k:Y se ha transmitido de Ibn Abbas y de un grupo de compañeros la opinión de que es lícito en caso de necesidad]], y es una de las transmisiones del imam Ahmad ibn Hanbal —Dios tenga misericordia de ellos—. Y Ibn Abbas, Ubayy ibn Kaʿb, Saʿid ibn Jubayr y al-Suddi leían: «Y por aquellas de quienes gozáis hasta un plazo fijado, dadles su retribución como obligación». Y Mujahid dijo: fue revelado sobre el matrimonio temporal. [[k:Pero la mayoría sostiene lo contrario]], y lo fundamental es lo que consta en los dos Sahih…"],
  prueba="Otro caso: Ibn Kathir recoge la opinión de Ibn Abbas y de otros compañeros, e incluso su lectura del versículo, y se queda con la de la mayoría."),

 dict(id="K06", tag=T2, chip="Tipo: la aplicación al vídeo", specs=["V01", "H05", "H18"],
  title="En la misma página (3:78): atribuye la frase a Ibn Abbas, cita a Wahb… y da su propia opinión, distinta",
  ref="Ibn Kathir, Tafsir, sobre el Corán 3:78", ar_ref="تفسير ابن كثير، آل عمران ٧٨", site=KSU, url=K + "sura3-aya78.html",
  es=v1['V01']['es'] + hc['H05']['es'] + hc['H18']['es'],
  prueba="La aplicación al vídeo. En 3:78, Ibn Kathir pone «nadie elimina el texto de un libro de Dios» bajo «así lo transmitió al-Bujari de Ibn Abbas», cita a Wahb («no se ha cambiado ni una letra») y luego da su opinión: en los ejemplares de su época sí han entrado cambios. Que Ibn Kathir piense otra cosa no quita que atribuya la frase a Ibn Abbas. Usar la opinión de Ibn Kathir contra Ibn Abbas es confundir lo que Ibn Kathir transmite con lo que Ibn Kathir opina.",
  ojo="Ibn Kathir distingue (en azul): los libros tal como Dios los reveló están preservados; lo que critica son los ejemplares y traducciones de su tiempo."),
]
for c in KCARDS:
    c.setdefault('uso', c['tag'])
