# -*- coding: utf-8 -*-
# Tarjetas de la pestaña Historia. [[k:...]] = naranja (frase clave); [[a:...]] = azul (matiz o lo que juega en contra).
# Campos extra: year (fecha de muerte), who, postura (columna «Postura» de la tabla).

KSU_T = "https://quran.ksu.edu.sa/tafseer/tabary/"
KSU_K = "https://quran.ksu.edu.sa/tafseer/katheer/sura3-aya78.html"
F13 = "https://www.islamweb.net/ar/library/content/52/13832/"
KSU = "quran.ksu.edu.sa (Universidad Rey Saúd)"
IW = "islamweb.net"

HCARDS = [
 dict(id="H01", year="23 H", who="Umar, según al-Shaʿbi", postura="Positiva",
  title="«Me maravillaba de cómo la Torá confirma el Corán, y el Corán la Torá»",
  ref="al-Tabari, Tafsir, sobre el Corán 2:97, n.º 1608 y 1609", ar_ref="تفسير الطبري، البقرة ٩٧، رقم ١٦٠٨–١٦٠٩", site=KSU, url=KSU_T+"sura2-aya97.html",
  es=["1608 — Me contó Muhammad ibn al-Muthanna: nos contó Ribʿi ibn ʿUlayya, de Dawud ibn Abi Hind, de al-Shaʿbi, que dijo: Umar acampó en al-Rawhaʾ y vio a unos hombres que se apresuraban hacia unas piedras para rezar junto a ellas. Dijo: «¿Qué hacen estos?». Dijeron: «Dicen que el Mensajero de Dios ﷺ rezó aquí». Le desagradó y dijo: «[No es más que esto:] al Mensajero de Dios ﷺ le llegó la hora de la oración en un valle, rezó y luego partió y lo dejó». Luego se puso a contarles y dijo: «[[k:Yo asistía a los judíos el día de su estudio, y me maravillaba de cómo la Torá confirma el Furqán [el Corán], y de cómo el Furqán confirma la Torá]]».",
      "1609 — Me contó Yaʿqub ibn Ibrahim: nos contó Ibn ʿUlayya, de Dawud, de al-Shaʿbi, que dijo: dijo Umar: «[[k:Yo era un hombre que frecuentaba a los judíos el día de su estudio]]»; y mencionó algo parecido al relato de Ribʿi."],
  prueba="Es el recuerdo más antiguo que se conserva de un compañero ante la Torá que se leía en Medina: Umar la escuchaba y veía que confirmaba el Corán.",
  ojo="Al-Shaʿbi no conoció a Umar: la cadena es sólida hasta al-Shaʿbi y está cortada después (mursal). Detalles en el Vídeo 2, bloque 8, y en IH16 e IH17."),

 dict(id="H02b", year="68 H", who="Ibn Abbas", postura="Interpretación + libros añadidos",
  title="La otra narración: «cambiaron el Libro de Dios… y escribieron con sus manos»",
  ref="Sahih al-Bujari 7363 (Kitab al-Iʿtisam)", ar_ref="صحيح البخاري ٧٣٦٣", site="hadithunlocked.com", url="https://hadithunlocked.com/bukhari:7363",
  es=["«¿Cómo preguntáis a la Gente del Libro por algo, cuando vuestro Libro, revelado al Mensajero de Dios ﷺ, es el más reciente? Lo recitáis puro, sin mezcla. Y [vuestro Libro] os ha contado que la Gente del Libro [[k:cambió el Libro de Dios y lo alteró]], [[k:y escribieron con sus manos el libro y dijeron: “Esto viene de Dios”]], para venderlo a bajo precio. ¿No os impide el saber que os ha llegado preguntarles? No, por Dios: no hemos visto a ninguno de ellos preguntaros por lo que se os ha revelado.»"],
  prueba="Es la narración que usa Tibyanan, y es real. Es palabra de Ibn Abbas (mawquf) y parafrasea el Corán 2:79: «¡ay de quienes escriben el libro con sus manos y luego dicen: esto viene de Dios!».",
  ojo="Hay que mostrarla entera. Junto con la glosa de Ibn Atiyya (H02a) da la postura de la tabla: interpretación + libros añadidos. Cómo se armonizan las dos: IH09 y Vídeo 1, bloque 6."),

 dict(id="H03", year="90 H", who="Abu al-ʿAliya", postura="Cambio local",
  title="«Fueron a la descripción de Muhammad en su libro y la desplazaron de su lugar»",
  ref="al-Tabari, Tafsir, sobre el Corán 2:79, n.º 1394", ar_ref="تفسير الطبري، البقرة ٧٩، رقم ١٣٩٤", site=KSU, url=KSU_T+"sura2-aya79.html",
  es=["1394 — Me contó al-Muthanna: nos contó Adam: nos contó Abu Jaʿfar, de al-Rabiʿ, de Abu al-ʿAliya, sobre Su palabra «¡Ay de quienes escriben el libro con sus manos y luego dicen: esto viene de Dios, para venderlo a bajo precio!»: dijo: «[[k:Fueron a la descripción de Muhammad ﷺ que Dios había revelado en su libro y la desplazaron de su lugar]], buscando con ello un bien de esta vida». Y dijo [Dios]: «¡Ay de ellos por lo que escribieron sus manos, y ay de ellos por lo que ganan!»."],
  prueba="Voz temprana de un cambio concreto: la descripción de Muhammad. No dice que toda la Torá esté falsificada.",
  ojo="Este texto juega en contra de la versión fuerte («nadie habló de cambios en el texto»). La tesis que aguanta es «nadie habla de falsificación total en los dos primeros siglos»."),

 dict(id="H04", year="104 H", who="Mujahid", postura="Ambiguo",
  title="«Los que la tergiversan y los que la ocultan son sus sabios»",
  ref="al-Tabari, Tafsir, sobre el Corán 2:75, n.º 1328", ar_ref="تفسير الطبري، البقرة ٧٥، رقم ١٣٢٨", site=KSU, url=KSU_T+"sura2-aya75.html",
  es=["1328 — Me lo contó Muhammad ibn ʿAmr: nos contó Abu ʿAsim: nos contó ʿIsa, de Ibn Abi Najih, de Mujahid, sobre la palabra de Dios «¿Esperáis que os crean, cuando un grupo de ellos escuchaba la palabra de Dios y luego la tergiversaba después de haberla entendido, a sabiendas?»: [[k:los que la tergiversan y los que la ocultan son sus sabios]]."],
  prueba="Mujahid (m. 104 H), alumno de Ibn Abbas, dice quién tergiversa (los sabios) y lo une a ocultar, pero no dice cómo. Por eso la tabla lo marca como ambiguo."),

 dict(id="H05", year="c. 114 H", who="Wahb ibn Munabbih", postura="Interpretación + libros añadidos",
  title="«No se ha cambiado ni una letra»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 3:78 (de Ibn Abi Hatim)", ar_ref="تفسير ابن كثير، آل عمران ٧٨", site=KSU, url=KSU_K,
  es=["Y dijo Wahb ibn Munabbih: «[[k:La Torá y el Evangelio, tal como Dios los reveló, no han sido cambiados en una sola letra]]; [[k:pero extravían [a la gente] con la tergiversación y la interpretación, y con libros que escribían ellos mismos]], “y dicen: viene de Dios, y no viene de Dios”. [[k:En cuanto a los libros de Dios, están preservados y no cambian]]». Lo transmitió Ibn Abi Hatim."],
  prueba="Wahb (m. c. 114 H), alumno de Ibn Abbas y de los que más sabían de la Torá: ni una letra cambiada; el extravío viene de la interpretación y de libros que ellos escribían.",
  ojo="Ibn Kathir no lo comparte para su propia época; lo explica justo después (H18)."),

 dict(id="H06", year="117 H", who="Qatada", postura="Libros añadidos",
  title="«Escribieron un libro con sus manos… y dijeron: esto viene de Dios»",
  ref="al-Tabari, Tafsir, sobre el Corán 2:79, n.º 1393", ar_ref="تفسير الطبري، البقرة ٧٩، رقم ١٣٩٣", site=KSU, url=KSU_T+"sura2-aya79.html",
  es=["1393 — Nos contó al-Hasan ibn Yahya: nos informó ʿAbd al-Razzaq: nos informó Maʿmar, de Qatada, sobre Su palabra «¡Ay de quienes escriben el libro con sus manos y luego dicen: esto viene de Dios!»: dijo: «[[k:Había gente de los hijos de Israel que escribió un libro con sus manos para aprovecharse de la gente, y dijeron: esto viene de Dios; y no venía de Dios]]»."],
  prueba="Qatada (m. 117 H) lee el Corán 2:79 como un libro nuevo escrito por ellos, no como un cambio dentro del texto de la Torá."),

 dict(id="H08", year="182 H", who="Ibn Zayd", postura="Libro falso junto al verdadero",
  title="Tenían «el Libro de Dios» y «ese otro libro», y sacaban uno u otro según el soborno",
  ref="al-Tabari, Tafsir, sobre el Corán 2:75, n.º 1331", ar_ref="تفسير الطبري، البقرة ٧٥، رقم ١٣٣١", site=KSU, url=KSU_T+"sura2-aya75.html",
  es=["1331 — Nos contó Yunus: nos informó Ibn Wahb: dijo Ibn Zayd, sobre Su palabra «escuchaban la palabra de Dios y luego la tergiversaban»: dijo: «La Torá que Él les reveló: la tergiversaban; [[a:hacían en ella de lo lícito ilícito y de lo ilícito lícito]], de lo verdadero falso y de lo falso verdadero. [[k:Cuando venía a ellos el que tenía razón con un soborno, le sacaban el Libro de Dios; y cuando venía el que no la tenía con un soborno, le sacaban aquel [otro] libro]], y en él tenía razón. Y si venía alguien a preguntarles algo sin derecho ni soborno ni nada, le mandaban lo justo»."],
  prueba="Para Ibn Zayd (m. 182 H) el Libro de Dios seguía en sus manos; junto a él tenían «ese otro libro», que sacaban según el soborno.",
  ojo="También dice que «hacían de lo lícito ilícito» (en azul): es tergiversar el juicio, sin decir que el Libro de Dios desapareciera."),

 dict(id="H09", year="256 H", who="al-Bujari", postura="Interpretación",
  title="«Nadie elimina el texto de un libro de Dios; lo tergiversan interpretándolo»",
  ref="Sahih al-Bujari, Kitab al-Tawhid (texto del capítulo), y Fath al-Bari 13/533", ar_ref="صحيح البخاري، كتاب التوحيد · فتح الباري ١٣/٥٣٣", site=IW, url=F13,
  es=["Capítulo de la palabra de Dios: «Es un Corán glorioso, en una Tabla preservada», y «Por el monte, y por un Libro escrito». Dijo Qatada: «escrito»; «yasṭurūn»: trazan; «en la Madre del Libro»: el conjunto del Libro y su origen; «no pronuncia»: no dice nada sin que se le anote. Y dijo Ibn Abbas: se anota el bien y el mal. «[[k:Yuḥarrifūn: yuzīlūn (tergiversan: eliminan). Y nadie elimina el texto de un libro de entre los libros de Dios, poderoso y majestuoso, sino que lo tergiversan: lo interpretan de una forma que no es su interpretación]]».",
      "Dijo nuestro maestro Ibn al-Mulaqqin en su comentario: «[[k:Esto que dijo es una de las dos opiniones sobre la interpretación de este versículo, y es la que él eligió]] —es decir, al-Bujari—. Muchos de nuestros compañeros han declarado expresamente que los judíos y los cristianos cambiaron la Torá y el Evangelio, y de ello dedujeron que es lícito tratar sus hojas sin respeto; y eso contradice lo que dice aquí al-Bujari». Fin de la cita."],
  prueba="Bujari (m. 256 H) recoge en su Sahih, bajo «y dijo Ibn Abbas», que nadie elimina el texto de los libros de Dios. Sea de Ibn Abbas o suya, Ibn al-Mulaqqin dice que es la opinión que eligió Bujari.",
  ojo="Si la frase es de Ibn Abbas o un añadido de Bujari está discutido: IH01, IH03 e IH08."),

 dict(id="H13b", year="456 H", who="Ibn Hazm (citado por Ibn Hajar)", postura="Texto alterado",
  title="«Nos ha llegado que hay musulmanes que niegan que estén alterados»",
  ref="Ibn Hajar, Fath al-Bari 13/534, citando a Ibn Hazm, al-Fisal", ar_ref="فتح الباري ١٣/٥٣٤ نقلًا عن الفصل لابن حزم", site=IW, url=F13,
  es=["[[k:Abu Muhammad ibn Hazm]] enumeró en su libro al-Fisal fi l-milal wa-l-nihal muchas cosas de este tipo…",
      "Luego citó cosas del texto de la Torá que tienen ahora en sus manos, en las que la mentira es muy evidente. Y después dijo: «[[k:Nos ha llegado que hay un grupo de musulmanes que niegan que la Torá y el Evangelio que tienen en sus manos los judíos y los cristianos estén alterados]]; [[a:y lo que les lleva a eso es lo poco que les importan los textos del Corán y de la Sunna]]»."],
  prueba="El sistematizador de la falsificación total (m. 456 H) reconoce que en su tiempo había musulmanes que la negaban. Sus pruebas son de contenido (pasajes que considera falsos), no manuscritos.",
  ojo="Ibn Hazm descalifica a esos musulmanes (en azul): muestra la frase entera. El texto original de al-Fisal está en H13a."),

 dict(id="H17", year="728 H", who="Ibn Taymiyya", postura="Parcial",
  title="«Cada una de estas dos opiniones la han sostenido muchos musulmanes»",
  ref="Ibn Taymiyya, Majmuʿ al-Fatawa 13/103–104 (ed. Ibn Qasim)", ar_ref="مجموع الفتاوى ١٣/١٠٣–١٠٤", site="ar.wikisource.org (transcripción del texto)", url="https://ar.wikisource.org/wiki/مجموع_الفتاوى/المجلد_الثالث_عشر/فصل_في_تحريف_الإنجيل",
  es=["Ya se dijo antes de esto que se ha afirmado: «No hay en el mundo un ejemplar con lo mismo que Dios reveló en la Torá y el Evangelio; todo eso está cambiado, porque la transmisión masiva (tawātur) de la Torá se interrumpió, y el Evangelio se tomó de cuatro [personas]». Entre quienes lo dicen, unos sostienen que mucho de lo que hay en la Torá o el Evangelio es falso y no es palabra de Dios, y otros dicen: «no, eso es poco». [[k:Y se ha dicho: nadie alteró ni una de las letras de los libros; solo alteraron sus sentidos con la interpretación]]. [[k:Y cada una de estas dos opiniones la han sostenido muchos musulmanes]]. Lo correcto es la tercera opinión: [[k:que en la tierra había ejemplares auténticos, que perduraron hasta la época del Profeta ﷺ]], [[a:y muchos ejemplares alterados]]. Quien dice que no se alteró ninguno de los ejemplares afirma algo que no puede probar; y [[k:quien dice que todos los ejemplares se alteraron después del Profeta ﷺ dice algo que se sabe que es un error]], pues el Corán les manda juzgar por lo que Dios reveló en la Torá y el Evangelio, e informa de que en ellos está Su juicio; [[k:y no hay en el Corán ninguna noticia de que cambiaran todos los ejemplares]]."],
  prueba="Ibn Taymiyya (m. 728 H), autor de la gran refutación clásica del cristianismo, reconoce que la opinión «ni una letra alterada» la sostenían muchos musulmanes, y rechaza que todos los ejemplares se corrompieran después del Profeta.",
  ojo="Él cree que había muchos ejemplares alterados (en azul). La página de wikisource no muestra el número de página; la referencia impresa es 13/103–104."),

 dict(id="H18", year="774 H", who="Ibn Kathir", postura="Texto alterado (en su época)",
  title="«No hay duda de que ha entrado en ello el cambio»… y las traducciones árabes, llenas de errores",
  ref="Ibn Kathir, Tafsir, sobre el Corán 3:78", ar_ref="تفسير ابن كثير، آل عمران ٧٨", site=KSU, url=KSU_K,
  es=["Si Wahb se refería a lo que tienen en sus manos, [[k:no hay duda de que en ello han entrado el cambio, la tergiversación, la adición y la supresión]]; [[k:y en cuanto a la traducción al árabe que circula, tiene grandes errores, muchas adiciones y supresiones, y graves equivocaciones]]. Es del tipo de la interpretación del traductor que arabiza, y la comprensión de muchos de ellos —o más bien de la mayoría, o de todos— es corrupta. Pero si se refería a los libros de Dios tal como son de parte de Él, [[a:esos, como dijo, están preservados y no ha entrado en ellos nada]]."],
  prueba="Ibn Kathir (m. 774 H) cree que en los ejemplares de su época hay cambios, adiciones y supresiones, y que las traducciones árabes están llenas de errores: la postura «texto alterado (en su época)».",
  ojo="Matiz (en azul): no niega que lo revelado por Dios esté preservado; habla de los ejemplares y traducciones de su tiempo."),

 dict(id="H19b", year="804 H", who="Ibn al-Mulaqqin (citado por Ibn Hajar)", postura="Texto alterado (mayoritario en su escuela)",
  title="«Muchos de nuestros compañeros declararon que cambiaron la Torá y el Evangelio»",
  ref="Ibn Hajar, Fath al-Bari 13/533, citando a Ibn al-Mulaqqin", ar_ref="فتح الباري ١٣/٥٣٣ نقلًا عن ابن الملقن", site=IW, url=F13,
  es=["Dijo nuestro maestro Ibn al-Mulaqqin en su comentario: «[[a:Esto que dijo es una de las dos opiniones sobre la interpretación de este versículo, y es la que él eligió]] —es decir, al-Bujari—. [[k:Muchos de nuestros compañeros han declarado expresamente que los judíos y los cristianos cambiaron la Torá y el Evangelio]], y de ello dedujeron que es lícito tratar sus hojas sin respeto; y eso contradice lo que dice aquí al-Bujari». Fin de la cita."],
  prueba="Ibn al-Mulaqqin (m. 804 H) da fe de que en su escuela (shafiʿí) muchos sostenían que se cambió la Torá y el Evangelio; y a la vez reconoce (en azul) que la opinión contraria es la que eligió Bujari.",
  ojo="El texto original, en su propio comentario (al-Tawdih), está en H19a."),

 dict(id="H21", year="852 H", who="Ibn Hajar", postura="Abierto",
  title="Recoge cuatro opiniones y se niega a llamar falsa la de «solo el sentido»",
  ref="Ibn Hajar, Fath al-Bari 13/533–534", ar_ref="فتح الباري لابن حجر ١٣/٥٣٣–٥٣٤", site=IW, url=F13,
  es=["Dijo uno de los comentaristas tardíos: sobre esta cuestión hay varias opiniones. [[k:Primera: que fue cambiada entera]]; es lo que implica la opinión, ya citada, de que se puede tratar [sus hojas] sin respeto, y es un exceso. Hay que entender que quienes lo dicen de forma absoluta se refieren a la mayor parte; si no, es negar lo evidente, y los versículos y los relatos que dicen que de ella quedaron muchas cosas sin cambiar son muchos. Entre ellos, la palabra de Dios: «los que siguen al Mensajero, el Profeta iletrado, al que encuentran escrito junto a ellos en la Torá y el Evangelio»; y la historia de la lapidación de los dos judíos, en la que aparece el versículo de la lapidación; y lo apoya la palabra de Dios: «Di: traed la Torá y leedla, si sois sinceros». [[k:Segunda: que el cambio se produjo, pero en la mayor parte de ella]]; sus pruebas son muchas, y la primera hay que entenderla así. [[k:Tercera: que se produjo en una pequeña parte y la mayor parte sigue como estaba]]; la defendió el shaykh Taqi al-Din ibn Taymiyya en su libro al-Jawab al-sahih li-man baddala din al-Masih. [[k:Cuarta: que el cambio y la alteración se produjeron solo en los sentidos, no en las palabras; y es la que se menciona aquí]].",
      "[[k:Y calificar de falsa esa opinión, con lo expuesto, también es objetable]]: se ha atribuido a Wahb ibn Munabbih, que es de los que más sabían de la Torá, [[k:y se ha atribuido también a Ibn Abbas, el intérprete del Corán]]. Debería haber dejado de rechazarla a empujones…"],
  prueba="Ibn Hajar (m. 852 H) expone las cuatro opiniones sin quedarse con una, y se niega a llamar falsa la de «solo el sentido».",
  ojo="Las cuatro opiniones las expone citando a «uno de los comentaristas tardíos». Más contexto: IH02 e IH10."),
]

SH = "shamela.ws (Maktaba Shamila; paginación igual a la edición impresa)"
HCARDS += [
 dict(id="H03x", year="Extra", who="Relato atribuido al Profeta vía ʿUthman (no está en la tabla)", postura="Texto alterado (relato que Ibn Kathir no acepta)",
  title="«Tergiversaron la Torá, añadieron… y borraron el nombre de Muhammad»: Ibn Kathir lo llama «muy extraño»",
  ref="Ibn Kathir, Tafsir, sobre el Corán 2:79 (también en al-Tabari 2:79, n.º 1395)", ar_ref="تفسير ابن كثير، البقرة ٧٩", site=KSU, url="https://quran.ksu.edu.sa/tafseer/katheer/sura2-aya79.html",
  es=["[…] de ʿUthman ibn ʿAffan, del Mensajero de Dios ﷺ, sobre «¡Ay de ellos por lo que escribieron sus manos, y ay de ellos por lo que ganan!»: dijo: «El “ay” (wayl) es un monte en el Fuego, y es lo que se reveló sobre los judíos, [[a:porque tergiversaron la Torá, añadieron en ella lo que quisieron, borraron de ella lo que no les gustaba y borraron de la Torá el nombre de Muhammad ﷺ]]. Por eso Dios se enfadó con ellos y retiró parte de la Torá», y dijo: «¡Ay de ellos por lo que escribieron sus manos, y ay de ellos por lo que ganan!». [[k:Y esto también es muy extraño]] (gharīb jiddan)."],
  prueba="Es el único relato que pone en boca del Profeta que borraron y añadieron en la Torá. Ibn Kathir, que lo transmite, lo califica de «muy extraño» (gharīb jiddan): un relato aislado que no da por fiable.",
  ojo="No está en la tabla, pero conviene tenerlo a mano: si Tibyanan lo presenta como «palabra del Profeta», la respuesta es el juicio de Ibn Kathir. Revisa su cadena antes de usarlo (al-Tabari 2:79, n.º 1395)."),

 dict(id="H07a", year="150 H", who="Muqatil ibn Sulayman", postura="Cambio local",
  title="«Los jefes de los judíos de Medina borraron de la Torá la descripción de Muhammad»",
  ref="Muqatil ibn Sulayman, Tafsir, sobre el Corán 2:79, vol. 1, p. 118 (ed. Shihata)", ar_ref="تفسير مقاتل بن سليمان ١/١١٨", site=SH, url="https://shamela.ws/book/23614/49",
  es=["«¡Ay de quienes escriben el libro con sus manos!»: algo distinto de la descripción de Muhammad ﷺ. [[k:Y es que los jefes de los judíos de Medina borraron de la Torá la descripción de Muhammad ﷺ]] y escribieron otra en su lugar, y dijeron a los judíos algo distinto de la descripción de Muhammad. «Y luego dicen»: esta descripción «viene de Dios, para venderlo a bajo precio», es decir, el pequeño beneficio que la gente humilde de los judíos les daba cada año de sus cosechas y sus frutos. Dice: «¡Ay de ellos por lo que escribieron sus manos!», es decir, en la Torá, [[k:al cambiar la descripción de Muhammad]] ﷺ."],
  prueba="Muqatil (m. 150 H) sí habla de un cambio en el texto: borraron la descripción de Muhammad y escribieron otra. Es un cambio concreto, no la falsificación de toda la Torá.",
  ojo="Este texto juega en contra de la versión fuerte de la tesis; muéstralo. Matices: su tafsir nos llega en una recensión posterior (de al-Hudhayl ibn Habib), y Muqatil fue muy criticado como transmisor por los especialistas en hadiz."),

 dict(id="H07b", year="150 H", who="Muqatil ibn Sulayman", postura="Cambio local",
  title="«Escribieron en la Torá algo distinto de la descripción de Muhammad y borraron su descripción»",
  ref="Muqatil ibn Sulayman, Tafsir, sobre el Corán 3:78, vol. 1, p. 286 (ed. Shihata)", ar_ref="تفسير مقاتل بن سليمان ١/٢٨٦", site=SH, url="https://shamela.ws/book/23614/193",
  es=["«Retuercen sus lenguas con el Libro»: [[k:con «retorcer» se refiere a la tergiversación con las lenguas]] en lo relativo a Muhammad ﷺ; «para que lo creáis parte del Libro», es decir, de la Torá. Dice Dios, poderoso y majestuoso: «y no es parte del Libro»: [[k:escribieron —es decir, en la Torá— algo distinto de la descripción de Muhammad ﷺ]] [[k:y borraron su descripción]]; «y dicen: es» —esta descripción— «de parte de Dios, y no es de parte de Dios», sino que la escribieron ellos."],
  prueba="Aquí Muqatil junta las dos cosas: tergiversar con la lengua al recitar y, en concreto, cambiar por escrito la descripción de Muhammad. Siempre sobre ese punto, no sobre el conjunto de la Torá."),

 dict(id="H11a", year="310 H", who="al-Tabari (opinión propia)", postura="Mixta",
  title="«Los rabinos escriben mentiras con sus manos y las hacen pasar por el Libro de Dios»",
  ref="al-Tabari, Tafsir, sobre el Corán 2:79 (comentario del propio al-Tabari)", ar_ref="تفسير الطبري، البقرة ٧٩", site=KSU, url=KSU_T+"sura2-aya79.html",
  es=["Con Su palabra «¡Ay de quienes escriben el libro con sus manos!», nuestro Señor hizo saber a Sus siervos creyentes [[k:que los rabinos de los judíos se encargan de escribir con sus manos mentiras e invenciones contra Dios]], a sabiendas y con intención de mentir sobre Dios, [[k:y luego las hacen pasar por algo que viene de Dios y que está en el Libro de Dios]], mintiendo y calumniando a Dios."],
  prueba="Es la postura del propio al-Tabari (m. 310 H) sobre 2:79: los rabinos escriben mentiras y las presentan como el Libro de Dios. Habla de escritos falsos atribuidos a Dios; no dice que el texto de la Torá haya desaparecido.",
  ojo="Para la «Torá quemada y restituida por Esdras», mira H11b y H11c; para lo de «la Torá que tienen hoy», H11d."),

 dict(id="H11b", year="310 H", who="al-Tabari (relato de Wahb)", postura="Mixta",
  title="La Torá «fue quemada y se perdió»… y Esdras la restituyó",
  ref="al-Tabari, Tarikh al-rusul wa-l-muluk, vol. 1, pp. 556–557 (ed. Abu al-Fadl Ibrahim)", ar_ref="تاريخ الطبري ١/٥٥٦–٥٥٧", site=SH, url="https://shamela.ws/book/9783/553",
  es=["Luego, cuando entraron en Siria, entraron sin tener consigo el pacto de Dios: [[k:la Torá les había sido arrebatada, y fue quemada y se perdió]]. Esdras (ʿUzayr) estaba entre los cautivos de Babilonia, y volvió a Siria llorándola noche y día; se había apartado de la gente y vagaba por el fondo de los valles y los desiertos llorando. Estando así, en su pena por la Torá y su llanto por ella, se le acercó un hombre mientras estaba sentado y le dijo: «Esdras, ¿qué te hace llorar?». Dijo: «Lloro por el Libro de Dios y Su pacto, que estaba entre nosotros. Nuestros pecados llevaron a que nuestro Señor se enfadara con nosotros y diera poder sobre nosotros a nuestro enemigo, que mató a nuestros hombres, arrasó nuestro país [[k:y quemó el Libro de Dios que estaba entre nosotros]], sin el cual no se arreglan ni esta vida ni la otra —o algo así dijo—. ¿Por qué voy a llorar, si no lloro por esto?». Dijo: «¿Te gustaría que te fuera devuelto?». Dijo: «¿Hay manera?». Dijo: «Sí. Vuelve, ayuna, purifícate y purifica tu ropa, y nos vemos aquí mañana». Esdras volvió, ayunó, se purificó y purificó su ropa, fue al lugar de la cita y se sentó. Aquel hombre —que era un ángel que Dios le había enviado— le trajo un recipiente con agua y le dio de beber de él, [[k:y la Torá quedó presente en su pecho]]. Volvió a los hijos de Israel y les dispuso la Torá, que reconocían, con lo lícito y lo ilícito, sus normas y sus obligaciones."],
  prueba="Al-Tabari recoge que la Torá se quemó y que Esdras la restituyó. En el relato, la Torá restituida es la verdadera, la que «reconocían».",
  ojo="No es opinión del propio al-Tabari: es un relato que transmite de Wahb ibn Munabbih vía Ibn Ishaq (empieza en la p. 548)."),

 dict(id="H11c", year="310 H", who="al-Tabari (relato de al-Suddi)", postura="Mixta",
  title="Esdras escribió la Torá entera… «la cotejaron y la encontraron igual»",
  ref="al-Tabari, Tafsir, sobre el Corán 9:30 (relato de al-Suddi, n.º 16622 en la numeración de Shakir)", ar_ref="تفسير الطبري، التوبة ٣٠", site=KSU, url=KSU_T+"sura9-aya30.html",
  es=["Esdras volvió, y era de los que más sabían de la Torá. Dijo: «Hijos de Israel, os he traído la Torá». Dijeron: «Esdras, tú no eras un mentiroso». Se ató una pluma a cada dedo y escribió con todos sus dedos, [[k:y escribió la Torá entera]]. Cuando volvieron los sabios, les contaron lo de Esdras; aquellos sabios sacaron los libros de la Torá que habían enterrado en los montes —estaban enterrados en tinajas—, [[k:los cotejaron con la Torá de Esdras y la encontraron igual]]."],
  prueba="En esta versión, la Torá que escribe Esdras coincide con los ejemplares antiguos que se habían enterrado: el relato defiende que el texto restituido es el mismo.",
  ojo="Es un relato de al-Suddi (m. 127 H) que recoge al-Tabari, no una opinión del propio al-Tabari."),

 dict(id="H11d", year="310 H", who="al-Tabari", postura="Mixta",
  title="«La Torá que tienen en sus manos hoy»: la frase existe, pero en un cálculo de cronología",
  ref="al-Tabari, Tarikh al-rusul wa-l-muluk, vol. 1, p. 17 (ed. Abu al-Fadl Ibrahim)", ar_ref="تاريخ الطبري ١/١٧", site=SH, url="https://shamela.ws/book/9783/15",
  es=["Los judíos sostienen que todo lo que consta para ellos —según lo que hay en la Torá, desde que Dios creó a Adán hasta el momento de la hégira, [[k:y eso en la Torá que tienen en sus manos hoy]]— son cuatro mil seiscientos cuarenta y dos años."],
  prueba="La expresión «la Torá que tienen en sus manos hoy» existe, pero aquí sirve para fechar el mundo, no para defender que haya una Torá falsa.",
  ojo="La Wikipedia en inglés, citando a Adang, dice que al-Tabari creía en otra Torá hecha por los rabinos y usada en su época. No hemos encontrado ese pasaje en árabe, y la nota de Wikipedia remite a páginas que hablan de otro autor (al-Qasim al-Rassi). No uses esa afirmación en el vídeo."),
]

AR = "archive.org (texto OCR de un escaneo)"
MTU = "https://mtafsir.net/threads/أجوبة-ابن-حزم-على-اعتراضات-نفاة-تحريف-التوراة-والأنجيل.6305/"
HCARDS += [
 dict(id="H02a", year="68 H", who="Ibn Abbas (según Ibn Atiyya)", postura="Interpretación + libros añadidos",
  title="«Ibn Abbas sostuvo que su tergiversación es solo por interpretación, y el texto de la Torá permanece»",
  ref="Ibn Atiyya, al-Muharrar al-wajiz, sobre el Corán 2:75, vol. 1, p. 260 (ed. Awqaf de Catar)", ar_ref="المحرر الوجيز لابن عطية ١/٢٦٠", site=IW, url="https://www.islamweb.net/ar/library/content/207/51/",
  es=["Tergiversar una cosa es desviarla de un estado a otro. [[k:Ibn Abbas —Dios esté complacido con ambos— sostuvo que su tergiversación y su cambio son solo por la interpretación, y que el texto de la Torá permanece]]; [[a:y un grupo de sabios sostuvo que cambiaron palabras por su cuenta]], y que eso es posible en la Torá porque se les encomendó a ellos guardarla, y no es posible en el Corán porque Dios garantizó Él mismo su preservación."],
  prueba="Ibn Atiyya (m. 541 H) atribuye a Ibn Abbas, sin ponerlo en duda, la opinión de que solo hubo interpretación y de que el texto de la Torá permanece.",
  ojo="Ibn Atiyya recoge también la opinión contraria (en azul). Su propio veredicto está en H15."),

 dict(id="H10a", specs=["H10a1","H10a2"], year="255 H", who="al-Jahiz", postura="Texto alterado (según al-Qaduri; ver «Ojo»)",
  title="Los Evangelios, obra de «cuatro personas» que se contradicen… pero la Torá «sí, es verdad»",
  ref="al-Jahiz, al-Radd ʿala al-Nasara, en Rasaʾil al-Jahiz, ed. Harun, vol. 3, pp. 328 y 334", ar_ref="الرد على النصارى، رسائل الجاحظ ٣/٣٢٨ و٣/٣٣٤", site=SH, url="https://shamela.ws/book/10428/1054",
  es=["Nuestra respuesta: que recibieron su religión de cuatro personas: dos de ellas, apóstoles según dicen, Juan y Mateo; y dos de los que respondieron después, Marcos y Lucas. [[k:Y de estos cuatro no se puede descartar el error ni el olvido, ni la mentira deliberada]], ni que se pusieran de acuerdo, ni que pactaran repartirse la autoridad cediendo cada uno al otro la parte que le había fijado. Si dicen: «Eran demasiado virtuosos para mentir a sabiendas, demasiado cuidadosos para olvidar algo, demasiado elevados para equivocarse en la religión de Dios o descuidar un pacto», decimos: [[k:las diferencias entre sus relatos en el Evangelio y las contradicciones de sus libros]], y su desacuerdo sobre la naturaleza misma del Mesías, junto con la diferencia de sus leyes, prueban que tenemos razón sobre ellos y que vosotros no os habéis fijado.",
      "Si dicen: «Habladnos de Dios y de la Torá: [[k:¿no es verdad?]]», decimos: [[k:«Sí»]]. Dicen: «Pues en ella está “Israel es mi primogénito”, y todo lo que nos reprocháis es conocido en los libros». Decimos: [[k:«Esa gente fracasó por su poco conocimiento de los sentidos del lenguaje y por la mala traducción»]]…"],
  prueba="Al-Jahiz (m. 255 H) ataca los Evangelios como obra de cuatro hombres falibles que se contradicen, pero dice que la Torá es verdad y achaca los problemas a la mala interpretación y a la mala traducción.",
  ojo="En el texto conservado no usa «tergiversar» ni «cambiar» referido a las Escrituras. La etiqueta de al-Qaduri («alteración del texto») solo se sostiene en parte, y sobre todo para los Evangelios. Página 3/334: https://shamela.ws/book/10428/1060"),

 dict(id="H10b", year="s. III H", who="ʿAli ibn Rabban al-Tabari", postura="Texto alterado (pasajes concretos)",
  title="«Esto también lo considero una alteración y una corrupción en el Evangelio, por parte de los traductores y los copistas»",
  ref="ʿAli ibn Rabban al-Tabari, al-Din wa-l-dawla, ed. Nuwayhid (Beirut, 1973), p. 193", ar_ref="الدين والدولة لعلي بن ربن الطبري، ص ١٩٣", site=AR, url="https://archive.org/stream/0438-pdf_202101/",
  lang="árabe (OCR)",
  es=["…[si se refería con] estas palabras a los signos [hechos] por manos del Mesías; y si lo dijo de sí mismo, entonces el Mesías hizo lo contrario de lo que dijo y contradijo su primera palabra, y eso no le corresponde ni cabe pensarlo de él. [[k:Esto también lo considero una alteración y una corrupción en el Evangelio, por parte de los traductores y los copistas]]."],
  prueba="ʿAli ibn Rabban (s. III H), cristiano convertido al islam, señala pasajes concretos del Evangelio que cree corrompidos por traductores y copistas.",
  ojo="El texto en línea es un OCR con errores (letras persas, palabras partidas): compruébalo en la edición impresa. En el resto del libro argumenta a partir del texto bíblico: su acusación es sobre pasajes concretos, no sobre todo el libro."),

 dict(id="H10s", year="255 H – s. III", who="al-Jahiz e Ibn Rabban (según al-Qaduri)", postura="Texto alterado", secondary=True,
  title="La clasificación de al-Qaduri en la que se basa la fila de la tabla",
  ref="Samir al-Qaduri, Multaqa Ahl al-Tafsir (2005)", ar_ref="سمير القدوري، ملتقى أهل التفسير", site="mtafsir.net (artículo de un investigador actual)", url=MTU,
  es=["…[Se puede dividir a los autores en dos grandes grupos:] [[k:el grupo que sostiene que la alteración se produjo en el texto y en el sentido]] —sus partidarios son muchos; mencionamos algunos de cuyas opiniones tenemos noticia—: 1. [[k:al-Jahiz]]. 2. [[k:ʿAli ibn Rabban al-Tabari]]."],
  prueba="La fila de la tabla sobre al-Jahiz e Ibn Rabban se basa en esta clasificación del investigador marroquí Samir al-Qaduri. Las fuentes originales (H10a y H10b) solo la confirman en parte."),

 dict(id="H12a", year="403 H", who="al-Baqillani", postura="Interpretación (según al-Qaduri; ver H12b)",
  title="Que la Torá y el Evangelio vienen de Moisés y de Jesús se sabe «por necesidad»",
  ref="al-Baqillani, al-Tamhid, ed. Haydar (1987), pp. 158–159", ar_ref="التمهيد للباقلاني ص ١٥٨–١٥٩", site=SH, url="https://shamela.ws/book/6389/136",
  es=["Si alguien se empeñara en eso, negaría lo que se sabe por necesidad, y no habría que discutir con él; [[k:igual que si alguien pretendiera que la Torá y el Evangelio no forman parte de lo que apareció por medio de Moisés y de Jesús —la paz sea con ellos—: sería un obstinado y negaría]] [lo que se sabe por necesidad]."],
  prueba="Al-Baqillani (m. 403 H) pone como ejemplo de algo que se sabe por transmisión masiva (tawatur) que la Torá y el Evangelio vienen de Moisés y de Jesús. Es la base del argumento que le atribuye al-Qaduri.",
  ojo="Mira H12b y H12c antes de presentarlo como defensor de «solo el sentido»."),

 dict(id="H12b", specs=["H12b1","H12b2"], year="403 H", who="al-Baqillani", postura="Mixta (corrige la tabla)",
  title="«Tergiversaron, alteraron y cambiaron»… «el error y la tergiversación entran mucho en la transmisión»",
  ref="al-Baqillani, al-Tamhid, ed. Haydar (1987), pp. 208–209", ar_ref="التمهيد للباقلاني ص ٢٠٨–٢٠٩", site=SH, url="https://shamela.ws/book/6389/186",
  es=["…Y el reino de los hijos de Israel no se mantuvo porque le desobedecieron [a Moisés] en vida y después de su muerte, [[k:y tergiversaron, alteraron y cambiaron]]; y por eso desapareció su reino…",
      "…Ellos solo transmiten las palabras de Moisés, las traducen, las pasan de una lengua a otra y las interpretan, [[k:y el error y la tergiversación entran mucho en la transmisión]]; así que no se impone por necesidad que sea correcto lo que transmiten e interpretan…"],
  prueba="En el mismo libro, al-Baqillani dice que tergiversaron, alteraron y cambiaron, y que en la transmisión y traducción de las palabras de Moisés entra mucho error.",
  ojo="No hemos encontrado ningún pasaje suyo que limite el tahrif al sentido. En la tabla, su postura debe pasar a «mixta». Página 209: https://shamela.ws/book/6389/187"),

 dict(id="H12c", year="403 H", who="al-Baqillani", postura="Mixta (corrige la tabla)",
  title="«…después de haber tergiversado la Torá y cambiado la descripción del Mensajero»",
  ref="al-Baqillani, al-Intisar li-l-Qurʾan, ed. al-Qudah (2001), vol. 2, p. 669", ar_ref="الانتصار للقرآن للباقلاني ٢/٦٦٩", site=SH, url="https://shamela.ws/book/1397/617",
  es=["…Dios, ensalzado sea, niega eso de Sí mismo al decir «y no viene de Dios». Lo que pretendieron es que Dios había revelado la Torá así, tergiversada y cambiada, según hicieron creer a su gente baja, al vulgo y a la chusma; [[k:y lo pretendieron después de haber tergiversado la Torá y haberla alterado, y de haber cambiado la descripción del Mensajero y la mención de la buena nueva sobre él en la Torá]]. Y dijo Dios: «retuercen sus lenguas con el Libro para que lo creáis parte del Libro» (es decir, de la Torá)…"],
  prueba="Aquí al-Baqillani habla de un cambio concreto: la descripción del Profeta y la buena nueva sobre él, como Abu al-ʿAliya y Muqatil."),

 dict(id="H13a", specs=["H13a1","H13a2"], year="456 H", who="Ibn Hazm", postura="Texto alterado",
  title="En su propio libro: «Nos ha llegado que hay musulmanes que, por ignorancia, niegan que estén alterados»",
  ref="Ibn Hazm, al-Fisal fi l-milal wa-l-ahwaʾ wa-l-nihal, vol. 1, pp. 159–160 (Maktabat al-Khanji)", ar_ref="الفصل في الملل والأهواء والنحل ١/١٥٩–١٦٠", site=SH, url="https://shamela.ws/book/6521/151",
  es=["Dijo Abu Muhammad [Ibn Hazm]: [[k:Nos ha llegado que hay un grupo de musulmanes que, por ignorancia, niegan que la Torá y el Evangelio que tienen en sus manos los judíos y los cristianos estén alterados]]; [[a:y lo que les ha llevado a ello es lo poco que les importan los textos del Corán y de la Sunna]]. ¿Acaso no han oído la palabra de Dios: «Gente del Libro, ¿por qué revestís la verdad de falsedad y ocultáis la verdad a sabiendas?», y Su palabra: «y un grupo de ellos oculta la verdad a sabiendas»?",
      "…y Su palabra: «desplazan las palabras de su lugar»; y de esto hay muchísimo en el Corán. [[k:Y decimos a quien, entre los musulmanes, dice que su transmisión es masiva (tawātur), que da certeza y sirve de prueba]]: no hay duda de que ellos no discrepan en que [[a:lo que han transmitido de Moisés y de Jesús —la paz sea con ellos— no menciona en absoluto a Muhammad ﷺ]]…"],
  prueba="En su propio libro, Ibn Hazm (m. 456 H) reconoce que había musulmanes que negaban la alteración, y que algunos se apoyaban en la transmisión masiva (tawatur). Su respuesta es de contenido: si la transmisión fuera fiable, habría que aceptar también que no mencionan a Muhammad.",
  ojo="Ibn Hazm los llama ignorantes (en azul): muéstralo. Página 160: https://shamela.ws/book/6521/152"),

 dict(id="H14", year="486 H", who="ʿIsa ibn Sahl (según al-Qaduri)", postura="Interpretación", secondary=True,
  title="«Los judíos y los cristianos pueden decirle a Ibn Hazm…»: la única noticia de su libro perdido",
  ref="Samir al-Qaduri, Multaqa Ahl al-Tafsir (2005), resumiendo al-Tanbih ʿala shudhudh Ibn Hazm", ar_ref="سمير القدوري، ملتقى أهل التفسير (عن التنبيه على شذوذ ابن حزم)", site="mtafsir.net (artículo de un investigador actual)", url=MTU,
  es=["Frente a este grupo hay otro que no escribió un libro ni un capítulo propio sobre la tergiversación dentro de una refutación de la Gente del Libro, sino que se atuvo a una posición teórica: [[k:que la tergiversación se produjo en el sentido, porque creía que los libros de judíos y cristianos se transmitieron de forma masiva (tawātur)]]. Entre ellos: 1. el cadí Abu Bakr al-Baqillani (m. 403 H). 2. [[k:El cadí ʿIsa ibn Sahl al-Jayyani]] (m. 486 H). Su opinión está en su libro al-Tanbih ʿala shudhudh Ibn Hazm («Advertencia sobre las rarezas de Ibn Hazm»), [[k:donde reprocha a Ibn Hazm que diga que los libros de la Gente del Libro están alterados]], y le dice: «Los judíos y los cristianos pueden decirle a Ibn Hazm: seguimos religiones que nos trajeron nuestros mensajeros; si tú lo niegas, reniegas de lo que trae tu Libro (es decir, el Corán) y, según tu ley, debes morir. Y que algunos de los nuestros tergiversaran y otros se salieran no anula nuestra ley, igual que los jariyíes y los innovadores no anularon vuestra ley ni deshicieron vuestra religión con su aparición». Luego dice Ibn Sahl: «Esto es correcto y basta para mostrar la calumnia de Ibn Hazm… Si les hubiera argumentado que su religión y su ley quedaron abrogadas por lo que se reveló a Muhammad ﷺ, habría acertado y se habría librado del problema». [[k:Fin de sus palabras, en resumen]]."],
  prueba="ʿIsa ibn Sahl (m. 486 H), cadí andalusí, escribió contra Ibn Hazm reprochándole que dijera que los libros de la Gente del Libro están alterados.",
  ojo="Su libro no se ha publicado (solo hay un fragmento manuscrito en la Qarawiyyin de Fez). Esto es un resumen de al-Qaduri («en resumen»), no las palabras exactas de Ibn Sahl: preséntalo así."),

 dict(id="H15", specs=["H02a","H15b"], year="541 H", who="Ibn Atiyya", postura="Recoge ambas; su veredicto: «las dos cosas»",
  title="Recoge la postura de Ibn Abbas… y concluye: «no hay duda de que hicieron las dos cosas»",
  ref="Ibn Atiyya, al-Muharrar al-wajiz, sobre el Corán 2:75 (vol. 1, p. 260) y 5:13 (vol. 3, p. 130), ed. Awqaf de Catar", ar_ref="المحرر الوجيز ١/٢٦٠ و٣/١٣٠", site=IW, url="https://www.islamweb.net/ar/library/content/207/358/",
  es=["Tergiversar una cosa es desviarla de un estado a otro. [[k:Ibn Abbas —Dios esté complacido con ambos— sostuvo que su tergiversación y su cambio son solo por la interpretación, y que el texto de la Torá permanece]]; [[a:y un grupo de sabios sostuvo que cambiaron palabras por su cuenta]], y que eso es posible en la Torá porque se les encomendó a ellos guardarla, y no es posible en el Corán porque Dios garantizó Él mismo su preservación.",
      "Los sabios discrepan sobre el sentido de «desplazan las palabras»: [[k:un grupo —entre ellos Ibn Abbas— dijo: su tergiversación es por la interpretación; no tenían capacidad de cambiar las palabras de la Torá]], ni les era posible, [[k:y lo prueba que el versículo de la lapidación siguiera ahí]] y que necesitaran que el lector pusiera la mano encima. Otro grupo dijo: no, también tergiversaron las palabras y las cambiaron, e hicieron las dos cosas según pudieron. Dijo el cadí Abu Muhammad [Ibn Atiyya]: las palabras del Corán admiten los dos sentidos; Su palabra «¡Ay de quienes escriben el libro con sus manos!» implica cambio; [[a:y no hay duda de que hicieron las dos cosas]]."],
  prueba="Ibn Atiyya (m. 541 H) atribuye a Ibn Abbas la postura de «solo interpretación», con el argumento del versículo de la lapidación.",
  ojo="Su conclusión propia (en azul) es que hicieron las dos cosas. En el guion: el argumento de la lapidación es del grupo de Ibn Abbas que él recoge, no una prueba suya, y Ibn Atiyya no defiende que el texto esté intacto."),

 dict(id="H16", specs=["H16a","H16b"], year="606 H", who="Fajr al-Din al-Razi", postura="Interpretación (con matices)",
  title="«En un libro transmitido masivamente no es posible cambiar las palabras»",
  ref="al-Razi, al-Tafsir al-kabir, sobre el Corán 5:13 (vol. 11, p. 148) y 4:46 (vol. 10, p. 95), Dar al-Kutub al-ʿIlmiyya", ar_ref="التفسير الكبير للرازي ١١/١٤٨ و١٠/٩٥", site=IW, url="https://www.islamweb.net/ar/library/content/132/2103/",
  es=["Luego [Dios], ensalzado sea, menciona algunas consecuencias de esa dureza, y dice: «desplazan las palabras de su lugar». Esta tergiversación puede ser la interpretación falsa, y puede ser el cambio de las palabras; [[k:y ya hemos explicado antes que lo primero es más adecuado, porque en un libro transmitido de forma masiva (tawātur) no es posible cambiar las palabras]].",
      "Tercera cuestión: sobre cómo fue la tergiversación hay varias explicaciones. [[a:Una: que cambiaban una palabra por otra]], como cuando desplazaron de su lugar en la Torá [la descripción] «de estatura media» poniendo en su lugar «moreno y alto», o cambiaron «la lapidación» poniendo en su lugar «el castigo»; es como la palabra de Dios: «¡Ay de quienes escriben el libro con sus manos y luego dicen: esto viene de Dios!» (2:79). Si se dice: [[k:«¿Cómo es posible esto en un libro cuyas letras y palabras, una a una, alcanzaron la transmisión masiva conocida en Oriente y Occidente?»]], diríamos: quizá se pueda responder que eran pocos, y los que conocían el Libro eran poquísimos, y así pudieron hacer esa tergiversación. La segunda: que por tergiversación se entiende sembrar dudas falsas e interpretaciones corruptas, y desviar la palabra de su sentido verdadero a uno falso con artificios verbales, como hacen los innovadores de nuestro tiempo con los versículos que contradicen sus doctrinas; [[k:y esta es la más correcta]]."],
  prueba="Al-Razi (m. 606 H) prefiere entender el tahrif como interpretación falsa, porque un libro transmitido masivamente no puede cambiar sus palabras.",
  ojo="En 4:46 recoge primero la opinión del cambio de palabras (en azul), y al comentar 5:41 admite que también sacaron palabras del libro. Prefiere la interpretación, pero no excluye todo cambio. Página de 4:46: https://www.islamweb.net/ar/library/content/132/1770/"),

 dict(id="H19a", specs=["H19a1","H19a2"], year="804 H", who="Ibn al-Mulaqqin (su propio texto)", postura="Texto alterado (mayoritario en su escuela)",
  title="En su propio comentario: «lo que dijo sobre “yuḥarrifūn” es su opinión, y es una de las dos opiniones»",
  ref="Ibn al-Mulaqqin, al-Tawdih li-sharh al-Jamiʿ al-sahih, vol. 33, pp. 570 y 572 (Awqaf de Catar, 2008)", ar_ref="التوضيح لشرح الجامع الصحيح ٣٣/٥٧٠ و٥٧٢", site=IW, url="https://www.islamweb.net/ar/library/content/305/11700/",
  es=["«Yuḥarrifūn» (an-Nisāʾ 46): yuzīlūn. [[k:Y nadie elimina el texto de un libro de entre los libros de Dios, sino que lo tergiversan: lo interpretan de una forma que no es su interpretación]]. «Dirāsatuhum»: su recitación.",
      "Y el dicho de Ibn Abbas —Dios esté complacido con ambos— lo transmitió de él ʿAli ibn Abi Talha al-Shami en su Tafsir; [[k:y lo que dijo sobre «yuḥarrifūn» es su opinión, y es una de las dos opiniones]]; [[a:y que nuestros compañeros permitan limpiarse con las hojas de la Torá y el Evangelio, alegando que fueron cambiados, la contradice]]."],
  prueba="Es el texto del propio Ibn al-Mulaqqin (m. 804 H). La frase «es su opinión» va justo después de «el dicho de Ibn Abbas lo transmitió ʿAli ibn Abi Talha»: el sujeto no está claro y puede ser Ibn Abbas. La aclaración «es decir, al-Bujari» que aparece en Fath al-Bari (H19b, IH01) es de Ibn Hajar.",
  ojo="La cita de Ibn Hajar no coincide palabra por palabra con este texto impreso (habla de «tratar sus hojas sin respeto» en vez de «limpiarse con ellas»): puede ser otra versión del comentario o una cita libre. No digas que Ibn Hajar «manipuló» la cita. Página 570: https://www.islamweb.net/ar/library/content/305/11699/"),

 dict(id="H20a", specs=["H20a1","H20a2"], year="808 H", who="Ibn Khaldun", postura="Interpretación",
  title="«Ibn Abbas, según lo que transmite de él al-Bujari, dijo que eso es improbable… lo tergiversaron con la interpretación»",
  ref="Ibn Khaldun, Kitab al-ʿIbar (la Historia), vol. 2, pp. 7–8, ed. Shahada (Dar al-Fikr)", ar_ref="تاريخ ابن خلدون (العبر) ٢/٧–٨", site=SH, url="https://shamela.ws/book/12320/843",
  es=["En cuanto a lo que se dice de que sus sabios cambiaron pasajes de la Torá según los intereses de su religión: [[k:Ibn Abbas, según lo que transmite de él al-Bujari en su Sahih, dijo que eso es improbable]], [[k:y dijo: «Dios nos libre de que una nación de las naciones se proponga cambiar su Libro, revelado a su profeta»]], o algo con ese sentido. Y dijo: «solo lo cambiaron…",
      "…[[k:y lo tergiversaron con la interpretación]]». Lo atestigua la palabra de Dios: «y tienen la Torá, en la que está el juicio de Dios» (5:43); [[k:si hubieran cambiado las palabras de la Torá, no tendrían la Torá en la que está el juicio de Dios]]. Y lo que dice el noble Corán al atribuirles la tergiversación y el cambio [[k:se refiere a la interpretación]], [[a:salvo que hayan entrado cambios en las palabras por descuido y falta de precisión]]…"],
  prueba="Ibn Khaldun (m. 808 H) atribuye a Ibn Abbas, «según lo que transmite de él al-Bujari», que es improbable que cambiaran la Torá y que la tergiversación fue por interpretación, y lo apoya en el Corán 5:43. Es otro gran autor que atribuye esa idea a Ibn Abbas.",
  ojo="Está en Kitab al-ʿIbar (la Historia), no en la Muqaddima. Ibn Khaldun parafrasea: «Dios nos libre…» no es la redacción de Bujari. Admite cambios por descuido de copistas (en azul). Página 8: https://shamela.ws/book/12320/844"),

 dict(id="H20b", year="808 H", who="Ibn Khaldun (Muqaddima)", postura="Interpretación",
  title="«La afirmación de ese cambio no es la preferida por los investigadores… como mencionó al-Bujari»",
  ref="Ibn Khaldun, al-Muqaddima, introducción, vol. 1, p. 17 (edición de 2005, probablemente la de al-Shaddadi)", ar_ref="مقدمة ابن خلدون ١/١٧", site=AR, url="https://archive.org/stream/1_20230830_20230830_1222/1_djvu.txt",
  lang="árabe (OCR)",
  es=["Y si alguien objeta contra esa noticia que solo aparece en la Torá, y que los judíos la cambiaron, como es sabido, [respondemos]: [[k:la afirmación de ese cambio no es la preferida por los investigadores rigurosos]], y no ha de tomarse en su sentido literal, [[k:porque la costumbre impide que la gente de las religiones haga eso con sus escrituras divinas]], [[k:como mencionó al-Bujari en su Sahih]]. Así, este gran crecimiento de los hijos de Israel sería un milagro que rompe la costumbre…"],
  prueba="En la Muqaddima, Ibn Khaldun dice que el cambio de la Torá «no es la opinión preferida por los investigadores» y se remite a lo que dice al-Bujari en su Sahih. Es el pasaje que Rosenthal traduce: «unacceptable to thorough scholars».",
  ojo="Este pasaje solo está en algunos manuscritos (Rosenthal, nota 51) y falta en las ediciones basadas en Bulaq. Aquí se ve en un OCR de archive.org: compruébalo en la edición impresa antes de citarlo."),

 dict(id="H22a", year="885 H", who="al-Biqaʿi", postura="Uso positivo",
  title="Defiende citar la Torá y el Evangelio: «la prohibición se limita a lo que se sabe que fue cambiado»",
  ref="al-Biqaʿi, Nazm al-durar, sobre el Corán 2:34", ar_ref="نظم الدرر للبقاعي، البقرة ٣٤", site=IW, url="https://www.islamweb.net/ar/library/content/214/44/",
  es=["[[k:Si alguien rechaza que se cite la Torá o el Evangelio]], sin ver que lo mejor, en el debate, es responder a cada uno con lo que él mismo cree…",
      "Si algún shafiʿí entiende que sus imames prohibieron leer cualquiera de los libros antiguos, apoyándose en lo que dice el imam Abu al-Qasim al-Rafiʿi en su comentario —«los libros de la Torá y el Evangelio no se pueden aprovechar, porque cambiaron y alteraron», y lo mismo dijeron otros de la escuela—, [[k:se le responde: eso se limita a lo que se sabe que fue cambiado]].",
      "Nuestro maestro, el gran memorizador de su época, Abu al-Fadl ibn Hajar, trató a fondo la cuestión al final de su comentario de al-Bujari, y lo último que concluyó fue distinguir entre quien está firmemente asentado en las ciencias de la ley —a quien le está permitido mirarlo, porque extrae de ahí lo que aprovecha a los bien guiados— y los demás, a quienes no les está permitido. [[k:Y lo apoyó en que los imames, antiguos y modernos, los han mirado]] y han respondido a la gente de los dos Libros con lo que sacaban de ellos: [[k:si no fuera lícito, no lo habrían hecho]]…",
      "…Luego escribí sobre ello una buena obra, que titulé [[k:«al-Aqwal al-qawima fi hukm al-naql min al-kutub al-qadima»]] («Las opiniones rectas sobre citar los libros antiguos»)."],
  prueba="Al-Biqaʿi (m. 885 H), discípulo de Ibn Hajar, defiende citar la Torá y el Evangelio: la prohibición solo afecta a lo que se sabe que fue cambiado. Y se apoya en la conclusión de su maestro (IH14).",
  ojo="Su postura le costó una dura polémica: al-Sajawi escribió contra él un tratado titulado «La prohibición de citar la Torá y el Evangelio»."),

 dict(id="H22b", year="885 H", who="al-Biqaʿi", postura="Uso positivo",
  title="Un ejemplo: cita Deuteronomio 18 («os suscitaré un profeta de entre vuestros hermanos, como yo»)",
  ref="al-Biqaʿi, Nazm al-durar, sobre el Corán 7:157, vol. 8, pp. 107–108", ar_ref="نظم الدرر للبقاعي ٨/١٠٧–١٠٨", site=IW, url="https://www.islamweb.net/ar/library/content/214/1103/",
  es=["[[k:Y en la Torá también hay algo de esto, en el capítulo once del quinto libro]]: «Cuando entréis en la tierra que os da Dios, vuestro Señor, no hagáis como las obras de esos pueblos, y que no haya entre vosotros quien busque la enseñanza de los adivinos». Luego dice: «Porque esos pueblos cuya tierra heredáis obedecían a adivinos y astrólogos, pero a vosotros no os da eso Dios, vuestro Señor; [[k:sino que os suscitará un profeta de entre vuestros hermanos, como yo]]: obedeced a ese profeta, como pedisteis a Dios, vuestro Señor, en Horeb el día de la asamblea, cuando dijisteis: “Que no oigamos la voz de Dios, nuestro Señor, ni veamos este gran fuego, para no morir”. Y dijo el Señor: “Qué bien han hablado. Les suscitaré un profeta de entre sus hermanos, como tú; pondré Mis palabras en su boca y les dirá lo que Yo le mande; y a quien no acepte la palabra de ese profeta que habla en Mi nombre, Yo me vengaré de él y de su tribu”». Fin. Así lo he visto traducido en algunos ejemplares de la Torá."],
  prueba="Un ejemplo práctico: al-Biqaʿi cita la Torá (Dt 18) en su tafsir, tomada de «algunos ejemplares traducidos», como texto válido para argumentar."),

 dict(id="H22c", year="885 H", who="al-Biqaʿi", postura="Uso positivo",
  title="«…grandes imames, como al-Razi y al-Baghawi, han citado [mucho de ello]»",
  ref="al-Biqaʿi, al-Aqwal al-qawima fi hukm al-naql min al-kutub al-qadima, cap. 6, p. 437 (ed. de tesis de Umm al-Qura)", ar_ref="الأقوال القويمة في حكم النقل من الكتب القديمة، ص ٤٣٧", site=AR, url="https://archive.org/details/20250703_20250703_1416",
  lang="árabe (OCR)",
  es=["[Si lo que molesta a quien lo niega, por su poca familiaridad con los libros de los imames, es que se cite lo que hay en los libros] antiguos, [[k:este imam exegeta y otros grandes imames, como al-Razi y al-Baghawi, han citado]] [mucho de ello]."],
  prueba="En su tratado, al-Biqaʿi señala que grandes exegetas como al-Razi y al-Baghawi ya citaban material de los libros antiguos.",
  ojo="OCR con errores (letras persas). El «consenso tácito» que menciona la Wikipedia en inglés no es de al-Biqaʿi: es de su contemporáneo al-Kafiyaji (m. 879 H), en un aval que al-Biqaʿi reproduce en el capítulo 1 del tratado."),

 dict(id="H23", year="1891 d. C.", who="Rahmatullah al-Kairanawi", postura="Texto alterado",
  title="«La tergiversación literal, con sus tres tipos —cambio, adición y supresión—, está probada»",
  ref="Rahmatullah al-Kairanawi, Izhar al-haqq, vol. 2, p. 427 (ed. Malkawi, Riad, 1989)", ar_ref="إظهار الحق للكيرانوي ٢/٤٢٧", site=SH, url="https://shamela.ws/book/22721/413",
  es=["[La tergiversación] es de dos clases: literal y de sentido. [[a:Entre nosotros y los cristianos no hay disputa sobre la segunda]], porque todos ellos admiten que los judíos la cometieron en el Antiguo Testamento, en la interpretación de los versículos que, según ellos, aluden al Mesías, y en la interpretación de las normas que para los judíos son eternas; y los sabios protestantes reconocen que la cometieron los papistas en los libros de los dos Testamentos, igual que los papistas se lo reprochan con dureza a ellos; así que no hace falta probarla. Queda la primera, que los sabios protestantes niegan en apariencia con vehemencia para confundir a los musulmanes ignorantes, y han presentado en sus tratados pruebas engañosas y falsas para hacer dudar a los lectores; por eso necesita prueba, y quiero probarla en este libro, con la ayuda del Creador de la tierra y los cielos. Y digo: [[k:la tergiversación literal, en todas sus formas —es decir, cambiando palabras, añadiéndolas y suprimiéndolas—, está probada en los libros mencionados]], y expondré estos tres tipos por orden en tres apartados."],
  prueba="Kairanawi (m. 1891), en la obra de referencia de la polémica moderna, sostiene la tergiversación literal. Es la tesis de Tibyanan, y es del siglo XIX.",
  ojo="Fíjate en cómo construye el argumento: usa la crítica bíblica protestante y católica de su época, no fuentes islámicas antiguas."),

 dict(id="H24", year="Siglo XXI", who="Abdullah Saeed, académico musulmán", postura="Positiva", lang="inglés",
  title="«Si los textos siguen más o menos como en el siglo VII, el respeto que el Corán les mostró debería mantenerse hoy»",
  ref="Abdullah Saeed, «The Charge of Distortion of Jewish and Christian Scriptures», The Muslim World 92 (2002), citado en Wikipedia (inglés), «Tahrif»", ar_ref="", site="en.wikipedia.org (versión fija del 21-9-2026)", url="https://en.wikipedia.org/w/index.php?title=Tahrif&oldid=1375960251",
  es=["Aunque haya una corrupción textual asociada a la interpretación, las Escrituras mismas siguen siendo fiables y pueden considerarse «Libros de Dios». Para el Corán, el concepto de «Libro de Dios» se aplicaba con propiedad a las Escrituras de judíos y cristianos, aunque, desde el punto de vista musulmán, quizá no fueran «exactamente como eran» en tiempos de Moisés o de Jesús y, en algunos casos, estuvieran traducidas de las lenguas originales o narradas por alguien distinto del profeta que recibió la revelación. [[k:Como las Escrituras «reconocidas» de judíos y cristianos siguen siendo hoy en gran medida como eran en tiempos del Profeta]], es difícil sostener que las referencias coránicas a la Torá y al Evangelio se referían solo a una Torá y un Evangelio «puros», tal como existían en tiempos de Moisés y de Jesús. [[k:Si los textos siguen más o menos como estaban en el siglo VII]], el respeto que el Corán les mostró entonces debería mantenerse hoy."],
  prueba="Un académico musulmán contemporáneo llega a la misma conclusión: el argumento no es exclusivo de apologistas cristianos.",
  ojo="Wikipedia es una fuente secundaria; el artículo original está en H24b."),

 dict(id="H24b", year="Siglo XXI", who="Abdullah Saeed, académico musulmán", postura="Positiva", lang="inglés",
  title="El artículo original: «casi todos los intérpretes… vieron la corrupción en gran medida en la interpretación»",
  ref="Abdullah Saeed, «The Charge of Distortion of Jewish and Christian Scriptures», The Muslim World 92 (2002), pp. 419–436, conclusión, p. 434", ar_ref="", site="copia en PDF del artículo (alojada por terceros)", url="https://bible-quran-video.s3.amazonaws.com/Documents/The-Charge-of-Distortion-of-Jewish-and-Christian-Scriptures_Abdullah+Saeed.pdf",
  es=["…[[k:casi todos los intérpretes cuyas opiniones se examinan aquí parecen haber visto la corrupción como algo que reside en gran medida en la interpretación]]: por ejemplo, cambiar lo lícito (ḥalāl) en ilícito (ḥarām) o al revés, y ocultar u oscurecer lo que hay en la Escritura para confundir a otros, como en el caso del versículo 5:41. Una adición y una omisión deliberadas y a gran escala, en textos con una larga tradición de transmisión y ampliamente conocidos, serían difíciles. Rāzī y Qurṭubī, en particular, parecen sostener esta opinión. Aunque haya una corrupción textual asociada a la interpretación, las Escrituras mismas siguen siendo fiables y pueden considerarse «Libros de Dios»… [[k:Como las Escrituras «reconocidas» de judíos y cristianos siguen siendo hoy en gran medida como eran en tiempos del Profeta, es difícil sostener que las referencias coránicas a la Torá y al Evangelio se referían solo a una Torá y un Evangelio «puros»]], tal como existían en tiempos de Moisés y de Jesús. [[k:Si los textos siguen más o menos como estaban en el siglo VII, el respeto que el Corán les mostró entonces debería mantenerse hoy]]. [[k:Muchos intérpretes del Corán, de Ṭabarī a Rāzī, a Ibn Taymiyya e incluso a Quṭb, parecen inclinados a compartir esta opinión]]."],
  prueba="En la conclusión de su artículo, Saeed dice que casi todos los intérpretes que estudia (al-Tabari, al-Razi, al-Qurtubi, Ibn Taymiyya…) situaban la corrupción sobre todo en la interpretación.",
  ojo="La copia del PDF está alojada por terceros; para el vídeo basta con esta captura y la referencia de la revista."),
]
