# -*- coding: utf-8 -*-
# ---------- 3. Relatos, heresiógrafos e historiadores ----------
JAW = "Ibn Taymiyya, al-Jawab al-sahih li-man baddala din al-Masih (Dar al-ʿAsima)"
RID = "Sayf ibn ʿUmar, Kitab al-ridda wa-l-futuh, ed. Qasim al-Samarrai (2.ª impr., Riad: Dar Umayya, 1418/1997)"
add(3, "Ibn Ishaq (m. 150 H / 767), en Ibn Hisham", key="II", specs=["T4-29"],
 title="Los cristianos de Najrán, «de la religión del rey»: «el tercero de tres… porque Dios dice “hicimos”; pero es Él, Jesús y María»",
 ref="Ibn Hisham, al-Sira al-nabawiyya, ed. al-Saqqa, al-Abyari y Shalabi (al-Babi al-Halabi), vol. 1, p. 575 (la delegación de los cristianos de Najrán)",
 ar_ref="سيرة ابن هشام ١/٥٧٥", site=SH, url=S + "23833/598",
 es=["Y eran, en cuanto al cristianismo, de la religión del rey, aunque discrepaban entre ellos: [[k:dicen «es Dios», y dicen «es hijo de Dios», y dicen «es el tercero de tres»]]. Y así es lo que dicen los cristianos. Argumentan «es Dios» con que resucitaba a los muertos, curaba las enfermedades, anunciaba lo oculto y creaba del barro algo con forma de pájaro y luego soplaba en él y se convertía en pájaro, y todo eso por orden de Dios —bendito y ensalzado—, «para hacer de él un signo para la gente» (19:21). Argumentan «es hijo de Dios» con que dicen: no se le conoce padre, y habló en la cuna, y eso no lo había hecho nadie de los hijos de Adán antes que él. [[k:Y argumentan «es el tercero de tres» con lo que Dios dice: «hicimos», «mandamos», «creamos», «decretamos»]]; y dicen: si fuera uno, no diría sino «hice», «decreté», «mandé», «creé»; [[k:pero es Él, Jesús y María]]."],
 prueba="Es el texto más antiguo de la biografía del Profeta, del mismo siglo que Muqatil. Ibn Ishaq describe la fe de los cristianos de Najrán, «de la religión del rey» (la Iglesia imperial), y explica su «tercero de tres» como Dios, Jesús y María.",
 ojo="No da fuente: es una descripción del propio Ibn Ishaq. Y se delata sola: los cristianos de Najrán prueban la Trinidad con el plural «hicimos, mandamos» del Corán, un libro en el que no creían. Es un argumento que un musulmán pone en boca de cristianos. Además, según la historia de la Iglesia, los cristianos de Najrán eran sobre todo miafisitas, no de «la religión del rey».")

add(3, "Sayf ibn ʿUmar (m. c. 180 H / 796)", key="Sy", specs=["TS1", "TS2"],
 title="El «rey Pablo» de Sayf: «Matad a los cristianos»… y luego enseña a uno de los cuatro: «el tercero de tres: Jesús es hijo, y su padre, y su madre»",
 ref=f"{RID}, n.º 133, pp. 136 y 138 (escaneo del libro impreso)",
 ar_ref="الردة والفتوح لسيف بن عمر ص ١٣٦ و١٣٨، رقم ١٣٣", site="archive.org (escaneo; es el mismo PDF que islamland.com/uploads/books/35696.pdf)", url="https://archive.org/details/20220829_20220829_1712 (pp. 136 y 138)",
 lang="árabe (escaneo de la edición impresa)",
 es=["[133] [[k:Nos contó al-Sari: dijo: nos contó Shuʿayb: dijo: nos contó Sayf, de ʿAtiyya, de Yazid al-Faqʿasi, de Ibn Abbas, que dijo]]: Jesús —la paz sea con él— llamó a los hijos de Israel, y le respondieron los que Dios quiso. Cuando Dios —poderoso y majestuoso— lo elevó, a la gente le agradaron sus palabras, y sus compañeros llegaron a setecientas familias. [[k:Entonces dijo Pablo —cuyo sobrenombre era Abu Shaʾul, y era el rey en aquel tiempo—]]: «Matad a los cristianos». Huyeron; los persiguió a caballo hasta llegar a los pasos de montaña, y se le escaparon. Entonces les dijo Pablo: «Sus palabras son agradables y han entrado en vuestros enemigos; no…»",
     "…Dijeron: «¡Dilo!». Dijo: «Sacad de aquí a la gente de la casa», y no quedaron más que Jacobo, Nestorio, Malkun y el Creyente. Lo hicieron, y dijo: «¿Sabéis de algún ser humano que creara del barro una criatura, soplara en ella y se convirtiera en un ser vivo?». Dijeron: «No». Dijo: «¿Sabéis de algún ser humano que curara al ciego y al leproso y resucitara a los muertos?». Dijeron: «No». Dijo: «¿Sabéis de algún ser humano que anunciara a la gente lo que comen y lo que guardan en sus casas?». Dijeron: «No». Dijo: «[[k:Pues yo afirmo que Dios —ensalzado sea— se nos manifestó y luego se ocultó]]». Uno de ellos dijo: «¡Es verdad!». [[k:El otro dijo: «Es Dios, y Jesús es Su hijo». Y el otro dijo: «No; sino que es el tercero de tres: Jesús es hijo, y su padre, y su madre»]]. [[a:Y el Creyente se espantó y dijo: «¡Dios os maldiga!; ¡ay de vosotros!; por Dios, este no ha pretendido otra cosa que corromperos!»]]. Y nos asombra que lo aceptemos de él, cuando nosotros somos los compañeros de Jesús y él no…"],
 prueba="Es el relato que citaba el análisis que enviaste. Pablo, que aquí es «el rey» y persigue a los cristianos, finge convertirse y enseña cuatro doctrinas a cuatro discípulos. Una de ellas es la «trinidad» de Jesús, su padre y su madre. La cadena impresa es exactamente la que daba el análisis (más detalles en la sección 5).",
 ojo="Es una leyenda: Pablo nunca fue rey, y Nestorio (siglo V) y Jacobo (siglo VI) no pudieron ser discípulos de Pablo. Además, la «trinidad» de padre, madre e hijo sale del Corán (5:116), no de ningún texto cristiano (#Fk#). Ni siquiera al-Tabari recoge este relato (#SyN#).")

again(3, "al-Farraʾ (m. 207 H / 822)", 'R14', key="Fa",
 prueba="El germen de la leyenda de Pablo en un gramático del siglo II H: «un hombre malvado» se mete entre los cristianos y enseña tres doctrinas: «Él es Él», «es Su hijo», «es el tercero de tres».",
 ojo="Aquí el «tercero de tres» no incluye a María: no se dice quiénes son los tres. Sin nombre ni fuente («se cuenta»). La versión con María aparece en Sayf (#Sy#) y en al-Thaʿlabi (#Tl#).")

again(3, "al-Thaʿlabi (m. 427 H / 1035)", 'R34', key="Tl",
 prueba="La versión «clásica» de la leyenda de Pablo, la que repiten los comentaristas de 9:30. Pablo deja como sucesor a Nestorio «y le enseñó que Jesús, María y el dios eran tres». Otra vez la trinidad con María, atribuida a un discípulo concreto.",
 ojo="No da fuente. En su comentario de 5:73, el mismo al-Thaʿlabi dice que los nestorianos creen en «Padre, Hijo y Espíritu Santo» (#Th#). Es decir, sabía que esa no era su doctrina. Además, Nestorio (siglo V) no pudo ser discípulo de Pablo (siglo I).")

add(3, "al-Yaʿqubi (m. c. 292 H / 905)", key="Yq", specs=["tYq3"],
 title="Constantino cuenta trece doctrinas sobre Jesús; la primera: «el Mesías y su madre eran dos dioses»",
 ref="al-Yaʿqubi, Tarikh, vol. 1 (apartado «Los reyes cristianos de los romanos»), p. 60 de ketabonline (paginación automática, no la impresa)",
 ar_ref="تاريخ اليعقوبي ١/٦٠ (ترقيم آلي)", site="ketabonline.com", url="https://ketabonline.com/ar/books/18614/read?part=1&page=60",
 es=["El primero de los reyes de los romanos que pasó de la doctrina griega al cristianismo fue Constantino. La causa fue que estaba en guerra con un pueblo, [[k:y vio en sueños como si bajaran del cielo lanzas con cruces encima]]; al amanecer puso cruces en sus lanzas, combatió y venció, y esa fue la causa de que se hiciera cristiano. […] [[k:Y se reunieron en Nicea trescientos dieciocho obispos]] y cuatro patriarcas […].<br>La causa de que Constantino los reuniera fue que, cuando se hizo cristiano, quiso conocerlo a fondo; contó las doctrinas de sus fieles [[k:y encontró trece doctrinas]]: [[k:la de quien decía que el Mesías y su madre eran dos dioses]]; la de quien decía que procede del Padre como una llama que se separa de otra; la de quien afirmaba su divinidad; la de quien afirmaba que era siervo; […] la de quien decía que es la Palabra; la de quien decía que es el Hijo; […] [[k:la de quien decía que es un profeta entre los profetas]]; y la de quien decía que es divino y humano. […]"],
 prueba="Un historiador musulmán del siglo III H pone la creencia «el Mesías y su madre eran dos dioses» entre las trece doctrinas que Constantino encontró antes de Nicea. Es una doctrina minoritaria entre otras.",
 ojo="Es la misma lista que da el cronista cristiano Ibn al-Bitriq un siglo después (#Bt#). Pero Nicea no la confirma: el credo de los 318 obispos es otro. Al-Yaʿqubi no da fuente. La paginación de ketabonline es automática y no corresponde a la edición impresa.")

add(3, "al-Yahiz (m. 255 H / 869)", key="Jh", specs=["T2-22", "T2-23"],
 title="Siglo III H: los cristianos ya protestaban: «nunca creyeron que María fuera diosa, ni en secreto ni en público»",
 ref="al-Yahiz, al-Mujtar fi l-radd ʿala l-nasara, ed. Muhammad ʿAbd Allah al-Sharqawi, pp. 53–54 (introducción del autor)",
 ar_ref="المختار في الرد على النصارى للجاحظ ص ٥٣–٥٤", site=SH, url=S + "37716/2 · 37716/3",
 es=["Y mencionasteis que dijeron: la prueba de que nuestro libro es falso y nuestra religión corrupta es [[k:que les atribuimos lo que no conocen entre ellos ni conocen de sus antepasados]], porque afirmamos que Dios —poderoso y majestuoso— dijo en Su libro por boca de Su profeta Muhammad ﷺ: [[k:«Y cuando Dios dijo: Jesús, hijo de María, ¿dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?»]],",
     "[[k:y que afirman que nunca profesaron que María fuera diosa en secreto, ni lo pretendieron jamás en público]]. Y que afirman [[k:que les atribuimos lo que no conocen]], como atribuimos a los judíos lo que no conocen, cuando nuestro libro dijo y nuestro profeta atestiguó que los judíos dijeron: ʿUzayr es hijo de Dios, la mano de Dios está atada y Dios es pobre y ellos ricos. Y eso no lo dice ningún ser humano ni se conoce en ninguna religión."],
 prueba="Es el registro musulmán más antiguo de la objeción cristiana. Ya en el siglo III H los cristianos decían que 5:116 les atribuye algo que «no conocen»: nunca creyeron que María fuera diosa.",
 ojo="Es al-Yahiz quien cuenta la objeción, no un texto cristiano. Y el resumen que se conserva de su obra no recoge su respuesta a este punto concreto.")

add(3, "Ibn al-Bitriq (Eutiquio, m. 328 H / 940) y su cita en Ibn Taymiyya", key="Bt", specs=["TE1", "T2-02"],
 title="Un patriarca cristiano: en Nicea, entre 2.048 obispos, «había quien decía que el Mesías y su madre son dos dioses aparte de Dios: los barbaranitas, llamados marianitas»",
 ref="Saʿid ibn al-Bitriq (Eutiquio de Alejandría), Nazm al-yawhar (Annales), ed. L. Cheikho (CSCO), vol. 1, p. 126; y su cita en " + JAW + ", vol. 4, p. 220",
 ar_ref="تاريخ ابن البطريق ١/١٢٦؛ الجواب الصحيح ٤/٢٢٠", site="archive.org (escaneo de la ed. Cheikho) y shamela.ws", url="https://archive.org/details/annaleseuty00euty/page/n133 · " + S + "170/1554",
 lang="árabe (escaneo de la edición impresa y cita en Ibn Taymiyya)",
 es=["…y lo expliquemos a toda la gente. Y el rey Constantino mandó a todos los países, reunió a los patriarcas y a los obispos, y se reunieron en la ciudad de Nicea, al cabo de un año y dos meses, dos mil cuarenta y ocho obispos; y eran de opiniones y religiones distintas. [[k:Entre ellos estaba quien decía que el Mesías y su madre son dos dioses aparte de Dios; y son los barbaranitas, y se les llama marianitas]]. Y entre ellos estaba quien decía que el Mesías es, respecto al Padre, como…",
     "Y el rey Constantino mandó a todos los países, reunió a los patriarcas y a los obispos, y se reunieron en la ciudad de Nicea, al cabo de un año y dos meses, dos mil cuarenta y ocho obispos, [[k:y eran de opiniones y de religiones distintas]]. [[k:Entre ellos estaba quien decía: «el Mesías y María son dos dioses aparte de Dios»; y son los mariamanitas]], y se les llama marianitas."],
 prueba="Es el único autor cristiano antiguo, aparte de Epifanio, que menciona una secta que divinizaba a María: los «barbaranitas» o «marianitas». De él copian Ibn Taymiyya, al-Maqrizi y probablemente Ibn Hazm. El escaneo muestra el texto impreso de la edición crítica.",
 ojo="Ibn al-Bitriq escribe en el siglo X, seis siglos después de Nicea, y repite casi palabra por palabra la frase del Corán («dos dioses aparte de Dios»). No menciona tortas, ni mujeres, ni Arabia, ni da fuente. Sus 2.048 obispos no son históricos. Y la secta es una de las minorías rechazadas, no la doctrina del concilio. (En el escaneo, la nota 2 corrige «ilahayn» en «ilahan», un cambio gramatical.)")

add(3, "al-Maqdisi (m. después de 355 H / 966)", key="Mqd", specs=["T2-38"],
 title="al-Maqdisi: melquitas, jacobitas y nestorianos «están de acuerdo en que lo que adoran son tres hipóstasis: Padre, Hijo y Espíritu Santo, un solo Dios»",
 ref="al-Mutahhar ibn Tahir al-Maqdisi, al-Badʾ wa-l-taʾrij, ed. Cl. Huart (París: Leroux), vol. 4, p. 42",
 ar_ref="البدء والتاريخ ٤/٤٢", site=SH, url=S + "12318/702",
 es=["En cuanto a los melquitas, los jacobitas y los nestorianos, [[a:están de acuerdo en que lo que adoran son tres hipóstasis]], y que estas tres hipóstasis son una sola cosa, una sustancia eterna, [[a:y su sentido es: Padre, Hijo y Espíritu Santo, un solo Dios]]; y que el Hijo bajó del cielo [[a:y se revistió de un cuerpo de María]], y apareció a la gente resucitando, curando y anunciando; luego fue muerto, crucificado y herido, salió de la tumba al tercer día, se apareció a un grupo de sus compañeros, que lo reconocieron plenamente, y luego subió al cielo y se sentó a la derecha de Dios. Esto es lo que todos ellos creen."],
 prueba="Un historiador musulmán del siglo IV H describe bien la fe común de las tres iglesias: Padre, Hijo y Espíritu Santo, un solo Dios. María es solo de quien el Hijo tomó un cuerpo.",
 ojo="Ninguno. En su lista de sectas cristianas no aparece ninguna que adorara a María.")

add(3, "al-Qadi ʿAbd al-Yabbar (m. 415 H / 1025)", key="AJ", specs=["T2-24", "T2-25", "T2-26"],
 title="ʿAbd al-Yabbar: los cristianos dicen «es mentira: de su madre no dijimos que fuera diosa»; respuesta: «no es una afirmación, es una pregunta»… y la veneración",
 ref="al-Qadi ʿAbd al-Yabbar, Tathbit dalaʾil al-nubuwwa, ed. ʿAbd al-Karim ʿUthman (Dar al-Mustafa), vol. 1, pp. 145–147",
 ar_ref="تثبيت دلائل النبوة ١/١٤٥–١٤٧", site=SH, url=S + "9789/153 · 9789/154 · 9789/155",
 es=["Y dijo vuestro compañero en vuestro libro: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?». [[k:Y dijeron los cristianos: «Esto es mentira, pues aunque digamos de él que es dios, de su madre no dijimos que sea diosa»]]. [[k:Se le responde: no informó de que ellos dijeran eso]]; aquí no hay una afirmación que pueda ser verdad o mentira. Solo dijo «¿Dijiste tú…?», y eso no es una afirmación […]; lo aparente de esta frase es la pregunta […], [[k:y su sentido es hacer confesar, para sacar la respuesta del preguntado]]. Es como cuando le dice a Moisés: «¿Qué es eso que tienes en la diestra, Moisés?» […]. Así le dijo al Mesías: ¿dijiste esto de ti o de tu madre, la que te dio a luz […]?, para que se viera su inocencia por todos los lados. […] [[k:Y además, entre los cristianos hay quien ha dicho el sentido de esto, aunque no lo haya dicho con estas palabras]], porque dijeron que María quedó pura cuando recibió la sustancia divina y la dio a luz, y toda sustancia no recibe…",
     "…sino lo que es de su sustancia […], y esta es una segunda respuesta clara: entre ellos hay quien lo ha dicho abiertamente. Y esto está claro en los libros de la iglesia que hay en Juzistán y en otras regiones de Irak, en escritura siríaca; y se ha traducido de ello en una carta que escribió ʿAbd Yashuʿ ibn Bahriz, obispo de Harrán y Raqqa y luego metropolitano de Mosul y la Yazira, a un sacerdote jacobita llamado Badus: [[k:«Tú no niegas que la Virgen pura es dios, como tú la ves, sino un ser humano, como la vemos nosotros»]]. [[k:Y esto es una declaración de estos de que María es dios, y los nestorianos les contradicen en eso]] […]. Y dicen que ella es la madre del Mesías, hijo de Dios, […] [[k:y que está sentada en el trono a la izquierda del Señor, padre de su hijo, y su hijo a Su derecha]]. [[k:Y la invocan y le piden abundancia de sustento]], salud del cuerpo, larga vida y perdón de los pecados, y que sea para ellos, ante su hijo y el padre de su hijo, muralla, apoyo, tesoro, intercesora y pilar. Y si un hombre honrara a otro con la décima parte de esta veneración…",
     "…se podría decir en la lengua de los árabes, y en cualquier lengua, [[k:que lo ha tomado por dios]]. ¿No ves Su palabra «Han tomado a sus rabinos y a sus monjes como señores aparte de Dios» (9:31)? Y no ayunaron ni rezaron para ellos, sino que los imitaron: les prohibieron lo lícito y lo prohibieron […]. Y esto es menos que lo que dijeron de María. […] Y aunque no tuviéramos esos textos de los que dijeron de ella que es diosa […]; la veneraron y la elevaron sobre los ángeles y los profetas, y le pidieron lo que se pide a Dios […], hasta el punto de que los jacobitas dicen en sus súplicas a María: «[[k:¡Oh María, madre del Mesías, sé para nosotros muralla, apoyo, tesoro y pilar!]]», y los nestorianos dicen: «¡Oh madre del Mesías, sé para nosotros lo mismo!»; y reprochan la súplica de los jacobitas y les dicen: «[[k:No digáis “madre de Dios”; decid “madre del Mesías”]]»…"],
 prueba="Es la discusión más seria del tema en un teólogo musulmán clásico. ʿAbd al-Yabbar (siglo V H) recoge la objeción cristiana tal cual («de su madre no dijimos que sea diosa») y da tres respuestas: 5:116 es solo una pregunta; algunos lo dicen «en sentido»; y la veneración equivale a «tomarla por dios», como en 9:31.",
 ojo="Su única prueba de que alguien la llamó «dios» es una carta polémica de un obispo nestoriano contra los jacobitas. El nestoriano exagera la postura rival para atacar el título «Madre de Dios». Las súplicas que cita son peticiones de intercesión («sé para nosotros… intercesora»), no la creencia en una diosa. Y su primera respuesta reconoce que 5:116 «no informa» de que los cristianos lo dijeran.")

add(3, "Ibn Hazm (m. 456 H / 1064)", key="IHz", specs=["T2-04", "T2-05"],
 title="Ibn Hazm: «los barbaranitas dicen que Jesús y su madre son dos dioses aparte de Dios»… «y este grupo ya ha desaparecido»",
 ref="Ibn Hazm, al-Fisal fi l-milal wa-l-ahwaʾ wa-l-nihal (Maktabat al-Janyi), vol. 1, pp. 47–48",
 ar_ref="الفصل لابن حزم ١/٤٧–٤٨", site=SH, url=S + "6521/39 · 6521/40",
 es=["Y los cristianos son grupos. Entre ellos, los seguidores de Arrio […]. Y entre ellos, los seguidores de Pablo de Samosata […]; [[a:su doctrina era el monoteísmo puro y verdadero]], y que Jesús es siervo de Dios y Su mensajero como uno de los profetas […]. Y entre ellos estaba Macedonio […]. [[k:Y entre ellos, los barbaranitas, que dicen que Jesús y su madre son dos dioses aparte de Dios —poderoso y majestuoso—]].",
     "[[k:Y este grupo ya ha desaparecido]]. Su núcleo hoy son tres grupos; el mayor es el de los melquitas, que es la doctrina de todos los reyes cristianos dondequiera que estén, salvo Abisinia y Nubia […]. Y dicen que Dios es lo que expresan con [[a:tres causas: Padre, Hijo y Espíritu Santo, todas eternas]]; que Jesús es Dios completo y hombre completo […]; [[a:y que María dio a luz a Dios y al hombre]], y que ambos juntos son una sola cosa, hijo de Dios —ensalzado sea Dios por encima de su incredulidad—."],
 prueba="Ibn Hazm, el gran heresiógrafo andalusí, conoce una secta que hacía de Jesús y su madre «dos dioses aparte de Dios», con el mismo nombre que da Ibn al-Bitriq (#Bt#): los barbaranitas.",
 ojo="Ibn Hazm dice que esa secta «ya ha desaparecido» y que la Trinidad de las iglesias de su tiempo es Padre, Hijo y Espíritu Santo (en azul). Su descripción de la secta copia otra vez las palabras del Corán. Además, en la frase siguiente pone a Pablo de Samosata «antes del cristianismo», lo que muestra que su información histórica no es fiable.")

add(3, "al-Shahrastani (m. 548 H / 1153)", key="Sh", specs=["T2-10", "T2-11"],
 title="al-Shahrastani: «uno en la sustancia y tres en las hipóstasis»: «los llamaron Padre, Hijo y Espíritu Santo»; María «dio a luz a un dios eterno»",
 ref="al-Shahrastani, al-Milal wa-l-nihal (Muʾassasat al-Halabi), vol. 2, pp. 26–27 (capítulo sobre los cristianos)",
 ar_ref="الملل والنحل للشهرستاني ٢/٢٦–٢٧", site=SH, url=S + "11812/263 · 11812/265",
 es=["…por sí misma, no por ocupar un lugar ni tener volumen. [[a:Así que es uno en la sustancia y tres en las hipóstasis]]; [[a:y con las hipóstasis se refieren a atributos, como la existencia, la vida y el conocimiento]], [[a:y los llamaron Padre, Hijo y Espíritu Santo]]; y solo el conocimiento se revistió y se encarnó, no las demás hipóstasis.",
     "Y los melquitas declararon que la sustancia es distinta de las hipóstasis, como lo descrito y el atributo; [[a:y por eso declararon la Trinidad, y de ellos informó el Corán]]: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres». Y dijeron los melquitas: el Mesías es humanidad universal, no particular, y es eterno desde la eternidad, de un eterno; [[a:y María —la paz sea con ella— dio a luz a un dios eterno]]."],
 prueba="El manual de religiones más famoso del islam medieval explica el «tercero de tres» de 5:73 con la Trinidad melquita: Padre, Hijo y Espíritu Santo. María solo aparece como la que dio a luz a Dios.",
 ojo="Ninguno contra el punto. En todo su capítulo sobre los cristianos no aparece ninguna secta que adorara a María.")

add(3, "Ibn Taymiyya (m. 728 H / 1328)", key="IT1", specs=["T2-12", "T2-13", "T2-14"],
 title="Ibn Taymiyya: el «tercero de tres» es el de «Padre, Hijo y Espíritu Santo»; la lectura de Jesús y su madre es de «un grupo», y los marianitas «dicen que María es dios»",
 ref=f"{JAW}, vol. 2, pp. 13–15",
 ar_ref="الجواب الصحيح ٢/١٣–١٥", site=SH, url=S + "170/399 · 170/400 · 170/401",
 es=["…lo explicaron con la Trinidad conocida de ellos, la que está en su Credo. Y hay quien dice que «Dios es el Mesías, hijo de María» es lo que dicen los jacobitas, [[a:y que «el tercero de tres» es lo que dicen los cristianos que hablan del Padre, el Hijo y el Espíritu Santo]], que con ellos hicieron a Dios el tercero de tres [[a:y llamaron a cada uno de los tres dios y señor]]. [[k:Y un grupo lo explicó con que hicieron a Jesús y a su madre dos dioses a los que se adora aparte de Dios]].",
     "[al-Suddi] dijo: [[k:Dijeron los cristianos: «Dios es el Mesías y su madre». Y eso es Su palabra]]: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116). Y se ha dicho una tercera opinión, más extraña aún, de Abu Sajr: […] es lo que dicen los judíos, «ʿUzayr es hijo de Dios», y los cristianos, «el Mesías es hijo de Dios», y así hicieron a Dios el tercero de tres; [[k:y esto es débil]]. [[k:Y Saʿid ibn al-Bitriq ha mencionado, en las noticias de los cristianos]], que hay entre ellos un grupo al que llaman…",
     "[[k:…los marianitas, que dicen que María es dios y que Jesús es dios]]. [[a:Y la primera [opinión] es la acertada]], [[a:pues todos los cristianos que están de acuerdo con el Credo dicen que Dios es el tercero de tres]], y Dios les prohibió decirlo: «¡Gente del Libro! No exageréis en vuestra religión […] y no digáis tres» (4:171); y mencionó en esta aleya la Trinidad y la unión, y se las prohibió."],
 prueba="Ibn Taymiyya, el gran polemista contra los cristianos, prefiere entender el «tercero de tres» como la Trinidad del Credo: Padre, Hijo y Espíritu Santo. La lectura con María la atribuye a «un grupo» de comentaristas, y la secta marianita la conoce solo por Ibn al-Bitriq.",
 ojo="Es una concesión importante para el debate. Para Ibn Taymiyya, 5:73 y 4:171 se refieren a la Trinidad real y no a María. María queda solo en 5:116 y se refiere a una secta concreta (#IT2#).")

add(3, "Ibn Taymiyya (m. 728 H / 1328)", key="IT2", specs=["T2-17", "T2-18", "T2-19"],
 title="Ibn Taymiyya: unos le piden a María su intercesión, otros le piden directamente, «y otros la adoran como adoran al Mesías»… y 5:116 «no lo cuenta de todos los cristianos»",
 ref=f"{JAW}, vol. 4, pp. 255–257",
 ar_ref="الجواب الصحيح ٤/٢٥٥–٢٥٧", site=SH, url=S + "170/1589 · 170/1590 · 170/1591",
 es=["Y mencionó —glorificado y ensalzado sea— que los dos comían alimentos, porque eso es de las pruebas más claras de que son criaturas sometidas a un señor, pues el Creador es uno, eterno, no come ni bebe. [[k:Y mencionó a María junto con el Mesías porque hay cristianos que la tomaron por otro dios y la adoraron como adoraron al Mesías]]. [[k:Y los que no dicen esto]], muchos de ellos le piden todo lo que se pide…",
     "…a Dios, hasta decirle: «perdóname y ten misericordia de mí», y otras cosas, sobre la base de que ella intercede por eso ante su hijo. [[k:Unas veces dicen: «¡Oh madre de Dios, intercede por nosotros ante Dios!»]]; otras le piden las necesidades que se piden a Dios, sin mencionar intercesión; [[k:y otros la adoran como adoran al Mesías]]. Y Saʿid ibn al-Bitriq contó esto de ellos al mencionar su reunión con Constantino en Nicea. Dijo: y eran de opiniones y religiones distintas. [[k:Entre ellos estaba quien decía: el Mesías y su madre son dos dioses aparte de Dios; son los mariamanitas]], y se les llama marianitas; [[k:así lo dijo Ibn Hazm]]. Y Dios dijo: «Y cuando Dios dijo: Jesús, hijo de María, ¿dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios? […]» (5:116–117). [[k:Y Él —glorificado sea— no contó esto de todos los cristianos]], sino que preguntó…",
     "…al Mesías [[k:una pregunta con la que reprende a quien lo tomó a él y a su madre como dos dioses aparte de Dios]]."],
 prueba="Ibn Taymiyya distingue tres casos: los que piden la intercesión de María, los que le piden directamente, y un grupo que la adora como al Mesías, la secta de Ibn al-Bitriq. Y concluye que 5:116 «no lo cuenta de todos los cristianos».",
 ojo="Es otra concesión importante: según Ibn Taymiyya, el versículo no describe la fe cristiana en general, sino a una secta. Su prueba de esa secta es, otra vez, solo Ibn al-Bitriq, y a través de él, Ibn Hazm.")

add(3, "Ibn Taymiyya (m. 728 H / 1328)", key="IT3", specs=["T2-20", "T2-21"],
 title="Ibn Taymiyya: llamar al Mesías «hijo de Dios» les obliga a hacer a María «compañera de Dios y Su mujer», «como dijeron algunos exagerados»",
 ref=f"{JAW}, vol. 4, pp. 486–487",
 ar_ref="الجواب الصحيح ٤/٤٨٦–٤٨٧", site=SH, url=S + "170/1820 · 170/1821",
 es=["Y lo que aclara esto es que los cristianos selectos y sus sabios —aunque permitan decir que el Mesías es hijo de Dios— [[k:se ven obligados a que María sea la compañera de Dios y Su mujer]], [[k:como dijeron algunos de ellos que exageran]]; [[k:y hay entre ellos quien hace a María diosa junto con Dios, como hizo dios al Mesías]]. Y si dicen eso, hacen a Dios compañera e hijo, y hacen al Mesías, hijo…",
     "…de María, y a su madre dos dioses aparte de Dios, como hizo quien lo hizo de ellos. [[k:Pues adoran a María y la invocan con lo que invocan a Dios]] —glorificado sea— y al Mesías, [[k:y la hacen diosa como hacen dios al Mesías]], y dicen: [[k:«¡Oh madre de Dios, perdónanos y ten misericordia de nosotros!»]], y cosas así, y le piden lo que se pide a Dios —poderoso y majestuoso—. [[k:Y hay entre ellos quien dice de María que es la compañera de Dios]] —glorificado y ensalzado sea—."],
 prueba="Aquí Ibn Taymiyya lleva la idea al extremo. Si Jesús es «hijo de Dios», María sería la «compañera» de Dios, y dice que algunos «exagerados» lo dijeron. Es la lógica de 6:101 (#Q101#): un hijo requiere una compañera.",
 ojo="No da ninguna fuente cristiana que llame a María «compañera» o «mujer» de Dios. Es su deducción polémica. Y las oraciones que cita («madre de Dios, ten misericordia») son súplicas de intercesión de la liturgia, no la creencia en una diosa.")

add(3, "Ibn Qayyim al-Yawziyya (m. 751 H / 1350)", key="IQ", specs=["T2-27"],
 title="Ibn Qayyim: «una secta cuyo dogma es que Dios es el tercero de tres, que María es Su compañera y que el Mesías es Su hijo»",
 ref="Ibn Qayyim al-Yawziyya, Hidayat al-hayara fi aywibat al-yahud wa-l-nasara (ʿAtaʾat al-ʿIlm), p. 16",
 ar_ref="هداية الحيارى ص ١٦", site=SH, url=S + "5705/85",
 es=["Di lo que quieras de una secta [[k:cuyo dogma básico es que Dios es el tercero de tres, que María es Su compañera y que el Mesías es Su hijo]]; que Él bajó del trono de Su grandeza [[k:y se fundió con el vientre de la compañera]], y le pasó lo que le pasó hasta que fue muerto, murió y fue enterrado. Su religión es adorar las cruces e invocar las imágenes pintadas de rojo y amarillo en las paredes; [[k:dicen en sus súplicas: «¡Oh madre de Dios, danos sustento, perdónanos y ten misericordia de nosotros!»]]."],
 prueba="El discípulo de Ibn Taymiyya resume la fe cristiana como una familia divina: Dios, Su «compañera» María y Su hijo. Es la versión más cruda de la idea del Padre, la Madre y el Hijo.",
 ojo="Es polémica, no descripción. Ningún credo cristiano llama a María «compañera» de Dios. Su maestro Ibn Taymiyya reconoce que la Trinidad del Credo es Padre, Hijo y Espíritu Santo (#IT1#) y que 5:116 no se refiere a todos los cristianos (#IT2#).")

add(3, "al-Maqrizi (m. 845 H / 1442)", key="Mz", specs=["T2-01"],
 title="al-Maqrizi: en Nicea, «entre ellos quien decía que el Mesías y su madre son dos dioses aparte de Dios: los mariamitas»",
 ref="al-Maqrizi, al-Mawaʿiz wa-l-iʿtibar bi-dhikr al-jitat wa-l-athar (Dar al-Kutub al-ʿIlmiyya), vol. 4, p. 398",
 ar_ref="خطط المقريزي ٤/٣٩٨", site=SH, url=S + "11566/1729",
 es=["Y se reunieron seis meses después en la ciudad de Nicea, [[k:y eran dos mil trescientos cuarenta obispos, en desacuerdo sobre el Mesías]]. Entre ellos había quien decía que el Hijo procede del Padre como una llama de fuego que se enciende de otra […]; y quien decía que María no llevó al Mesías nueve meses, sino que pasó por sus entrañas como el agua por el canalón […]; y quien decía que el Mesías es un hombre creado […], y esta es la doctrina de Pablo de Samosata […]; y quien decía que los dioses son tres, uno bueno, uno malo y uno justo entre ellos, y esta es la doctrina de Marción y sus seguidores; [[k:y quien decía que el Mesías y su madre son dos dioses aparte de Dios, y esta es la doctrina de los mariamitas (al-Maraʾima), de entre las sectas de los cristianos]]; y quien decía que Dios creó al Hijo, que es la Palabra, en la eternidad […]; y quien decía que el Hijo es engendrado del Padre antes de todos los tiempos, no creado, sustancia de Su sustancia, luz de Su luz […], y esta es la doctrina de los trescientos dieciocho."],
 prueba="Al-Maqrizi copia la lista de Ibn al-Bitriq (sin citarlo aquí). La secta mariamita es una de las doctrinas presentes en Nicea, junto a Marción, Pablo de Samosata y otras.",
 ojo="Es la misma fuente única de siempre (#Bt#). Y la doctrina de los 318, el Credo de Nicea, es «engendrado, no creado, sustancia de Su sustancia», sin María. Al-Maqrizi da 2.340 obispos, otra cifra distinta de la de Ibn al-Bitriq.")

add(3, "al-Qurtubi, al-Iʿlam (siglo VII H)", key="QI", specs=["T2-29", "T2-30"],
 title="«Las tres hipóstasis son para vosotros dioses, Jesús es un cuarto… y una facción vuestra afirma que María es diosa»",
 ref="al-Qurtubi, al-Iʿlam bi-ma fi din al-nasara min al-fasad wa-l-awham, ed. Ahmad Hiyazi al-Saqqa, pp. 114 y 254",
 ar_ref="الإعلام بما في دين النصارى من الفساد والأوهام ص ١١٤ و٢٥٤", site=SH, url=S + "6517/68 · 6517/203",
 es=["Y es que [[k:las tres hipóstasis son para vosotros dioses, y Jesús es un cuarto dios]], y el cuerpo, un quinto; [[k:y una facción vuestra pretende que María es diosa]], así que los dioses, según esa facción, son seis.",
     "Así que Dios declaró inocentes al Mesías y a su madre, por boca de Su profeta, de lo que los judíos dijeron de ellos […]; y así como atestiguó la inocencia del Mesías y de su madre de lo que les atribuyeron los judíos, atestiguó su inocencia de lo que vosotros les atribuisteis y les inventasteis. [[k:Y es que una facción vuestra dice que María es diosa]], [[a:y vosotros os habéis puesto de acuerdo en que el Mesías es dios e hijo de Dios]], y nuestro profeta —la paz sea con él— dice, informando de Dios: «El Mesías, hijo de María, no es más que un mensajero; antes de él pasaron otros mensajeros, y su madre es veraz» (5:75)."],
 prueba="Un polemista andalusí, escribiendo contra un cristiano, cuenta las tres hipóstasis como los «dioses» cristianos y a María como un dios más, pero solo según «una facción».",
 ojo="Él mismo distingue: el acuerdo de los cristianos es que el Mesías es Dios e hijo de Dios (en azul). La divinidad de María la atribuye solo a «una facción», sin decir cuál.")

add(3, "Salih ibn al-Husayn al-Yaʿfari (m. 668 H / 1270)", key="Jf", specs=["T2-36", "T2-37"],
 title="al-Yaʿfari: rezar a María «añade a la Trinidad un cuarto dios»… «y los dioses son seis: el Padre, el Hijo, el Espíritu Santo, el Mesías, María y el Bautista»",
 ref="Salih ibn al-Husayn al-Yaʿfari, Tajyil man harrafa al-Tawrat wa-l-Inyil, ed. Mahmud ʿAbd al-Rahman Qadah (Maktabat al-ʿUbaykan), vol. 2, pp. 634 y 640",
 ar_ref="تخجيل من حرف التوراة والإنجيل ٢/٦٣٤ و٢/٦٤٠", site=SH, url=S + "12002/593 · 12002/599",
 es=["Y sabe que esta oración también se dedica a adorar a María —la paz sea con ella—, y está fuera de los principios de los cristianos; [[k:porque al cuerpo de María no se le unió nada, según todos los cristianos, sino que su cuerpo es como los demás cuerpos de los hijos de Adán]]. Y si fuera lícito adorar a María por haber llevado al Mesías por promesa de Dios, sería lícito adorar a Isabel, a Sara y a Agar, pues llevaron [hijos] por promesa de Dios. [[k:Así que los cristianos han añadido a la Trinidad]] / [[k:un cuarto dios, y han contradicho a la gente antigua de su religión]].",
     "Y en esta oración han añadido un sexto dios, que es Juan, pues dijeron: «¡Oh Juan, el que bautizó al Mesías, sálvanos de las desgracias!». [[k:Así que los dioses son seis: el Padre, el Hijo, el Espíritu Santo, el Mesías, María y el Bautista]]."],
 prueba="El polemista egipcio critica las oraciones a María de la liturgia como si fueran adoración. Pero, al hacerlo, deja claro que María no está en la Trinidad: añadirla sería un «cuarto dios».",
 ojo="Reconoce que «según todos los cristianos» María es un ser humano como los demás, sin unión con la divinidad. Su cuenta de «seis dioses», que incluye a Juan el Bautista, muestra que trata la intercesión de los santos como si fuera adoración. Al-Qarafi (m. 684 H) repite el mismo argumento.")

add(3, "al-Yaʿfari (m. 668 H) y su editor moderno", key="Jf2", specs=["T2-34", "T2-35"],
 title="Los «marianitas» de al-Yaʿfari negaban la virginidad de María; el editor moderno: «la Iglesia no reconoce la divinidad de María»",
 ref="al-Yaʿfari, Tajyil man harrafa al-Tawrat wa-l-Inyil, ed. Mahmud ʿAbd al-Rahman Qadah, vol. 2, p. 606 y nota 2 del editor",
 ar_ref="تخجيل من حرف التوراة والإنجيل ٢/٦٠٦ وحاشيته", site=SH, url=S + "12002/565",
 es=["Y entre los cristianos hay [[k:una secta conocida como los marianitas (al-Maryamiyya)]], [[k:que afirman que María, cuando dio a luz al Mesías, no era virgen]], y que antes de él había tenido varios hijos de José.",
     "[Nota del editor:] E Ibn al-Bitriq mencionó a este grupo en su libro Nazm al-yawhar, y lo copiaron de él Ibn Taymiyya en al-Yawab al-sahih, Ibn al-Qayyim en Hidayat al-hayara y al-Maqrizi en sus Jitat. [[k:E Ibn Hazm lo mencionó con el nombre de barbaranitas, y dijo que ha desaparecido]]. Y Dios —poderoso y majestuoso— refutó a este grupo en Su palabra: «Y cuando Dios dijo: Jesús, hijo de María, ¿dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116). [[k:Aunque los cristianos dicen que este grupo se extinguió y que la Iglesia no reconoce la divinidad de María]], y cree que la Virgen María es un ser humano."],
 prueba="La nota del editor moderno resume toda la cadena de fuentes musulmanas sobre la secta mariana: todas vienen de Ibn al-Bitriq (y de Ibn Hazm). Y reconoce que la Iglesia no considera a María divina.",
 ojo="El texto medieval y la nota no hablan de lo mismo. Para al-Yaʿfari, los «marianitas» eran una secta que negaba la virginidad de María, y el editor los confunde con la secta de Ibn al-Bitriq. El nombre «marianitas» se usó para grupos distintos.")

add(3, "al-Bujari (m. 256 H / 870)", key="Bk", specs=["T4-24", "T4-25"],
 title="Hadiz auténtico del Día del Juicio: «¿Qué adorabais?». Los cristianos: «Adorábamos al Mesías, hijo de Dios». Ni rastro de María",
 ref="al-Bujari, al-Yamiʿ al-sahih (ed. Sultaniyya, Bulaq 1311 H), Kitab al-tawhid, n.º 7439, vol. 9, pp. 129–130",
 ar_ref="صحيح البخاري ٩/١٢٩–١٣٠، رقم ٧٤٣٩", site=SH, url=S + "1681/11051",
 es=["Y se les dice a los judíos: «¿Qué adorabais?». Dicen: [[k:«Adorábamos a ʿUzayr, hijo de Dios»]]. Y se les dice: «Mentís»…",
     "…«Dios no ha tenido compañera ni hijo. ¿Qué queréis?». Dicen: «Queremos que nos des de beber». Se les dice: «Bebed», y caen en el Infierno. [[k:Luego se les dice a los cristianos: «¿Qué adorabais?»]]. Y dicen: [[k:«Adorábamos al Mesías, hijo de Dios»]]. Y se les dice: «Mentís; Dios no ha tenido compañera ni hijo»…"],
 prueba="En el hadiz más auténtico sobre el juicio a los cristianos, lo que confiesan es «adorábamos al Mesías, hijo de Dios». Es lo que de verdad creen los cristianos. María no aparece como objeto de culto.",
 ojo="La respuesta «Dios no ha tenido compañera ni hijo» repite la idea de 6:101: la filiación entendida como engendrar con una compañera. Pero no se nombra a María. Y el hadiz es del género escatológico, no una descripción de doctrinas.")
