# -*- coding: utf-8 -*-
# ---------- 2. Los comentaristas del Corán ----------
MUQ = "Tafsir Muqatil ibn Sulayman, ed. ʿAbd Allah Mahmud Shihata"
add(2, "Muqatil ibn Sulayman (m. 150 H / 767)", key="Mq", specs=["T1-03", "T1-01", "T1-02"],
 title="«Dios es el tercero de tres: Él es dios, Jesús es dios y María es diosa»: el comentario completo más antiguo se lo atribuye a los melquitas",
 ref=f"{MUQ}, vol. 1, p. 463 (sobre el Corán 5:14) y pp. 494–495 (sobre 5:72–75)",
 ar_ref="تفسير مقاتل ١/٤٦٣ و١/٤٩٤–٤٩٥", site=SH, url=S + "23614/326 · 23614/357 · 23614/358",
 es=["[Los nestorianos] dijeron: «Jesús es hijo de Dios». Y dijeron los mar-yaʿqubíes [jacobitas]: «Dios es el Mesías, hijo de María». [[k:Y dijeron los ʿibadat al-malik [«los del rey», los melquitas]: «Dios —poderoso y majestuoso— es el tercero de tres: Él es dios, Jesús es dios y María es diosa»]], inventando mentiras contra Dios —bendito y ensalzado—. Pero Dios es un solo Dios, y Jesús es siervo de Dios y Su profeta ﷺ, como Dios —glorificado sea— se describió a Sí mismo: «Uno, el Eterno; no engendró ni fue engendrado, y nadie es igual a Él».",
     "[[k:Se reveló sobre los cristianos de Najrán, los mar-yaʿqubíes]] —entre ellos al-Sayyid, al-ʿAqib y otros—, que dijeron: «Dios es el Mesías, hijo de María». «Y dijo el Mesías: Hijos de Israel, adorad a Dios, mi Señor y vuestro Señor», es decir, proclamad la unicidad de Dios, mi Señor y vuestro Señor. «A quien asocie algo a Dios» —diciendo que Dios es el Mesías, hijo de María, y muriendo en esa idolatría— «Dios le prohíbe el Paraíso y su morada será el Fuego; y los injustos», es decir, los idólatras, «no tendrán auxiliadores» (72): nadie que les impida el Fuego. [[k:«Han caído en la incredulidad los que dicen: Dios es el tercero de tres», es decir, los melquitas, que dijeron: Dios…]]",
     "…el Mesías y María. [[k:Dice Dios —poderoso y majestuoso—, desmintiendo lo que dicen]]: «No hay más dios que un Dios único; y si no dejan de decir» la idolatría «que dicen, a los que de ellos no crean les alcanzará un castigo doloroso» (73): doloroso, y además la muerte por la espada y el tributo (yizia) como castigo para los que queden. […] «El Mesías, hijo de María, no es más que un mensajero; antes de él pasaron otros mensajeros, y su madre es veraz», es decir, creyente […]. «Los dos comían alimentos»: [[k:si fueran dos dioses, no comerían alimentos]]. «Mira», Muhammad, «cómo les explicamos las señales», es decir, las pruebas, [[k:sobre Jesús y María: que los dos comían alimentos, y los dioses no comen]]."],
 prueba="Es el comentario completo del Corán más antiguo que se conserva, y es explícito: los «tres» de 5:73 son Dios, Jesús y María. Y no lo atribuye a una secta marginal, sino a los melquitas, la Iglesia del imperio bizantino.",
 ojo="Muqatil no da ninguna fuente: es su propia explicación. Y lo que atribuye a los melquitas es falso. Su credo era el de Nicea y Calcedonia: Padre, Hijo y Espíritu Santo. Llamaban a María «Madre de Dios» (Theotokos), nunca «diosa». Además, reparte las doctrinas entre sectas de forma distinta a otros comentaristas (comparar #Qt# y #IJ#).")

again(2, "Qatada (m. 117 H / 735), en al-Tabari", 'R08', key="Qt",
 prueba="Otro de los relatos más antiguos: uno de los cuatro sabios después de Jesús dice «él es dios, su madre es diosa y Dios es dios». Sus seguidores son los «israelitas» de los cristianos. Es la misma trinidad de Dios, Jesús y María que en Muqatil (#Mq#).",
 ojo="Qatada dice dos veces «se nos ha contado», sin decir quién. Pone a jacobitas y nestorianos el día después de la ascensión, cuando esas iglesias nacieron en los siglos V y VI. Y la secta de María es aquí «los israelitas», no los melquitas.")

again(2, "Ibn Jurayj (m. 150 H / 767), en al-Tabari", 'R11', key="IJ",
 prueba="Ibn Jurayj repite la trinidad de Dios, Jesús y María: «es el tercero de tres: Dios es dios, él es dios y su madre es diosa». Y la atribuye a «los israelitas, los reyes de los cristianos», es decir, a la religión de los emperadores. Coincide con Muqatil (#Mq#), que la atribuye a los melquitas.",
 ojo="Los nombres son anacrónicos: Nestorio (m. c. 451) y Mar Yaʿqub (Jacobo Baradeo, m. 578) no pudieron discutir el día de la ascensión. Es una tradición sin cadena hasta ningún testigo.")

add(2, "al-Suddi (m. 127 H / 745), en al-Tabari", key="Sd", specs=["T1-07", "T1-08"],
 title="al-Suddi: «Dijeron los cristianos: Él, el Mesías y su madre»; «y eso es Su palabra: tomadme a mí y a mi madre como dos dioses»",
 ref=f"{TAB}, sobre el Corán 5:73, n.º 12294–12295, vol. 10, p. 483; sobre 5:116, n.º 13028, vol. 11, p. 234",
 ar_ref="تفسير الطبري ١٠/٤٨٣ و١١/٢٣٤", site=SH, url=S + "43/5752 · 43/6082",
 es=["Y un grupo de comentaristas dijo algo parecido a lo que decimos: que con estas aleyas se refería a los cristianos. Mención de quien lo dijo: 12294 — Nos contó Muhammad ibn al-Husayn: nos contó Ahmad ibn al-Mufaddal: [[k:nos contó Asbat, de al-Suddi]]: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres». Dijo: [[k:Dijeron los cristianos: «Él, el Mesías y su madre». Y eso es lo que dice Dios]]: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116). 12295 — Nos contó al-Qasim: nos contó al-Husayn: me contó Hayyay, de Ibn Jurayj: dijo Muyahid: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres», lo mismo.",
     "Y se dijo: Dios le dijo esto a Jesús cuando lo elevó hacia Sí, en esta vida. Mención de quien lo dijo: 13028 — Nos contó Muhammad ibn al-Husayn: nos contó Ahmad ibn Mufaddal: nos contó Asbat, de al-Suddi: «Y cuando Dios dijo: Jesús, hijo de María, ¿dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?». Dijo: [[k:Cuando Dios elevó a Jesús, hijo de María, hacia Sí, los cristianos dijeron lo que dijeron, y afirmaron que Jesús se lo había mandado]]."],
 prueba="Es la fuente de la lectura «Dios + Jesús + María» en casi todos los comentaristas posteriores. Al-Suddi une 5:73 con 5:116: los «tres» son Dios, el Mesías y su madre. Muyahid (m. 104 H) dice «lo mismo», aunque no se copia su texto.",
 ojo="La cadena Asbat ← al-Suddi es la de los comentarios de al-Suddi, que muchos críticos del hadiz consideran débil. Y al-Suddi no fue testigo de nada: es un comentarista del siglo II H. Al-Tabari pone esta opinión justo después de su propia explicación de los tres como «hipóstasis» (#Tb#).")

add(2, "al-Tabari (m. 310 H / 923)", key="Tb", specs=["T1-06", "T1-09", "T1-10"],
 title="al-Tabari: los «tres» son «una sola sustancia en tres hipóstasis»… pero en 5:116, Jesús y su madre, «dos objetos de culto»",
 ref=f"{TAB}, sobre el Corán 5:73 (vol. 10, p. 482), 5:116 (vol. 11, p. 237) y 4:171 (vol. 9, p. 422)",
 ar_ref="تفسير الطبري ١٠/٤٨٢ و١١/٢٣٧ و٩/٤٢٢", site=SH, url=S + "43/5751 · 43/6085 · 43/5105",
 es=["[[k:Y esta es la doctrina que tenía la mayoría de los cristianos antes de dividirse en jacobitas, melquitas y nestorianos]]. Decían, según lo que nos ha llegado: «[[k:El Dios eterno es una sola sustancia que abarca tres hipóstasis: un padre que engendra y no es engendrado, un hijo engendrado que no engendra,]] [[a:y una “zawy” que sigue entre los dos]]». Dice Dios, desmintiéndolos en lo que dicen: «No hay más dios que un Dios único»: no tenéis, gentes, más que un solo objeto de culto, que no es padre de nada ni engendrado, sino creador de todo padre y todo engendrado. […] «Les alcanzará un castigo doloroso»: a los que dicen esto y a los que dicen lo otro, «Él es el Mesías, hijo de María», [[k:porque los dos grupos son incrédulos e idólatras]]…",
     "Dijo Abu Yaʿfar: La interpretación de las palabras es: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses?», [[k:es decir, dos objetos de culto que adoráis aparte de Dios]]. Dijo Jesús: «Gloria a Ti», Señor, lejos de que yo haga eso o lo diga. «No me corresponde decir aquello a lo que no tengo derecho»: no me corresponde decirlo, [[k:porque yo soy un siervo creado y mi madre es una sierva Tuya; ¿cómo van un siervo y una sierva a pretender ser señores?]] […] Dice Dios, informando de Su profeta Jesús ﷺ, que se desentiende ante Él [[k:de lo que los incrédulos de entre los cristianos dijeron de él y de su madre]].",
     "Dijo Abu Yaʿfar: «Creed en Dios y en Sus mensajeros» significa: creed, gente del Libro, en la unicidad y el señorío de Dios, que no tiene hijo, y creed a Sus mensajeros en lo que os trajeron de Dios, y en lo que os he dicho: [[k:que Dios es uno, sin socio, sin compañera, sin hijo]]. «Y no digáis tres», es decir: [[k:no digáis «los señores son tres»]]."],
 prueba="El mayor comentarista clásico da las dos cosas. En 5:73 explica los «tres» como la doctrina de las hipóstasis, la de la mayoría de los cristianos. Pero en 5:116 da por hecho que los cristianos hicieron a Jesús y a su madre «dos objetos de culto», sin plantear ninguna duda.",
 ojo="En 5:73 la tercera hipóstasis no es María. Las ediciones imprimen «zawy» (en azul), que puede significar «consorte», pero que solo se diferencia de «ruh» (espíritu) en los puntos de dos letras. Ninguna de las dos lecturas nombra a María, y la frase va precedida de «según lo que nos ha llegado». En 4:171 no dice quiénes son los tres.")

add(2, "Ibn Abi Hatim (m. 327 H / 938)", key="IAH", specs=["T1-11"],
 title="Ibn Abi Hatim sobre «el tercero de tres»: al-Suddi, «Dios es el Mesías y su madre»; Abu Sajr, Dios con ʿUzayr y el Mesías",
 ref="Ibn Abi Hatim, Tafsir al-Qurʾan al-ʿazim musnadan, ed. Asʿad Muhammad al-Tayyib, vol. 4, p. 1179, n.º 6645–6647 (sobre el Corán 5:73)",
 ar_ref="تفسير ابن أبي حاتم ٤/١١٧٩", site=SH, url=S + "8658/1169",
 es=["6645 — Nos contó mi padre: nos contó Abu Hudhayfa: nos contó Shibl, de ʿAbd Allah ibn Kathir, que oyó a Muyahid decir: [[k:Los hijos de Israel se dividieron en tres grupos sobre Jesús]]: un grupo dijo: «Es Dios»; otro grupo dijo: «Es el hijo de Dios»; y otro dijo: «Es el siervo de Dios, Su mensajero y Su espíritu», y estos son los moderados, y de ellos son los musulmanes de la gente del Libro. 6646 — Nos informó Ahmad ibn ʿUthman ibn Hakim al-Awdi, por carta: nos contó Ahmad ibn al-Mufaddal: nos contó Asbat, de al-Suddi: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres»: dijeron los cristianos: [[k:«Dios es el Mesías y su madre». Y eso es Su palabra]]: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?». Segunda opinión: 6647 — Nos contó ʿAli ibn al-Hasan al-Hisinyani: nos contó Saʿid ibn al-Hakam ibn Abi Maryam: nos contó al-Mufaddal: me contó Abu Sajr, sobre «Han caído en la incredulidad los que dicen: Dios es el tercero de tres»: dijo: [[a:es lo que dicen los judíos, «ʿUzayr es hijo de Dios», y los cristianos, «el Mesías es hijo de Dios»]]; así hicieron a Dios el tercero de tres."],
 prueba="La recopilación con cadenas más completa de los primeros siglos solo tiene, sobre los «tres», la frase de al-Suddi (Dios, el Mesías y su madre) y una opinión distinta.",
 ojo="La segunda opinión (en azul) entiende los «tres» como Dios, ʿUzayr y el Mesías, sin María. Ibn Kathir la llama «extraña», según la nota del editor. Ibn Abi Hatim no tiene nada de Ibn Abbas ni de ningún Compañero que identifique a los «tres» con Dios, Jesús y María.")

add(2, "al-Thaʿlabi (m. 427 H / 1035)", key="Th", specs=["T1-12"],
 title="al-Thaʿlabi: «el tercero de tres» son los nestorianos, «que dijeron: Padre, Hijo y Espíritu Santo»",
 ref="al-Thaʿlabi, al-Kashf wa-l-bayan ʿan tafsir al-Qurʾan (Dar al-Tafsir, Yeda), vol. 11, p. 449 (sobre el Corán 5:72–73)",
 ar_ref="تفسير الثعلبي ١١/٤٤٩", site=SH, url=S + "18686/5890",
 es=["…es decir, los melquitas. «Y dijo el Mesías: Hijos de Israel, adorad a Dios, mi Señor y vuestro Señor; a quien asocie algo a Dios, Dios le prohíbe el Paraíso, y su morada será el Fuego; y los injustos no tendrán auxiliadores». 73 — «Han caído en la incredulidad los que dicen: Dios es el tercero de tres»: [[a:es decir, los nestorianos; y es que dijeron: Padre, Hijo y Espíritu Santo]]."],
 prueba="Juega en contra de la lectura «Dios + Jesús + María». Para este gran comentarista, los «tres» de 5:73 son el Padre, el Hijo y el Espíritu Santo.",
 ojo="Atribuye la Trinidad solo a los nestorianos y el «Dios es el Mesías» a los melquitas. Las tres iglesias confesaban la misma Trinidad, y la diferencia entre ellas estaba en la persona de Cristo, no en la Trinidad. El mismo al-Thaʿlabi, en la leyenda de Pablo, cuenta que Pablo enseñó a Nestorio «que Jesús, María y el dios eran tres» (#Tl#).")

add(2, "al-Wahidi (m. 468 H / 1076)", key="Wa", specs=["T1-15", "T1-16", "T1-17"],
 title="al-Wahidi: dos caminos: los comentaristas, «Dios, María y Jesús»; los teólogos, «tres hipóstasis: Padre, Hijo y Espíritu Santo»",
 ref="al-Wahidi, al-Tafsir al-basit (Universidad Imam Muhammad ibn Saʿud), vol. 7, pp. 481–483 (sobre el Corán 5:73)",
 ar_ref="التفسير البسيط للواحدي ٧/٤٨١–٤٨٣", site=SH, url=S + "13231/4116 · 13231/4117 · 13231/4118",
 es=["En cuanto al significado de lo que dicen los cristianos —Dios los maldiga—, «el tercero de tres», hay dos caminos. [[k:El más claro y el que mejor se ajusta a las palabras es el camino de los comentaristas]], que dijeron: [[k:con «el tercero de tres» los cristianos querían decir Dios, María y Jesús; afirmaron que la divinidad está repartida entre los tres]] y que cada uno de ellos es un dios. Confirma esta doctrina suya Su palabra al Mesías: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116).",
     "[[k:Y en esto se ve claramente que asociaban a María y a Jesús a la divinidad]]. [[k:Es la opinión que elige al-Zayyay]], que dijo sobre «el tercero de tres»: dijeron que Dios es uno de tres dioses. […] Este es un camino sobre la aleya. [[a:Y los teólogos cuentan de los cristianos, sobre su Trinidad, que dicen que el Creador es una sola sustancia y que es tres hipóstasis: Padre, Hijo y Espíritu Santo]], y que estos tres son un solo Dios; dicen que el nombre de Dios abarca las tres cosas, como el sol es un nombre que abarca el disco, el rayo y el calor. Con el Padre se refieren a la esencia, con el Hijo a la Palabra y con el Espíritu al poder […]; y afirmaron que el Padre es dios, el Hijo es dios y el Espíritu es dios, y Él es un solo Dios.",
     "Y este no es el lugar para extenderse en refutarlos. Según esto, lo que Dios cuenta de ellos en «Han caído en la incredulidad los que dicen: Dios es el tercero de tres» es el sentido de su doctrina: [[a:aunque no digan abiertamente que es uno de tres dioses, eso se sigue de lo que dicen; solo evitan la expresión]]. Porque si dicen que cada una de las hipóstasis es dios, lo han hecho el tercero de tres dioses, y decir después que es un solo Dios contradice lo que dijeron. Siendo así, [[a:es correcto atribuirles, como doctrina, lo que se sigue de ella]]. Y de los comentaristas siguió este camino al-Kalbi."],
 prueba="Al-Wahidi da el mejor resumen del debate interno: la lectura «Dios, María y Jesús» es la de «los comentaristas» y de al-Zayyay (m. 311 H), y él la considera la que mejor se ajusta al texto.",
 ojo="Él mismo reconoce que lo que los cristianos dicen es otra cosa: tres hipóstasis, Padre, Hijo y Espíritu Santo, un solo Dios. Para salvar el versículo recurre a «lo que se sigue» de su doctrina (en azul): reconoce que los cristianos no dicen «uno de tres dioses».")

add(2, "Ibn al-Anbari (m. 328 H), en al-Wahidi", key="Wa2", specs=["T1-18"],
 title="«En la aleya no se dice que tomaran a Jesús y a su madre como dos dioses: es una pregunta a Jesús»",
 ref="al-Wahidi, al-Tafsir al-basit, vol. 7, p. 605 (sobre el Corán 5:116–118), citando a Abu Bakr ibn al-Anbari",
 ar_ref="التفسير البسيط للواحدي ٧/٦٠٥", site=SH, url=S + "13231/4240",
 es=["[Ibn] al-Anbari: Cuando Dios le dijo a Jesús «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?», él solo entendió que los cristianos le atribuían una mentira; y dijo «Y si les perdonas» esa atribución, «Tú eres el Poderoso, el Sabio», porque quien cuenta una incredulidad no es incrédulo si no la adopta. [[a:Y en la aleya no se dice que tomaran a Jesús y a su madre como dos dioses: es solo una pregunta a Jesús, si lo mandó o si lo dijo o no]]. Y lo aparente de esta pregunta implica que los cristianos le atribuyeron que lo había mandado."],
 prueba="Un gramático clásico admite que 5:116 no afirma que los cristianos adoraran a Jesús y a María como dos dioses: es una pregunta. Es una salida que usan los apologistas actuales.",
 ojo="Esta lectura salva al Corán de error, pero deja a 5:116 sin valor como descripción de la fe cristiana. Ya no sirve para decir que el Corán «conoce» una trinidad con María.")

add(2, "al-Samʿani (m. 489 H / 1096)", key="Sm", specs=["T1-13", "T1-14"],
 title="al-Samʿani: los tres son «Padre, Hijo y Espíritu Santo»… y «si alguien dice: no tomaron a su madre por diosa…»",
 ref="al-Samʿani, Tafsir al-Qurʾan, ed. Yasir ibn Ibrahim y Ghunaym ibn ʿAbbas (Dar al-Watan), vol. 2, p. 55 (sobre 5:73) y p. 82 (sobre 5:116)",
 ar_ref="تفسير السمعاني ٢/٥٥ و٢/٨٢", site=SH, url=S + "8320/1261 · 8320/1330",
 es=["Su palabra: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres»: hay algo omitido, [[a:es decir, el tercero de tres dioses]], y hace falta suponerlo, porque se puede decir que [Dios] es el tercero de tres, como dice: «No hay conversación secreta de tres en que Él no sea el cuarto» (58:7). Y «el tercero de tres» [[a:es lo que dicen: Padre, Hijo y Espíritu Santo; y es la doctrina de los jacobitas]]. Y dijeron: el Espíritu Santo no es Él ni otro que Él, y lo mismo el Hijo, y Dios es el conjunto de todo.",
     "…es decir, cuando recompense: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?». Se dijo: es una pregunta de reproche, dirigida en realidad a su pueblo, y la sabiduría de preguntarle era que su pueblo oyera su negativa, porque afirmaban que Jesús les había mandado tomarlo por dios. [[k:Y si alguien dice: no tomaron a su madre por diosa; ¿qué significa entonces «tomadme a mí y a mi madre como dos dioses»?]] Se responde: [[k:como Dios quiso mencionar a Jesús junto con su madre, dijo «dos dioses», como se dice «los dos ʿUmar» al mencionar juntos a Abu Bakr y ʿUmar]] […] Y se dijo: [[k:Jesús era una parte de María; al tomarlo por dios, fue como si tomaran a su madre por diosa]]; por eso dijo: «dos dioses aparte de Dios»."],
 prueba="Al-Samʿani plantea la objeción en voz alta: «no tomaron a su madre por diosa». Y para 5:73 da como «tres» al Padre, al Hijo y al Espíritu Santo, no a María.",
 ojo="Sus dos respuestas reconocen el problema. La primera es gramatical: un dual que no significa dos dioses, como «los dos ʿUmar» por Abu Bakr y ʿUmar. La segunda dice que, como Jesús salió de María, es «como si» la divinizaran. Ninguna afirma que los cristianos adoraran a María como diosa. (La edición imprime «ilayha» por «ilahan», una errata.)")

add(2, "al-Baghawi (m. 516 H / 1122)", key="Bg", specs=["T1-19"],
 title="al-Baghawi: el «tercero de tres» son «los marcosianos»: «la divinidad está repartida entre Dios, María y Jesús»",
 ref="al-Baghawi, Maʿalim al-tanzil (Dar Tayba), vol. 3, p. 82 (sobre el Corán 5:72–73)",
 ar_ref="تفسير البغوي ٣/٨٢", site=SH, url=S + "41/846",
 es=["…y son los melquitas y los jacobitas de entre ellos. «Y dijo el Mesías: Hijos de Israel, adorad a Dios, mi Señor y vuestro Señor; a quien asocie algo a Dios, Dios le prohíbe el Paraíso, y su morada será el Fuego; y los injustos no tendrán auxiliadores». «Han caído en la incredulidad los que dicen: Dios es el tercero de tres»: [[k:es decir, los marcosianos (al-Murqusiyya)]]; y hay algo implícito, que significa: el tercero de tres dioses, porque dicen: [[k:la divinidad está repartida entre Dios, María y Jesús, y cada uno de ellos es un dios; así que son tres dioses]]. Lo aclara Su palabra al Mesías: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116)."],
 prueba="Al-Baghawi da la lectura «Dios, María y Jesús» y pone nombre a la secta: al-Murqusiyya. Ya no la atribuye a todos los cristianos ni a los melquitas, sino a un grupo concreto.",
 ojo="No se conoce ninguna secta con ese nombre que adorara a María. Los «marcosianos» de los heresiólogos griegos eran gnósticos del siglo II, seguidores de un tal Marco, y no tienen relación con María. Al-Baghawi no da fuente.")

add(2, "al-Zamajshari (m. 538 H / 1144)", key="Zm", specs=["T1-20", "T1-21"],
 title="al-Zamajshari: «si es cierto lo que se cuenta» de las hipóstasis… pero el Corán indica «Dios, el Mesías y María, tres dioses», y «el relato de Dios es más fiable»",
 ref="al-Zamajshari, al-Kashshaf (Dar al-Kitab al-ʿArabi), vol. 1, pp. 593–594 (sobre el Corán 4:171)",
 ar_ref="الكشاف ١/٥٩٣–٥٩٤", site=SH, url=S + "23627/596 · 23627/597",
 es=["«Tres» es predicado de un sujeto omitido. [[a:Si es cierto lo que se cuenta de ellos, que dicen: es una sola sustancia en tres hipóstasis, la hipóstasis del Padre, la del Hijo y la del Espíritu Santo]], y que con la hipóstasis del Padre se refieren a la esencia, con la del Hijo al conocimiento y con la del Espíritu Santo a la vida, [[a:entonces se sobrentiende «Dios es tres»; y si no, se sobrentiende «los dioses son tres»]]. Y lo que indica el Corán es que declararon abiertamente que Dios, el Mesías…",
     "[[k:…y María son tres dioses, y que el Mesías es hijo de Dios, nacido de María]]. ¿No ves Su palabra «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» y «Y dijeron los cristianos: el Mesías es hijo de Dios»? [[k:Y lo conocido y difundido de ellos es que dicen que en el Mesías hay divinidad y humanidad, por parte del padre y de la madre]]. Y lo indica Su palabra: «El Mesías, Jesús, hijo de María, es solo…»: afirma que es hijo de María, unido a ella como los hijos a sus madres, y que su unión con Dios es la de Su mensajero […]. [[k:Y el relato de Dios es más fiable que el relato de cualquier otro]]."],
 prueba="Es el texto más fuerte para decir que el Corán entiende la Trinidad como Dios, Jesús y María. Al-Zamajshari, gran filólogo, dice que «lo que indica el Corán» es que los cristianos llamaron a Dios, al Mesías y a María «tres dioses». Ante la versión de las hipóstasis, prefiere el Corán: «el relato de Dios es más fiable».",
 ojo="Es un argumento circular: como el Corán lo dice, tiene que ser lo que creen, aunque «lo que se cuenta de ellos» diga otra cosa. Él mismo reconoce que la doctrina conocida es la de las hipóstasis y la de las dos naturalezas de Cristo. Ningún texto cristiano que cite dice «Dios, el Mesías y María son tres dioses».")

add(2, "Fajr al-Din al-Razi (m. 606 H / 1210)", key="Rz1", specs=["T1-22", "T1-23"],
 title="al-Razi: «algunos comentaristas»: Dios, María y Jesús; «los teólogos»: Padre, Hijo y Espíritu Santo",
 ref="al-Razi, Mafatih al-ghayb (Dar Ihyaʾ al-Turath al-ʿArabi), vol. 12, pp. 408–409 (sobre el Corán 5:73)",
 ar_ref="تفسير الرازي ١٢/٤٠٨–٤٠٩", site=SH, url=S + "23635/2071 · 23635/2072",
 es=["Segunda cuestión: sobre la explicación de lo que dicen los cristianos, «el tercero de tres», hay dos caminos. El primero: [[k:lo que dicen algunos comentaristas, que con ello querían decir que Dios, María y Jesús son tres dioses]]; y lo confirma Su palabra al Mesías: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116). Así que «el tercero de tres» es uno de tres dioses, y la prueba de que eso es lo que quiere decir es Su palabra al refutarlos: «No hay más dios que un Dios único». […] [[k:El segundo camino: los teólogos cuentan de los cristianos]] que dicen: una sola sustancia, tres hipóstasis: Padre, Hijo…",
     "…y Espíritu Santo, y estos tres son un solo Dios, como el sol es un nombre que abarca el disco, el rayo y el calor; [[a:con el Padre se refieren a la esencia, con el Hijo a la Palabra y con el Espíritu a la vida]] […]; y dijeron que la Palabra, que es el habla de Dios, se mezcló con el cuerpo de Jesús como el agua con el vino […]; [[a:y afirmaron que el Padre es dios, el Hijo es dios y el Espíritu es dios, y el conjunto es un solo Dios]]. Y sabe que esto es falso a primera vista para la razón: tres no son uno y uno no es tres; y no hay en el mundo doctrina más corrupta ni más evidentemente falsa que la de los cristianos."],
 prueba="Al-Razi recoge las dos lecturas de los «tres». La de Dios, María y Jesús es la de «algunos comentaristas», y se apoya en 5:116.",
 ojo="Lo que «cuentan los teólogos», que conocían la doctrina cristiana de primera mano, es Padre, Hijo y Espíritu Santo (en azul). Al-Razi no cita ninguna fuente cristiana con María entre los tres.")

add(2, "Fajr al-Din al-Razi (m. 606 H / 1210)", key="Rz2", specs=["T1-24"],
 title="al-Razi: «ningún cristiano sostuvo la divinidad de Jesús y María negando la de Dios; ¿cómo se les atribuye esto?»",
 ref="al-Razi, Mafatih al-ghayb, vol. 12, p. 465 (sobre el Corán 5:116)",
 ar_ref="تفسير الرازي ١٢/٤٦٥", site=SH, url=S + "23635/2128",
 es=["Segunda cuestión: en «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» hay dos preguntas. Una: ¿cómo le cuadra la pregunta al que conoce lo oculto? Otra: sabía que Jesús no había dicho eso; ¿por qué se lo dice? Y si decís que el fin es reprender a los cristianos, decimos: [[k:ningún cristiano sostuvo la divinidad de Jesús y de María negando la divinidad de Dios; ¿cómo puede atribuírseles esta doctrina, si ninguno de ellos la sostuvo?]] La respuesta a la primera: es una pregunta de reproche. La respuesta a la segunda: dios es el creador, y [[k:los cristianos creen que el creador de los milagros que aparecieron por mano de Jesús y María es Jesús y María]], y que Dios no los creó en absoluto; […] así que es cierto que, [[k:respecto a algunas cosas, afirmaron que Jesús y María eran dioses]] y que Dios no lo era; y con esta interpretación queda bien este relato."],
 prueba="Uno de los grandes teólogos del islam plantea el problema con todas las letras: ningún cristiano dijo eso. Y para salvar el versículo tiene que inventar una «creencia» cristiana: que Jesús y María, y no Dios, crearon los milagros.",
 ojo="La objeción de al-Razi es sobre «aparte de Dios» (min dun Allah), no sobre si se divinizaba a María. Pero su respuesta atribuye a los cristianos algo que no creen: para ellos los milagros son obra de Dios. Y María no hace milagros en los Evangelios.")

add(2, "Fajr al-Din al-Razi (m. 606 H / 1210)", key="Rz3", specs=["T1-25", "T1-26"],
 title="al-Razi sobre 4:171: «no digáis: Dios es uno en sustancia y tres en hipóstasis»; «la doctrina de los cristianos es muy oscura»",
 ref="al-Razi, Mafatih al-ghayb, vol. 11, pp. 271–272 (sobre el Corán 4:171)",
 ar_ref="تفسير الرازي ١١/٢٧١–٢٧٢", site=SH, url=S + "23635/1936 · 23635/1937",
 es=["Primera cuestión: el sentido es: [[a:no digáis que Dios —glorificado sea— es uno en sustancia y tres en hipóstasis]]. [[a:Y sabe que la doctrina de los cristianos es muy oscura]]; lo que se saca de ella es que afirmaron una esencia descrita con tres atributos; solo que, aunque los llamen atributos, en realidad son esencias, porque admiten que se encarnen en Jesús y en María…",
     "Segunda cuestión: «tres» es predicado de un sujeto omitido, y discreparon sobre cuál es, de varias maneras. La primera: la que dijimos, [[a:es decir, no digáis «las hipóstasis son tres»]]. La segunda: [[k:dijo al-Zayyay: no digáis «nuestros dioses son tres»; porque el Corán indica que los cristianos dicen que Dios, el Mesías y María son tres dioses]], y la prueba es Su palabra: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116). La tercera: dijo al-Farraʾ: no digáis «son tres», como en «dirán: tres» (18:22); porque mencionar a Jesús y a María junto a Dios con esta expresión hace pensar que son dos dioses."],
 prueba="En 4:171 la lectura de al-Razi es la de las hipóstasis (en azul); la de «Dios, el Mesías y María» es la segunda, la de al-Zayyay (m. 311 H). La única prueba de al-Zayyay es el propio 5:116, no ninguna fuente cristiana.",
 ojo="Al-Razi dice que la doctrina cristiana es «muy oscura» y aun así la describe bien: una esencia con tres «atributos». La lectura de al-Zayyay es circular: se prueba con el Corán lo que dice el Corán.")

add(2, "al-Qurtubi (m. 671 H / 1273)", key="Qr1", specs=["T1-27"],
 title="al-Qurtubi sobre 4:171: Ibn Abbas, «Dios, Su compañera y Su hijo»… y «todos los cristianos dicen: una sustancia y tres hipóstasis»",
 ref="al-Qurtubi, al-Yamiʿ li-ahkam al-Qurʾan (Dar al-Kutub al-Misriyya), vol. 6, p. 23 (sobre el Corán 4:171)",
 ar_ref="تفسير القرطبي ٦/٢٣", site=SH, url=S + "20855/2120",
 es=["«Y no digáis» nuestros dioses «son tres», según al-Zayyay. [[k:Dijo Ibn Abbas: con la trinidad se refiere a Dios —ensalzado sea—, a Su compañera y a Su hijo]]. Y dijeron al-Farraʾ y Abu ʿUbayd: es decir, no digáis «son tres», como en «Dirán: tres» (18:22). Dijo Abu ʿAli: se sobrentiende «no digáis: Él es el tercero de tres», y se omitieron el sujeto y el nombre regido. [[a:Y los cristianos, con todas sus sectas, están de acuerdo en la Trinidad y dicen: Dios es una sola sustancia y tiene tres hipóstasis]], y hacen de cada hipóstasis un dios."],
 prueba="Aquí aparece una frase atribuida a Ibn Abbas: los tres son «Dios, Su compañera y Su hijo». Es decir, la Trinidad como una familia: padre, madre e hijo.",
 ojo="Al-Qurtubi no da cadena ni fuente para la frase de Ibn Abbas, y no la hemos encontrado en las recopilaciones con cadena que hemos revisado (al-Tabari, Ibn Abi Hatim: #IAH#). Y él mismo añade, en azul, que todos los cristianos confiesan una sustancia en tres hipóstasis.")

add(2, "al-Qurtubi (m. 671 H / 1273)", key="Qr2", specs=["T1-28", "T1-29"],
 title="al-Qurtubi: «el tercero de tres» es «Padre, Hijo y Espíritu Santo»; y «si se dice: los cristianos no tomaron a María por diosa…»",
 ref="al-Qurtubi, al-Yamiʿ li-ahkam al-Qurʾan, vol. 6, p. 249 (sobre 5:73) y p. 375 (sobre 5:116)",
 ar_ref="تفسير القرطبي ٦/٢٤٩ و٦/٣٧٥", site=SH, url=S + "20855/2346 · 20855/2472",
 es=["Y esta es la doctrina de las sectas cristianas, melquitas, nestorianos y jacobitas, [[a:porque dicen: Padre, Hijo y Espíritu Santo, un solo Dios; y no dicen «tres dioses»]], pero ese es el sentido de su doctrina; solo evitan la expresión, y se sigue de ella.",
     "Y los comentaristas discreparon sobre el sentido de esta pregunta, que no es una pregunta aunque tenga forma de pregunta, en dos opiniones. Una: le preguntó por ello para reprender a quien se lo atribuía, para que su negativa después de la pregunta desmintiera con más fuerza. La segunda: con esta pregunta quiso hacerle saber que su pueblo cambió después de él y le atribuyó lo que no dijo. [[k:Y si se dice: los cristianos no tomaron a María por diosa, ¿cómo dice eso de ellos?]] Se dice: [[k:como dicen que ella no dio a luz a un hombre, sino a un dios, se sigue que, por ser él parte de ella, ella está en el lugar de quien dio a luz]]; y al seguírseles eso, quedaron en el lugar de quienes lo dicen."],
 prueba="Al-Qurtubi, en 5:116, plantea la objeción tal cual: «los cristianos no tomaron a María por diosa». Y en 5:73 explica los «tres» como Padre, Hijo y Espíritu Santo, la doctrina de las tres iglesias.",
 ojo="Su respuesta es de nuevo «lo que se sigue»: como dicen que María dio a luz a Dios (Theotokos), «es como si» la hicieran diosa. Es decir, reconoce que no lo dicen. El argumento tampoco funciona: la madre de un rey no es reina por ser parte de él.")

add(2, "al-Baydawi (m. 685 H / 1286)", key="Bd", specs=["T1-36", "T1-37", "T1-38"],
 title="al-Baydawi: en 4:171, «Dios, el Mesías y María»; en 5:73, las «tres hipóstasis»; en 5:116, «adorarlos los acerca a Dios»",
 ref="al-Baydawi, Anwar al-tanzil (Dar Ihyaʾ al-Turath al-ʿArabi), vol. 2, p. 111 (sobre 4:171), p. 138 (sobre 5:73) y p. 151 (sobre 5:116)",
 ar_ref="تفسير البيضاوي ٢/١١١ و٢/١٣٨ و٢/١٥١", site=SH, url=S + "23588/270 · 23588/297 · 23588/310",
 es=["«Y no digáis tres»: [[k:es decir, los dioses son tres: Dios, el Mesías y María; y lo atestigua Su palabra]]: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?»; [[k:o «Dios es tres», si es cierto que dicen que Dios es tres hipóstasis: el Padre, el Hijo y el Espíritu Santo]], y con el Padre se refieren a la esencia, con el Hijo al conocimiento y con el Espíritu Santo a la vida.",
     "Es decir, uno de tres; [[a:y es un relato de lo que dijeron los nestorianos y los melquitas de entre ellos, que afirman las tres hipóstasis]]; y lo anterior era lo que dicen los jacobitas, que afirman la unión.",
     "Quiere con ello reprender a los incrédulos y confundirlos. «Aparte de Dios» […]; y «aparte» significa o bien la alteridad, para señalar que adorar a Dios junto con otro es como no adorarlo […], o bien la inferioridad, [[k:porque no creían que los dos merecieran culto por sí mismos, sino que afirmaban que adorarlos lleva a adorar a Dios]]; como si se dijera: tomadme a mí y a mi madre como dos dioses por medio de los cuales llegáis a Dios."],
 prueba="Al-Baydawi es el comentario escolar clásico en el mundo otomano. En 4:171 pone primero la lectura «Dios, el Mesías y María» y la de las hipóstasis con un «si es cierto». En 5:116 explica el «culto» a María como intercesión: no la creen dios por sí misma.",
 ojo="Es contradictorio. En 5:73 el «tercero de tres» son las tres hipóstasis de nestorianos y melquitas (en azul), sin María. Y en 5:116 su explicación ya no habla de una trinidad, sino de pedir la intercesión de Jesús y María. Eso es la veneración cristiana de María, no una creencia de que María es Dios.")

add(2, "Ibn Kathir (m. 774 H / 1373)", key="IK", specs=["T1-30", "T1-31", "T1-32"],
 title="Ibn Kathir: de las dos lecturas de 5:73, «la más clara» es la de al-Suddi: «hicieron al Mesías y a su madre dos dioses junto con Dios»",
 ref="Ibn Kathir, Tafsir al-Qurʾan al-ʿazim, ed. Sami al-Salama (Dar Tayba), vol. 3, p. 158 (sobre 5:73), vol. 2, p. 479 (sobre 4:171) y vol. 3, p. 232 (sobre 5:116)",
 ar_ref="تفسير ابن كثير ٣/١٥٨ و٢/٤٧٩ و٣/٢٣٢", site=SH, url=S + "8473/1423 · 8473/1261 · 8473/1497",
 es=["Y esta es una opinión extraña sobre la aleya: que se refiere a los dos grupos, judíos y cristianos. Lo correcto es que se reveló sobre los cristianos en particular; lo dijeron Muyahid y otros. Luego discreparon sobre ello. Se dijo: [[a:se refiere a los incrédulos de entre ellos que hablan de las tres hipóstasis: la hipóstasis del Padre, la del Hijo y la de la Palabra que procede]] del Padre al Hijo —ensalzado sea Dios muy por encima de lo que dicen—; dijeron Ibn Yarir y otros: las tres sectas, melquitas, jacobitas y nestorianos, sostienen estas hipóstasis […]. [[k:Y dijeron al-Suddi y otros: se reveló porque hicieron al Mesías y a su madre dos dioses junto con Dios, y así hicieron a Dios]] el tercero de tres en este sentido. Dijo al-Suddi: es como Su palabra al final de la sura: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses?» (5:116). [[k:Y esta opinión es la más clara; y Dios sabe más]].",
     "Y Su palabra «Creed en Dios y en Sus mensajeros»: es decir, creed que Dios es uno, único, sin compañera ni hijo, y sabed con certeza que Jesús es siervo de Dios y Su mensajero; por eso dijo: [[k:«Y no digáis tres», es decir: no hagáis a Jesús y a su madre socios junto con Dios]] —ensalzado sea Dios muy por encima de eso—. Y esta aleya es como la de la sura de la Mesa: «Han caído en la incredulidad los que dicen: Dios es el tercero de tres» (5:73), y como la del final de la misma sura: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116) […]. [[k:Y los cristianos —sobre ellos la maldición de Dios—, por su ignorancia, no tienen regla]] ni límite en su incredulidad; sus opiniones y su extravío están dispersos: unos lo creen dios, otros socio, otros hijo.",
     "Esto también es de lo que Dios dirá a Su siervo y mensajero Jesús, hijo de María —la paz sea con él—, [[k:diciéndole el Día de la Resurrección, en presencia de quienes lo tomaron a él y a su madre como dos dioses aparte de Dios]]: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?». Y es una amenaza a los cristianos, un reproche y una reprensión ante todos los testigos."],
 prueba="Ibn Kathir, el comentario más leído hoy, elige la lectura de al-Suddi como «la más clara»: el «tercero de tres» significa que hicieron a Jesús y a su madre dioses junto con Dios. En 4:171, «no digáis tres» = no hagáis socios de Dios a Jesús y a su madre.",
 ojo="Él mismo cita la otra lectura, la de las hipóstasis, que según Ibn Yarir sostienen las tres iglesias. Y su descripción es confusa: hace de la tercera hipóstasis «la Palabra que procede del Padre al Hijo», cuando para los cristianos la Palabra es el Hijo. Prefiere a al-Suddi sin dar ninguna prueba cristiana.")

add(2, "Abu Hayyan (m. 745 H / 1344)", key="AH", specs=["T1-33", "T1-34", "T1-35"],
 title="Abu Hayyan: «los comentaristas mencionan que ningún cristiano dijo que María fuera diosa»",
 ref="Abu Hayyan, al-Bahr al-muhit (Dar al-Fikr), vol. 4, pp. 329–330 (sobre 5:73) y p. 416 (sobre 5:116)",
 ar_ref="البحر المحيط ٤/٣٢٩–٣٣٠ و٤/٤١٦", site=SH, url=S + "23591/2477 · 23591/2478 · 23591/2564",
 es=["[[k:Estos son los melquitas de los cristianos, los que sostienen la Trinidad]]. Y lo aparente de «el tercero de tres» es uno de tres dioses. [[k:Dijeron los comentaristas: con ello querían decir que Dios —ensalzado sea—, Jesús y su madre son tres dioses]]; y lo confirma…",
     "[[a:Y los teólogos cuentan de los cristianos que dicen: una sola sustancia, tres hipóstasis: Padre, Hijo y Espíritu Santo]]; y estos tres son un solo Dios, como el sol abarca el disco, el rayo y el calor; con el Padre se refieren a la esencia, con el Hijo a la Palabra y con el Espíritu a la vida […]; y afirmaron que el Padre es dios, el Hijo es dios y el Espíritu es dios, y el conjunto es un solo Dios. Y esto es falso a primera vista para la razón: tres no son uno, y uno no es tres.",
     "[[k:Y los comentaristas mencionan que ningún cristiano dijo que María fuera diosa; ¿cómo se dice entonces «dos dioses»?]] Y respondieron que, [[k:como dijeron que no dio a luz a un hombre, sino a un dios]], se les sigue que digan, por ser él parte de ella, la divinidad de quien lo dio a luz; y quedaron en el lugar de quien lo dice. Fin. Y lo aparente es que esta frase se dijo en la realidad, pero no por Jesús; [[k:y que la frase se dijera no implica que se tomara [a María por diosa] de hecho]]."],
 prueba="Abu Hayyan, gran gramático andalusí, da la frase más clara de toda la tradición: «los comentaristas mencionan que ningún cristiano dijo que María fuera diosa». No lo dice un cristiano: lo dicen los propios comentaristas musulmanes.",
 ojo="Aun así recoge en 5:73 la lectura «Dios, Jesús y su madre» como la de «los comentaristas». Y en 5:116 termina diciendo que la frase «se dijo», pero sin que nadie tomara de hecho a María por diosa: queda como una acusación sin sujeto.")

add(2, "Tafsir al-Yalalayn (al-Suyuti, m. 911 H / 1505)", key="Jl", specs=["T1-39", "T1-40"],
 title="al-Yalalayn: «no digáis: los dioses son tres: Dios, Jesús y su madre»; y en 5:73, «son una secta de los cristianos»",
 ref="Tafsir al-Yalalayn (Dar al-Hadith), p. 133 (sobre 4:171) y p. 151 (sobre 5:73); ambas partes son de Yalal al-Din al-Suyuti",
 ar_ref="تفسير الجلالين ص ١٣٣ و١٥١", site=SH, url=S + "12876/789 · 12876/881",
 es=["«Creed en Dios y en Sus mensajeros, y no digáis» [[k:los dioses «son tres»: Dios, Jesús y su madre]].",
     "«Han caído en la incredulidad los que dicen: Dios es el tercero de» tres dioses, [[k:es decir, uno de ellos; y los otros dos son Jesús y su madre; y son una secta de los cristianos]]."],
 prueba="Uno de los comentarios breves más usados hasta hoy enseña sin matices que los «tres» son Dios, Jesús y su madre.",
 ojo="En 5:73 lo limita a «una secta de los cristianos», no a los cristianos en general. Así, el mismo libro admite que la Trinidad de las iglesias no es esa.")

add(2, "al-Alusi (m. 1270 H / 1854)", key="Al1", specs=["T1-41", "T1-43"],
 title="al-Alusi: «el sentido obvio» de 5:73 es Dios, Jesús y su madre… y los melquitas «dicen que la divinidad se unió al Mesías, no a María»",
 ref="al-Alusi, Ruh al-maʿani (Dar al-Kutub al-ʿIlmiyya), vol. 3, p. 372 (sobre 5:73) y p. 201 (sobre 4:171)",
 ar_ref="روح المعاني ٣/٣٧٢ و٣/٢٠١", site=SH, url=S + "22835/1391 · 22835/1220",
 es=["[[k:Y con los tres se referían —según lo que se transmite de al-Suddi— al Creador, glorioso es Su nombre, a Jesús y a su madre —la paz sea con ellos—; cada uno de los tres es dios según ellos]], y la divinidad está repartida entre ellos; y lo confirma Su palabra al Mesías: «¿Dijiste tú a la gente: tomadme a mí y a mi madre como dos dioses aparte de Dios?» (5:116); y es lo que se entiende a primera vista de lo aparente de Su palabra…",
     "Luego discreparon. Los melquitas, seguidores de Malka, que apareció en Bizancio y se apoderó de ella, sostuvieron que las hipóstasis son distintas de la sustancia eterna y que cada una de ellas es dios, [[a:y declararon abiertamente la Trinidad y dijeron: Dios es el tercero de tres]] —glorificado y ensalzado sea por encima de lo que le asocian—; y que la Palabra se unió al cuerpo del Mesías […], [[k:y que María dio a luz a un dios eterno]], aunque discrepan sobre si María es un ser humano universal o particular; [[a:y están de acuerdo en que la unión de la divinidad fue con el Mesías, no con María]]."],
 prueba="Para al-Alusi, el último gran comentarista clásico, la lectura de al-Suddi (Dios, Jesús y su madre) es «lo que se entiende a primera vista» de 5:73.",
 ojo="En 4:171 describe la doctrina melquita con más exactitud: los que dicen «tercero de tres» son los que creen en las tres hipóstasis, y María solo dio a luz a Dios. Y añade: «la unión de la divinidad fue con el Mesías, no con María». Es decir, los melquitas no hacen de María una diosa.")

add(2, "al-Alusi (m. 1270 H / 1854)", key="Al2", specs=["T1-42"],
 title="al-Alusi: «se ha visto un problema en la aleya: no se sabe de ningún cristiano que tomara a María por diosa»",
 ref="al-Alusi, Ruh al-maʿani, vol. 4, p. 62 (sobre el Corán 5:116)",
 ar_ref="روح المعاني ٤/٦٢", site=SH, url=S + "22835/1456",
 es=["[[k:Y se ha visto un problema en la aleya: no se sabe de ningún cristiano que tomara a María —la paz sea con ella— por diosa]]. Se ha respondido de varias maneras. La primera: como hicieron dios a Jesús —la paz y las bendiciones sean con él—, se les sigue que hagan lo mismo con su madre, porque el hijo es de la especie de quien lo da a luz; así que dijo «dos dioses» a modo de consecuencia que se les impone. La segunda: [[k:como la veneraron con la veneración que se da a un dios, se le aplicó el nombre de dios]], igual que se aplicó el nombre de señor a los rabinos y a los monjes en «Han tomado a sus rabinos y a sus monjes como señores aparte de Dios» (9:31), por haberlos venerado como a un señor […]. La tercera: es posible que hubiera entre ellos quien lo dijera. Y apoya esta opinión [[k:lo que contó Abu Yaʿfar al-Imami de algunos cristianos: que en el pasado hubo un grupo llamado los marianitas (al-Maryamiyya) que creían que María era diosa]]; igual que hubo entre los judíos un grupo que creía que ʿUzayr era hijo de Dios. [[k:Y para mí es la mejor de las respuestas]]. Y lo que afirmó quien lo afirmó, que los cristianos creen, etc., no se admite para los cristianos de nuestro tiempo, y nadie digno de confianza lo ha transmitido de ellos."],
 prueba="Al-Alusi (siglo XIX) resume el estado de la cuestión: el versículo plantea un «problema», porque no se conoce ningún cristiano que tomara a María por diosa. Ofrece tres soluciones y elige la de una secta antigua, la de los marianitas.",
 ojo="Su única prueba de esa secta es «lo que contó Abu Yaʿfar al-Imami de algunos cristianos», sin fuente. Y reconoce que, en los cristianos de su tiempo, nadie digno de confianza ha transmitido esa creencia. La segunda respuesta, la de la veneración, lleva al mismo resultado que 9:31 (#Q931#): «tomar como dios» no significa creer que alguien es Dios.")
