# -*- coding: utf-8 -*-
# Texto de las tarjetas. [[k:...]] = naranja (frase clave), [[a:...]] = azul (lo que se responde / lo que dice la otra parte)

IW = "islamweb.net"
WS = "ar.wikisource.org (transcripción del texto)"
F13 = "https://www.islamweb.net/ar/library/content/52/13832/"
HADY = "https://ar.wikisource.org/wiki/مقدمة_فتح_الباري/الفصل_الرابع"
NUZHA = "https://ar.wikisource.org/wiki/نزهة_النظر_في_توضيح_نخبة_الفكر_في_مصطلح_أهل_الأثر"

CARDS = [
 dict(id="IH01", tema="Vídeo 1",
  title="«Y es posible que sea la continuación de las palabras de Ibn Abbas»",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 533", ar_ref="فتح الباري لابن حجر ١٣/٥٣٣", site=IW, url=F13,
  uso="Vídeo 1 · captura 1 (bloques 0 y 2)",
  es=["Su dicho: («Y nadie elimina el texto de un libro de entre los libros de Dios, poderoso y majestuoso, sino que lo tergiversan: lo interpretan de una forma que no es su interpretación»). En la transmisión de al-Kushmihani: «lo interpretan con una interpretación que no es la suya». Dijo nuestro maestro Ibn al-Mulaqqin en su comentario: «[[a:Esto que dijo es una de las dos opiniones sobre la interpretación de este versículo, y es la que él eligió]] —es decir, al-Bujari—. Muchos de nuestros compañeros [de escuela] han declarado expresamente que los judíos y los cristianos cambiaron la Torá y el Evangelio, y de ello dedujeron que es lícito tratar sus hojas sin respeto; y esto contradice lo que dice aquí al-Bujari». Fin de la cita. [[a:Y esto es casi explícito en que su dicho «Y nadie…», hasta el final, son palabras de al-Bujari, que las añadió a la explicación de Ibn Abbas]]; [[k:y es posible que sea la continuación de las palabras de Ibn Abbas en su explicación del versículo]]."],
  prueba="Ibn Hajar no «lo deja claro». Recoge la lectura de Ibn al-Mulaqqin (la frase sería de al-Bujari) y en la misma línea añade la otra posibilidad: que sea de Ibn Abbas. Y aun con la lectura de Ibn al-Mulaqqin, es «la opinión que eligió al-Bujari».",
  ojo="Ibn Hajar no dice cuál de las dos es la correcta: deja las dos abiertas."),

 dict(id="IH02", tema="Vídeos 1 y 2",
  title="Ibn Hajar corrige a al-Zarkashi: no se puede llamar «falsa» a esa opinión",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 534", ar_ref="فتح الباري لابن حجر ١٣/٥٣٤", site=IW, url=F13,
  uso="Vídeo 1 · captura 3 (bloque 2) · Vídeo 2 · captura 8 (bloque 6)",
  es=["Dijo el shaykh Badr al-Din al-Zarkashi: «Algunos autores tardíos se dejaron engañar por esto —es decir, por lo que dijo al-Bujari— y dijeron que sobre la tergiversación de la Torá hay discrepancia: si fue en el texto y en el sentido, o solo en el sentido; [[a:se inclinó por lo segundo y consideró lícito leerla, y es una opinión falsa]]. No hay discrepancia en que la tergiversaron y la cambiaron, y ocuparse en leerla y copiarla no es lícito por consenso. El Profeta ﷺ se enfadó cuando vio con Umar una hoja con algo de la Torá, y dijo: “Si Moisés estuviera vivo, no le cabría más que seguirme”. Si no fuera un pecado, no se habría enfadado por ello».<br><br>Digo [Ibn Hajar]: si el consenso está probado, no hay nada que discutir. Pero él lo ha limitado a ocuparse en copiarla y leerla: si se refiere a quien se dedica a eso y a nada más, no prueba lo que busca, porque se entendería que, si se dedica a ello junto con otras cosas, sería lícito; y si se refiere a dedicarse a ello sin más, eso es precisamente lo que está en discusión. [[k:Y calificar de falsa esa opinión, después de lo expuesto, también es objetable]]: [[k:se ha atribuido a Wahb ibn Munabbih, que es de los que más sabían de la Torá]], [[k:y se ha atribuido también a Ibn Abbas, el intérprete del Corán]]. [[k:Debería haber dejado de rechazarla a empujones]] [sin argumentos] y haberse ocupado de refutar las pruebas del contrario que he expuesto. [[k:Y su argumento de la historia de Umar para prohibirlo —donde pretende que hay consenso— también es objetable]]; lo explicaré después de exponer las vías del hadiz."],
  prueba="Cuando al-Zarkashi llama falsa (bāṭil) la opinión de que la alteración fue del sentido y no del texto, Ibn Hajar le responde que no puede despacharla así, porque se atribuye a Wahb y a Ibn Abbas, «el intérprete del Corán»: usa la atribución a Ibn Abbas como argumento. Y quien usa el hadiz de Umar es al-Zarkashi; Ibn Hajar lo objeta.",
  ojo="Ibn Hajar no dice que esa opinión sea la correcta; dice que no se puede declarar falsa sin refutar sus pruebas."),

 dict(id="IH03", tema="Vídeo 1",
  title="«No lo he visto con cadena conectada… aunque lo anterior y lo posterior son palabras suyas»",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 533", ar_ref="فتح الباري لابن حجر ١٣/٥٣٣", site=IW, url=F13,
  uso="Vídeo 1 · captura 4 (bloque 2)",
  es=["Su dicho («yuharrifūn: yuzīlūn», ‘tergiversan: eliminan’): [[a:no he visto esto transmitido con cadena conectada como palabras de Ibn Abbas por una vía firme]], [[k:a pesar de que lo que va antes es de sus palabras, y también lo que va después]], que es su dicho «dirāsatuhum: tilāwatuhum» (‘su estudio: su recitación’) y lo que sigue. Todo eso lo transmitió Ibn Abi Hatim por la vía de Ali ibn Abi Talha, de Ibn Abbas. Y ya se citó, en el capítulo «Cada día Él está en un asunto», algo de Ibn Abbas que difiere de lo que se dice aquí, es decir, de explicar yuharrifūn con yuzīlūn. [[k:Eso sí: lo transmitió Ibn Abi Hatim por la vía de Wahb ibn Munabbih]]."],
  prueba="En azul, lo que subrayaron en su entorno; en naranja, lo que cortaron. Ibn Hajar no encontró una cadena firme para esa glosa concreta, pero dice que lo de antes y lo de después sí son palabras de Ibn Abbas, y que la glosa la transmite Wahb.",
  ojo="Ibn Hajar señala también que en otro capítulo (el de Bujari 7523) hay de Ibn Abbas algo que difiere de esta glosa. Es la «contradicción» que el guion trata en el bloque 6 con la regla de armonizar (tarjeta IH09)."),

 dict(id="IH04", tema="«Dijo Fulano»",
  title="Las dos fórmulas: «dijo» (firme) y «se menciona» (débil)",
  ref="Ibn Hajar, Hady al-Sari (introducción a Fath al-Bari), cap. 4", ar_ref="هدي الساري مقدمة فتح الباري · الفصل الرابع", site=WS, url=HADY,
  uso="Vídeo 1 · captura 5 (bloque 3)",
  es=["Por taʿlīq se entiende [el hadiz] al que se le ha suprimido el comienzo de la cadena —uno o más transmisores, aunque sea hasta el final de la cadena—. [[k:Unas veces lo afirma con firmeza]], como con «dijo» (qāla), [[k:y otras no lo afirma con firmeza]], como con «se menciona» (yudhkaru).",
      "[El que en el libro solo aparece sin cadena completa] tiene dos formas: o lo cita con fórmula firme (jazm), o con fórmula de debilidad (tamrīḍ). [[k:De la primera fórmula se deduce la autenticidad hasta aquel de quien lo cita]]; pero queda por examinar a los transmisores que menciona de ese hadiz.",
      "La segunda fórmula, la de debilidad, [[k:no permite deducir la autenticidad]] hasta aquel de quien lo cita; pero entre esos casos hay lo que es auténtico y lo que no lo es."],
  prueba="«Dijo Fulano» es la fórmula firme: al-Bujari lo da por auténtico hasta Fulano. «Se menciona» es la débil: ahí hay de todo. En nuestro caso al-Bujari escribe «wa-qāla Ibn Abbas» («y dijo Ibn Abbas»): fórmula firme.",
  ojo="Estos fragmentos hablan de los hadices del Profeta; para los dichos de compañeros, mira la tarjeta IH05. La transcripción de wikisource tiene erratas de tecleo (por ejemplo, «إلا» donde debe ir «إلى»); las he traducido por el sentido."),

 dict(id="IH05", tema="«Dijo Fulano»",
  title="Dichos de compañeros: al-Bujari solo usa la fórmula firme si son auténticos o están compensados",
  ref="Ibn Hajar, Hady al-Sari (introducción a Fath al-Bari), cap. 4", ar_ref="هدي الساري مقدمة فتح الباري · الفصل الرابع", site=WS, url=HADY,
  uso="Refuerzo del bloque 3 (Vídeo 1)",
  es=["Esta es la norma de los [hadices] que se remontan al Profeta. En cuanto a los dichos de compañeros y sucesores (mawqūfāt), [[k:afirma con firmeza los que son auténticos según él, aunque no cumplan su condición]], [[k:y no afirma con firmeza los que tienen en su cadena debilidad o un corte, salvo cuando están compensados]], ya sea porque llegan por otra vía o porque son conocidos de quien los dijo. Y los dichos que cita —fatwas de los compañeros y de los sucesores, [[k:y sus interpretaciones de muchos versículos]]— los trae como apoyo y refuerzo de las posturas que elige en las cuestiones en que discrepan los imames."],
  prueba="Es exactamente nuestro caso: la interpretación de un versículo por un compañero, citada con «y dijo Ibn Abbas». Según Ibn Hajar, al-Bujari solo la cita así si es auténtica para él o está compensada, y la usa para apoyar la postura que elige.",
  ojo="La regla cubre lo que al-Bujari atribuye a Ibn Abbas. Si la frase «nadie elimina el texto…» forma parte de esa atribución o es un añadido es otra cuestión: la del idraj (tarjeta IH08)."),

 dict(id="IH06", tema="«Dijo Fulano»",
  title="al-Nukat 1/325: la fórmula firme es auténtica hasta quien se cita",
  ref="Ibn Hajar, al-Nukat ʿala kitab Ibn al-Salah, vol. 1, p. 325", ar_ref="النكت على كتاب ابن الصلاح لابن حجر ١/٣٢٥", site=IW, url="https://www.islamweb.net/ar/library/content/313/40/",
  uso="Vídeo 1 · captura 5 (bloque 3)",
  es=["El segundo [tipo] —el que en el libro solo aparece sin cadena completa (muʿallaq)— tiene dos formas: con fórmula firme o con fórmula de debilidad. [[k:La primera es auténtica hasta aquel de quien lo cita]], y queda por examinar a los transmisores que menciona; parte de ello cumple su condición."],
  prueba="El mismo criterio, en la obra de Ibn Hajar sobre la ciencia del hadiz. Es la cita que trae islamqa (respuesta 269251); aquí está en el propio libro, con volumen y página."),

 dict(id="IH07", tema="«Dijo Fulano»",
  title="Fath al-Bari 10/55: al-Bujari «no afirma con firmeza sino lo que es apto para ser aceptado»",
  ref="Ibn Hajar, Fath al-Bari, vol. 10, p. 55 (hadiz de los instrumentos, Bujari 5590)", ar_ref="فتح الباري لابن حجر ١٠/٥٥", site=IW, url="https://www.islamweb.net/ar/library/content/52/10218/",
  uso="Vídeo 1 · captura 7 (bloque 3)",
  es=["En cuanto a si lo oyó de Hisham [ibn ʿAmmar] sin intermediario o con intermediario, no tiene ninguna consecuencia, [[k:porque [al-Bujari] no afirma con firmeza sino lo que es apto para ser aceptado, sobre todo cuando lo presenta como prueba]].",
      "[[k:Y está establecido entre los grandes memorizadores (ḥuffāẓ) que lo que al-Bujari trae en sus taʿālīq con fórmula firme es auténtico hasta aquel de quien lo cita, aunque no sea uno de sus maestros]].",
      "Uno de ellos [de los dos puntos que señalo]: que al-Tabarani transmitió el hadiz en su Muʿjam al-Kabir de Musa ibn Sahl al-Juwayni y de Jaʿfar ibn Muhammad al-Firyabi, ambos de Hisham; y el Muʿjam al-Kabir es más conocido que el Musnad al-Shamiyyin, así que es mejor remitir a él. Además, lo transmitió Abu Nuʿaym en su Mustakhraj sobre al-Bujari, por la vía de ʿAbdan ibn Muhammad al-Marwazi y por la de Abu Bakr al-Baghandi, ambos de Hisham; [[k:y lo transmitió Ibn Hibban en su Sahih]], de al-Husayn ibn ʿAbdallah al-Qattan, de Hisham."],
  prueba="Bujari 5590 es un muʿallaq con «dijo Hisham ibn ʿAmmar», igual que «y dijo Ibn Abbas». Ibn Hajar no lo descarta por ser muʿallaq: aplica la regla de la fórmula firme y muestra las vías conectadas. Si «es muallaq» bastara para tirar una cita, caería también este hadiz.",
  ojo="La frase «el hadiz es auténtico, de conexión conocida», que se cita mucho en este debate, es de Ibn al-Salah, citado por Ibn Hajar en esta misma página. En el guion, mejor: «Ibn Hajar lo acepta y muestra que está conectado por otras vías»."),

 dict(id="IH08", tema="Interpolación",
  title="Cómo se demuestra una interpolación (idraj)",
  ref="Ibn Hajar, Nuzhat al-Nazar fi tawdih Nukhbat al-Fikar", ar_ref="نزهة النظر في توضيح نخبة الفكر", site=WS, url=NUZHA,
  uso="Vídeo 1 · captura 6 (bloque 3)",
  es=["En cuanto a la interpolación en el texto (mudraj al-matn): consiste en que en el texto aparezca algo que no es parte de él. Unas veces está al principio, otras en medio y otras al final —que es lo más frecuente—, porque se produce al unir una frase a otra, o al fundir, sin separación, un dicho de los compañeros o de quienes vinieron después con un dicho del Profeta ﷺ: eso es la interpolación en el texto.<br><br>La interpolación se reconoce:<br>· [[k:porque llega otra transmisión que separa la parte interpolada de aquello en lo que se interpoló]];<br>· [[k:o porque lo declara expresamente el transmisor, o alguno de los imames que conocen bien el tema]];<br>· [[k:o porque es imposible que el Profeta ﷺ dijera eso]]."],
  prueba="Para afirmar que «nadie elimina el texto…» es un añadido de al-Bujari hay que probarlo por uno de estos tres medios. No hay ninguna transmisión que la separe; nadie lo declara expresamente (Ibn al-Mulaqqin lo ve «casi explícito», e Ibn Hajar deja abierta la otra opción); y no es imposible que Ibn Abbas lo dijera: Wahb, su alumno, dice lo mismo.",
  ojo="Ibn Hajar formula estos criterios pensando sobre todo en dichos añadidos a palabras del Profeta; aquí se aplican por analogía a un dicho de un compañero."),

 dict(id="IH09", tema="Armonizar",
  title="La regla para dos informes que chocan: primero, armonizar",
  ref="Ibn Hajar, Nuzhat al-Nazar fi tawdih Nukhbat al-Fikar", ar_ref="نزهة النظر في توضيح نخبة الفكر", site=WS, url=NUZHA,
  uso="Vídeo 1 · captura 10 (bloque 6) · Vídeo 2 · bloque 7",
  es=["Si [un informe aceptado] tiene otro que lo contradice, o bien el que lo contradice es aceptable como él, o bien es rechazable. Lo segundo no tiene efecto, porque al fuerte no le afecta que le contradiga el débil. Y si la contradicción es con otro de su mismo nivel, [[k:o bien es posible armonizar lo que dicen ambos sin forzarlos, o no]]: [[k:si es posible armonizarlos, es el tipo llamado «hadices aparentemente contradictorios» (mukhtalif al-ḥadīth)]].",
      "Así, lo que aparentemente se contradice sigue este orden: [[k:la armonización, si es posible]]; después, ver cuál abroga y cuál queda abrogado; después, dar preferencia a uno, si se puede determinar; y por último, abstenerse de aplicar cualquiera de los dos."],
  prueba="Ante las dos narraciones de Ibn Abbas (Bujari 7523, «cambiaron… y escribieron con sus manos», y la glosa «nadie elimina el texto»), la regla de Ibn Hajar obliga a intentar armonizarlas antes de descartar una. Y se armonizan sin forzar: lo que «escribieron con sus manos» son libros propios e interpretaciones, como dice Wahb, no un borrado del texto. Lo mismo vale en el Vídeo 2 para el hadiz de Umar frente a los hadices de la lapidación.",
  ojo="La regla está pensada para hadices del Profeta; aplicarla a dos dichos de un mismo compañero es por analogía, pero es el procedimiento normal."),

 dict(id="IH10", tema="Contexto",
  title="Las cuatro opiniones: decir que «la cambiaron entera» es un exceso",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 533", ar_ref="فتح الباري لابن حجر ١٣/٥٣٣", site=IW, url=F13,
  uso="Contexto (pestañas principal e Historia)",
  es=["Dijo uno de los comentaristas tardíos: sobre esta cuestión hay varias opiniones. Primera: que fue cambiada entera; es lo que implica la opinión, ya citada, de que se puede tratar [sus hojas] sin respeto, [[k:y es un exceso]]. [[k:Hay que entender que quienes lo dicen de forma absoluta se refieren a la mayor parte; si no, es negar lo evidente]], [[k:y los versículos y los relatos que dicen que de ella quedaron muchas cosas sin cambiar son muchos]]. Entre ellos, la palabra de Dios: «los que siguen al Mensajero, el Profeta iletrado, al que encuentran escrito junto a ellos en la Torá y el Evangelio»; y la historia de la lapidación de los dos judíos, en la que aparece el versículo de la lapidación; y lo apoya la palabra de Dios: «Di: traed la Torá y leedla, si sois sinceros». Segunda: que el cambio se produjo, pero en la mayor parte de ella; sus pruebas son muchas, y la primera hay que entenderla así. Tercera: que se produjo en una pequeña parte y la mayor parte sigue como estaba; la defendió el shaykh Taqi al-Din ibn Taymiyya en su libro al-Jawab al-sahih li-man baddala din al-Masih. [[k:Cuarta: que el cambio y la alteración se produjeron solo en los sentidos, no en las palabras; y es la que se menciona aquí]]."],
  prueba="Incluso el comentarista que cita Ibn Hajar llama «exceso» a la tesis de la falsificación total, y la cuarta opinión (solo los sentidos) es «la que se menciona aquí», es decir, la del texto de al-Bujari.",
  ojo="No habla Ibn Hajar, sino «uno de los comentaristas tardíos» al que cita. Y la segunda opinión (cambio de la mayor parte) también está en la lista: no lo presentes como si Ibn Hajar defendiera que la Torá está intacta."),

 dict(id="IH11", tema="Vídeo 1",
  title="Ibn Hazm (s. V H.): «Nos ha llegado que hay musulmanes que niegan que estén alterados»",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 534 (citando a Ibn Hazm, al-Fisal)", ar_ref="فتح الباري لابن حجر ١٣/٥٣٤", site=IW, url=F13,
  uso="Vídeo 1 · captura 12 (bloque 7)",
  es=["[[k:Abu Muhammad ibn Hazm]] enumeró en su libro al-Fisal fi l-milal wa-l-nihal muchas cosas de este tipo…",
      "Luego dijo: «[[k:Nos ha llegado que hay un grupo de musulmanes que niegan que la Torá y el Evangelio que tienen en sus manos los judíos y los cristianos estén alterados]]; y lo que les lleva a eso es lo poco que les importan los textos del Corán y de la Sunna»."],
  prueba="El primero que sistematiza la falsificación total, en el siglo V, reconoce que había musulmanes que la negaban. Lo recoge Ibn Hajar.",
  ojo="Ibn Hazm los critica con dureza; muestra la frase entera, no solo la primera mitad."),

 dict(id="IH12", tema="Vídeo 2",
  title="Las vías del hadiz de Umar (1): al-Bazzar y Ahmad",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, pp. 534–535", ar_ref="فتح الباري لابن حجر ١٣/٥٣٤–٥٣٥", site=IW, url=F13,
  uso="Vídeo 2 · captura 1 (bloque 2) y bloques 3–4",
  es=["Lo transmitieron Ahmad y al-Bazzar —la redacción es de este— del hadiz de Jabir, que dijo: «[[k:Umar copió un escrito de la Torá en árabe]] y lo llevó al Profeta ﷺ; se puso a leer, y el rostro del Mensajero de Dios ﷺ cambiaba. Un hombre de los Ansar le dijo: “¡Ay de ti, hijo de al-Jattab! ¿No ves la cara del Mensajero de Dios ﷺ?”. Y el Mensajero de Dios ﷺ dijo: “No preguntéis a la Gente del Libro por nada, porque no os guiarán, ya que se extraviaron; [[k:y o bien desmentiréis una verdad, o bien creeréis una falsedad]]. Por Dios, si Moisés estuviera entre vosotros, no le sería lícito sino seguirme”». [[k:En su cadena está Jabir al-Juʿfi, que es débil]]. Y Ahmad y Abu Yaʿla, por otra vía de Jabir: que Umar trajo un escrito que había conseguido de unos libros de la Gente del Libro y se lo leyó al Profeta ﷺ, que se enfadó —y menciona algo parecido, sin lo del ansarí—; y en él: «Por Aquel en cuya mano está mi alma, si Moisés estuviera vivo, no le cabría más que seguirme». [[k:En su cadena está Mujalid ibn Saʿid, que es blando]]."],
  prueba="La versión que enseña Tibyanan (al-Bazzar) dice «en árabe» y «desmentiréis una verdad». Ibn Hajar califica las dos vías: Jabir al-Juʿfi, débil; Mujalid, blando."),

 dict(id="IH13", tema="Vídeo 2",
  title="Las vías del hadiz de Umar (2): al-Tabarani, Ahmad y Abu Yaʿla",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 535", ar_ref="فتح الباري لابن حجر ١٣/٥٣٥", site=IW, url=F13,
  uso="Vídeo 2 · bloques 2 y 5",
  es=["Y lo transmitió al-Tabarani [[k:con una cadena en la que hay un desconocido y uno discutido]], de Abu al-Dardaʾ: «Umar trajo unos extractos de la Torá…», y menciona algo parecido; nombra al ansarí que habló a Umar: ʿAbdallah ibn Zayd, el que vio [en sueños] la llamada a la oración; y en él: «Si Moisés estuviera entre vosotros y lo siguierais dejándome a mí, os extraviaríais lejos». Y lo transmitieron Ahmad y al-Tabarani del hadiz de ʿAbdallah ibn Thabit: «Vino Umar y dijo: “Mensajero de Dios, pasé junto a un hermano mío de los Banu Qurayza y me escribió unos extractos de la Torá; ¿te los presento?”. Y cambió el rostro del Mensajero de Dios ﷺ…» —el hadiz—, y en él: «Por Aquel en cuya mano está el alma de Muhammad, si Moisés amaneciera entre vosotros y lo siguierais dejándome a mí, os extraviaríais». Y Abu Yaʿla lo transmitió por la vía de Khalid ibn ʿUrfuta: «Estaba con Umar y vino un hombre de ʿAbd al-Qays; [Umar] le golpeó con un bastón que llevaba. Dijo: “¿Qué he hecho, Príncipe de los creyentes?”. Dijo: “¿Eres tú el que copió el libro de Daniel?”. Dijo: “Ordéname lo que quieras”. Dijo: “Ve y bórralo; si me llega que lo has leído o se lo has hecho leer a alguien, te castigaré duramente”. Luego dijo: “Fui y copié un libro de la Gente del Libro; luego vine, y el Mensajero de Dios ﷺ me dijo: ‘¿Qué es esto?’. Dije: ‘Un libro que he copiado para añadir saber a nuestro saber’. Y se enfadó hasta que se le enrojecieron las mejillas”». Y cuenta una historia en la que dice: «¡Gentes! Se me han dado las palabras que lo abarcan todo y sus conclusiones, y se me ha abreviado el discurso; [[k:os lo he traído blanco y puro]]; no os desconcertéis». [[k:En su cadena está ʿAbd al-Rahman ibn Ishaq al-Wasiti, que es débil]]."],
  prueba="Todas las vías tienen algún transmisor débil, desconocido o discutido, y ninguna dice que la Torá estuviera falsificada. El motivo que da el propio hadiz es «os lo he traído blanco y puro»: el mensaje nuevo basta."),

 dict(id="IH14", tema="Vídeo 2",
  title="«Juntas indican que tiene base» · «desaconsejado, no prohibido» · el enfado",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 535", ar_ref="فتح الباري لابن حجر ١٣/٥٣٥", site=IW, url=F13,
  uso="Vídeo 2 · capturas 5 y 8 (bloques 1 y 6)",
  es=["Estas son todas las vías de este hadiz; [[k:y aunque en ellas no hay ninguna que sirva de prueba, en conjunto indican que tiene base]]. Lo que parece [correcto] es [[k:que el desagrado por ello es de desaconsejamiento, no de prohibición]]. Lo mejor en esta cuestión es distinguir: quien no se ha afianzado ni es de los firmemente arraigados en la fe no debe mirar nada de eso; en cambio, el arraigado puede hacerlo, sobre todo cuando hace falta para responder al contrario. Lo prueba [[k:que los imames, antiguos y modernos, han citado de la Torá y han obligado a los judíos a reconocer a Muhammad ﷺ con lo que extraen de su propio libro]]; si no creyeran que es lícito mirarla, no lo habrían hecho ni habrían coincidido en ello. En cuanto a su argumento a favor de la prohibición por el enfado, y su afirmación de que, si no fuera pecado, no se habría enfadado, se le objeta que [[k:a veces se enfadaba por algo desaconsejado o por algo que no es lo mejor]], si lo hacía alguien de quien no era propio, [[k:como cuando se enfadó porque Muʿadh alargó la recitación en la oración del alba]]; y a veces se enfadaba con quien no entendía algo evidente, como el que preguntó por el camello extraviado. Ya se vio en el «Libro del saber» el enfado al exhortar, y en el «Libro de los modales», qué enfado es lícito."],
  prueba="Ibn Hajar concede que el episodio tiene base, pero concluye lo contrario que al-Zarkashi: leer la Torá es desaconsejable para quien no está firme y lícito para el sabio, y los imames la han citado siempre como prueba. El enfado no demuestra prohibición."),

 dict(id="IH15", tema="Vídeo 2",
  title="«Porque la Torá es uno de los libros de Dios»",
  ref="Ibn Hajar, Fath al-Bari, vol. 13, p. 526", ar_ref="فتح الباري لابن حجر ١٣/٥٢٦", site=IW, url="https://www.islamweb.net/ar/library/content/52/13810/",
  uso="Vídeo 2 · bloque 3 (la copia en árabe)",
  es=["Su dicho: (Capítulo: lo que es lícito de la explicación de la Torá y de los libros de Dios). Así en la versión de Abu Dharr; en la de los demás: «de la explicación de la Torá y de otros libros de Dios, ensalzado sea». En ambos casos se une lo general a lo particular, [[k:porque la Torá es uno de los libros de Dios]]. Su dicho: (en árabe y en otras), es decir, en otras lenguas; en la transmisión de al-Kushmihani: «en hebreo y en otras»; ambas tienen su sentido. [[k:En resumen: lo que está, por ejemplo, en árabe se puede expresar en hebreo, y al revés]]."],
  prueba="Al-Bujari dedica un capítulo a lo que es lícito explicar de la Torá en árabe y en otras lenguas, e Ibn Hajar lo justifica así: «la Torá es uno de los libros de Dios»."),

 dict(id="IH16", tema="Vídeo 2",
  title="Umar en la escuela judía: «vías que se fortalecen unas a otras»",
  ref="Ibn Hajar, Fath al-Bari, vol. 8, p. 16 en la edición de islamweb (capítulo «Quien sea enemigo de Gabriel»)", ar_ref="فتح الباري لابن حجر ٨/١٦ (طبعة إسلام ويب)", site=IW, url="https://www.islamweb.net/ar/library/content/52/8064/",
  uso="Vídeo 2 · captura 11 (bloque 8)",
  es=["Y al-Tabari transmitió por la vía de al-Shaʿbi «[[k:que Umar iba a los judíos, escuchaba la Torá y se maravillaba de cómo confirmaba lo que hay en el Corán]]. Dijo: pasó junto a ellos el Profeta ﷺ, y dije: “Os conjuro por Dios, ¿sabéis que es el Mensajero de Dios?”. Su sabio le dijo: “Sí, sabemos que es el Mensajero de Dios”. Dijo: “¿Y por qué no le seguís?”. Dijeron: “Tenemos un enemigo y un aliado entre los ángeles, y a su profecía se ha unido nuestro enemigo de entre los ángeles”». Y menciona el hadiz, y que alcanzó al Profeta ﷺ y este le recitó el versículo. Y lo trae también por la vía de Qatada, de Umar, de forma parecida. Y Ibn Abi Hatim y al-Tabari lo traen también por la vía de ʿAbd al-Rahman ibn Abi Layla: «Un judío encontró a Umar y le dijo: “El Gabriel del que habla vuestro compañero es enemigo nuestro”. Y Umar dijo: “Quien sea enemigo de Dios, de Sus ángeles, de Sus mensajeros, de Gabriel y de Miguel… Dios es enemigo de los incrédulos”. Y se reveló tal como él lo había dicho». [[k:Y estas son vías que se fortalecen unas a otras]]."],
  prueba="Ibn Hajar resume la vía de al-Shaʿbi así: Umar escuchaba la Torá y se maravillaba de cómo confirmaba el Corán. Y de las vías dice: «se fortalecen unas a otras».",
  ojo="Lo que las vías refuerzan es el episodio (Umar con los judíos y el versículo de Gabriel). El detalle de que «se maravillaba» solo está en la vía de al-Shaʿbi, y ninguna vía llega conectada hasta Umar."),

 dict(id="IH17", tema="Vídeo 2",
  title="Ibn Abi Layla y Umar: «se discute si le oyó»",
  ref="Ibn Hajar, Taqrib al-Tahdhib 1/597, en la ficha de transmisores de la Shamela", ar_ref="تقريب التهذيب لابن حجر ١/٥٩٧ · فهرس الرواة (الشاملة)", site="shamela.ws", url="https://shamela.ws/narrator/3234",
  uso="Vídeo 2 · bloque 8 (la vía de Ibn Abi Layla)",
  es=["Dijo Abu Hatim: «Se transmite de ʿAbd al-Rahman que vio a Umar, [[k:y algunos sabios ponen entre él y Umar a al-Baraʾ ibn ʿAzib, y otros a Kaʿb ibn ʿUjra]]». [Tahdhib al-Tahdhib 2/548] · ʿAbd al-Rahman [ibn Abi Hatim] dijo: «Pregunté a mi padre por ʿAbd al-Rahman ibn Abi Layla y dijo: no hay problema con él». [al-Jarh wa-l-taʿdil 5/301] · Preguntaron a Abu Hatim: «¿Oyó ʿAbd al-Rahman ibn Abi Layla de Bilal?». Dijo: «Bilal salió pronto hacia Siria, en el califato de Umar; si lo vio, fue de pequeño, pues nació durante el califato de Umar. Y se transmite de ʿAbd al-Rahman ibn Abi Layla que vio a Umar, y algunos sabios ponen entre él y Umar a al-Baraʾ ibn ʿAzib, y otros a Kaʿb ibn ʿUjra». [Tuhfat al-tahsil 1/303] · Dijo Ibn Abi Hatim: «Pregunté a mi padre: ¿es correcto que ʿAbd al-Rahman ibn Abi Layla oyera de Umar? [[k:Dijo: no]]». [Tuhfat al-tahsil 1/303] · Dijo Ibn Abi Hatim: «Pregunté a mi padre: ¿es correcto que Ibn Abi Layla oyera de Umar? Dijo: no». [Tahdhib al-Tahdhib 2/548]",
      "Ibn Hajar: «[[k:Se discute si oyó de Umar]]». [Taqrib al-Tahdhib 1/597] · «Y de ʿAbdallah ibn Zayd ibn ʿAbd Rabbih, y no le oyó». [Tahdhib al-Tahdhib 2/548] · Ibn al-Barqi dijo en Rijal al-Muwattaʾ, en la biografía de ʿAbd al-Rahman ibn Abi Layla, el conocido sucesor: «Alcanzó al Profeta ﷺ». Parece que lo confundió con su padre; otros han declarado que nació en tiempos de Umar, se discute si es auténtico que le oyera, y tiene relatos sin intermediario (marāsīl). [al-Isaba 6/561] · «Fiable» (thiqa). [Taqrib al-Tahdhib 1/597]"],
  prueba="La vía de Ibn Abi Layla tampoco llega con seguridad a Umar: Ibn Hajar dice que se discute si le oyó, y Abu Hatim lo niega. Por eso el guion dice que ninguna vía llega conectada hasta Umar.",
  ojo="La ficha de la Shamela es una recopilación moderna; las referencias entre corchetes son las que da la propia ficha."),
]
