# -*- coding: utf-8 -*-
# Ibn Hazm, al-Fisal: cómo argumenta que la Torá y el Evangelio están alterados.
# [[k:...]] naranja = frase clave; [[a:...]] azul = matiz o lo que juega en contra.

B = "https://shamela.ws/book/6521/"
SITE = "shamela.ws (Maktaba Shamila; paginación igual a la ed. de Maktabat al-Khanji, El Cairo)"
AR = "الفصل في الملل والأهواء والنحل لابن حزم "
P1 = "Parte 1 · Su criterio"
P2 = "Parte 2 · «No coincide con el Corán»"
P3 = "Parte 3 · Argumentos que no dependen del Corán"
P4 = "Parte 4 · Cuando le conviene, lo usa"
CIRC = "Tipo: depende del Corán o de la doctrina islámica (circular ante un cristiano)"
INT = "Tipo: interno o histórico (no circular)"
SEL = "Tipo: uso selectivo del texto"

def ref(p): return f"Ibn Hazm, al-Fisal fi l-milal wa-l-ahwaʾ wa-l-nihal, {p}"

ZCARDS = [
 dict(id="Z01", tag=P1, chip="Tipo: premisa", specs=["Z01"],
  title="«Todo libro en el que se escriba una mentira es falso»: así empieza su crítica",
  ref=ref("vol. 1, p. 93"), ar_ref=AR+"١/٩٣", site=SITE, url=B+"85",
  es=["Dijo Abu Muhammad: [[k:todo libro en el que se haya escrito una mentira es falso, inventado, y no viene de Dios]], poderoso y majestuoso. Así queda clara la falsedad de la religión de los magos, igual que quedó clara la falsedad de la religión de los judíos y de los cristianos, exactamente igual; alabado sea Dios, Señor de los mundos.<br><br>Capítulo sobre las contradicciones evidentes y las mentiras claras del libro que los judíos llaman la Torá, de sus demás libros y de los cuatro Evangelios, [[k:con las que se tiene la certeza de su tergiversación y su cambio]] y de que no son lo que Dios, poderoso y majestuoso, reveló.<br><br>Dijo Abu Muhammad: mencionaremos, si Dios quiere, la mentira que hay en esos libros, de la que nadie con un mínimo de discernimiento duda que es mentira contra Dios y contra los ángeles…"],
  prueba="Ibn Hazm (m. 456 H) fija su premisa al empezar: basta una mentira para que el libro entero sea falso. La pregunta es quién decide qué es «mentira». Lo dice en Z02."),

 dict(id="Z02", tag=P1, chip=CIRC, specs=["Z02"],
  title="Su vara de medir: «lo que el Corán confirma, lo creemos; lo que el texto desmiente, lo desmentimos»",
  ref=ref("vol. 1, p. 160"), ar_ref=AR+"١/١٦٠", site=SITE, url=B+"152",
  es=["La Gente del Libro leía la Torá en hebreo y la explicaba en árabe a los musulmanes, y el Mensajero de Dios ﷺ dijo: «No creáis a la Gente del Libro ni la desmintáis, y decid: creemos en lo que se nos ha revelado y en lo que se os ha revelado, y nuestro Dios y vuestro Dios es uno». Dijo Abu Muhammad: [[k:esta es exactamente nuestra postura]], alabado sea Dios: [[k:lo que el Corán y la Sunna del Profeta ﷺ confirman, lo creemos]]; [[k:lo que el texto desmiente, o cuya mentira es evidente, lo desmentimos]]; y lo que ningún texto confirma ni desmiente, y puede ser verdad o mentira, ni lo creemos ni lo desmentimos, y decimos lo que el Mensajero de Dios ﷺ nos mandó decir, como hacemos con la profecía de aquellos cuyo nombre no menciona ningún texto."],
  prueba="Aquí está su criterio: el Corán y la Sunna deciden qué parte de la Torá es verdad y qué parte es mentira. Dentro del islam es coherente; como prueba ante un cristiano es una petición de principio, porque da por probado justo lo que se discute.",
  ojo="Cita el mismo hadiz de Bujari (U07), pero le añade una condición: «no creáis ni desmintáis» queda solo para lo que el Corán no confirma ni desmiente; lo que choca con el Corán, lo desmiente."),

 dict(id="Z03", tag=P1, chip=CIRC, specs=["Z03"],
  title="La «Torá verdadera» es la que describe el Corán: «afirmamos que no es esta que tienen»",
  ref=ref("vol. 1, p. 152"), ar_ref=AR+"١/١٥٢", site=SITE, url=B+"144",
  es=["En cuanto a la Torá, [los judíos] nunca coincidieron con nosotros en ella, porque nosotros reconocemos una Torá verdadera que Dios reveló a Moisés —la paz sea con él— y a sus compañeros, [[k:porque Dios nos lo dijo en Su Libro]], que habla por boca del veraz Mensajero de Dios ﷺ; [[k:y afirmamos con certeza que no es esta que tienen en sus manos]] tal como está, sino que muchos de ellos la tergiversaron y la cambiaron. Ellos reconocen esta que tienen en sus manos, y no conocen la que nosotros creemos."],
  prueba="La «Torá verdadera» de Ibn Hazm no es un manuscrito que se pueda enseñar: es la que el Corán describe. Por definición, cualquier Torá real que no coincida con el Corán será «otra»."),

 dict(id="Z04", tag=P1, chip=CIRC, specs=["Z04"],
  title="Él mismo lo admite: «solo argumentamos con esto después de probar su misión»",
  ref=ref("vol. 1, p. 158"), ar_ref=AR+"١/١٥٨", site=SITE, url=B+"150",
  es=["En cuanto a que el Mensajero de Dios ﷺ citara la Torá sobre la lapidación del adúltero casado, y que Ibn Salam golpeara la mano de Ibn Suriya cuando la puso sobre el versículo de la lapidación, es verdad, y es de lo que dijimos antes: que Dios lo dejó para avergonzarlos y como prueba contra ellos. [[k:Y solo se argumenta contra ellos con todo esto después de haber probado su misión ﷺ con pruebas]] claras y deslumbrantes, mediante la transmisión que no deja excusa, como hemos explicado y explicaremos, si Dios quiere. Luego traemos lo que Dios dejó en sus libros alterados que lo menciona, para humillarlos, avergonzarlos y poner en evidencia su extravío, [[k:no porque lo necesitemos en absoluto]]; alabado sea Dios. [[a:Y en cuanto a la noticia de que el Profeta tomó la Torá y dijo «creo en lo que hay en ti», es una noticia mentirosa, inventada]]."],
  prueba="El orden de su argumento lo dice él: primero se prueba que Muhammad es profeta, y después se juzga la Torá desde ahí. La «alteración» no es una prueba independiente: es una consecuencia de su fe. Ante un cristiano, el debate tiene que ir a la profecía, no a la Torá.",
  ojo="Ibn Hazm llama «inventado» el relato «creo en lo que hay en ti» (en azul), parecido al de Abu Dawud 4449 («creo en ti y en Quien te reveló»), que al-Albani califica de hasan (U09b)."),

 dict(id="Z05", tag=P2, chip=CIRC, specs=["Z05"],
  title="El argumento central: el Corán dice que Muhammad está en la Torá; no está; luego la cambiaron",
  ref=ref("vol. 1, p. 160"), ar_ref=AR+"١/١٦٠", site=SITE, url=B+"152",
  es=["Y decimos a quien, entre los musulmanes, dice que su transmisión es masiva (tawātur), que da certeza y sirve de prueba: no hay duda de que ellos no discrepan en que [[k:lo que han transmitido de Moisés y de Jesús —la paz sea con ellos— no menciona en absoluto a Muhammad ﷺ]] ni anuncia su profecía. Si esos que lo dicen les creen en una parte de lo que transmiten, tienen que creerles en todo, quieran o no; y si les desmienten en una parte y les creen en otra, se contradicen y se ve su obstinación; y es falso que una única transmisión, llegada de una misma manera, sea en parte verdad y en parte falsedad. No sabemos cómo un musulmán se permite negar la tergiversación de la Torá y el Evangelio cuando oye la palabra de Dios: «Muhammad es el Mensajero de Dios; los que están con él son duros con los incrédulos y compasivos entre ellos… Esa es su descripción en la Torá, y su descripción en el Evangelio es como una semilla que echa su brote, lo fortalece, engruesa y se yergue sobre su tallo…» (48:29). [[k:Y nada de esto está en lo que tienen en sus manos los judíos y los cristianos]] y dicen que es la Torá y el Evangelio. [[k:Así que estos ignorantes no tienen más remedio que creer a su Señor]] —que los judíos y los cristianos cambiaron la Torá y el Evangelio— o volver a la necedad, desmentir a su Señor, creer a los judíos y a los cristianos y unirse a ellos… Aunque no hubiera ningún texto que dijera que los cambiaron, sabríamos con certeza que los cambiaron, como sabemos lo que vemos con nuestros sentidos; [[k:pero se han juntado la observación y el texto]]."],
  prueba="Es el núcleo y es circular: «el Corán dice que Muhammad está descrito en la Torá y el Evangelio; los que tienen no lo describen; luego los cambiaron». La conclusión depende de dar por verdadero el Corán, que es justo lo que un cristiano discute. Con la misma lógica, un cristiano «probaría» que el Corán está alterado porque no coincide con el Evangelio.",
  ojo="Aquí dice que lo que transmiten «no menciona en absoluto a Muhammad»; en Z16 y Z18 dice que lo anuncian «claramente». Y la imagen de la semilla que crece por sí sola sí está en el Evangelio (Marcos 4:26–28)."),

 dict(id="Z06", tag=P2, chip=CIRC, specs=["Z06"],
  title="Abraham y los ángeles: «¿dónde queda esta mentira frente a la palabra de Dios en esta misma historia?»",
  ref=ref("vol. 1, p. 104 (sobre Génesis 18)"), ar_ref=AR+"١/١٠٤", site=SITE, url=B+"96",
  es=["La sexta: que cuenta que comieron pan, asado, mantequilla y leche; y lejos de él que esto sea noticia de Dios, ni de los ángeles. [[k:¿Dónde queda esta mentira insulsa y vergonzosa]], que se parece a la mente de los judíos que la creen, [[k:frente a la verdad luminosa y clara, iluminada por la certeza, de la palabra de Dios, poderoso y majestuoso, en esta misma historia]]: «Nuestros mensajeros vinieron a Abraham con la buena nueva. Dijeron: “Paz”. Dijo: “Paz”. Y no tardó en traer un ternero asado. Y cuando vio que sus manos no lo tocaban, los desconoció y sintió miedo de ellos. Dijeron: “No temas: hemos sido enviados al pueblo de Lot”» (11:69–70)… ¡Qué lejos está la luz de la verdad de las tinieblas de la mentira!"],
  prueba="La «prueba» es que el Génesis (los ángeles comen) no coincide con el Corán (no comen). Eso muestra que los dos relatos difieren, no cuál cambió. Para decidirlo, da por supuesto que el verdadero es el Corán."),

 dict(id="Z07", tag=P2, chip=CIRC, specs=["Z07a","Z07b"],
  title="Aarón y el becerro: «la verdad es que quien les hizo el becerro fue el Samiri»",
  ref=ref("vol. 1, pp. 124–125 (sobre Éxodo 32)"), ar_ref=AR+"١/١٢٤–١٢٥", site=SITE, url=B+"116",
  es=["Este capítulo supera todo lo anterior: [[k:que Aarón, siendo un profeta enviado, se proponga hacer a su pueblo un dios]] al que adoren en vez de Dios, poderoso y majestuoso, pregone «mañana es fiesta del Señor», levante un altar al becerro, les ayude a ofrecerle sacrificios, y luego los desnude y les descubra las nalgas para bailar y cantar delante del becerro…",
      "¿Dónde queda este delirio insulso y esta mentira inventada [[k:frente a la luz de la verdad, de la que la razón atestigua que es correcta, que trajo Muhammad, el Mensajero de Dios ﷺ]], de parte de Dios, poderoso y majestuoso, cuando dice en esta misma historia lo único posible: «Y el pueblo de Moisés tomó, después de él, de sus joyas, un becerro, un cuerpo que mugía…» (7:148); y «Así lo lanzó el Samiri, y les sacó un becerro…»; «Aarón ya les había dicho antes: “Pueblo mío, solo habéis sido puestos a prueba con él…”»; «…“Hijo de mi madre, el pueblo me consideró débil y casi me matan”» (20:87–94; 7:150). [[k:Esta es la verdad: quien les hizo el becerro fue el Samiri, el incrédulo extraviado]]; Aarón se lo prohibió con todas sus fuerzas, pero le desobedecieron y casi lo matan. Ya ha amanecido para quien tiene ojos, y ha brillado la verdad de Su palabra frente a la mentira de los mentirosos."],
  prueba="Otra vez la vara es el Corán: el Éxodo dice que fue Aarón; el Corán, que fue el Samiri. Ibn Hazm concluye que miente el Éxodo porque contradice al Corán.",
  ojo="Añade un argumento de razón (un profeta no haría un ídolo), pero también depende de una doctrina islámica: la impecabilidad de los profetas (ʿiṣma), que la Biblia no comparte."),

 dict(id="Z08", tag=P2, chip=CIRC, specs=["Z08a","Z08b"],
  title="María y José en Lucas: «¿dónde queda esta falsedad frente a la palabra de Dios?»",
  ref=ref("vol. 2, pp. 50–51 (sobre Lucas 2:48)"), ar_ref=AR+"٢/٥٠–٥١", site=SITE, url=B+"207",
  es=["¿Cómo dice Lucas —que para ellos está por encima de Moisés— que José el carpintero es el padre del Mesías, en más de un lugar, y lo repite como algo sabido? ¿Y cómo dice María a su hijo «tu padre te buscaba», refiriéndose a su marido, según vosotros? ¿Cómo va a ser su padre, si no tiene padre? Eso solo se dice del padrastro de alguien cuyo padre se conoce: se le dice «tu padre» refiriéndose a quien lo cría, porque no hay confusión; pero en alguien que no tiene padre, llamar padre al marido de su madre es confusión, engaño y camino a la desgracia. ¿Y cómo va a vivir la Virgen María con su marido, según ellos —Dios les rompa la boca—, más de trece años, como vive un hombre con su mujer, cerrando la misma puerta? ¿Y cómo puede ser, con esto, que nació sin varón? [[k:¿Dónde queda esta falsedad inventada frente a la luz que sigue la palabra de Dios]], verdadera, en Su revelación que habla a Su Mensajero veraz, «al que no llega la falsedad ni por delante ni por detrás», cuando dice:",
      "Dijo Abu Muhammad: [[k:esta es la verdad clara, que se confirma a sí misma]], no la mentira contradictoria; y es lo único posible, porque si ella hubiera tenido marido nadie habría reprochado su parto; y si no hubiera habido la prueba de que él habló en la cuna, no sería admisible, ni para nosotros ni para nadie, que lo concibió sin eso, y sería una pretensión falsa que nadie podría creer."],
  prueba="En el Evangelio hace lo mismo: lo que no encaja con el relato coránico de María (sura 19) es «falsedad»; lo que dice el Corán es «la verdad que se confirma a sí misma».",
  ojo="Su objeción a «tu padre» (Lc 2:48) pasa por alto que Lucas aclara que Jesús era hijo de José «según se creía» (Lc 3:23)."),

 dict(id="Z09", tag=P2, chip=CIRC, specs=["Z09a","Z09b"],
  title="Lot y sus hijas: «que Dios dejara a Su profeta caer en esta enorme indecencia»",
  ref=ref("vol. 1, pp. 105–106 (sobre Génesis 19)"), ar_ref=AR+"١/١٠٥–١٠٦", site=SITE, url=B+"97",
  es=["En estos capítulos hay escándalos y vergüenzas [[k:que hacen estremecer la piel de los creyentes en Dios]] que conocen los derechos de los profetas —la paz sea con ellos—.",
      "…[atribuyen] a Dios, poderoso y majestuoso, que [[k:dejara a Su profeta y mensajero ﷺ caer en esta enorme indecencia]] de acostarse con sus dos hijas, una tras otra. Si dicen: «No tiene culpa, porque lo hizo borracho y sin saber quiénes eran», decimos: ¿y qué hizo cuando las vio embarazadas, cuando vio que habían dado a luz dos hijos ilegítimos y cuando las vio criar a los hijos de la fornicación? Son escándalos eternos, invento de herejes que se burlan de Dios y de Sus mensajeros. Y la tercera: que atribuyen a Dios que hiciera descender de Lot a los hijos de esos dos bastardos y les diera en herencia dos países, como heredaron los hijos de Israel y los de Esaú, hijos de Isaac, exactamente igual. ¡Dios está muy por encima de eso!"],
  prueba="La razón para rechazar el texto es teológica: un profeta no puede hacer eso. Es la doctrina islámica de la impecabilidad de los profetas aplicada a la Biblia.",
  ojo="En la Biblia, Lot no es un profeta en sentido islámico, y el relato cuenta un pecado sin aprobarlo. Juzgarlo con la ʿiṣma es medir la Biblia con una regla islámica."),

 dict(id="Z10", tag=P2, chip=CIRC, specs=["Z10a","Z10b"],
  title="Jacob lucha con Dios: «certeza de que su Torá está cambiada»… y el Profeta luchó con Rukana",
  ref=ref("vol. 1, pp. 110–111 (sobre Génesis 32)"), ar_ref=AR+"١/١١٠–١١١", site=SITE, url=B+"102",
  es=["Menciona en este lugar que [[k:Jacob luchó con Dios]], poderoso y majestuoso —Dios está por encima de eso y de cualquier parecido con Sus criaturas, cuánto más del juego de la lucha, que solo practican los ociosos, mientras que la gente sensata no lo hace sin necesidad—; y no se conformaron con este escándalo, sino que dijeron…",
      "…que Dios, poderoso y majestuoso, fue incapaz de derribarle, según el texto de su Torá; y lo confirma lo que cuentan de Dios, que dijo: «Has sido fuerte con Dios, ¡cuánto más con los hombres!». Me contó alguien entendido en hebreo que por eso lo llamó Israel: «El» es en su lengua, sin duda ni discusión, el nombre de Dios, y el sentido es «sujetó a Dios», recordando el agarre tras la lucha, cuando le dijo «suéltame» y Jacob le respondió «no te soltaré hasta que me bendigas». He golpeado con este capítulo la cara de los que se ponían a discutir conmigo en todas las reuniones; se mantuvieron en que el texto de la Torá dice que Jacob luchó con Elohim, y que la palabra Elohim se usa para el ángel, así que luchó con un ángel. Les dije: el contexto anula lo que decís, porque en él está «has sido fuerte con Dios, ¡cuánto más con los hombres!», y que Jacob dijo «he visto a Dios cara a cara y he salvado la vida»; no puede asombrarse de salvar la vida por haber visto a un ángel, ni el toque de un ángel llevaría a Jacob a prohibir a los hijos de Israel comer el tendón del muslo para siempre; y en él está que llamó al lugar Penuel porque se encontró con El, que es Dios, sin otra posibilidad para vosotros. Y aunque fuera un ángel, como pretendéis al debatir, también sería un error que lucharan un profeta y un ángel sin motivo: eso es propio de seres de la misma naturaleza, no de ángeles y profetas. [[a:Si se dice: «Habéis transmitido que vuestro Profeta luchó con Rukana ibn ʿAbd Yazid»]], decimos: sí, porque Rukana era tan fuerte que nadie en Arabia podía con él, y el Mensajero de Dios ﷺ no se distinguía por una fuerza especial; lo llamó al islam y Rukana le dijo: «Si me derribas, creeré en ti», viendo que eso sería un milagro; el Profeta le mandó prepararse y lo derribó enseguida, y Rukana se hizo musulmán al cabo de un tiempo. Entre las dos cosas hay la diferencia que hay entre la razón y la necedad, y cada situación tiene su palabra. Pero si, según vosotros, los ángeles comen trozos de pan para fortalecer el corazón, y asado, leche, mantequilla y tortas, ¿qué tiene de raro que algunos luchen con la gente por los caminos? Son desgracias que atestiguan su extravío y su abandono, [[k:y la certeza de que su Torá está cambiada]]."],
  prueba="El criterio es teológico: Dios no puede luchar con un hombre. Y cuando le recuerdan que el Profeta luchó con Rukana (en azul), lo justifica como milagro: la misma clase de hecho se acepta en una tradición y se declara falsificación en la otra."),

 dict(id="Z11", tag=P2, chip=CIRC, specs=["Z11a","Z11b"],
  title="«A nuestra semejanza» y «como uno de nosotros»: «su falsedad se sabe por evidencia de la razón»",
  ref=ref("vol. 1, pp. 95 y 97 (sobre Génesis 1:26 y 3:22)"), ar_ref=AR+"١/٩٥ و١/٩٧", site=SITE, url=B+"87",
  es=["«Hagamos a Adán a nuestra imagen, a nuestra semejanza». Dijo Abu Muhammad: si solo hubiera dicho «a nuestra imagen», tendría una explicación buena y un sentido correcto: atribuir la imagen a Dios como se atribuye lo que Él posee y crea, como cuando dices «esto es obra de Dios», o dices del mono, de lo feo y de lo bello «esta es la imagen de Dios», es decir, la forma que Dios dio y la cualidad que solo Él posee y crea. [[k:Pero su «a nuestra semejanza» impide las interpretaciones]], cierra las salidas y corta los caminos, y obliga necesariamente a que Adán se parezca a Dios, poderoso y majestuoso; [[k:y que esto es falso se sabe por evidencia de la razón]], porque «semejanza» y «parecido» significan lo mismo, y lejos de Dios tener semejante o parecido.",
      "«He aquí que Adán ha llegado a ser como uno de nosotros en el conocimiento del bien y del mal; y ahora, que no extienda la mano y tome del árbol de la vida, coma y viva para siempre»; y Dios lo expulsó de los jardines del Edén. Dijo Abu Muhammad: que cuenten de Dios que dijo «he aquí que Adán ha llegado a ser como uno de nosotros» [[k:es una de las calamidades del tiempo]], [[k:y obliga necesariamente a que sean dioses, más de uno]]. Este dicho perverso e inventado llevó a muchos judíos selectos a creer que quien creó a Adán no fue sino una criatura que Dios creó antes de Adán, que comió del árbol del que comió Adán, conoció el bien y el mal, luego comió del árbol de la vida y se convirtió en un dios entre los dioses. Nos refugiamos en Dios de esta incredulidad necia, y Le alabamos por habernos guiado a la religión resplandeciente y clara, cuya pureza de toda mezcla atestigua que viene de Dios."],
  prueba="Aquí el argumento es de razón y de doctrina (Dios no tiene semejante ni plural), no de comparación con el Corán. Aun así, el método es el mismo: lo que no encaja con su teología es alteración.",
  ojo="Ibn Hazm sí acepta leer «a nuestra imagen» de forma no literal, como lee el hadiz de Bujari «Dios creó a Adán a su imagen» y los versículos que hablan de la mano o el rostro de Dios. A la Torá no le concede esa misma lectura cuando dice «semejanza»: ahí declara que la interpretación queda cerrada."),

 dict(id="Z12", tag=P3, chip=INT, specs=["Z12"],
  title="Matusalén y el diluvio: un problema de cifras",
  ref=ref("vol. 1, p. 98 (sobre Génesis 5–7)"), ar_ref=AR+"١/٩٨", site=SITE, url=B+"90",
  es=["Después menciona que Matusalén, hijo de Henoc, hijo de Jared, vivió novecientos sesenta y nueve años; que le nació Lamec cuando tenía ciento ochenta y siete; y que a Lamec, a los ciento ochenta y dos, le nació Noé —la paz sea con él—. Así que no hay duda de que Matusalén tenía trescientos sesenta y nueve años cuando nació Noé, y se sigue necesariamente que Noé tenía seiscientos años cuando murió Matusalén. Fijaos bien en esto.",
      "Se sigue necesariamente, sin escapatoria, [[k:que Matusalén, hijo de Henoc, entró en el arca y murió en ella]] dos meses menos tres días antes de que salieran; y [la Torá] afirma tajantemente que no entró en el arca nadie salvo Noé, sus tres hijos, su mujer y las tres mujeres de sus hijos, y que no se salvó de ahogarse ningún ser humano ni animal fuera del arca. Son mentiras evidentes —Dios nos libre de algo así—: según el texto de su Torá, Matusalén no se ahogó, porque si se hubiera ahogado no habría completado el año en que Noé cumplía seiscientos, y según su texto lo completó; además, para ellos es alabado y nunca mereció la destrucción. Y descartaron que entrara en el arca, al afirmar que no entró nadie salvo Noé, sus tres hijos y sus mujeres; y descartaron que se salvara fuera, al afirmar que no se salvó ni persona ni animal fuera de ella. Y Matusalén tiene que estar en uno de esos tres casos. [[k:Así aparece la mentira pura en la transmisión de su Torá]], necesariamente, y todo el que razona tiene la certeza de que no fue revelada por Dios ni la trajo profeta alguno, porque Dios no miente y los profetas no traen mentiras; así que es seguro que es obra de un hereje ignorante o de alguien que se burla de ellos. Nos refugiamos en Dios de estar en su lugar. Y en este capítulo hay bastante."],
  prueba="Este argumento no es circular: es una contradicción interna de cifras. Merece otra respuesta: como mucho prueba un problema en los números de una genealogía, no que el libro entero sea un invento.",
  ojo="Es un problema conocido: los manuscritos antiguos (texto hebreo, griego y samaritano) dan cifras distintas en estas genealogías, y la tradición judía ya lo discutía. Es un problema de copia de números, no de contenido."),

 dict(id="Z13", tag=P3, chip=INT, specs=["Z13a","Z13b"],
  title="La muerte de Moisés al final de la Torá: «no pudo revelarse a Moisés en vida»",
  ref=ref("vol. 1, pp. 140–141 (sobre Deuteronomio 34)"), ar_ref=AR+"١/١٤٠–١٤١", site=SITE, url=B+"132",
  es=["Luego dice al final de su Torá: «[[k:Y murió Moisés, siervo de Dios, en ese lugar]], en la tierra de Moab, frente a Bet-Peor, [[k:y ningún ser humano ha conocido el lugar de su tumba hasta hoy]]. Moisés tenía ciento veinte años cuando murió; no se le había debilitado la vista ni movido los dientes. Los hijos de Israel lo lloraron en las llanuras de Moab treinta días y completaron su duelo. Luego Josué, hijo de Nun, se llenó del espíritu de Dios cuando Moisés le impuso las manos; los hijos de Israel le obedecieron e hicieron lo que Dios mandó a Moisés. Y no surgió después de Moisés en Israel un profeta como él…»",
      "Dijo Abu Muhammad: este es el final de su Torá y su conclusión; y este capítulo es testigo justo, prueba completa, argumento tajante y demostración veraz de que su Torá está cambiada y de que es una historia compuesta que les escribió alguien por ignorancia o a propósito, y que no fue revelada por Dios, [[k:pues no es posible que este capítulo se revelara a Moisés en vida]]… y su dicho «nadie ha conocido su tumba hasta hoy» basta para mostrar lo que hemos dicho, [[k:y que es una historia compuesta mucho tiempo después]], necesariamente."],
  prueba="Tampoco es circular: el relato de la muerte de Moisés no lo escribió Moisés. Pero lo que prueba es que el libro tiene partes añadidas por otros, cosa que la propia tradición judía dice (el Talmud atribuye esos versículos finales a Josué). No prueba que lo demás sea inventado."),

 dict(id="Z14", tag=P3, chip=INT, specs=["Z14a","Z14b"],
  title="Su argumento histórico: reyes idólatras, la Torá quemada, Esdras… usando libros que él llama «corruptos»",
  ref=ref("vol. 1, pp. 147–148"), ar_ref=AR+"١/١٤٧–١٤٨", site=SITE, url=B+"139",
  es=["Y quedó claro con certeza que el reino de los hijos de Judá y de Benjamín, después de la muerte de Salomón, duró cuatrocientos años menos algunos, con una diferencia entre sus libros de una docena de años; [[a:y ya dijimos que son libros corruptos y falsos]].",
      "…entre ellos [sus reyes] hubo quien borró los nombres de Dios de la Torá, [[k:y quien la quemó y acabó con su rastro]]; y después de ellos no encontramos que apareciera entre ellos fe, sino incredulidad y asesinato de profetas, hasta que su reino se acabó del todo con la invasión de Nabucodonosor.",
      "…hasta que se la dictó de memoria Esdras el escriba, el aaronita; [[k:y ellos admiten que la encontró entre ellos con muchos defectos y la corrigió]]; y esto basta.",
      "Con menos que esto basta, para quien razona, [[k:para saber que es un libro cambiado, mentiroso, inventado]], y una religión fabricada distinta de la que reconocen que les trajo Moisés."],
  prueba="Es su argumento histórico, y no es circular. Pero tiene un problema: para reconstruir esa historia se apoya en los libros históricos de los judíos, que él mismo acaba de llamar «corruptos y falsos» (en azul).",
  ojo="Al-Tabari transmite la misma historia de Esdras con la conclusión contraria: la Torá restituida era la misma (H11b, H11c). Página 148: https://shamela.ws/book/6521/140"),

 dict(id="Z15", tag=P3, chip=INT, specs=["Z15"],
  title="Las genealogías de Mateo y Lucas… y cómo despacha la armonización: «esta locura»",
  ref=ref("vol. 2, p. 13"), ar_ref=AR+"٢/١٣", site=SITE, url=B+"170",
  es=["¡Asombraos de esta desgracia que les ha caído, qué fea, qué horrible, qué sucia, qué vil, qué baja y qué ruin! [[k:Mateo el mentiroso hace descender al Mesías de José el carpintero]], y luego a José de los reyes hijos de Salomón, hijo de David, padre tras padre; y Lucas hace descender a José el carpintero de otros padres distintos de los de Mateo, hasta llegar a Natán, hijo de David, hermano de Salomón. Necesariamente las dos genealogías son mentira, y mienten los dos malditos; [[k:es absolutamente imposible que las dos genealogías sean verdad]].",
      "Algunos de sus grandes antiguos, de sus extraviadores, dijeron que [[a:una de las dos genealogías es la del nacimiento y la otra la de un hombre que lo adoptó]], según la antigua costumbre de los hijos de Israel de que, si uno moría sin hijos y otro se casaba con su mujer, el hijo que ella tenía de este se atribuía al muerto. Y respondimos a quien nos opuso esta locura: ¿de dónde sacas eso? ¿Dónde lo has encontrado, en Lucas o en Mateo? Pretender algo no le cuesta a nadie, y es falso salvo que lo respalde una prueba."],
  prueba="Es un argumento interno (las dos genealogías difieren), no circular. Pero fíjate en cómo responde a la armonización clásica (la ley del levirato, en azul): la llama «locura» sin examinarla. Es lo contrario de la regla de Ibn Hajar: si se puede armonizar sin forzar, se armoniza (IH09)."),

 dict(id="Z16", tag=P4, chip=SEL, specs=["Z16"],
  title="La misma Torá «alterada» le sirve como «texto explícito» sobre Muhammad (Dt 18 y Dt 33)",
  ref=ref("vol. 1, p. 90"), ar_ref=AR+"١/٩٠", site=SITE, url=B+"82",
  es=["…además de lo que hay en la Torá [[k:del anuncio claro del Mensajero de Dios ﷺ]], en Su palabra en ella: «Suscitaré a los hijos de Israel un profeta de entre sus hermanos; pondré Mi palabra en su boca, y a quien le desobedezca, Yo me vengaré de él». Dijo Abu Muhammad: esta descripción no corresponde a nadie más que a Muhammad ﷺ, y los hermanos de los hijos de Israel son los hijos de Ismael. Y Su palabra en el quinto libro: «Vino Dios desde el Sinaí, brilló desde Seír y se manifestó desde los montes de Parán». Dijo Abu Muhammad: el Sinaí es sin duda el lugar de la misión de Moisés —la paz sea con él—, Seír el de la misión de Jesús —la paz sea con él—, y Parán es sin duda La Meca, lugar de la misión de Muhammad ﷺ; la prueba es que Abraham —la paz sea con él— instaló a Ismael en Parán, y nadie discute que lo instaló en La Meca. [[k:Así que esto es un texto explícito sobre la misión del Profeta]] ﷺ."],
  prueba="Si el texto es fiable cuando confirma el Corán y falso cuando lo contradice, el criterio no es la historia del texto, sino el Corán.",
  ojo="Compáralo con Z05 (1/160): allí dice que lo que transmiten «no menciona en absoluto a Muhammad»."),

 dict(id="Z17", tag=P4, chip=SEL, specs=["Z17a","Z17b","Z17c"],
  title="Deuteronomio 18: «este es el texto de la Torá»; Deuteronomio 13: «por Dios, Moisés nunca lo dijo»",
  ref=ref("vol. 1, pp. 89 y 139–140"), ar_ref=AR+"١/٨٩ و١/١٣٩–١٤٠", site=SITE, url=B+"81",
  es=["…sino que en ella está: «A quien venga a vosotros pretendiendo ser profeta y sea un mentiroso, no le creáis; y si decís: ¿cómo sabremos si miente o dice la verdad?, mirad: si dice algo de parte de Dios y no ocurre como dijo, es un mentiroso». [[k:Este es el texto de lo que hay en la Torá]].",
      "Luego menciona en el quinto libro: «Si surge entre vosotros un profeta que dice haber tenido un sueño y os anuncia algo que va a pasar, y sucede como lo describió, y después os dice: “Seguid a los hijos de los dioses de las naciones”, [[k:no le escuchéis]]».",
      "Lejos de Dios que Moisés —la paz sea con él— dijera estas palabras; [[k:por Dios, nunca las dijo]]: mintió sobre él el mentiroso que cambió la Torá. Y lejos de Dios mostrar un signo por medio de quien pueda mentir o mandar algo falso: eso sería confundir Dios a Sus siervos y mezclar la verdad con la falsedad, hasta que no quedara prueba para establecer una verdad ni anular una falsedad. Sabed que este capítulo de su Torá, y el capítulo maldito en el que los magos hicieron algo parecido a lo que hizo Moisés, anulan para los judíos que los creen la profecía de todo profeta que reconocen, porque en ellos no hay diferencia entre Moisés y los demás profetas, y los mentirosos y los magos —lejos de Dios tal cosa—. Y esto, junto con lo que dice después: «Todo profeta que invente entre vosotros por su cuenta una profecía que no le mandé, o profetice llamando a los dioses y los ídolos, matadle; y si decís en vuestro interior: ¿cómo se sabrá si viene de Dios o de él mismo?, esta es la señal: si anuncia algo y no ocurre, sabed que es de él mismo». Dijo Abu Muhammad: [[k:esto son palabras correctas]]."],
  prueba="Dos pasajes del mismo libro: el que sirve para validar a Muhammad (una profecía que se cumple prueba al profeta) es «palabras correctas»; el que dice que no se siga a un profeta cuyo signo se cumple pero que llama a otros dioses, «por Dios, Moisés nunca lo dijo». El criterio es lo que conviene a su tesis.",
  ojo="Deuteronomio 13 no se contradice con el 18: dice que el milagro no basta si el mensaje lleva a otros dioses. Es una prueba de fidelidad, no una contradicción."),

 dict(id="Z18", tag=P4, chip=SEL, specs=["Z18a","Z18b"],
  title="Su explicación: Dios «les detuvo la mano» en lo que anuncia a Muhammad y «dejó una parte como prueba contra ellos»",
  ref=ref("vol. 1, pp. 155 y 157"), ar_ref=AR+"١/١٥٥ و١/١٥٧", site=SITE, url=B+"147",
  es=["…además de que en ello está que Dios [[k:les dejó cambiar lo que quiso retirar de su libro, y les detuvo la mano en lo que quiso dejar como prueba nuestra contra ellos y milagro de nuestro Profeta]] ﷺ. En el salmo sesenta y uno [según su numeración] está que los árabes y los de Saba le pagarán tributo y le seguirán, y que la sangre tendrá precio ante él —y esa es la descripción del precio de sangre, que solo existe en nuestra religión—; y también: «y aparecerá desde la ciudad (al-Madina)», así, textualmente; y esto es un anuncio claro del Mensajero de Dios.",
      "Si se dice: «Vosotros reconocéis la Torá y el Evangelio, y argumentáis contra los judíos y los cristianos con lo que hay en ellos sobre las cualidades de vuestro Profeta; vuestro Profeta argumentó con su texto en la historia de la lapidación del adúltero casado; se transmite que ʿAbdallah ibn Salam golpeó la mano de ʿAbdallah ibn Suriya cuando la puso sobre el versículo de la lapidación, y que el Profeta ﷺ tomó la Torá y dijo “creo en lo que hay en ti”; y en vuestro Libro está: “Gente del Libro, no estáis en nada hasta que cumpláis la Torá y el Evangelio y lo que se os ha revelado de vuestro Señor”; y: “Di: traed la Torá y leedla, si sois sinceros”; y: “Revelamos la Torá, en la que hay guía y luz; por ella juzgaban los profetas que se sometieron…”; y: “Que la gente del Evangelio juzgue por lo que Dios reveló en él”; y: “Si hubieran cumplido la Torá y el Evangelio…”; y: “Vosotros, a quienes se dio el Libro, creed en lo que hemos revelado confirmando lo que tenéis”», decimos —y con Dios está el éxito—: todo esto es verdad, [[a:salvo su dicho «creo en lo que hay en ti», que es falso y nunca fue auténtico]]; todo concuerda con lo que decimos sobre el cambio de la Torá y el Evangelio, y nada de ello es prueba para quien pretende que están en manos de judíos y cristianos tal como se revelaron, como explicaremos ahora con prueba clara, si Dios quiere. Dijo Abu Muhammad: reconocer la Torá y el Evangelio, sí; ¿qué sentido tiene plantearnos eso, si nunca los hemos negado? Al contrario, declaramos incrédulo a quien los niega. Solo decimos que Dios reveló la Torá a Moisés de verdad, los Salmos a David de verdad, el Evangelio a Jesús de verdad, las hojas a Abraham y a Moisés de verdad, y libros que no nos nombró a profetas que no nos nombró, de verdad; creemos en todo eso… Y dijimos y decimos que los incrédulos de los hijos de Israel cambiaron la Torá y los Salmos, añadieron y quitaron, [[k:y Dios dejó una parte de ellos como prueba contra ellos, como quiso]] —«no se Le pregunta por lo que hace; a ellos sí se les preguntará», «nadie revoca Su juicio»—; y los incrédulos cristianos cambiaron el Evangelio igual, añadieron y quitaron, y Dios dejó una parte como prueba contra ellos, como quiso…; y se borró lo que cambiaron de esos libros."],
  prueba="Es su explicación de por qué la Torá «alterada» sigue anunciando a Muhammad: Dios dejó intacto lo que sirve de prueba. Con esa explicación, todo lo que coincide con el Corán es auténtico y todo lo que no, alterado: la tesis no se puede refutar con ningún texto, porque se ajusta a cualquier resultado.",
  ojo="Mira la lista de objeciones que él mismo recoge: son los versículos del Corán que tratan la Torá y el Evangelio de la época del Profeta como vigentes (5:44–47, 5:66–68, 3:93, 4:47). Sus respuestas están en Z20. Página 157: https://shamela.ws/book/6521/149"),

 dict(id="Z19", tag=P4, chip=SEL, specs=["Z19"],
  title="La misma frase de Lucas: «hijo de José» es alteración; «profeta» es «lo que se escapó de su alteración»",
  ref=ref("vol. 2, p. 51 (sobre Lucas 4:22–24)"), ar_ref=AR+"٢/٥١", site=SITE, url=B+"208",
  es=["En el capítulo cuarto del Evangelio de Lucas: «La gente daba testimonio a su favor y se admiraba de sus palabras y de lo que les recomendaba, y decía: “¿No es este el hijo de José el carpintero?”. Él les dijo: “Sí. Ya sé que me diréis: médico, cúrate a ti mismo, y haz en tu tierra lo que hemos oído que hiciste en Cafarnaún. En verdad os digo que ningún profeta es aceptado en su tierra”». Dijo Abu Muhammad: en este capítulo hay tres cosas enormes. La primera: que le dijeran «¿no es este el hijo de José?» y él dijera «sí»: [[k:esto afirma que es hijo del carpintero, y lejos de Dios tal cosa]]. La segunda: que reconociera, y estuvieran de acuerdo, en que no hizo ningún signo ante la gente, y solo dijo que los hizo en los desiertos. La tercera, que es la verdad: que les dijo que es un profeta; [[k:y esto es lo que se escapó de su alteración]], y Dios lo dejó como prueba contra ellos."],
  prueba="En un mismo párrafo, Lucas es «alteración» cuando choca con el Corán (hijo de José) y «verdad que se escapó» cuando coincide (profeta).",
  ojo="El «sí» sale de la traducción árabe que usaba: en Lucas 4:23 Jesús no responde que sea hijo de José, sino «sin duda me diréis este refrán…»."),

 dict(id="Z20", tag=P4, chip=SEL, specs=["Z20a","Z20b"],
  title="Los versículos que tratan la Torá como vigente: «antes de que se produjera el cambio»",
  ref=ref("vol. 1, pp. 158–159"), ar_ref=AR+"١/١٥٨–١٥٩", site=SITE, url=B+"150",
  es=["En cuanto a Su palabra «Di: traed la Torá y leedla, si sois sinceros» (3:93): sí, [[k:se refiere a una mentira que dijeron y atribuyeron a la Torá]], como acostumbraban, añadida a la mentira que sus antepasados pusieron en su Torá; el Profeta los dejó en evidencia sobre esa mentira reciente al pedir que trajeran la Torá, si eran sinceros, y quedó clara su mentira.",
      "[Sobre «Revelamos la Torá… por ella juzgaban los profetas…» (5:44):] sí, esto es verdad en su sentido literal, tal como es; ya dijimos que Dios reveló la Torá y juzgaron por ella los profetas que se sometieron —como Moisés, Aarón, David, Salomón y los profetas que hubo entre ellos—, y los rabinos y doctores de sus tiempos, que no eran profetas sino jueces nombrados por los profetas, [[k:antes de que se produjera el cambio]]. Esta es nuestra postura, y en este versículo no hay ni texto ni prueba de que no se cambiara después. [[a:Y quien, de entre los musulmanes, crea por su ignorancia que este versículo se reveló sobre la lapidación de los dos judíos casados que fornicaron, ha creído algo falso]], ha dicho una mentira, ha interpretado lo imposible y ha contradicho el Corán.",
      "…porque sabemos necesariamente que tienen verdad y falsedad, y no es lícito creer la falsedad en absoluto; así que es seguro que Él lo reveló confirmando la verdad que tienen; [[k:y ya dijimos que Dios dejó en la Torá y el Evangelio verdad, para que sea prueba contra ellos]] y aumente su humillación."],
  prueba="Ante los versículos del Corán que tratan la Torá de Medina como vigente, su salida es decir que hablan de «antes del cambio» o de una «mentira reciente».",
  ojo="Llama ignorantes (en azul) a los musulmanes que leían 5:44 con la historia de la lapidación, que es justo lo que dice el hadiz de Muslim 1700 (U09d): «y Dios reveló “Mensajero, que no te entristezcan…”»."),

 dict(id="Z21", tag="El doble rasero", chip="Tipo: el criterio que no aplica a la Biblia", specs=["Z21"],
  title="«Si judíos y cristianos dijeran esto de los transmisores de sus libros, no se lo reprocharíamos»",
  ref=ref("vol. 2, p. 24"), ar_ref=AR+"٢/٢٤", site=SITE, url=B+"181",
  es=["Nosotros no negamos que los transmisores se equivoquen, cuando hay prueba de que es un error; y consta en el Corán y en los relatos firmes, por vía de Umar ibn al-Jattab, de su hijo y de otros, del Profeta ﷺ, que nadie sabe cuándo llegará la Hora salvo Dios. [[k:Y si los cristianos y los judíos dijeran algo así de los transmisores de sus libros, no se lo reprocharíamos]], ni les negaríamos que haya errores en su transmisión; [[a:lo que les reprochamos es que atribuyan a Dios la mentira pura]] y afirmen que viene de Dios; y reprochamos a los cristianos que hagan infalible a alguien de quien consta la mentira y tomen de él su religión, y que den por ciertos todos los relatos contradictorios y todo asunto que se desmiente a sí mismo."],
  prueba="Cuando un hadiz parece fallar (el muchacho que vería la Hora), Ibn Hazm lo atribuye a un error de los transmisores (Qatada y Maʿbad), no a una falsificación. Y reconoce que, si judíos y cristianos dijeran lo mismo de sus textos, «no se lo reprocharíamos». Esa es la clave: los problemas internos de Z12–Z15 se explican igual, como errores de transmisión en pasajes concretos, no como un libro fabricado.",
  ojo="Para ser justos con él (en azul): Ibn Hazm no dice que la Biblia tenga solo errores de copia; dice que lo que reprocha es «atribuir a Dios la mentira pura». Pero quién decide qué es «mentira pura» y qué es un error de transmisión es otra vez su criterio de Z02: lo que choca con el Corán es mentira; lo que choca dentro del hadiz es error del transmisor."),
]

for c in ZCARDS:
    c.setdefault('uso', "Pestaña Ibn Hazm · " + c['tag'])
