# -*- coding: utf-8 -*-
# Tarjetas de la recopilación sobre el matrimonio de menores en las fuentes suníes (M01–M37).
# [[k:...]] naranja = frase clave; [[a:...]] azul = matiz, discrepancia o lo que juega en contra.
from mtafsir import TAF
SH = "shamela.ws (Maktaba Shamila; paginación igual a la edición impresa)"
S = "https://shamela.ws/book/"
HU = "hadithunlocked.com"
H = "https://hadithunlocked.com/"

def T(k, **kw):
    d = {x: y for x, y in TAF[k].items() if x not in ('d', 'who')}
    d['tag_who'] = TAF[k]['who']
    d.update(kw)
    return d

C = []
def add(sec, who, **kw):
    kw['sec'] = sec; kw.setdefault('tag_who', who); C.append(kw)

# ---------- 1. Siglos I–II H ----------
add(1, "Aisha (m. 58 H), en al-Bujari (m. 256 H / 870)", specs=["mBk1"],
 title="Bujari, «Capítulo: el hombre casa a sus hijos pequeños» y 5133: «se casó con ella a los seis años y le fue llevada a los nueve»",
 ref="al-Bujari, al-Jamiʿ al-sahih, Kitab al-nikah, capítulo 39 (título) y hadiz 5133", ar_ref="صحيح البخاري، كتاب النكاح، باب ٣٩ وحديث ٥١٣٣",
 site=HU, url=H + "bukhari/67/39",
 es=["67.39 — Capítulo: [[k:el hombre casa a sus hijos pequeños]], por Su palabra: «Y las que no han menstruado» (65:4): [[k:les fijó un plazo de espera de tres meses antes de la pubertad]].",
     "[De Aisha:] que el Profeta ﷺ [[k:se casó con ella cuando tenía seis años]], [[k:y le fue llevada cuando tenía nueve]], y estuvo con él nueve [años]. [Bujari 5133]"],
 prueba="Al-Bujari titula el capítulo con una norma general, casar a los hijos pequeños, y la funda en el Corán 65:4: el plazo de espera que fija el versículo es «antes de la pubertad». Debajo pone el hadiz de Aisha.",
 ojo="El título es de al-Bujari; el hadiz es de Aisha, por Hisham ibn ʿUrwa. Hoy algunos musulmanes discuten estas edades, pero ninguna de las fuentes clásicas de esta recopilación las pone en duda.")
add(1, "Aisha (m. 58 H), en al-Bujari (m. 256 H / 870)", specs=["mBk2"],
 title="Bujari 3894: Aisha jugaba en un columpio cuando la llevaron… «y me entregó a él; yo tenía entonces nueve años»",
 ref="al-Bujari, al-Jamiʿ al-sahih, Manaqib al-Ansar, hadiz 3894", ar_ref="صحيح البخاري ٣٨٩٤", site=HU, url=H + "bukhari:3894",
 es=["[Aisha:] [[k:El Profeta ﷺ se casó conmigo cuando yo tenía seis años]]. Llegamos a Medina y nos alojamos entre los Banu al-Harith ibn Jazraj. Tuve fiebre y se me cayó el pelo, y luego me volvió a crecer hasta los hombros. Mi madre, Umm Ruman, vino a buscarme [[k:mientras yo estaba en un columpio, con unas amigas]]. Me llamó a gritos y fui sin saber qué quería de mí. Me tomó de la mano y me dejó en la puerta de la casa; yo jadeaba, hasta que recuperé un poco el aliento. Luego tomó un poco de agua, me la pasó por la cara y la cabeza y me hizo entrar en la casa. Allí había unas mujeres de los Ansar, que dijeron: «Con el bien y la bendición, y con la mejor suerte». Me entregó a ellas y me arreglaron. Y no me sorprendió sino el Mensajero de Dios ﷺ, a media mañana, [[k:y me entregó a él; yo tenía entonces nueve años]]."],
 prueba="Es el relato de la propia Aisha: estaba jugando en un columpio con sus amigas cuando la llevaron, la arreglaron y la entregaron al Profeta, a los nueve años.")
add(1, "Aisha (m. 58 H), en Muslim (m. 261 H / 875)", specs=["mMus"],
 title="Muslim, «Capítulo: el padre casa a la virgen pequeña» y 1422: «le fue llevada a los nueve años, con sus muñecas con ella»",
 ref="Muslim, al-Sahih, Kitab al-nikah, capítulo 10 (título) y hadiz 1422 (versiones a y c)", ar_ref="صحيح مسلم، كتاب النكاح، باب ١٠ وحديث ١٤٢٢",
 site=HU, url=H + "muslim/16/10",
 es=["Capítulo: [[k:el padre casa a la virgen pequeña]].",
     "[Aisha:] El Mensajero de Dios ﷺ se casó conmigo [[k:a los seis años]], [[k:y consumó el matrimonio conmigo cuando yo tenía nueve]]. Dijo: llegamos a Medina y tuve fiebre un mes, y el pelo me creció hasta los hombros. Umm Ruman vino a buscarme [[k:mientras yo estaba en un columpio con mis amigas]]. Me llamó a gritos y fui sin saber qué quería de mí. Me tomó de la mano y me dejó en la puerta; yo decía «¡ah, ah!», hasta que se me pasó el ahogo. Me hizo entrar en una casa donde había unas mujeres de los Ansar, que dijeron: «Con el bien y la bendición, y con la mejor suerte». Me entregó a ellas; me lavaron la cabeza y me arreglaron, y no me sorprendió sino el Mensajero de Dios ﷺ, a media mañana; y me entregaron a él. [1422a]",
     "Que el Profeta ﷺ se casó con ella cuando tenía siete años, [[k:y le fue llevada en cortejo nupcial cuando tenía nueve, con sus muñecas con ella]], y murió él cuando ella tenía dieciocho. [1422c]"],
 prueba="Muslim titula el capítulo «el padre casa a la virgen pequeña» y recoge el mismo relato: contrato a los seis o siete años, consumación a los nueve, y llegó a la casa del Profeta con sus muñecas.",
 ojo="Unas versiones dicen seis años y otras siete para el contrato; todas dicen nueve para la consumación.")
add(1, "Aisha (m. 58 H), en al-Bujari; comentario de Ibn Hajar (m. 852 H)", specs=["mBk4", "mFB10"],
 title="Bujari 6130: «yo jugaba con las muñecas en casa del Profeta»… y la explicación: «porque entonces aún no había llegado a la pubertad»",
 ref="al-Bujari, al-Jamiʿ al-sahih, Kitab al-adab, hadiz 6130; e Ibn Hajar, Fath al-Bari, vol. 10, p. 527 (ed. Salafiyya)", ar_ref="صحيح البخاري ٦١٣٠؛ فتح الباري ١٠/٥٢٧",
 site=HU + " y " + SH, url=H + "bukhari:6130",
 es=["[Aisha:] [[k:Yo jugaba con las muñecas en casa del Profeta ﷺ]], [[k:y tenía amigas que jugaban conmigo]]; cuando entraba el Mensajero de Dios ﷺ, ellas se escondían de él, y él me las mandaba y jugaban conmigo.",
     "Dijo al-Jattabi: en este hadiz [se ve] que jugar con muñecas no es como entretenerse con las demás imágenes, sobre las que hay amenaza; [[k:y solo se le permitió a Aisha porque entonces aún no había llegado a la pubertad]]. Digo [Ibn Hajar]: afirmarlo con seguridad es discutible, pero es posible, [[k:porque Aisha tenía en la campaña de Jaybar catorce años]], cumplidos, pasados o casi; y en la de Tabuk ya había llegado sin duda a la pubertad. Así que se prefiere la versión de quien dice que fue en Jaybar, y se armoniza con lo que dijo al-Jattabi, porque eso es mejor que la contradicción."],
 prueba="Las muñecas, que en general se consideraban imágenes prohibidas, se le permitían a Aisha precisamente porque, ya casada y viviendo con el Profeta, era una niña que no había llegado a la pubertad.",
 ojo="La explicación es de al-Jattabi (m. 388 H), y Ibn Hajar solo la da por «posible». No está en el hadiz.")
add(1, "los primeros sucesores (m. 94–124 H), en ʿAbd al-Razzaq (m. 211 H / 827)", specs=["mAR"],
 title="ʿAbd al-Razzaq, capítulo «el matrimonio de los dos menores»: «si los padres casan a los pequeños, su matrimonio es válido»",
 ref="ʿAbd al-Razzaq al-Sanʿani, al-Musannaf, Kitab al-nikah, «باب نكاح الصغيرين», n.º 10417, 10419, 10423 y 10427", ar_ref="مصنف عبد الرزاق ١٠٤١٧، ١٠٤١٩، ١٠٤٢٣، ١٠٤٢٧",
 site=HU, url=H + "abdalrazzaq/16/12",
 es=["[ʿUrwa:] El Profeta ﷺ se casó con Aisha cuando tenía seis años, [[k:y le fue llevada cuando tenía nueve, con sus muñecas con ella]], y murió él cuando ella tenía dieciocho. [10417]",
     "[ʿIkrima:] Que ʿAli ibn Abi Talib casó a su hija, [[k:una niña que jugaba con las niñas]], con Umar ibn al-Jattab. [10419]",
     "[Al-Hasan, al-Zuhri y Qatada:] [[k:Si los padres casan a los pequeños, su matrimonio es válido]]. [10423]",
     "[Hisham ibn ʿUrwa:] Mi padre casó a un hijo suyo pequeño, [[k:uno de cinco años y el otro de seis]]; él murió y ella heredó de él cuatro mil dinares o algo así. [10427]"],
 prueba="La colección más antigua de dichos de los primeros musulmanes ya tiene un capítulo para casar a menores. Al-Hasan al-Basri (m. 110 H), Qatada (m. 117) y al-Zuhri (m. 124) lo dan por válido si lo hacen los padres; ʿUrwa (m. 94) casó a un niño de cinco años con una niña de seis; y se cuenta que ʿAli casó con Umar a una hija suya que aún jugaba con las niñas.",
 ojo="Las cadenas acaban en los sucesores, no en el Profeta, y la página no da calificación. En el mismo capítulo, los n.º 10420–10421 describen un contacto físico de Umar con la niña; se omiten por el criterio de esta recopilación.")
C.append(T('muq', sec=1))
add(1, "Ibn Ishaq (m. 150 H / 767), en la cadena de Ahmad (m. 241 H)", specs=["mAhm"],
 title="Ibn Ishaq en la cadena (Ahmad 26870): «si esta hijita de al-ʿAbbas llega a mayor mientras yo vivo, me casaré con ella»",
 ref="Musnad Ahmad, n.º 26870, con la calificación de al-Arnaʾut", ar_ref="مسند أحمد ٢٦٨٧٠", site=HU, url=H + "ahmad:26870",
 es=["Nos contó Yaʿqub: nos contó mi padre, [[a:de Ibn Ishaq]]: me contó Husayn ibn ʿAbd Allah ibn ʿAbbas, de ʿIkrima, cliente de ʿAbd Allah ibn ʿAbbas, de ʿAbd Allah ibn ʿAbbas, de Umm al-Fadl bint al-Harith: que el Mensajero de Dios ﷺ vio a Umm Habib bint ʿAbbas [[k:cuando ya había pasado la edad del destete]]. Dijo: y él dijo: «[[k:Si esta hijita de al-ʿAbbas llega a mayor mientras yo vivo, me casaré con ella]]».",
     "[[a:Su cadena es débil]] (al-Arnaʾut)."],
 prueba="Es el único texto de este tema que pasa por Ibn Ishaq: el Profeta ve a una niña que apenas ha dejado el pecho y dice que se casará con ella si llega a mayor.",
 ojo="Es débil: al-Arnaʾut califica la cadena de débil, y al-Haythami llama a Husayn ibn ʿAbd Allah «abandonado» (matruk). Además, el texto condiciona el matrimonio a que la niña «llegue» (balaghat), es decir, a que crezca. Úsalo solo con esta calificación.")

# ---------- 2. Siglo III H ----------
add(2, "al-Shafiʿi (m. 204 H / 820)", specs=["mSh1", "mSh2"],
 title="al-Shafiʿi, al-Umm: el caso de Aisha «prueba que el padre tiene más derecho sobre la virgen que ella misma»",
 ref="al-Shafiʿi, al-Umm, vol. 5, pp. 18 y 102 (Dar al-Fikr, 2.ª ed., 1403/1983)", ar_ref="الأم للشافعي ٥/١٨ و٥/١٠٢", site=SH, url=S + "1655/1185",
 es=["De Aisha: «El Profeta ﷺ se casó conmigo [[k:cuando yo tenía seis o siete años, y consumó el matrimonio conmigo cuando tenía nueve]]» —la duda es de al-Shafiʿi—. Dijo al-Shafiʿi: como el Mensajero de Dios estableció que el combate se impone a los quince años, y los musulmanes lo aplicaron a las penas, y Dios lo dispuso así para los huérfanos al decir «hasta que alcancen la edad de casarse; y si veis en ellos madurez…» (4:6), y nadie tiene autoridad sobre sí mismo sino el de quince años o la de quince, salvo que él alcance antes la pubertad o ella la menstruación, y entonces tienen autoridad sobre sí mismos, [[k:el hecho de que Abu Bakr casara a Aisha con el Profeta ﷺ]] a los seis años, y que él consumara con ella a los nueve, prueba [[k:que el padre tiene más derecho sobre la virgen que ella misma]]. [5/18]",
     "Todo esto es cuando la esposa es adulta, [[k:o está cerca de la pubertad, o es corpulenta, de modo que una como ella puede soportar la relación]]; y si no puede soportarla, [[k:su familia puede impedir la consumación hasta que pueda soportar la relación]], y el marido no tiene que pagarle la dote ni nada de ella, ni su manutención, hasta que esté en situación de que se tenga relación con una como ella y se la deje a solas con él. [5/102]"],
 prueba="El fundador de la escuela shafiʿí usa el matrimonio de Aisha (contrato a los seis o siete, consumación a los nueve) para sentar que el padre decide por la hija virgen. La consumación la liga a la capacidad física, no a una edad.",
 ojo="Exige que sea el padre (o el abuelo) y que la hija sea virgen. En la misma p. 102 regula la responsabilidad del marido si la lesiona al consumar; no se reproduce.")
add(2, "Ibn Hisham (m. 213 o 218 H / 828 o 833)", specs=["mIH1", "mIH2", "mIH3"],
 title="La Sira de Ibn Hisham: «siete años… nueve o diez»; pero lo dice Ibn Hisham, no Ibn Ishaq",
 ref="Ibn Hisham, al-Sira al-nabawiyya, vol. 2, pp. 643–644 (ed. al-Saqqa y otros, Halabi, 2.ª ed., 1955)", ar_ref="سيرة ابن هشام ٢/٦٤٣–٦٤٤", site=SH, url=S + "23833/1381",
 es=["[[k:Dijo Ibn Hisham]]: Y fueron nueve: Aisha bint Abi Bakr, Hafsa bint ʿUmar ibn al-Jattab, Umm Habiba bint Abi Sufyan ibn Harb, Umm Salama bint Abi Umayya ibn al-Mughira, Sawda bint Zamʿa ibn Qays, Zaynab bint Jahsh ibn Riʾab, Maymuna bint al-Harith ibn Hazn, Juwayriya bint al-Harith ibn Abi Dirar y Safiyya bint Huyayy ibn Ajtab, [[k:según me contaron varios sabios]]. [2/643]",
     "Y el Mensajero de Dios ﷺ se casó con Aisha, hija de Abu Bakr al-Siddiq, en La Meca, [[k:cuando ella tenía siete años]], [[k:y consumó el matrimonio con ella en Medina cuando tenía nueve o diez]]. El Mensajero de Dios ﷺ no se casó con ninguna otra virgen. Se la dio en matrimonio su padre, Abu Bakr, y el Mensajero de Dios ﷺ le dio una dote de cuatrocientos dírhams. [2/644]",
     "[[a:Dijo Ibn Hisham: Ibn Ishaq contradice este relato]]: cuenta que Salit y Abu Hatib estaban ausentes, en Abisinia, en ese momento. [2/644]"],
 prueba="La Sira de Ibn Ishaq nos ha llegado a través de Ibn Hisham. La edad de Aisha (siete años en el contrato, nueve o diez en la consumación) está en la lista de esposas que introduce el propio Ibn Hisham: «dijo Ibn Hisham… según me contaron varios sabios».",
 ojo="Honestidad: no lo atribuyas a Ibn Ishaq. En esa misma lista Ibn Hisham anota que Ibn Ishaq discrepa en otro detalle (en azul): la lista es suya. En lo que se conserva de Ibn Ishaq no se ha encontrado una edad de Aisha.")
add(2, "Ibn Saʿd (m. 230 H / 845)", specs=["mIS1", "mIS2", "mIS3"],
 title="Ibn Saʿd: «el día en que consumó conmigo yo tenía nueve años… y todavía jugaba con las muñecas»; Umm Kulthum, «una niña que no había llegado a la pubertad»",
 ref="Ibn Saʿd, al-Tabaqat al-kubra, vol. 8, pp. 46, 47 y 338 (ed. ʿAta, Dar al-Kutub al-ʿIlmiyya, 1990)", ar_ref="الطبقات الكبرى ٨/٤٦، ٤٧، ٣٣٨", site=SH, url=S + "1686/2713",
 es=["Oí a Aisha decir: El Mensajero de Dios ﷺ se casó conmigo en Shawwal del año diez de la profecía, tres años antes de la hégira, [[k:cuando yo tenía seis años]]. El Mensajero de Dios ﷺ emigró y llegó a Medina el lunes, doce de Rabiʿ al-Awwal, y celebró la boda conmigo en Shawwal, a los ocho meses de la emigración. [[k:Y el día en que consumó el matrimonio conmigo yo tenía nueve años]]. [8/46]",
     "Nos informó ʿAbd al-Rahman ibn Abi al-Zinad, de Hisham ibn ʿUrwa, de su padre, de Aisha: El Mensajero de Dios ﷺ se casó conmigo [[k:cuando yo tenía seis años, y consumó el matrimonio conmigo cuando tenía nueve]]. [[k:Y cuando entré con él, yo todavía jugaba con las muñecas con las niñas]]. [8/47]",
     "[Umm Kulthum bint ʿAli:] Se casó con ella Umar ibn al-Jattab [[k:cuando era una niña que no había llegado a la pubertad]], y siguió con él hasta que lo mataron. [8/338]"],
 prueba="El gran diccionario biográfico del siglo III H repite las edades de Aisha con detalle (cuándo se firmó el contrato y cuándo se consumó) y dice de Umm Kulthum, hija de ʿAli, que Umar se casó con ella antes de la pubertad.",
 ojo="Los dos primeros relatos son de al-Waqidi (Muhammad ibn ʿUmar), al que los críticos de hadiz consideran abandonado (matruk). La noticia de Umm Kulthum la da Ibn Saʿd sin cadena. Los datos de Aisha están también en Bujari y Muslim (M01–M03).")
add(2, "los compiladores de hadices (m. 256–303 H)", specs=["mBk3", "mAD", "mIM", "mNas1", "mNas2"],
 title="Los títulos de capítulo: «quien consuma el matrimonio con una mujer de nueve años», «el matrimonio de las pequeñas, que casan los padres»…",
 ref="al-Bujari, Nikah, cap. 60 y 5158; Abu Dawud, Nikah, cap. 34 y 2121; Ibn Maja, Nikah, cap. 13; al-Nasaʾi, Nikah, caps. 29 y 78 y 3378", ar_ref="البخاري ٥١٥٨؛ أبو داود ٢١٢١؛ ابن ماجه؛ النسائي ٣٣٧٨",
 site=HU, url=H + "bukhari/67/60",
 es=["67.60 — Capítulo: [[k:quien consuma el matrimonio con una mujer de nueve años]]. [Bujari]",
     "[ʿUrwa:] El Profeta ﷺ se casó con Aisha cuando tenía seis años, [[k:y consumó el matrimonio con ella cuando tenía nueve]], y estuvo con él nueve [años]. [Bujari 5158]",
     "12.34 — [[k:Capítulo sobre casar a los pequeños]]. [Abu Dawud]",
     "[Aisha:] El Mensajero de Dios ﷺ se casó conmigo cuando yo tenía siete años —dijo Sulayman: o seis— [[k:y consumó el matrimonio conmigo cuando tenía nueve]]. [Abu Dawud 2121]",
     "[[k:Capítulo: el matrimonio de las pequeñas, que casan los padres]]. [Ibn Maja]",
     "[[k:Capítulo: el hombre casa a su hija pequeña]]. [al-Nasaʾi]",
     "26.78 — [[k:Capítulo: consumar el matrimonio con una de nueve años]]. [al-Nasaʾi]",
     "[Aisha:] El Mensajero de Dios ﷺ se casó conmigo cuando yo tenía seis años, y consumó el matrimonio conmigo [[k:cuando tenía nueve años; y yo jugaba con las muñecas]]. [al-Nasaʾi 3378]"],
 prueba="Los grandes compiladores del siglo III H no se limitan a transmitir el hadiz: lo convierten en norma con títulos de capítulo. Bujari: «quien consuma el matrimonio con una mujer de nueve años»; al-Nasaʾi: «consumar el matrimonio con una de nueve años»; Ibn Maja: «el matrimonio de las pequeñas, que casan los padres».",
 ojo="Los títulos son de los compiladores; los hadices de debajo, de Aisha y de ʿUrwa. En Abu Dawud 2121 el narrador duda entre seis y siete años; al-Albani y al-Arnaʾut lo dan por auténtico.")
add(2, "al-Tirmidhi (m. 279 H / 892)", specs=["mTir"],
 title="al-Tirmidhi: Ahmad e Ishaq y la huérfana de nueve años; y Aisha: «cuando la niña cumple nueve años, es mujer»",
 ref="al-Tirmidhi, al-Jamiʿ, comentario al hadiz 1109 (Kitab al-nikah, «lo que se dice sobre obligar a la huérfana a casarse»)", ar_ref="جامع الترمذي، عقب الحديث ١١٠٩", site=HU, url=H + "tirmidhi:1109",
 es=["Y algunos dijeron: no es válido casar a la huérfana hasta que llegue a la pubertad, ni hay opción [de anularlo] en el matrimonio; es lo que dicen Sufyan al-Thawri, al-Shafiʿi y otros sabios. [[k:Y dijeron Ahmad e Ishaq: si la huérfana cumple nueve años y la casan, y ella acepta, el matrimonio es válido]], y no tiene opción [de anularlo] cuando llegue a la pubertad; [[k:y lo argumentaron con el hadiz de Aisha]]: que el Profeta ﷺ consumó el matrimonio con ella cuando tenía nueve años. [[k:Y Aisha dijo: cuando la niña cumple nueve años, es mujer]]."],
 prueba="Al-Tirmidhi recoge que Ahmad ibn Hanbal e Ishaq ibn Rahawayh daban por válido casar a la huérfana de nueve años con su aceptación, apoyándose en Aisha, y cita a Aisha: a los nueve años la niña «es mujer».",
 ojo="La frase de Aisha la cita sin cadena. Al-Thawri y al-Shafiʿi exigen la pubertad para la huérfana; para la hija casada por su padre no la exigen (ver M08).")

# ---------- 3. Siglo IV H ----------
C.append(T('tab', sec=3))
add(3, "al-Tabari (m. 310 H / 923)", specs=["mTabT1", "mTabT2"],
 title="al-Tabari, Historia: «el día en que se casó con ella era pequeña, no apta para la relación»",
 ref="al-Tabari, Tarij al-rusul wa-l-muluk, vol. 3, pp. 161 y 163 (Dar al-Maʿarif, 2.ª ed., 1967)", ar_ref="تاريخ الطبري ٣/١٦١ و١٦٣", site=SH, url=S + "9783/1435",
 es=["En cuanto a Aisha, [[k:el día en que se casó con ella era pequeña, no apta para la relación]]. [3/161]",
     "[Aisha:] El Mensajero de Dios consumó el matrimonio conmigo en mi casa, sin que se sacrificara por mí un camello ni una oveja, [[k:y yo tenía entonces nueve años]]. [3/163]"],
 prueba="El historiador más importante del islam primitivo explica así por qué la boda se retrasó: Aisha era demasiado pequeña. Y la consumación, en su propio relato, fue a los nueve años.",
 ojo="La primera frase es explicación de al-Tabari; la segunda, un relato de Aisha por la cadena de Muhammad ibn ʿAmr.")
add(3, "Ibn al-Mundhir (m. 318 H / 930)", specs=["mMun1", "mMun2"],
 title="Ibn al-Mundhir, el libro del consenso: «coincidieron en que es válido que el padre case a su hija pequeña virgen»",
 ref="Ibn al-Mundhir, al-Ijmaʿ, p. 78, n.º 350 (Dar al-Muslim, 2004); y al-Ishraf, vol. 5, p. 19, masʾala 2573 (Maktabat Makka, 2004)", ar_ref="الإجماع لابن المنذر ص ٧٨؛ الإشراف ٥/١٩", site=SH, url=S + "12445/77",
 es=["350 — [[k:Y coincidieron en que es válido que el padre case a su hija pequeña virgen, si la casa con un hombre de su condición (kufʾ)]]. [al-Ijmaʿ]",
     "Está probado que Abu Bakr casó a Aisha con el Mensajero de Dios ﷺ, [[k:y ella tenía entonces siete años]]. Masʾala 2573 — [[k:Y los sabios coinciden en que es válido que el padre case a su hija virgen pequeña]], si la casa con un hombre de su condición. Esto dicen Malik, al-Thawri, al-Layth ibn Saʿd, al-Awzaʿi, ʿUbayd Allah ibn al-Hasan, al-Shafiʿi, Ahmad, Ishaq, Abu ʿUbayd, Abu Thawr y los partidarios de la opinión [los hanafíes], y su prueba es el hadiz de Aisha. [al-Ishraf]"],
 prueba="El gran recopilador de consensos da la norma como unánime y enumera las escuelas que la sostienen, con el hadiz de Aisha como prueba.",
 ojo="La condición es que la case con un hombre «de su condición» (kufʾ). En al-Ishraf da siete años como edad de Aisha. Su consenso no menciona a Ibn Shubruma (ver la sección de voces en contra).")
add(3, "al-Tahawi (m. 321 H / 933)", specs=["mTah1a", "mTah3"],
 title="al-Tahawi: también los demás tutores pueden casar a los pequeños; y la noticia de la discrepancia de Ibn Shubruma",
 ref="al-Tahawi, al-Mujtasar, citado en al-Jassas, Sharh Mujtasar al-Tahawi, vol. 4, p. 292 (Dar al-Bashaʾir, 2010); y al-Jassas, Mujtasar Ijtilaf al-ʿulamaʾ, vol. 2, p. 257, masʾala 726 (Dar al-Bashaʾir, 2.ª ed., 1417)", ar_ref="شرح مختصر الطحاوي ٤/٢٩٢؛ مختصر اختلاف العلماء ٢/٢٥٧", site=SH, url=S + "16546/1857",
 es=["([[k:Y los demás tutores pueden casar a los pequeños, y [los esposos] se heredan por ello]].) [al-Mujtasar]",
     "Dijeron nuestros compañeros: los tutores de los pequeños, el más cercano y luego el siguiente; [[k:y no tienen opción [de anularlo] cuando los casa el padre o el abuelo]], y sí la tienen cuando los casa otro, según Abu Hanifa y Muhammad. Y dijo Abu Yusuf: no tienen opción. Y transmitió Bishr ibn al-Walid, de Abu Yusuf, [[a:de Ibn Shubruma, que no es válido que los padres casen a los pequeños]]. [Ijtilaf al-ʿulamaʾ]"],
 prueba="Para el gran jurista hanafí, no solo el padre: cualquier tutor puede casar a los menores, y el matrimonio ya produce herencia entre los esposos. Y es él quien transmite la discrepancia de Ibn Shubruma que repiten los autores posteriores.",
 ojo="Los dos textos nos llegan citados por al-Jassas, no en una obra de al-Tahawi conservada aparte.")
jas = T('jas', sec=3)
jas['specs'] = ["mJas", "mTah1b", "mTah2"]
jas['ref'] = "al-Jassas, Ahkam al-Qurʾan, vol. 2, p. 346 (ed. Qamhawi); y Sharh Mujtasar al-Tahawi, vol. 4, pp. 292–293 (Dar al-Bashaʾir, 2010)"
jas['ar_ref'] = "أحكام القرآن للجصاص ٢/٣٤٦؛ شرح مختصر الطحاوي ٤/٢٩٢–٢٩٣"
jas['es'] = jas['es'] + [
 "En cuanto al padre y al abuelo, [[k:no hay discrepancia entre los juristas de las ciudades en que pueden casar a los pequeños]], [[a:salvo algo que se cuenta de ʿUthman al-Batti]] y de Ibn… [Sharh Mujtasar al-Tahawi 4/292]",
 "[…Shubruma, que dijeron:] no casa el padre a la pequeña. [[k:Y es una opinión aislada en la comunidad, a la que precedió con lo contrario la primera generación]]. Y la prueba del Libro exige que es falsa: Su palabra «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres, si dudáis, su plazo es de tres meses, y las que no han menstruado». [[k:Así dio por válido el repudio de la pequeña]], [[k:y le impuso el plazo de espera si el matrimonio había sido consumado]]; y el repudio no se produce sino en un contrato válido. Y por la Sunna: que el Profeta ﷺ se casó con Aisha cuando era pequeña; se la dio en matrimonio Abu Bakr. [4/293]"]
jas['prueba'] = jas['prueba'] + " En su comentario a al-Tahawi es aún más explícito: 65:4 impone el plazo de espera a la pequeña «si el matrimonio había sido consumado», y la discrepancia es «una opinión aislada»."
C.append(jas)

# ---------- 4. Siglo V H ----------
add(4, "Ibn Battal (m. 449 H / 1057)", specs=["mIB1a", "mIB1b", "mIB2", "mIB3"],
 title="Ibn Battal: los padres pueden casar a sus hijas pequeñas «aunque estén en la cuna»; y al-Muhallab: «desde el momento en que es creada»",
 ref="Ibn Battal, Sharh Sahih al-Bujari, vol. 7, pp. 172–173 y 247–248 (Maktabat al-Rushd, 2.ª ed., 1423/2003)", ar_ref="شرح صحيح البخاري لابن بطال ٧/١٧٢–١٧٣ و٢٤٧–٢٤٨", site=SH, url=S + "10486/3405",
 es=["[[k:Los sabios coinciden en que los padres pueden casar a sus hijas pequeñas]], [[k:aunque estén en la cuna]]; pero sus maridos no pueden consumar el matrimonio con ellas sino cuando sean aptas [7/172]",
     "para la relación y puedan soportar a los hombres; [[k:y su situación en esto varía según su constitución y su capacidad]]. Aisha, cuando el Profeta ﷺ se casó con ella, tenía seis años, y consumó el matrimonio con ella a los nueve. [7/173]",
     "[Dijo al-Muhallab:] Los sabios coinciden en que [[k:el padre puede casar a su hija pequeña, aunque todavía no esté en edad de tener relaciones]], por la generalidad del versículo «y las que no han menstruado» (65:4); [[k:y es lícito casar a la que no ha menstruado desde el primer momento en que es creada]]. Y creo que al-Bujari quiso con este capítulo refutar a Ibn Shubruma, pues al-Tahawi cuenta de él que dijo: [[a:no es válido que los padres casen a las pequeñas, y ellas tienen opción [de anularlo] cuando llegan a la pubertad]]; y es una opinión que no sostuvo ningún otro jurista, y no se le presta atención por ser aislada y contraria a la prueba del Libro y la Sunna. [7/247]",
     "[[k:Y discreparon los sabios sobre el momento en que la mujer es llevada a su marido]], cuando el marido y la familia de la mujer no se ponen de acuerdo. Un grupo dijo: es llevada a [7/247]",
     "su marido cuando tiene nueve años, siguiendo el hadiz de Aisha; [[k:es lo que dicen Ahmad ibn Hanbal y Abu ʿUbayd]]. Y Abu Hanifa dijo: [[k:nos atenemos a los nueve, pero decimos]]: si los cumple y no puede soportar la relación, su familia puede impedirlo; y si no ha cumplido los nueve y es fuerte para los hombres, no pueden impedírselo a su marido. Y Malik decía: no hay manutención para la pequeña hasta que llegue a la pubertad y pueda soportar a los hombres. Y al-Shafiʿi dijo: [[k:si está cerca de la pubertad y es corpulenta, de modo que puede soportar la relación]], su marido puede consumar el matrimonio con ella; y si no puede soportarla, su familia puede impedírselo hasta que pueda. [7/248]"],
 prueba="El comentarista andalusí de Bujari lo dice sin rodeos: hay consenso en que el padre puede casar a sus hijas pequeñas aunque estén en la cuna, y la consumación espera a que «puedan soportar a los hombres», según la constitución de cada una. Y cita a al-Muhallab (m. 435 H): «es lícito casar a la que no ha menstruado desde el primer momento en que es creada».",
 ojo="Separa el contrato (lícito desde la cuna) de la consumación (cuando sea apta). La discrepancia de Ibn Shubruma va en azul.")
add(4, "al-Mawardi (m. 450 H / 1058)", specs=["mMaw"],
 title="al-Mawardi: «el padre casa a su hija virgen pequeña sin tener en cuenta su elección»",
 ref="al-Mawardi, al-Hawi al-kabir, vol. 9, p. 52 (Dar al-Kutub al-ʿIlmiyya, 1419/1999)", ar_ref="الحاوي الكبير ٩/٥٢", site=SH, url=S + "6157/3973",
 es=["En cuanto a las vírgenes pequeñas, los padres pueden obligarlas a casarse: [[k:el padre casa a su hija virgen pequeña sin tener en cuenta su elección]], y el contrato la obliga en su infancia y después de mayor; y lo mismo el abuelo, por arriba que sea, ocupa el lugar del padre al casar a la virgen pequeña si falta el padre. Y la prueba de ello, [[k:aunque es cosa en la que todos están de acuerdo]], es Su palabra: «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres, si dudáis, su plazo es de tres meses, y las que no han menstruado» (65:4), es decir, las pequeñas; y la pequeña está obligada al plazo de espera si el marido la repudia; [[k:luego prueba que es válido el contrato con ella en la infancia]]. Y se transmite de Aisha que dijo: el Mensajero de Dios ﷺ se casó conmigo cuando yo tenía siete años, y consumó el matrimonio conmigo cuando tenía nueve, y murió cuando yo tenía dieciocho."],
 prueba="El gran jurista shafiʿí de Bagdad da la norma como acuerdo general y la funda en el Corán 65:4 y en Aisha.",
 ojo="En 11/439 añade que la familia no tiene que entregarla mientras sea «de las que no se tiene relación con una como ella»: criterio de capacidad, no de edad.")
add(4, "Ibn Hazm (m. 456 H / 1064)", specs=["mHz1", "mHz2", "mHz3", "mHz4"],
 title="Ibn Hazm: el padre puede casar a su hija pequeña sin su permiso; al hijo varón, no; y la manutención se debe «aunque ella esté en la cuna»",
 ref="Ibn Hazm, al-Muhalla, vol. 9, pp. 38, 40, 44 y 249 (Dar al-Fikr), masʾalas 1826, 1827 y 1918", ar_ref="المحلى ٩/٣٨، ٤٠، ٤٤، ٢٤٩", site=SH, url=S + "767/3785",
 es=["[[k:El padre puede casar a su hija pequeña virgen —mientras no haya llegado a la pubertad— sin su permiso]], [[k:y ella no tiene opción [de anularlo] cuando llegue a la pubertad]]. Si es no virgen, por un marido que murió o la repudió, ni el padre ni otro pueden casarla hasta que llegue a la pubertad, y antes no cuenta su permiso. Y cuando la virgen y la no virgen llegan a la pubertad, ni el padre ni otro pueden casarla sino con su permiso; y si se hace, queda anulado para siempre. La no virgen se casa con quien quiere, aunque al padre no le guste. La virgen no puede casarse sino con su permiso y el de su padre a la vez. Y a la pequeña que no tiene padre nadie puede casarla, ni por necesidad ni sin ella, hasta que llegue a la pubertad; y nadie puede casar a la loca hasta que recobre el juicio y dé permiso, salvo el padre, si no ha llegado a la pubertad y está loca. Y en parte de lo que hemos dicho hay discrepancia: [[a:dijo Ibn Shubruma: no es válido que el padre case a su hija pequeña]] hasta que llegue a la pubertad y dé permiso. [9/38]",
     "La prueba de que el padre puede casar a su hija pequeña virgen es que Abu Bakr casó a Aisha con el Profeta ﷺ [[k:cuando ella tenía seis años; y esto es cosa conocida]], que no necesita cadena. [[k:Y quien pretenda que fue un privilegio [del Profeta] no merece atención]], por la palabra de Dios: «En el Mensajero de Dios tenéis un hermoso modelo, para quien espera en Dios y en el Último Día» (33:21): todo lo que él hizo podemos imitarlo, salvo que venga un texto de que es exclusivo suyo. [9/40]",
     "Ni el padre ni otro pueden casar al varón pequeño hasta que llegue a la pubertad; [[k:y si lo hace, queda anulado para siempre]]. Algunos lo permitieron, sin más prueba que compararlo con la niña. [9/44]",
     "1918 — El hombre mantiene a su mujer desde que contrae el matrimonio con ella, [[k:se le invite a consumarlo o no —aunque ella esté en la cuna—]], sea desobediente o no, rica o pobre, con padre o huérfana, virgen o no, libre o esclava, según sus medios. [9/249]"],
 prueba="El literalista Ibn Hazm restringe mucho: solo el padre, solo la hija virgen y solo antes de la pubertad. Pero lo permite, rechaza que fuera un privilegio del Profeta («todo lo que hizo podemos imitarlo»), lo prohíbe con los niños varones y da por supuesto el matrimonio de una niña en la cuna al regular la manutención.",
 ojo="No he encontrado en al-Muhalla una edad para la consumación. Recoge la discrepancia de Ibn Shubruma (en azul).")
add(4, "Ibn ʿAbd al-Barr (m. 463 H / 1071)", specs=["mAB1", "mAB2a", "mAB2b"],
 title="Ibn ʿAbd al-Barr: «los sabios coinciden en que el padre puede casar a su hija pequeña sin consultarla»; y Ahmad: no consumar «hasta que cumpla nueve años»",
 ref="Ibn ʿAbd al-Barr, al-Tamhid, vol. 19, pp. 98 y 107–108 (Ministerio de Awqaf de Marruecos, 1387)", ar_ref="التمهيد ١٩/٩٨ و١٠٧–١٠٨", site=SH, url=S + "1719/6349",
 es=["Dijo Abu ʿUmar: [[k:los sabios coinciden en que el padre puede casar a su hija pequeña sin consultarla]], porque el Mensajero de Dios ﷺ se casó con [[k:Aisha cuando tenía seis años]]; solo que los iraquíes dijeron que ella tiene opción [de anularlo] al llegar a la pubertad, y los del Hiyaz lo rechazaron; y para mí no tiene prueba quien le da esa opción. Y Dios sabe más. [19/98]",
     "Y dijo Ahmad ibn Hanbal: [[k:no veo que el juez ni el tutor puedan casar a la huérfana]] [19/107]",
     "hasta que cumpla nueve años. Dijo: y si la casan pequeña, antes de los nueve años, [[k:no veo que [el marido] consume con ella hasta que cumpla nueve años]]. [[a:Dijo Abu ʿUmar: no sé de nadie más que lo haya dicho]], y creo que lo tomó de la historia de Aisha en la consumación; el Mensajero de Dios ﷺ se casó con ella cuando tenía seis o siete años, y consumó el matrimonio con ella cuando tenía nueve o diez. [19/108]"],
 prueba="El gran malikí andalusí da el consenso y solo discute si la niña puede anularlo al llegar a la pubertad (para él, no). Y recoge la regla de Ahmad: la casada antes de los nueve años no se consuma hasta los nueve.",
 ojo="Ibn ʿAbd al-Barr dice que la cifra de los nueve años solo la sostiene Ahmad (en azul).")
C.append(T('wah', sec=4))
add(4, "al-Sarakhsi (m. c. 483 H / 1090)", specs=["mSar1", "mSar2", "mSar3"],
 title="al-Sarakhsi: «Qudama ibn Mazʿun se casó con la hija de al-Zubayr el día en que nació»; al-Asamm «era sordo y no oyó estos hadices»",
 ref="al-Sarakhsi, al-Mabsut, vol. 4, pp. 212–213 (Matbaʿat al-Saʿada; reimpr. Dar al-Maʿrifa), «باب نكاح الصغير والصغيرة»", ar_ref="المبسوط للسرخسي ٤/٢١٢–٢١٣", site=SH, url=S + "5423/897",
 es=["…que se casó con Aisha —Dios esté complacido con ella— cuando era pequeña, de seis años, y consumó el matrimonio con ella cuando tenía nueve, y estuvo con él nueve [años]». [[k:En el hadiz hay prueba de que es válido el matrimonio del niño y de la niña cuando los casan los padres]], [[a:al contrario de lo que dicen Ibn Shubruma y Abu Bakr al-Asamm]]: que no se casa al niño ni a la niña hasta que lleguen a la pubertad. [4/212]",
     "Y nuestra prueba es Su palabra «y las que no han menstruado» (65:4): Dios explicó el plazo de espera de la pequeña, y la causa del plazo de espera en la ley es el matrimonio; [[k:y eso prueba que se concibe el matrimonio de la pequeña]]. Y lo que quiere decir «hasta que alcancen la edad de casarse» (4:6) es la pubertad; además, el hadiz de Aisha es un texto explícito en ello, y lo mismo los demás relatos que hemos mencionado: [[k:Qudama ibn Mazʿun se casó con la hija de al-Zubayr el día en que nació]], y dijo: «si muero, ella es la mejor de mis herederas, y si vivo, es la hija de al-Zubayr»; Ibn Umar casó a una hija suya pequeña con ʿUrwa ibn al-Zubayr; ʿUrwa ibn al-Zubayr casó a la hija de su hermano con el hijo de su hermana, siendo los dos pequeños; un hombre dio en matrimonio a su hija pequeña a ʿAbd Allah ibn al-Hasan, y ʿAli lo validó; y una mujer casó a una hija suya pequeña con un hijo de al-Musayyab ibn Najaba, e Ibn Masʿud lo validó. Pero Abu Bakr al-Asamm [[k:era sordo y no oyó estos hadices]]. [4/212]",
     "Y en él hay prueba de que [[k:la pequeña puede ser llevada a su marido si es apta para los hombres]], pues ella le fue llevada cuando tenía nueve años, y era pequeña en apariencia. [4/213]",
     "Y además, en el hadiz se aclara que, [[k:si el padre casa a su hija, ella no tiene opción [de anularlo] cuando llega a la pubertad]]. [4/213]"],
 prueba="El gran manual hanafí refuta a quienes exigían la pubertad con el Corán 65:4, con Aisha y con una lista de precedentes de Compañeros, empezando por un matrimonio contraído el día en que nació la niña. Y despacha al disidente con un juego de palabras sobre su nombre, al-Asamm («el sordo»): «no oyó estos hadices».",
 ojo="Los precedentes de los Compañeros los da sin cadena. La consumación la liga a que sea «apta para los hombres».")

# ---------- 5. Siglos VI–VII H ----------
C.append(T('bag', sec=5))
C.append(T('ia', sec=5))
add(5, "al-Mazari (m. 536) y al-Qadi ʿIyad (m. 544 H / 1149)", specs=["mIy1", "mIy2", "mIy3"],
 title="Qadi ʿIyad: «no hay discrepancia… en que el padre puede casar a su hija pequeña» aunque no esté en edad de relaciones; un grupo «obligó a la niña de nueve años a la consumación»",
 ref="al-Qadi ʿIyad, Ikmal al-muʿlim bi-fawaʾid Muslim, vol. 4, pp. 572–573 (Dar al-Wafaʾ, 1419/1998), sobre Muslim 1422", ar_ref="إكمال المعلم ٤/٥٧٢–٥٧٣", site=SH, url=S + "122406/2494",
 es=["[Dijo el imam (al-Mazari):] Vi que Ibn Hanbal [[k:fijó los nueve años como la edad en que los tutores casan a la virgen huérfana si ella acepta]], por este hadiz de Aisha. Y eso no tiene sentido, salvo que quiera decir que es la edad en que tiene discernimiento y cuenta su aceptación, o que a esa edad ya menstrúan algunas niñas.",
     "Y este hadiz de Aisha [[k:es fundamento para que los padres obliguen a sus hijas vírgenes y para casar a las pequeñas]]. [[k:Y no hay discrepancia entre los sabios en que el padre puede casar a su hija pequeña, aunque todavía no esté en edad de tener relaciones]]; y después ella no tiene opción [de anularlo] cuando llega a la pubertad, según Malik, al-Shafiʿi y los juristas del Hiyaz. Y los de Iraq opinaron que tiene opción cuando llega a la pubertad.",
     "Y este hadiz es fundamento para fijar el momento de la consumación cuando hay disputa: [[k:un grupo obligó a la niña de nueve años a la consumación, y es lo que dicen Ahmad y Abu ʿUbayd]]; y Malik y al-Shafiʿi dijeron: [[k:el límite es que pueda soportar al hombre]]; al-Shafiʿi dijo: y que esté cerca de la pubertad. Abu Hanifa dijo: el límite es que pueda soportar a los hombres, [[k:aunque no haya cumplido los nueve]]; y por eso se le impide al marido si no puede, aunque haya cumplido los nueve, y es parecido a lo que dice Malik. Y la norma del marido sobre llevarla consigo y mantenerla es la misma: cuando ella está obligada a la consumación, él está obligado a mantenerla."],
 prueba="El comentario malikí de Muslim da el consenso sobre el contrato y resume la discusión sobre la consumación: Ahmad y Abu ʿUbayd obligan a la niña de nueve años; Malik, al-Shafiʿi y Abu Hanifa lo ligan a la capacidad física, incluso antes de los nueve.",
 ojo="La primera cita es de al-Mazari, que critica la regla de Ahmad para las huérfanas («no tiene sentido»).")
add(5, "al-Kasani (m. 587 H / 1191)", specs=["mKa1", "mKa2", "mKa3"],
 title="al-Kasani: la discrepancia sobre casar a los pequeños «es contraria al consenso de los Compañeros»; la manutención depende de si «se tiene relación con una como ella»",
 ref="al-Kasani, Badaʾiʿ al-sanaʾiʿ, vol. 2, p. 240 y vol. 4, p. 19 (1.ª ed. 1327–28; reimpr. Dar al-Kutub al-ʿIlmiyya)", ar_ref="بدائع الصنائع ٢/٢٤٠ و٤/١٩", site=SH, url=S + "8183/563",
 es=["En resumen, [[k:no hay discrepancia en que el padre y el abuelo tienen la potestad de casar [a los pequeños]]], [[a:salvo algo que se cuenta de ʿUthman al-Batti y de Ibn Shubruma]]: que dijeron que no tienen potestad de casarlos. [2/240]",
     "Y la generalidad del mandato incluye al padre y al abuelo; y Abu Bakr al-Siddiq casó a Aisha, [[k:cuando tenía seis años, con el Mensajero de Dios ﷺ]], y el Mensajero de Dios ﷺ se casó con ella; [[k:y ʿAli casó a su hija Umm Kulthum, siendo pequeña, con Umar ibn al-Jattab]]; y ʿAbd Allah ibn Umar casó a su hija, siendo pequeña, con ʿUrwa ibn al-Zubayr. Con eso queda claro que la opinión de aquellos dos [[k:es contraria al consenso de los Compañeros]] y queda rechazada. [2/240]",
     "[[k:Y si es pequeña pero ya se tiene relación con una como ella, es como la adulta en cuanto a la manutención]], porque la razón que obliga a la manutención está en las dos; [[k:y si todavía no se tiene relación con una como ella, no tiene manutención según nosotros]]; y según al-Shafiʿi sí la tiene, porque para él la causa es el matrimonio y la condición es que no sea desobediente, y eso se da. Para nosotros, la condición es que se entregue, y la entrega no se realiza en la pequeña con la que aún no se tiene relación, ni por ella ni por otro, porque en ella misma hay impedimento para la relación y el disfrute, al no ser apta para ello; falta la condición, y no se debe. [4/19]"],
 prueba="El gran sistematizador hanafí da el poder de casar a los menores al padre y al abuelo, cita los precedentes de Abu Bakr, ʿAli e Ibn Umar y declara la discrepancia contraria al consenso de los Compañeros. Y liga la manutención de la esposa niña a si ya es apta para la relación, no a su edad.")
add(5, "Ibn Rushd (Averroes, m. 595 H / 1198)", specs=["mIR"],
 title="Ibn Rushd (Averroes): «coincidieron en que el padre obliga… a su hija pequeña virgen, sin consultarla»",
 ref="Ibn Rushd, Bidayat al-mujtahid, vol. 3, p. 34 (Dar al-Hadith, El Cairo, 1425/2004)", ar_ref="بداية المجتهد ٣/٣٤", site=SH, url=S + "21739/491",
 es=["[[k:Y coincidieron en que el padre obliga a su hijo pequeño a casarse, y lo mismo a su hija pequeña virgen, sin consultarla]], por lo que está probado de que el Mensajero de Dios ﷺ se casó con Aisha a los seis o siete años, y consumó el matrimonio con ella a los nueve, casándola su padre Abu Bakr; [[a:salvo la discrepancia que se transmite de Ibn Shubruma]]. Y discreparon en dos cuestiones: una, si casa a la pequeña alguien que no sea el padre; y la segunda, si casa al pequeño alguien que no sea el padre. En cuanto a si casa a la pequeña alguien que no sea el padre, al-Shafiʿi dijo: la casan el abuelo paterno y el padre solamente. Malik dijo: no la casa sino el padre, o aquel a quien el padre se lo encomiende si designa al marido, salvo que se tema que ella se pierda o se corrompa. Abu Hanifa dijo: casa a la pequeña cualquiera que tenga tutela sobre ella, padre, pariente u otro, y ella tiene opción [de anularlo] al llegar a la pubertad."],
 prueba="Averroes, el filósofo y juez de Córdoba, en su manual de derecho comparado: todas las escuelas coinciden en que el padre puede casar a su hija pequeña sin consultarla; solo discrepa Ibn Shubruma.")
add(5, "Ibn Qudama (m. 620 H / 1223)", specs=["mIQ1", "mIQ2"],
 title="Ibn Qudama: puede casarla «aunque ella no quiera y se niegue»; y Ahmad: «si ha cumplido nueve años, se le entrega»",
 ref="Ibn Qudama, al-Mughni, vol. 7, pp. 40 (masʾala 5200) y 259 (fasl 5635) (Maktabat al-Qahira, 1388/1968)", ar_ref="المغني ٧/٤٠ و٢٥٩", site=SH, url=S + "8463/2850",
 es=["Y si el hombre casa a su hija virgen y la pone con alguien de su condición, el matrimonio es firme aunque a ella no le guste, sea mayor o pequeña. [[k:En cuanto a la virgen pequeña, no hay discrepancia]]. Ibn al-Mundhir dijo: todos los sabios de quienes conservamos algo coinciden en que es válido que el padre case a su hija virgen pequeña si la casa con alguien de su condición, [[k:y puede casarla aunque ella no quiera y se niegue]]. Y prueba que es lícito casar a la pequeña la palabra de Dios: «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres, si dudáis, su plazo es de tres meses, y las que no han menstruado» (65:4): fijó para las que no han menstruado un plazo de tres meses, y el plazo de tres meses solo se da por repudio en un matrimonio o por anulación; [[k:así que prueba que se la casa y se la repudia, y no tiene un permiso que se tenga en cuenta]]. [7/40]",
     "Y la posibilidad de relación en la pequeña se mide por su estado y su capacidad para ello; lo dijo el Qadi, y mencionó que varían: puede haber una de corta edad que sea apta y una mayor que no lo sea. [[k:Y Ahmad lo fijó en nueve años]]; dijo, en la transmisión de Abu al-Harith, sobre la pequeña a la que reclama su marido: [[k:si ha cumplido nueve años, se le entrega]]; [[k:no pueden retenerla después de los nueve]]. Y se basó en que el Profeta ﷺ consumó el matrimonio con Aisha cuando ella tenía nueve. Dijo el Qadi: [[a:para mí esto no es como límite]]; lo mencionó porque lo habitual es que con la de nueve años sea posible la relación; y cuando no es apta para la relación, su familia no está obligada a entregársela, [7/259]"],
 prueba="El gran manual hanbalí: el padre puede casar a su hija pequeña aunque ella no quiera; y según Ahmad, cuando cumple nueve años se le entrega al marido que la reclama, y la familia no puede retenerla.",
 ojo="El Qadi Abu Yaʿla matiza (en azul) que los nueve años no son un límite fijo, sino lo habitual: si no es apta, no hay que entregarla. La frase sigue con el motivo, el riesgo de una lesión grave para la niña, que no se reproduce.")
C.append(T('qur', sec=5))
add(5, "al-Nawawi (m. 676 H / 1277)", specs=["mNw1", "mNw2", "mNw3"],
 title="al-Nawawi: «los musulmanes coinciden en que [el padre] puede casar a su hija virgen pequeña»; la consumación, cuando «pueda soportar la relación… y no se fija con una edad»",
 ref="al-Nawawi, Sharh Sahih Muslim, vol. 9, p. 206, sobre Muslim 1422 (Dar Ihyaʾ al-Turath al-ʿArabi, 2.ª ed., 1392)", ar_ref="شرح النووي على مسلم ٩/٢٠٦", site=SH, url=S + "1711/2085",
 es=["[[k:Esto es explícito en que el padre puede casar a la pequeña sin su permiso]], porque ella no tiene permiso [que contar]; y el abuelo es como el padre para nosotros. Ya se expuso en el capítulo anterior la discrepancia sobre la exigencia del tutor. [[k:Y los musulmanes coinciden en que [el padre] puede casar a su hija virgen pequeña, por este hadiz]]; y cuando llega a la pubertad no tiene opción de anularlo según Malik, al-Shafiʿi y los demás juristas del Hiyaz; y los de Iraq dijeron que tiene opción cuando llega a la pubertad. En cuanto a los tutores distintos del padre y el abuelo, no pueden casarla según al-Shafiʿi, al-Thawri, Malik, Ibn Abi Layla, Ahmad, Abu Thawr, Abu ʿUbayd y la mayoría; dijeron: si la casa, no es válido. Y al-Awzaʿi, Abu Hanifa y otros de los antiguos dijeron que pueden todos los tutores, y es válido, y ella tiene opción cuando llega a la pubertad; salvo Abu Yusuf, que dijo que no tiene opción.",
     "En cuanto al momento de llevar a la pequeña casada y consumar con ella: si el marido y el tutor acuerdan algo que no le cause daño a la pequeña, se aplica; y si discrepan, [[k:Ahmad y Abu ʿUbayd dijeron: se obliga a ello a la niña de nueve años]], no a una menor. Y Malik, al-Shafiʿi y Abu Hanifa dijeron: [[k:el límite es que pueda soportar la relación, y eso varía de una a otra y no se fija con una edad; y esto es lo correcto]]. Y en el hadiz de Aisha no hay límite, ni se prohíbe a la que pueda soportarlo antes de los nueve, ni se permite a la que no pueda aunque haya cumplido los nueve.",
     "Y sabe que al-Shafiʿi y sus compañeros dijeron: [[a:es recomendable que el padre y el abuelo no casen a la virgen hasta que llegue a la pubertad y le pidan permiso]], [[a:para no ponerla en el cautiverio del marido contra su voluntad]]. Y lo que dijeron no contradice el hadiz de Aisha, porque lo que quieren decir es que no la case antes de la pubertad [[k:si no hay un beneficio claro que se tema perder con la espera]], como en el hadiz de Aisha; entonces es recomendable conseguir a ese marido, porque al padre se le manda buscar el bien de su hija y no debe perderlo. Y Dios sabe más."],
 prueba="El comentario de Muslim más leído: consenso sobre el contrato; para la consumación, Ahmad obliga a la niña de nueve años, y las otras tres escuelas la ligan a la capacidad física, sin edad mínima, ni siquiera por debajo de los nueve.",
 ojo="Honesto: al-Nawawi recoge que los shafiʿíes recomiendan esperar a la pubertad y pedirle permiso (en azul), aunque lo matiza: si hay un buen partido que se puede perder, recomienda casarla antes.")

# ---------- 6. Siglos VIII–IX H ----------
add(6, "Ibn Taymiyya (m. 728 H / 1328)", specs=["mTy1", "mTy2"],
 title="Ibn Taymiyya: nadie casa a la mujer sin su permiso «salvo la virgen pequeña, a la que su padre casa sin que haga falta su permiso»",
 ref="Ibn Taymiyya, Majmuʿ al-fatawa, vol. 32, pp. 39 y 49 (ed. del Complejo Rey Fahd)", ar_ref="مجموع الفتاوى ٣٢/٣٩ و٤٩", site=SH, url=S + "7289/15641",
 es=["A la mujer nadie debe casarla sino con su permiso, como ordenó el Profeta ﷺ; y si no quiere, no se la obliga a casarse, [[k:salvo la virgen pequeña, a la que su padre casa sin que haga falta su permiso]]. [32/39]",
     "Alabado sea Dios. Si el pretendiente es de su condición, [[k:es lícito casarla según la más correcta de las dos opiniones de los sabios]], que es la escuela de Abu Hanifa y la de Ahmad en lo más conocido de él. Luego, unos dicen que se la casa sin su orden y tiene opción [de anularlo], como la escuela de Abu Hanifa y una transmisión de Ahmad; y otros dicen: [[k:si ha cumplido nueve años, se la casa con su permiso, y no tiene opción cuando llega a la pubertad]]; y es lo aparente de la escuela de Ahmad. [32/49]"],
 prueba="Ibn Taymiyya, que defiende el consentimiento de la mujer como regla, hace la excepción de la niña virgen. Y para la niña sin padre sigue la regla de los nueve años de Ahmad.",
 ojo="La segunda fatwa responde a si el juez puede casar a una niña sin padre que no ha llegado a la pubertad. No he encontrado una fatwa suya sobre la edad de la consumación.")
C.append(T('ik', sec=6))
add(6, "Jalil ibn Ishaq (m. 776 H / 1374)", specs=["mKh1", "mKh2"],
 title="Jalil, el compendio malikí: el padre obliga a la virgen; la consumación se exige «si el marido ha llegado a la pubertad y es posible la relación con ella»",
 ref="Jalil ibn Ishaq, al-Mujtasar, pp. 96 y 105 (ed. Ahmad Jad, Dar al-Hadith, El Cairo, 1426)", ar_ref="مختصر خليل ص ٩٦ و١٠٥", site="usul.ai", url="https://usul.ai/t/mukhtasar-khalil/84",
 es=["…luego el padre; [[k:y obliga [a casarse] a la loca y a la virgen, aunque sea solterona]], salvo con alguien como un castrado, según lo más correcto; y a la no virgen si es pequeña, o [si perdió la virginidad] por accidente o por algo ilícito. [p. 96]",
     "…luego no hay obligación para la que ha llegado a la pubertad, [[k:salvo la huérfana de la que se teme que se corrompa y que ha cumplido diez años]], y se consulta al juez. [p. 96]",
     "Y si uno de los dos se adelanta [a pedirla], se obliga al otro en su favor, [[k:si el marido ha llegado a la pubertad y es posible la relación con ella]]; y se le da a ella un año de plazo si lo puso como condición por estar lejos de su tierra o por ser pequeña, y si no, es nulo, no más; [[k:y [se aplaza] por la enfermedad y la corta edad que impidan la relación]]. [p. 105]"],
 prueba="El manual de referencia de la escuela malikí resume la norma: el padre obliga a la hija virgen; los demás tutores solo pueden casar a la huérfana desde los diez años y con el juez; la consumación se puede exigir cuando la relación es posible y se aplaza por corta edad.",
 ojo="El texto es un compendio muy abreviado; la traducción completa entre corchetes lo que se sobreentiende.")
add(6, "Ibn Hajar al-ʿAsqalani (m. 852 H / 1449)", specs=["mFB1", "mFB2"],
 title="Ibn Hajar: «por consenso, aunque esté en la cuna» (citando a Ibn Battal); y al-Muhallab: «aunque todavía no esté en edad de tener relaciones»",
 ref="Ibn Hajar, Fath al-Bari, vol. 9, pp. 124 y 190 (ed. Salafiyya)", ar_ref="فتح الباري ٩/١٢٤ و١٩٠", site=SH, url=S + "1673/5279",
 es=["[Dijo Ibn Battal:] [[k:Es lícito casar a la pequeña con el mayor por consenso]], [[k:aunque esté en la cuna, pero no se le permite [al marido] estar con ella hasta que sea apta para la relación]]; así indicó que el título [del capítulo] no aporta nada, porque es asunto en el que hay consenso. Dijo: y del hadiz se deduce que el padre casa a la virgen pequeña sin pedirle permiso. Digo [Ibn Hajar]: parece que lo dedujo de que no se menciona, y no es una prueba clara; [[a:al contrario, es posible que fuera antes de que llegara la orden de pedir permiso a la virgen]], y es lo que parece, porque la historia ocurrió en La Meca antes de la hégira. [9/124]",
     "Es decir: [[k:prueba que su matrimonio antes de la pubertad es lícito]]; y es una buena deducción, pero en el versículo no se restringe al padre ni a la virgen. Se puede decir: en las relaciones conyugales lo básico es la prohibición, salvo lo que indique una prueba; y vino el hadiz de Aisha sobre Abu Bakr casándola antes de la pubertad, y lo demás queda en lo básico; por eso trajo el hadiz de Aisha. Dijo al-Muhallab: [[k:coinciden en que el padre puede casar a su hija pequeña virgen, aunque todavía no esté en edad de tener relaciones]], [[a:salvo que al-Tahawi cuenta de Ibn Shubruma que lo prohibía en la que no está en edad de tener relaciones]]; e Ibn Hazm cuenta de Ibn Shubruma, sin más, que el padre no casa a su hija virgen pequeña hasta que llegue a la pubertad y dé permiso, y que pretendió que el matrimonio del Profeta ﷺ con Aisha cuando tenía seis años [[a:fue un privilegio suyo]]; y en el extremo opuesto, al-Hasan y al-Najaʿi permitían al padre obligar a su hija, fuera mayor o pequeña, virgen o no. [9/190]"],
 prueba="El comentario de referencia de Bujari recoge las dos fórmulas: el contrato es lícito desde la cuna y la consumación espera a que sea apta. Y deja constancia del único disidente, Ibn Shubruma.",
 ojo="La primera cita es de Ibn Battal (m. 449 H) y la segunda de al-Muhallab (m. 435 H); Ibn Hajar las transmite y discute un detalle (si hacía falta pedirle permiso).")
add(6, "Badr al-Din al-ʿAyni (m. 855 H / 1451)", specs=["mAy1", "mAy2"],
 title="al-ʿAyni: «es lícito casar a las que no han menstruado desde el primer momento en que son creadas»",
 ref="Badr al-Din al-ʿAyni, ʿUmdat al-qari, vol. 20, pp. 126–127 (ed. Muniriyya; reimpr. Dar Ihyaʾ al-Turath)", ar_ref="عمدة القاري ٢٠/١٢٦–١٢٧", site=SH, url=S + "5756/6013",
 es=["Y parece que al-Bujari quiso con este título refutar a Ibn Shubruma, pues al-Tahawi cuenta de él que no es válido que los padres casen a los pequeños, y que ellas tienen opción cuando llegan a la pubertad. Dijo: [[a:y esto no lo dijo nadie más que él]], y no se le presta atención por ser aislado y contrario a la prueba del Libro y la Sunna. Y dijo al-Muhallab: coincidieron en que el padre puede casar a su hija pequeña, aunque todavía no esté en edad de tener relaciones, por la generalidad de Su palabra «y las que no han menstruado» (65:4); [[k:así que es lícito casar a las que no han menstruado desde el primer momento en que son creadas]]. Solo discreparon sobre los que no son padres. [20/126]",
     "[Y discreparon los sabios sobre el momento en que la mujer es llevada a su marido… y dijo un] grupo, entre ellos Ahmad y Abu ʿUbayd: [[k:[el marido] consuma cuando ella tiene nueve años, siguiendo el hadiz de Aisha]]; y de Abu Hanifa: nos atenemos a los nueve, pero decimos: [[k:si ha cumplido los nueve y no puede con la relación, su familia puede impedirlo]], [[k:y si no ha cumplido los nueve y es fuerte para los hombres, no pueden impedírselo a su marido]]; y Malik decía: no hay manutención para la pequeña hasta que llegue a la pubertad o pueda soportar a los hombres; y al-Shafiʿi dijo: si está cerca de la pubertad y es corpulenta, de modo que soporta la relación, su marido puede consumar con ella; y si no, su familia puede impedirlo hasta que la soporte. [20/127]"],
 prueba="El otro gran comentario de Bujari repite la fórmula de al-Muhallab y el cuadro de las escuelas: nueve años para Ahmad; para Abu Hanifa, incluso antes de los nueve si la niña es «fuerte para los hombres».",
 ojo="Las citas principales son de Mughlatay (autor de al-Talwih) y de al-Muhallab, que al-ʿAyni recoge. El texto impreso tiene erratas («يخضن» por «يحضن»).")
C.append(T('suy', sec=6))

# numeración y campos comunes
SECN = {1: "siglos I–II H", 2: "siglo III H", 3: "siglo IV H", 4: "siglo V H", 5: "siglos VI–VII H", 6: "siglos VIII–IX H"}
MCARDS = []
for i, c in enumerate(C, 1):
    c['id'] = f"M{i:02d}"
    c['tag'] = f"{SECN[c['sec']]} · {c.pop('tag_who')}"
    c['uso'] = f"Matrimonio de menores en las fuentes suníes · sección {c['sec'] + 1} ({SECN[c['sec']]})"
    if not c.get('ojo'): c.pop('ojo', None)
    MCARDS.append(c)
