# -*- coding: utf-8 -*-
# Tarjetas de tafsir de 65:4 (matrimonio de menores). Clave = id provisional; 'd' = año de muerte (H) para ordenar.
SH = "shamela.ws (Maktaba Shamila; paginación igual a la edición impresa)"
S = "https://shamela.ws/book/"
TAF = {
 'muq': dict(d=150, who="Muqatil ibn Sulayman (m. 150 H / 767)", specs=["mMuq"],
  title="Muqatil: «las muchachas que no han llegado a la menstruación, y han sido casadas y luego repudiadas»",
  ref="Muqatil ibn Sulayman, Tafsir, sobre el Corán 65:4 (vol. 4, p. 365), reproducido en Mawsuʿat al-tafsir al-maʾthur, vol. 21, p. 740, n.º 77363 (Dar Ibn Hazm, 2017)",
  ar_ref="تفسير مقاتل ٤/٣٦٥، في موسوعة التفسير المأثور ٢١/٧٤٠ رقم ٧٧٣٦٣",
  site=SH, url=S + "639/15209",
  es=["77363 — Dijo Muqatil ibn Sulayman: «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres» (65:4): es decir, las mujeres mayores que han dejado de menstruar. «Si dudáis»: es decir, si tenéis dudas y no se sabe cuál es su plazo de espera: «su plazo es de tres meses», si son repudiadas. «Y las que no han menstruado»: igual también; es decir, [[k:el plazo de espera de las muchachas (al-jawārī) que no han llegado a la menstruación]], [[k:y han sido casadas, y luego repudiadas]]: su plazo es de tres meses.",
      "(6) Tafsir de Muqatil ibn Sulayman, 4/365."],
  prueba="El comentario completo del Corán más antiguo que se conserva (siglo II H) explica «las que no han menstruado» como muchachas que aún no han llegado a la menstruación, ya casadas y repudiadas; el versículo les fija tres meses de espera.",
  ojo="La captura es de una enciclopedia moderna que reproduce a Muqatil con su referencia (4/365); la edición de Muqatil no se ha abierto. Como transmisor de hadices Muqatil tiene mala fama; aquí se cita como comentarista."),
 'tab': dict(d=310, who="al-Tabari (m. 310 H / 923)", specs=["mTabU", "mTabG", "mTabD"],
  title="al-Tabari: «las muchachas, por ser pequeñas, si sus maridos las repudian después de consumar el matrimonio»",
  ref="al-Tabari, Jamiʿ al-bayan, sobre el Corán 65:4, vol. 23, pp. 451–453 (ed. Dar al-Tarbiya wa-l-Turath; en la ed. al-Turki, 23/50–54)",
  ar_ref="تفسير الطبري ٢٣/٤٥١–٤٥٣",
  site=SH, url=S + "43/13681",
  es=["Ubayy ibn Kaʿb dijo: «Mensajero de Dios, hay plazos de espera de las mujeres que [[k:no se mencionan en el Libro: [los de] las pequeñas y las mayores]], y las embarazadas». [23/451]",
      "…Si lo correcto en esto es lo que hemos dicho, queda claro que la interpretación del versículo es: «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres, si dudáis» sobre la norma que les corresponde y su plazo de espera, sin saber cuál es: la norma de su plazo, si son repudiadas [[k:y son de aquellas con las que sus maridos ya han consumado el matrimonio]], es de tres meses. «Y las que no han menstruado»: dice: e igualmente el plazo de las que no han menstruado [[k:de entre las muchachas, por ser pequeñas]], [[k:si sus maridos las repudian después de consumar el matrimonio]]. [23/452]",
      "Nos contó Muhammad: nos contó Asbat, de al-Suddi, sobre Su palabra «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres»: dice: aquella cuya menstruación ha cesado; su plazo es de tres meses. «Y las que no han menstruado»: [[k:dijo: las muchachas]]. Nos contó Bishr: nos contó Yazid: nos contó Saʿid, de Qatada, sobre Su palabra «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres»: son las que han dejado de menstruar y ya no menstrúan; y las que no han menstruado [[k:son las vírgenes que no han menstruado]]; su plazo es de tres meses.",
      "Se me contó de al-Husayn: oí a Abu Muʿadh decir: nos contó ʿUbayd: oí a al-Dahhak decir sobre Su palabra «Y las que han perdido la esperanza de menstruar…»: dijo: las mujeres mayores. «Y las que no han menstruado»: [[k:las que no han llegado a la menstruación, y ya han sido tocadas]]; su plazo es de tres [meses]. [23/453]"],
  prueba="Para al-Tabari, el gran comentarista del siglo III–IV H, «las que no han menstruado» son muchachas que aún no menstrúan por su corta edad, repudiadas después de consumado el matrimonio. Cita en el mismo sentido a al-Suddi, Qatada y al-Dahhak («ya han sido tocadas», es decir, consumado).",
  ojo="Al-Tabari habla del plazo de espera; no fija ninguna edad. La cadena de al-Dahhak empieza con «se me contó», sin nombre. En la ed. al-Turki se lee «لصغرهن» («por su corta edad»), con el mismo sentido."),
 'jas': dict(d=370, who="al-Jassas (m. 370 H / 981)", specs=["mJas"],
  title="al-Jassas: «el repudio no se produce sino en un matrimonio válido; luego el versículo implica que es lícito casar a la pequeña»",
  ref="al-Jassas, Ahkam al-Qurʾan, sobre el Corán 4:3, vol. 2, p. 346 (ed. Qamhawi, Dar Ihyaʾ al-Turath al-ʿArabi)",
  ar_ref="أحكام القرآن للجصاص ٢/٣٤٦",
  site=SH, url=S + "23579/744",
  es=["…Y en este versículo hay también una prueba de [[k:que el padre puede casar a su hija pequeña]], ya que indica que pueden casarla los demás tutores, y él es el tutor más cercano. Y no sabemos que haya discrepancia sobre su licitud entre los antiguos y los posteriores de los juristas de las ciudades, [[a:salvo algo que transmitió Bishr ibn al-Walid de Ibn Shubruma]]: que no es lícito que los padres casen a los pequeños; y es la escuela de al-Asamm. Y prueba que esa escuela es falsa, además de lo que hemos dicho de este versículo, Su palabra: «Y las que han perdido la esperanza de menstruar de entre vuestras mujeres, si dudáis, su plazo es de tres meses, y las que no han menstruado» (65:4): [[k:así declaró válido el repudio de la pequeña que no ha menstruado]], [[k:y el repudio no se produce sino en un matrimonio válido]]; [[k:luego el versículo implica que es lícito casar a la pequeña]]. Y lo prueba que el Profeta ﷺ [[k:se casó con Aisha cuando ella tenía seis años]]: se la dio en matrimonio Abu Bakr al-Siddiq. Y esta noticia contiene dos sentidos: uno, que es lícito que el padre case a la pequeña; y el otro, que ella no tiene opción [de anularlo] después de la pubertad, porque el Profeta ﷺ no le dio a elegir después de la pubertad."],
  prueba="El jurista hanafí razona desde 65:4: si el Corán regula el repudio de la que no ha menstruado, es que puede estar casada. Lo apoya en Aisha, casada a los seis años, y concluye además que la niña casada por su padre no puede anular el matrimonio al llegar a la pubertad.",
  ojo="Él mismo recoge la discrepancia de Ibn Shubruma y al-Asamm (en azul); ver la sección de voces en contra."),
 'wah': dict(d=468, who="al-Wahidi (m. 468 H / 1076)", specs=["mWah"],
  title="al-Wahidi, por qué se reveló 65:4: faltaba el plazo de «las pequeñas, las mayores y las embarazadas»",
  ref="al-Wahidi, Asbab nuzul al-Qurʾan, sobre el Corán 65:4, p. 437 (ed. al-Humaydan, Dar al-Islah, 2.ª ed., 1412/1992)",
  ar_ref="أسباب النزول للواحدي ص ٤٣٧",
  site=SH, url=S + "11314/434",
  es=["Abu ʿUthman ʿAmr ibn Salim dijo: cuando se reveló el plazo de espera de las mujeres en la sura de la Vaca, sobre la repudiada y la viuda, Ubayy ibn Kaʿb dijo: «Mensajero de Dios, unas mujeres de Medina dicen: aún quedan mujeres de las que no se ha dicho nada». Dijo: «¿Cuáles?». Dijo: «[[k:Las pequeñas, las mayores y las embarazadas]]». Y se reveló este versículo: «Y las que han perdido la esperanza…», hasta el final.",
      "(1) Lo transmitieron al-Hakim (al-Mustadrak 2/492), Ibn Jarir (28/91), Ibn Rahawayh, Ibn al-Mundhir, Ibn Abi Hatim, Ibn Mardawayh y al-Bayhaqi (Fath al-Qadir 5/244), por vía de Mutarrif, de Abu ʿUthman, [[k:y su cadena es auténtica]]."],
  prueba="Según esta causa de la revelación, el versículo vino a cubrir el plazo de espera de tres grupos de mujeres que el Corán aún no había regulado: las pequeñas, las mayores y las embarazadas.",
  ojo="«Su cadena es auténtica» lo dice el editor moderno en nota al pie, no al-Wahidi. Ibn al-ʿArabi (siglo VI H) dice en cambio que el hadiz de Ubayy «no es auténtico» (ver su tarjeta)."),
 'bag': dict(d=516, who="al-Baghawi (m. 516 H / 1122)", specs=["mBag"],
  title="al-Baghawi: «y las que no han menstruado: es decir, las pequeñas que no han menstruado»",
  ref="al-Baghawi, Maʿalim al-tanzil, sobre el Corán 65:4, vol. 8, p. 152 (Dar Tayba, 4.ª ed., 1417/1997)",
  ar_ref="تفسير البغوي ٨/١٥٢",
  site=SH, url=S + "41/3205",
  es=["…las mujeres mayores que han dejado de menstruar. «Si dudáis»: si tenéis dudas sobre su norma, «su plazo es de tres meses». «Y las que no han menstruado»: [[k:es decir, las pequeñas que no han menstruado]]; su plazo también es de tres meses."],
  prueba="Al-Baghawi, comentarista shafiʿí muy leído, repite la lectura: «las que no han menstruado» son las pequeñas, con tres meses de espera."),
 'ia': dict(d=543, who="Ibn al-ʿArabi (m. 543 H / 1148)", specs=["mIA"],
  title="Ibn al-ʿArabi: 65:4 «es prueba de que el hombre puede casar a sus hijos pequeños»",
  ref="Ibn al-ʿArabi, Ahkam al-Qurʾan, sobre el Corán 65:4, vol. 4, p. 285 (ed. ʿAta, Dar al-Kutub al-ʿIlmiyya, 3.ª ed., 1424/2003)",
  ar_ref="أحكام القرآن لابن العربي ٤/٢٨٥",
  site=SH, url=S + "1464/2173",
  es=["[Cuestión: el hombre puede casar a sus hijos pequeños.] Cuarta cuestión: Su palabra «Y las que no han menstruado» (65:4) [[k:es prueba de que el hombre puede casar a sus hijos pequeños]]; porque Dios fijó en tres meses el plazo de espera de las mujeres que no han menstruado, [[k:y no tiene plazo de espera sino la que tiene matrimonio]]; así que lo prueba, y es [un argumento] brillante en su género."],
  prueba="El jurista malikí de al-Ándalus saca de 65:4 la misma conclusión que al-Jassas: si la que no ha menstruado tiene plazo de espera, es que puede estar casada; luego el padre puede casar a sus hijos pequeños.",
  ojo="En la misma página dice que el hadiz de Ubayy (la causa de la revelación) «no es auténtico»; su argumento no depende de él."),
 'qur': dict(d=671, who="al-Qurtubi (m. 671 H / 1273)", specs=["mQur"],
  title="al-Qurtubi: «y las que no han menstruado —es decir, la pequeña—: su plazo es de tres meses»",
  ref="al-Qurtubi, al-Jamiʿ li-ahkam al-Qurʾan, sobre el Corán 65:4, vol. 18, p. 165 (Dar al-Kutub al-Misriyya, 2.ª ed., 1384/1964)",
  ar_ref="تفسير القرطبي ١٨/١٦٥",
  site=SH, url=S + "20855/6741",
  es=["Su palabra: «Y las que no han menstruado» —[[k:es decir, la pequeña]]—: [[k:su plazo es de tres meses]]; se sobreentiende el predicado. Su plazo se cuenta en meses porque normalmente no tiene periodos, y Dios aplicó las normas según lo habitual; así que cuenta por meses. Si ve sangre a una edad en que es posible entre las mujeres, pasa a contar por la sangre, porque aparece lo principal, y cuando aparece lo principal no queda norma para el sustituto; igual que la mayor que contó por la sangre y luego se le retiró, que vuelve a los meses. Y esto es consenso."],
  prueba="Al-Qurtubi, el gran comentario jurídico malikí, lo da por sentado: «las que no han menstruado» es la pequeña, con tres meses de espera. En 33:49 recuerda que sin consumación no hay plazo de espera («por el texto del Libro y el consenso»).",
  ojo="La relación con 33:49 la hace él mismo en 14/202–204, pero citando la cláusula de las mayores, no la de las pequeñas."),
 'ik': dict(d=774, who="Ibn Kathir (m. 774 H / 1373)", specs=["mIK"],
  title="Ibn Kathir: «e igualmente las pequeñas que no han llegado a la edad de la menstruación: su plazo es de tres meses»",
  ref="Ibn Kathir, Tafsir al-Qurʾan al-ʿazim, sobre el Corán 65:4, vol. 8, p. 149 (ed. al-Salama, Dar Tayba, 2.ª ed., 1420/1999)",
  ar_ref="تفسير ابن كثير ٨/١٤٩",
  site=SH, url=S + "8473/4195",
  es=["Dice Dios, aclarando el plazo de espera de la mujer que ya no espera menstruar —la que ha dejado de menstruar por su edad—: que es de tres meses, en lugar de los tres periodos de la que menstrúa, como indica el versículo de la Vaca. [[k:E igualmente las pequeñas que no han llegado a la edad de la menstruación: su plazo es como el de la que ya no menstrúa, tres meses]]; por eso dice: «y las que no han menstruado»."],
  prueba="Ibn Kathir, el comentario más leído hoy, repite la misma lectura en el siglo VIII H: el versículo regula el plazo de espera de esposas que aún no tienen edad de menstruar."),
 'suy': dict(d=911, who="al-Suyuti (m. 911 H / 1505)", specs=["mSuy"],
  title="al-Suyuti: la causa de la revelación de 65:4, «las pequeñas, y las mayores que han dejado de menstruar»",
  ref="al-Suyuti, al-Durr al-manthur, sobre el Corán 65:4, vol. 8, p. 201 (Dar al-Fikr, 8 vols.)",
  ar_ref="الدر المنثور للسيوطي ٨/٢٠١",
  site=SH, url=S + "12884/6770",
  es=["…dijeron: «Aún queda del plazo de espera de las mujeres un plazo que no se ha mencionado en el Corán: [[k:las pequeñas, y las mayores que han dejado de menstruar]], y las embarazadas». Y Dios reveló la [sura] de las mujeres corta: «Y las que han perdido la esperanza de menstruar…», el versículo.",
      "Y transmitieron Ibn Abi Shayba e Ibn Mardawayh, por otra vía, de Ubayy [ibn] Kaʿb, que dijo: cuando se reveló el plazo de la viuda y de la repudiada, dije: «Mensajero de Dios, [[k:quedan mujeres: la pequeña, la mayor y la embarazada]]». Y se reveló: «Y las que han perdido la esperanza de menstruar…», el versículo."],
  prueba="Al final del periodo (siglo IX–X H), al-Suyuti sigue recogiendo la misma causa de la revelación: el versículo regula el plazo de espera de las pequeñas.",
  ojo="En esta edición la palabra «مدة» parece errata por «عدد»; el sentido no cambia."),
}
