# -*- coding: utf-8 -*-
# ---------- 4. Siglos VII–VIII H (XIII–XIV d. C.) ----------
JS = "Ibn Taymiyya, al-Jawab al-sahih li-man baddala din al-Masih (ed. Dar al-ʿAsima, 6 vols.)"
MF = "Ibn Taymiyya, Majmuʿ al-fatawa (ed. Complejo del Rey Fahd)"
HH = "Ibn Qayyim al-Jawziyya, Hidayat al-hayara fi ajwibat al-Yahud wa-l-Nasara (ed. ʿAtaʾat al-ʿIlm)"
BN = "Ibn Kathir, al-Bidaya wa-l-nihaya (ed. ʿAli Shiri, Dar Ihyaʾ al-Turath)"
ITW = "Ibn Taymiyya (m. 728 H / 1328)"
IQW = "Ibn al-Qayyim (m. 751 H / 1350)"
IKW = "Ibn Kathir (m. 774 H / 1373)"

add(4, ITW, key="IT1", specs=["rIT1a", "rIT1b", "rIT1c"],
 title="El argumento «de la mayoría»: la Torá se cortó con la destrucción de Jerusalén y la dictó «una sola persona, Esdras»; el Evangelio, cuatro que se equivocaron «hasta confundirlo con el crucificado»",
 ref=f"{JS}, vol. 2, pp. 395–397", ar_ref="الجواب الصحيح لابن تيمية ٢/٣٩٥–٣٩٧", site=SH, url=S + "170/779",
 es=["[[k:Y entre los argumentos de la mayoría]] —los que niegan que todas las palabras de estos libros anteriores que tiene la gente del Libro hayan sido reveladas por Dios sin que les haya entrado cambio, [[k:y dicen que el cambio entró en algunas de sus palabras]], y que no se sabe que sus palabras sean reveladas por Dios, de modo que no se puede argumentar con ellas contra lo que se sabe cierto— está que dijeron: la Torá y el Evangelio que hoy tiene la gente del Libro no se han transmitido masivamente (tawatur) desde Moisés y Jesús —la paz sea con ellos—. En cuanto a la Torá, [[k:su transmisión se cortó cuando Jerusalén fue destruida la primera vez]] y los hijos de Israel fueron desterrados de ella; luego cuentan que quien se la dictó después fue [[k:una sola persona llamada Esdras]], y pretenden que era profeta.",
     "Y hay quien dice que no era profeta, [[k:y que se cotejó con una copia antigua que se encontró]]; y se ha dicho que se trajo una copia que estaba en el Occidente. [[k:Y todo esto no implica la transmisión masiva de todas sus palabras]], ni impide que haya error en algunas, como ocurre con los libros cuya copia, cotejo y conservación están a cargo de unos pocos, dos o tres.",
     "En cuanto al Evangelio que tienen, [[k:ellos mismos reconocen que no lo escribió el Mesías]] —la paz sea con él— ni se lo dictó a quien lo escribió, [[k:sino que lo dictaron, después de la elevación del Mesías, Mateo y Juan]], que habían acompañado al Mesías —y no lo memorizó una multitud que alcance el número de la transmisión masiva—, [[k:y Marcos y Lucas, que no vieron al Mesías]]; y estos dicen que contaron algunas de las cosas que dijo el Mesías y algunas de sus noticias, y que no recogieron todas sus palabras y obras. Y en la transmisión de dos, tres o cuatro cabe el error, sobre todo porque se equivocaron en el propio Mesías, [[k:hasta el punto de confundirlo con el crucificado]]."],
 prueba="Ibn Taymiyya (m. 728 H) resume el argumento «de la mayoría» de los ulemas: la Torá no está transmitida masivamente, porque su transmisión se cortó con la destrucción de Jerusalén y la volvió a dictar un solo hombre, Esdras; y el Evangelio lo escribieron cuatro, dos de los cuales no vieron a Jesús, y que «se equivocaron hasta confundirlo con el crucificado».",
 ojo="Lo presenta como la postura de quienes dicen que el cambio entró «en algunas de sus palabras», no en todo el texto. Y el criterio del «tawatur» se le puede devolver: tampoco el Corán tuvo un texto único hasta la recensión de ʿUthman, que mandó quemar las demás copias (Bujari 4987).")

add(4, ITW, key="IT2", specs=["rIT2a", "rIT2b"],
 title="«En tiempos de Constantino cambiaron mucho de la religión del Mesías»: el Credo de los 318, la cruz de Helena, el cerdo, el oriente y las imágenes",
 ref=f"{JS}, vol. 2, p. 406, y vol. 3, p. 30", ar_ref="الجواب الصحيح لابن تيمية ٢/٤٠٦ و٣/٣٠", site=SH, url=S + "170/790",
 es=["Y esto es como el Credo (al-amana), que es la base de su religión, y su oración hacia el oriente, [[k:hacer lícito el cerdo, abandonar la circuncisión, venerar la cruz]] y poner imágenes en las iglesias, y otras de sus normas, [[k:que no están transmitidas del Mesías ni se mencionan en los Evangelios]] que transmiten de él. Están de acuerdo en que las palabras del Credo, que hicieron base de su religión, no están en los Evangelios ni proceden de los discípulos, y en que quienes lo compusieron fueron [[k:los del primer concilio, los que estaban con Constantino, al que asistieron trescientos dieciocho]], [[k:y que se opusieron a ʿAbd Allah ibn Arius, que hizo al Mesías siervo de Dios, como dicen los musulmanes]], y compusieron este Credo. Y este concilio fue mucho tiempo después del Mesías, más de trescientos años.",
     "…[[k:como la fiesta de la Cruz, que la inventó Helena de Harrán, madre de Constantino]]; [[k:y en tiempos de Constantino cambiaron mucho de la religión del Mesías, de las creencias y de las leyes]], [[k:e inventaron el Credo, que es la creencia de su fe]], una creencia que no pronuncia ninguno de los libros de los profetas que tienen, ni está transmitida de ningún profeta ni de ninguno de los discípulos que acompañaron al Mesías, sino que se la inventó un grupo de sus grandes: dicen que eran trescientos dieciocho."],
 prueba="La tesis de Ibn Taymiyya sobre Constantino: «en tiempos de Constantino cambiaron mucho de la religión del Mesías»; el Credo de Nicea no está en los Evangelios ni viene de los apóstoles; la oración al oriente, el cerdo, el abandono de la circuncisión, la cruz y las imágenes no vienen de Jesús. Y Arrio «hizo al Mesías siervo de Dios, como dicen los musulmanes».",
 ojo="Aquí el cambio es de doctrina y de leyes, no del texto de los Evangelios: el propio Ibn Taymiyya dice que esas cosas «no se mencionan en los Evangelios». La circuncisión y las leyes alimentarias ya se habían dejado para los gentiles en el siglo I (Hechos 15; Gálatas), no en el IV. Y Arrio no decía lo que dicen los musulmanes: para él el Hijo era una criatura anterior al mundo, por medio de la cual Dios lo creó todo.")

add(4, ITW, key="IT3", specs=["rIT3a", "rIT3b", "rIT3c"],
 title="Citando al cronista cristiano Ibn al-Bitriq: 2.048 obispos «de religiones distintas»; 318 en «la doctrina de Pablo el apóstol»; Constantino les da «su sello, su espada y su cetro»",
 ref=f"{JS}, vol. 4, pp. 220, 222 y 223 (cita de Saʿid ibn al-Bitriq, Nazm al-jawhar)", ar_ref="الجواب الصحيح لابن تيمية ٤/٢٢٠–٢٢٣", site=SH, url=S + "170/1554",
 es=["[Cita de Ibn al-Bitriq:] …Constantino ordenó al patriarca Alejandro que maldijera a Arrio y a todos los que decían lo mismo. Le dijo: «No; que el rey mande traer a los patriarcas y obispos para que tengamos un concilio, fijemos en él una decisión, maldigamos a Arrio y expliquemos la religión a la gente». El rey Constantino mandó a todos los países, reunió a los patriarcas y obispos, y se reunieron en la ciudad de Nicea, al cabo de un año y dos meses, [[k:dos mil cuarenta y ocho obispos]], [[k:y eran de opiniones y religiones distintas]].",
     "…Y entre ellos estaba quien decía: «Nuestro Señor es el Mesías»; [[k:y esa es la doctrina de Pablo el apóstol, y la doctrina de los trescientos dieciocho obispos]]. Dijo: Cuando el rey Constantino oyó sus doctrinas, se asombró, les dejó una casa, mandó que se les honrara y hospedara, y les ordenó discutir entre ellos para ver quién tenía la verdad y seguirlo. [[k:Y se pusieron de acuerdo trescientos dieciocho obispos en una sola religión y una sola opinión]], discutieron con el resto de los obispos, vencieron sus argumentos y mostraron la religión recta; y el resto de los obispos tenían religiones y opiniones distintas. El rey hizo para los trescientos dieciocho obispos una gran sesión especial, se sentó en medio, [[k:tomó su sello, su espada y su cetro y se los entregó]], y les dijo: «[[k:Hoy os doy poder sobre el reino]] para que hagáis lo que os parezca, lo que debéis hacer para sostener la religión y el bien de los creyentes». Bendijeron al rey, le ciñeron la espada y le dijeron: «Haz pública la religión cristiana y defiéndela».",
     "[[k:Y le compusieron cuarenta libros, con las normas y las leyes]], lo que deben hacer los obispos y lo que debe hacer el rey. El presidente del concilio fue Alejandro, patriarca de Alejandría, con el patriarca de Antioquía y el obispo de Jerusalén; y el patriarca de Roma envió a dos hombres. Acordaron desterrar a Arrio y a sus compañeros, los maldijeron a ellos y a todos los que dijeran lo mismo, [[k:y compusieron aquel Credo]], y establecieron que el Hijo nació del Padre antes de todas las criaturas, [[k:y que el Hijo es de la naturaleza del Padre, no creado]]."],
 prueba="Ibn Taymiyya copia, para refutarla, la crónica del patriarca melquita Saʿid ibn al-Bitriq (Eutiquio, m. 328 H / 940): 2.048 obispos «de opiniones y religiones distintas»; 318 coinciden en «la doctrina de Pablo el apóstol»; Constantino les entrega su sello, su espada y su cetro. De aquí salen las cifras y la escena que repiten los autores musulmanes posteriores.",
 ojo="La fuente es un cronista cristiano del siglo X, seis siglos después de Nicea, y sus cifras no son históricas (las listas antiguas tienen unos 250 obispos; los 2.048 aparecen en autores árabes tardíos). Y para Ibn al-Bitriq la «doctrina de Pablo el apóstol» es la ortodoxia apostólica, no un invento de Pablo.")

add(4, ITW, key="IT4", specs=["rIT4a", "rIT4b"],
 title="Citando a Ibn al-Bitriq: Constantino obliga a los judíos a hacerse cristianos y les hace comer cerdo a la salida de misa: «al que no comía se le mataba»",
 ref=f"{JS}, vol. 4, pp. 230 y 232 (cita de Saʿid ibn al-Bitriq)", ar_ref="الجواب الصحيح لابن تيمية ٤/٢٣٠ و٢٣٢", site=SH, url=S + "170/1564",
 es=["[Cita de Ibn al-Bitriq:] Dijo: Y el rey ordenó que ningún judío viviera en Jerusalén ni pasara por ella, [[k:y que quien no se hiciera cristiano fuera muerto]]. Muchos judíos se hicieron cristianos y se mostró la religión cristiana. Se le dijo al rey Constantino: «Los judíos se hacen cristianos por miedo a la muerte, pero siguen en su religión». Dijo el rey: «¿Cómo podemos saberlo?». [[k:Dijo Pablo el patriarca: «El cerdo está prohibido en la Torá]] y los judíos no comen carne de cerdo: que se maten cerdos, se cocine su carne y se les dé de comer; al que no coma sabremos que sigue en la religión judía». Dijo el rey: «Si el cerdo está prohibido en la Torá, ¿cómo vamos a comer carne de cerdo y dársela a la gente?». Le dijo Pablo el patriarca: «[[k:Nuestro señor el Mesías anuló todo lo que hay en la Torá y trajo otra ley y una Torá nueva, que es el Evangelio]]; y en su santo Evangelio dice: “Todo lo que entra en el vientre no es prohibido ni mancha; lo que mancha al hombre es lo que sale de su boca”».",
     "…«Por esta visión y por lo que dijo nuestro señor el Mesías en su santo Evangelio, [[k:Pedro y Pablo mandaron que comiéramos todo cuadrúpedo, cerdo incluido]], y todos los animales, como lícitos». Y el rey ordenó que se mataran cerdos, se cocinara su carne, se cortara en trozos pequeños y se pusiera a las puertas de las iglesias de todo su reino el domingo de Pascua, y a todo el que saliera de la iglesia se le daba un bocado de carne de cerdo; [[k:al que no comía se le mataba, y por eso mataron a mucha gente]]."],
 prueba="Otro pasaje de Ibn al-Bitriq copiado por Ibn Taymiyya: Constantino obliga a los judíos a hacerse cristianos y, para descubrir a los falsos conversos, les hace comer cerdo a la salida de misa, so pena de muerte. Es el origen del «cerdo impuesto por Constantino» que se repite en la polémica.",
 ojo="El «Pablo» de este pasaje es un patriarca del siglo IV, no el apóstol. La anécdota solo aparece en este cronista árabe del siglo X; ninguna fuente del siglo IV la menciona. Y la libertad de comer de todo ya está en el Nuevo Testamento (Marcos 7:19; Hechos 10, la visión de Pedro que cita el propio texto), tres siglos antes de Constantino.")

add(4, ITW, key="IT5", specs=["rIT5a", "rIT5b", "rIT5c"],
 title="Las fetuas: «una religión mezcla de monoteístas y politeístas»; la cruz «la inventó Constantino por un sueño»; Pablo «era judío y mostró el cristianismo por hipocresía»",
 ref=f"{MF}, vol. 17, p. 331; vol. 28, p. 611; vol. 35, p. 184", ar_ref="مجموع الفتاوى ١٧/٣٣١ و٢٨/٦١١ و٣٥/١٨٤", site=SH, url=S + "7289/8935",
 es=["Y por eso quien cambió la religión del Mesías [[k:compuso una religión mezcla de la religión de los monoteístas y la de los politeístas]]: aquellos adoraban al sol, la luna y los astros, les rezaban y se postraban ante ellos; [[k:y vino Constantino, rey de los cristianos, y sus seguidores, e inventaron la oración hacia el oriente]], e hicieron la postración hacia el sol en lugar de la postración ante él; y aquellos adoraban ídolos con cuerpo que dan sombra, [[k:y vinieron los cristianos y pintaron imágenes de los santos en las iglesias]], e hicieron imágenes pintadas en las paredes y los techos en lugar de las imágenes con cuerpo, de pie por sí mismas, que dan sombra.",
     "…[[k:aunque el Mesías y los discípulos seguían la ley de la Torá]]. Además, la oración hacia el oriente no la mandaron ni el Mesías ni los discípulos; [[k:la inventó Constantino u otro]]. [[k:Y lo mismo la cruz: la inventó Constantino por su opinión y por un sueño que pretendió haber tenido]]. El Mesías y los discípulos no mandaron nada de eso.",
     "El primero que inventó el rechazo [el chiismo extremo] fue un hipócrita y hereje llamado ʿAbd Allah ibn Sabaʾ, que quiso con ello corromper la religión de los musulmanes, [[k:como hizo Pablo, el autor de las cartas que tienen los cristianos]], que les inventó innovaciones con las que corrompió su religión; [[k:era judío, mostró el cristianismo por hipocresía y buscó corromperlo]]."],
 prueba="En sus fetuas, Ibn Taymiyya resume la tesis en frases cortas: el cristianismo de Constantino es una mezcla de monoteísmo y culto a los astros; la oración al oriente y la cruz las «inventó Constantino… por un sueño»; y Pablo «era judío, mostró el cristianismo por hipocresía y buscó corromperlo», igual que Ibn Sabaʾ con el islam.",
 ojo="Ibn Taymiyya duda él mismo («Constantino u otro»). La oración hacia el oriente es anterior a Constantino (Tertuliano, Orígenes) y la cruz era símbolo cristiano desde mucho antes (Tertuliano, hacia el 200, habla de signarse con la cruz). Y Pablo no «mostró el cristianismo por hipocresía»: murió ejecutado por predicarlo.")

add(4, IQW, key="IQ1", specs=["rIQ1a", "rIQ1b"],
 title="«Esta Torá es el libro de ʿUzayr»… «aunque en ella esté —o la mayor parte de ella sea— la Torá que Dios reveló a Moisés»",
 ref=f"{HH}, pp. 247–248", ar_ref="هداية الحيارى لابن القيم ص ٢٤٧–٢٤٨", site=SH, url=S + "5705/314",
 es=["Y vamos a explicar la verdadera causa del cambio de la Torá: los sabios y doctores de esa gente saben que, de esta Torá que tienen, [[k:ninguno de sus sabios y doctores cree que sea exactamente la Torá revelada a Moisés hijo de ʿImran]] en absoluto; porque Moisés guardó la Torá lejos de los hijos de Israel y no la difundió entre ellos, por miedo a que después de él discreparan en su interpretación y se dividieran en partidos, [[k:y solo la entregó a su clan, los hijos de Leví]]. Dijo: Y la prueba es lo que dice la Torá, cuya traducción es: «Moisés escribió esta Torá y la dio a los imames de los hijos de Leví». Los hijos de Aarón eran los jueces y gobernantes de los judíos, porque el sacerdocio, el servicio de los sacrificios y el Templo estaban en ellos; y Moisés no mostró a los hijos de Israel de la Torá más que media sura…",
     "…Los sacerdotes aaronitas eran los que conocían la Torá y sabían de memoria la mayor parte, [[k:y Nabucodonosor los mató a todos de una vez]] y quemó su Templo el día que tomó Jerusalén; y la Torá no estaba en sus lenguas, sino que cada uno sabía de memoria un pasaje. Cuando ʿUzayr vio que a la gente le habían quemado el Templo, se había perdido su reino, se había dispersado su comunidad y se les había quitado su libro, [[k:reunió de lo que sabía de memoria y de los pasajes que sabían los sacerdotes con lo que compuso esta Torá que tienen]]; por eso exageraron en venerar a ʿUzayr, dijeron de él lo que Dios cuenta en Su libro, y pretenden que la luz aparece hasta hoy sobre su tumba, junto a los pantanos de Irak, porque les hizo un libro que conserva su religión. [[k:Así que esta Torá que tienen es, en realidad, el libro de ʿUzayr]], [[a:aunque en ella esté —o la mayor parte de ella sea— la Torá que Dios reveló a Moisés]]. Dijo: Y esto indica que quien reunió estos pasajes era un hombre ignorante de los atributos del Señor; por eso atribuyó al Señor aquello de lo que Él está libre. Y a este hombre lo conocen judíos y cristianos como Esdras el escriba."],
 prueba="Ibn al-Qayyim (m. 751 H) copia casi palabra por palabra la explicación de al-Samawʾal (#Sam#): Moisés solo confió la Torá a los sacerdotes, Nabucodonosor los mató y Esdras la recompuso de memoria; por eso es «el libro de ʿUzayr».",
 ojo="Añade una concesión importante que al-Samawʾal no hace (en azul): «aunque en ella esté —o la mayor parte de ella sea— la Torá que Dios reveló a Moisés». Es decir, para Ibn al-Qayyim la Torá actual contiene, en su mayor parte, la revelación a Moisés.")

add(4, IQW, key="IQ2", specs=["rIQ2a", "rIQ2b"],
 title="«Cerca de trescientos años» fieles; luego lo hicieron todo al revés que los judíos: «se pusieron a deshacer la Ley norma por norma»",
 ref=f"{HH}, pp. 326–327", ar_ref="هداية الحيارى لابن القيم ص ٣٢٦–٣٢٧", site=SH, url=S + "5705/393",
 es=["[[k:Y los compañeros del Mesías siguieron así después de él cerca de trescientos años]]; [[k:luego la gente empezó a cambiar y alterar]], a congraciarse con la gente con lo que les gustaba y a hacer la contra a los judíos, aunque eso supusiera dejar la religión del Mesías y desprenderse de ella del todo. Vieron que los judíos habían dicho del Mesías que era un brujo, un loco, un embaucador, hijo de fornicación, [[k:y dijeron: «Es Dios completo, y es el hijo de Dios»]]. [[k:Vieron que los judíos se circuncidaban, y dejaron la circuncisión]]. Vieron que extremaban la pureza, y la dejaron del todo.",
     "…[vieron que] prohibían el cerdo, [[k:y lo hicieron lícito y lo convirtieron en emblema de su religión]]; vieron que prohibían muchas víctimas y animales, e hicieron lícito todo, desde el elefante hasta el mosquito; vieron que se orientaban hacia Jerusalén en la oración, [[k:y ellos se orientaron hacia el oriente]]; vieron que prohibían que Dios abrogara una ley que había dado, y ellos permitieron a sus obispos y patriarcas abrogar lo que quisieran; vieron que santificaban el sábado, [[k:y ellos santificaron el domingo y dejaron el sábado]] —aun reconociendo que el Mesías veneraba el sábado y lo guardaba—; vieron que aborrecían la cruz, porque en la Torá está «maldito el que cuelga de la cruz» —y los cristianos lo reconocen—, [[k:y ellos adoraron la cruz]]. Igual que en la Torá está prohibido el cerdo, y ellos hicieron un acto de culto comerlo; y en ella se manda la circuncisión, y ellos hicieron un acto de culto no hacerla —aun reconociendo que el Mesías dijo a sus compañeros: «He venido a cumplir la Torá y los mandamientos de los profetas anteriores a mí; no he venido a abolir, sino a completar…»—. [[k:Y los cristianos se pusieron a deshacerla norma por norma, para hacer la contra a los judíos]]."],
 prueba="La tesis de Ibn al-Qayyim: el cristianismo actual es un «anti-judaísmo» deliberado. Durante unos trescientos años los compañeros de Jesús siguieron su ley; luego, para llevar la contraria a los judíos, hicieron lo opuesto en todo: si los judíos lo llamaban brujo, ellos lo hicieron Dios; si se circuncidaban, ellos no; si rezaban hacia Jerusalén, ellos hacia el oriente; si aborrecían la cruz, ellos la adoraron.",
 ojo="Los plazos no cuadran entre los propios autores musulmanes: aquí la religión de Jesús dura «cerca de trescientos años»; en el hadiz que cita Ibn Kathir, doscientos (#IK2#); en al-Thaʿlabi, ochenta y uno (#Tl#); en Ibn Abbas, la facción creyente es exterminada enseguida (#IA1#). Además, casi todos esos cambios ya están en el Nuevo Testamento, escrito en el siglo I (Hechos 15, Gálatas, Marcos 7:19), no trescientos años después.")

add(4, IQW, key="IQ3", specs=["rIQ3a", "rIQ3b"],
 title="«En tiempos de Constantino… se cambió la religión del Mesías»: dos mil reunidos sin acuerdo y 318 «Padres» que fijan el Credo",
 ref=f"{HH}, pp. 328–329", ar_ref="هداية الحيارى لابن القيم ص ٣٢٨–٣٢٩", site=SH, url=S + "5705/395",
 es=["…que un grupo de cristianos salió de Jerusalén y fue a Antioquía y a otros lugares de Siria, y llamaron a la gente a la religión verdadera del Mesías: a obrar según la Torá, a prohibir las víctimas de quienes no eran de ella, a la circuncisión, a guardar el sábado, a prohibir el cerdo y lo que la Torá prohíbe. Eso les resultó pesado a las naciones; los cristianos se reunieron en Jerusalén y deliberaron cómo atraerse a las naciones para hacerles amable la religión del Mesías, [[k:y su decisión fue mezclarse con las naciones, hacerles concesiones]], tratar con ellas, comer sus víctimas, rebajarse a sus deseos, adoptar sus costumbres [[k:y crear una ley que estuviera entre la ley del Evangelio y la de las naciones]]; y escribieron sobre ello un libro. Y este fue uno de sus grandes concilios. Cada vez que querían introducir algo, se reunían en un concilio, hasta que celebraron el mayor concilio que han tenido, [[k:en tiempos de Constantino el romano, hijo de Helena de Harrán, la de la posada; y en su tiempo se cambió la religión del Mesías]].",
     "…[[k:Eran unos dos mil hombres]]; fijaron una decisión y luego la rechazaron. [[k:Luego se reunieron trescientos dieciocho de ellos]] —los cristianos los llaman «los Padres»— y fijaron la decisión que tienen hoy, [[k:que es la base de las bases para todas sus confesiones]]: nadie es cristiano del todo si no es con ella; la llaman «sínodo», y es el Credo (al-amana)."],
 prueba="Ibn al-Qayyim repite el esquema de ʿAbd al-Jabbar casi con sus mismas palabras: el concilio de Jerusalén «crea una ley a medio camino entre el Evangelio y las naciones», y en Nicea, «en tiempos de Constantino… se cambió la religión del Mesías». Dos mil reunidos sin acuerdo; 318 fijan el Credo.",
 ojo="Es una copia, no una fuente independiente: el texto sobre Antioquía y Jerusalén es el de ʿAbd al-Jabbar (#AJ1#), y la historia de Esdras, la de al-Samawʾal (#Sam#). Que muchos autores repitan lo mismo no lo hace más probable si todos copian de uno. Y el concilio de Jerusalén (Hechos 15) no creó «una ley intermedia» por conveniencia: discutió si los gentiles debían circuncidarse.")

add(4, IKW, key="IK1", specs=["rIK3"],
 title="Ibn Kathir rechaza el relato del rey romano que se hizo cristiano en el siglo I: «los romanos no entraron en la religión del Mesías sino después de trescientos años, con Constantino»",
 ref=f"{BN}, vol. 2, p. 113", ar_ref="البداية والنهاية لابن كثير ٢/١١٣", site=SH, url=S + "8376/503",
 es=["Y contó Ishaq ibn Bishr, de Mujahid ibn Jabr: que los judíos, cuando crucificaron a aquel hombre al que se hizo parecer, creyendo que era el Mesías —y la mayoría de los cristianos se lo concedieron por ignorancia—, se lanzaron contra sus compañeros con muertes, golpes y cárceles. El asunto llegó al señor de los romanos, que era el rey de Damasco en aquel tiempo, y se le dijo que los judíos habían atacado a los compañeros de un hombre que les decía que era el mensajero de Dios, que resucitaba a los muertos, curaba al ciego y al leproso y hacía maravillas, que lo habían matado y que habían humillado y encarcelado a sus compañeros. Mandó traerlos —entre ellos estaban Yahya hijo de Zacarías, Simón y un grupo—, les preguntó por el Mesías, se lo contaron, y les juró fidelidad en su religión, elevó su palabra, y la verdad se impuso a los judíos; mandó a por el crucificado, lo bajaron de su madero, trajeron el madero en el que habían crucificado a aquel hombre y lo veneró; por eso los cristianos veneran la cruz, [[k:y de ahí entró la religión cristiana en los romanos]]. [[k:Y en esto hay que objetar varias cosas]]: primera, que Yahya hijo de Zacarías es profeta y no aceptaría que el crucificado fuera Jesús, pues es infalible y sabe lo que ocurrió de verdad. Segunda, [[k:que los romanos no entraron en la religión del Mesías sino después de trescientos años, en tiempos de Constantino]], hijo de Constancio, el que construyó la ciudad que lleva su nombre, como contaremos. Tercera, que los judíos, cuando crucificaron a aquel hombre, lo tiraron con su madero e hicieron de aquel lugar un vertedero de basura, inmundicia, carroña y suciedades, y siguió así hasta el tiempo de ese Constantino; [[k:y su madre, Helena de Harrán, la de la posada, lo sacó de allí creyendo que era el Mesías]], y encontraron el madero en el que fue crucificado el crucificado, y contaron que ningún enfermo lo tocaba sin curarse. Dios sabe mejor si esto fue así o no…"],
 prueba="Ibn Kathir (m. 774 H), el gran historiador sirio, recoge el relato atribuido a Mujahid —el mismo que Ibn Ishaq cuenta en al-Tabari (#Tb1#): un rey romano del siglo I se hace cristiano y venera el madero del crucificado— y lo rechaza: «los romanos no entraron en la religión del Mesías sino después de trescientos años, en tiempos de Constantino».",
 ojo="Un dato de crítica interna muy útil: el propio Ibn Kathir desmonta con la cronología uno de los relatos islámicos sobre el origen del cristianismo. Pero su primer argumento tampoco cuadra: según los Evangelios (y la tradición islámica), Yahya, Juan el Bautista, murió antes que Jesús, así que no pudo estar en esa escena.")

add(4, IKW, key="IK2", specs=["rIK4"],
 title="«Los compañeros del Mesías siguieron su norma doscientos años» (hadiz «muy extraño»); y Pablo en Damasco: «y la fe de Pablo en el Mesías se volvió buena»",
 ref=f"{BN}, vol. 2, p. 119", ar_ref="البداية والنهاية لابن كثير ٢/١١٩", site=SH, url=S + "8376/509",
 es=["«Dios se llevó a David de entre sus compañeros, y no cayeron en la tentación ni cambiaron; [[k:y los compañeros del Mesías siguieron su norma y su guía doscientos años]]». [[a:Y este es un hadiz muy extraño, aunque lo declaró auténtico Ibn Hibban]]. Y contó Ibn Jarir, de Muhammad ibn Ishaq, que Jesús, antes de ser elevado, encargó a los discípulos que llamaran a la gente a adorar a Dios solo, sin asociado, y asignó a cada uno un grupo de gente en una región, de Siria, el oriente y el occidente; y contaron que amaneció cada uno hablando la lengua de aquellos a quienes el Mesías lo había enviado. Y cuentan varios que el Evangelio lo transmitieron de él cuatro: Lucas, Mateo, Marcos y Juan; [[k:y entre estos cuatro evangelios hay mucha diferencia]], de cada copia respecto a otra, y muchas añadidas y omisiones de unas respecto a otras; de estos cuatro, dos alcanzaron al Mesías y lo vieron, Mateo y Juan, y dos son de los compañeros de sus compañeros, Marcos y Lucas.",
     "Entre los que creyeron en el Mesías, de la gente de Damasco, había un hombre llamado Dinya [Ananías], que se escondía en una cueva dentro de la Puerta Oriental, cerca de la Iglesia de la Cruz, [[k:por miedo a Pablo el judío, que era injusto, opresor y odiaba al Mesías]] y lo que trajo. Había rapado la cabeza a su sobrino cuando creyó en el Mesías, lo había paseado por la ciudad y luego lo lapidó hasta que murió. Cuando Pablo oyó que el Mesías se dirigía hacia Damasco, preparó sus mulas y salió a matarlo; lo encontró en Kawkaba, y cuando se enfrentó a los compañeros del Mesías, vino un ángel, le golpeó la cara con la punta de su ala y lo dejó ciego. Al ver eso, le entró en el alma creer en el Mesías; fue a él, se disculpó por lo que había hecho y creyó en él, y él lo aceptó; le pidió que le pasara la mano por los ojos para que Dios le devolviera la vista, y le dijo: «Ve a Dinya, que está en Damasco, al extremo oriental de la calle Larga, y él rezará por ti». Fue, rezó por él, y le devolvió la vista; [[a:y la fe de Pablo en el Mesías se volvió buena]] —que es siervo de Dios y Su mensajero—, y se le construyó una iglesia con su nombre: la conocida iglesia de Pablo en Damasco, desde que la conquistaron los Compañeros hasta que se arruinó."],
 prueba="Ibn Kathir recoge un hadiz según el cual los compañeros de Jesús siguieron su camino doscientos años (que él mismo llama «muy extraño»), dice que los cuatro Evangelios difieren mucho entre sí, y cuenta la conversión de Pablo en Damasco… con un final sorprendente: «y la fe de Pablo en el Mesías se volvió buena».",
 ojo="Este Pablo de Ibn Kathir es un converso sincero, no el traidor de las leyendas de Sayf, al-Thaʿlabi, ʿAbd al-Jabbar o Ibn Hazm (#Sy#, #Tl#, #AJ3#, #IH2#). Y su versión no sigue a Hechos 9: allí quien se aparece es Jesús resucitado, no un ángel, y Jesús no «se dirigía a Damasco» en persona.")

add(4, IKW, key="IK3", specs=["rIK5a", "rIK5b", "rIK5c"],
 title="«Trescientos años después, la mayor calamidad»: Constantino se pasa al grupo mayoritario (los «melquitas») y el Credo, al-amana, «es en realidad la mayor traición»",
 ref=f"{BN}, vol. 2, pp. 119–121", ar_ref="البداية والنهاية لابن كثير ٢/١١٩–١٢١", site=SH, url=S + "8376/509",
 es=["Los compañeros del Mesías discreparon después de su elevación al cielo en varias opiniones, [[k:como dijo Ibn Abbas y otros de los imames de los primeros musulmanes]], según lo citamos en Su palabra «Dimos fuerza a los que creyeron contra su enemigo y se impusieron» (61:14). Dijeron Ibn Abbas y otros: unos dijeron: «Estuvo entre nosotros el siervo de Dios y Su mensajero, y fue elevado al…",
     "…cielo»; otros dijeron: «Es Dios»; y otros: «Es el hijo de Dios». La primera es la verdad, y las otras dos son una gran incredulidad, como dice: «Y discreparon los partidos entre ellos; ¡ay de los incrédulos por el testimonio de un día terrible!» (19:37). [[k:Y discreparon en la transmisión de los Evangelios en cuatro versiones, entre añadidos, omisiones, tergiversación y cambio]]. [[k:Luego, trescientos años después del Mesías, ocurrió la mayor desgracia y la mayor calamidad]]: los cuatro patriarcas y todos los obispos, sacerdotes, diáconos y monjes discreparon sobre el Mesías en tantas opiniones que no se pueden contar. [[k:Se reunieron y llevaron su pleito ante el rey Constantino]], el que construyó Constantinopla —y fue el primer concilio—. [[k:Y el rey se pasó a la opinión del grupo más numeroso que coincidió en una de esas doctrinas, y se les llamó los melquitas]] [los del rey], y rechazó y alejó a los demás. [[k:Y quedó aparte el grupo que seguía a ʿAbd Allah ibn Idyus [Arrio], que se mantuvo en que Jesús es un siervo de los siervos de Dios y un mensajero de Sus mensajeros]]: se fueron a vivir a los desiertos y estepas, construyeron ermitas, monasterios y celdas, se contentaron con una vida austera y no se mezclaron con aquellas religiones y sectas.",
     "Y los unos y los otros se volvieron incrédulos, y pusieron cánones y normas, algunas contrarias al Antiguo [Testamento], que es la Torá; [[k:hicieron lícitas cosas prohibidas por el texto de la Torá, entre ellas el cerdo, y rezaron hacia el oriente]] —y el Mesías no rezó sino hacia la Roca de Jerusalén, como todos los profetas después de Moisés; y Muhammad, el sello de los profetas, rezó hacia ella tras emigrar a Medina dieciséis o diecisiete meses, y luego se le cambió hacia la Kaaba que construyó Abraham—; [[k:y pusieron imágenes en las iglesias, que antes no las tenían]], y pusieron la creencia que memorizan sus niños, mujeres y hombres, [[k:a la que llaman «la confianza» (al-amana), y que es en realidad la mayor incredulidad y traición]]; y todos los melquitas, los nestorianos, seguidores de Nestorio, [[k:la gente del segundo concilio]], y los jacobitas, seguidores de Jacobo Baradeo, la gente del tercer concilio, creen en esta creencia y discrepan en su interpretación."],
 prueba="La versión «oficial» de Ibn Kathir: las discrepancias de Ibn Abbas al principio; los Evangelios transmitidos en cuatro versiones «con añadidos, omisiones, tergiversación y cambio»; trescientos años después, «la mayor calamidad»: Constantino se pasa al grupo mayoritario (los «melquitas», los del rey) y los arrianos, que decían que Jesús es siervo de Dios, se retiran al desierto. Y el juego de palabras: al-amana («la confianza», el Credo) es en realidad la mayor «traición» (jiyana).",
 ojo="Ibn Kathir mezcla dos teorías: la de Ibn Abbas (las sectas nacen justo después de la ascensión, #IA1#) y la de los cronistas (nacen trescientos años después, con Constantino). Se equivoca con los concilios: Nestorio fue condenado en el tercero (Éfeso, 431) y los jacobitas surgieron tras el cuarto (Calcedonia, 451). Y que los melquitas fueran «el grupo más numeroso» contradice a quienes dicen que solo 318 de 2.048 estaban de acuerdo (#Ms1#, #IT3#).")
