# -*- coding: utf-8 -*-
# ---------- 1. Siglos I–II H (VII–VIII d. C.) ----------
add(1, "Ibn Abbas (m. 68 H / 687), en Ibn Kathir (m. 774 H)", key="IA1", specs=["rIK1a", "rIK1b"],
 title="El cambiazo y los tres grupos: «estos son los jacobitas… los nestorianos… los musulmanes»; Ibn Kathir: «cadena auténtica hasta Ibn Abbas»",
 ref="Ibn Kathir, Tafsir al-Qurʾan al-ʿazim, sobre el Corán 4:157, vol. 2, pp. 449–450 (ed. Sami al-Salama, Dar Tayba), citando a Ibn Abi Hatim; también al-Nasaʾi, al-Sunan al-kubra 11527",
 ar_ref="تفسير ابن كثير ٢/٤٤٩–٤٥٠", site=SH, url=S + "8473/1231",
 es=["Dijo Ibn Abi Hatim: nos contó Ahmad ibn Sinan: nos contó Abu Muʿawiya, de al-Aʿmash, de al-Minhal ibn ʿAmr, de Saʿid ibn Jubayr, de Ibn Abbas, que dijo: Cuando Dios quiso elevar a Jesús al cielo, salió a sus compañeros —y en la casa había doce hombres de los discípulos—, es decir, salió hacia ellos de una fuente que había en la casa, con la cabeza goteando agua, y dijo: «Hay entre vosotros quien renegará de mí doce veces después de haber creído en mí». Luego dijo: «[[k:¿A quién de vosotros se le echará mi semejanza, para que lo maten en mi lugar y esté conmigo en mi rango?]]». Se levantó un joven, de los más jóvenes de ellos, y le dijo: «Siéntate». Lo repitió, se levantó aquel joven, y le dijo: «Siéntate». Lo repitió otra vez, se levantó el joven y dijo: «Yo». Dijo: «Tú eres ese». [[k:Y se le echó la semejanza de Jesús, y Jesús fue elevado al cielo por un tragaluz de la casa]]. Dijo: Y llegaron los que lo buscaban, de los judíos, [[k:tomaron al que se le parecía, lo mataron y luego lo crucificaron]].",
     "…Y se dividieron en tres grupos. Un grupo dijo: «[[k:Dios estuvo entre nosotros lo que quiso y luego subió al cielo]]»; y estos son los jacobitas. Otro grupo dijo: «[[k:Estuvo entre nosotros el hijo de Dios lo que quiso, y luego Dios lo elevó hacia Sí]]»; y estos son los nestorianos. Y otro grupo dijo: «[[k:Estuvo entre nosotros el siervo de Dios y Su mensajero lo que quiso, y luego Dios lo elevó hacia Sí]]»; y estos son los musulmanes. [[k:Los dos grupos incrédulos se aliaron contra el musulmán y lo mataron, y el islam siguió borrado hasta que Dios envió a Muhammad]] ﷺ.<br>[Ibn Kathir:] [[k:Esta cadena es auténtica hasta Ibn Abbas]], y la transmitió al-Nasaʾi de Abu Kurayb, de Abu Muʿawiya, de forma parecida."],
 prueba="Es el relato del cambiazo con la mejor cadena: Ibn Kathir la declara auténtica hasta Ibn Abbas. Y cuenta lo que pasó después: tres grupos (jacobitas, nestorianos y «musulmanes»); los dos primeros matan al tercero y «el islam siguió borrado» hasta Muhammad. Es decir, seis siglos sin nadie que siguiera la religión verdadera de Jesús.",
 ojo="Anacronismo grave: los nestorianos y los jacobitas no existían en el siglo I. Son las iglesias que se separaron tras los concilios de Éfeso (431) y Calcedonia (451), y llevan el nombre de Nestorio (m. c. 451) y de Jacobo Baradeo (m. 578). Un relato que los pone el día después de la ascensión no puede venir de un testigo. Además, «auténtica hasta Ibn Abbas» no es lo mismo que «auténtica»: Ibn Abbas (m. 68 H) no fue testigo y no dice de quién lo sabe.")

again(1, "Ibn Abbas (m. 68 H / 687), en al-Nasaʾi e Ibn Kathir", 'K01', key="K01",
 prueba="Segundo relato de Ibn Abbas sobre lo que pasó después de Jesús: unos reyes cambiaron la Torá y el Evangelio, mientras había creyentes que seguían leyéndolos; el rey les exige dejar de leerlos «salvo lo que habían cambiado de ellos», y los que se niegan se retiran a vivir como monjes (Corán 57:27). Es una alteración hecha por un poder político, en sus ejemplares, con creyentes que conservan el texto auténtico.",
 ojo="Ibn Kathir dice de este relato que «tiene algo de extraño» (en azul). Las calificaciones están divididas: al-Albani, «cadena auténtica, como dicho de Ibn Abbas»; ʿAli Zaʾi, «débil». No dice qué reyes ni cuándo; y no encaja con el relato anterior del mismo Ibn Abbas, donde los creyentes son exterminados por las otras dos sectas, no por unos reyes.")

add(1, "Ibn Abbas (m. 68 H / 687), en al-Tabari (m. 310 H)", key="IAuz", specs=["rUz1a", "rUz1b"],
 title="ʿUzayr (Esdras): Dios «les hizo olvidar la Torá y la borró de sus pechos»… y se la devolvió a él",
 ref=f"{TAB}, sobre el Corán 9:30, n.º 16621, vol. 14, pp. 202–203",
 ar_ref="تفسير الطبري ١٤/٢٠٢–٢٠٣، رقم ١٦٦٢١", site=SH, url=S + "43/7768",
 es=["Me contó Muhammad ibn Saʿd: me contó mi padre: me contó mi tío: me contó mi padre, de su padre, de Ibn Abbas, sobre Su palabra «Y dijeron los judíos: ʿUzayr es hijo de Dios» (9:30): Dijeron que es hijo de Dios porque ʿUzayr estaba entre la gente del Libro; tenían la Torá y la pusieron en práctica lo que Dios quiso; [[k:luego la descuidaron y obraron sin la verdad]], y el Arca estaba entre ellos. Cuando Dios vio que habían descuidado la Torá y obraban según sus pasiones, [[k:les retiró el Arca, les hizo olvidar la Torá y la borró de sus pechos]], y les envió una enfermedad: se les soltó el vientre hasta que al hombre se le iba el hígado, hasta que olvidaron la Torá y fue borrada de sus pechos; y entre ellos estaba ʿUzayr. Pasaron así lo que Dios quiso. ʿUzayr había sido antes uno de sus sabios, y pidió a Dios, suplicándole, que le devolviera lo que había sido borrado de su pecho de la Torá. Mientras rezaba suplicando a Dios, [[k:bajó una luz de Dios y entró en su interior]], y le volvió lo que se había ido de su interior de…",
     "…la Torá. Pregonó entre su pueblo y dijo: «Pueblo mío, [[k:Dios me ha dado la Torá y me la ha devuelto]]». Se puso a enseñarles, y pasaron lo que Dios quiso mientras él les enseñaba. Luego el Arca bajó, después de haberse ido de ellos; cuando vieron el Arca, compararon lo que había en ella con lo que ʿUzayr les enseñaba, [[k:y lo encontraron igual; y dijeron: «Por Dios, a ʿUzayr no se le dio esto sino porque es hijo de Dios»]]."],
 prueba="Versión de Ibn Abbas sobre el Antiguo Testamento: la Torá no se quema; Dios la borra de la memoria de los israelitas como castigo y se la devuelve a ʿUzayr (Esdras). Y la copia guardada en el Arca confirma que el texto restituido es idéntico.",
 ojo="La cadena es la de la familia al-ʿAwfi (Muhammad ibn Saʿd… ʿAtiyya al-ʿAwfi), que los críticos del hadiz consideran débil. Y no coincide con las demás versiones: en la de Wahb la Torá se quema (#H11b#), en la de al-Suddi la roban los amalecitas (#H11c#), y en la de al-Kalbi Nabucodonosor mata a todos los que sabían leerla (#Kl#).")

add(1, "Wahb ibn Munabbih (m. 110/114 H / 728–732), en al-Tabari", key="Wb1", specs=["rWb1a", "rWb1b"],
 title="Nabucodonosor arrasa Jerusalén: «mató a los hijos de Israel hasta exterminarlos»… «y los libros fueron quemados»",
 ref=f"{TAB}, sobre el Corán 2:259, n.º 5910 (vol. 5, p. 452) y n.º 5912 (vol. 5, p. 455)",
 ar_ref="تفسير الطبري ٥/٤٥٢ و٥/٤٥٥، رقم ٥٩١٠ و٥٩١٢", site=SH, url=S + "43/2758",
 es=["…Y entró Nabucodonosor con sus tropas en Jerusalén, pisoteó Siria [[k:y mató a los hijos de Israel hasta exterminarlos, y arrasó Jerusalén]]. Luego ordenó a sus tropas que cada hombre llenara su escudo de tierra y la echara en Jerusalén, y echaron tierra hasta llenarla. Después volvió a la tierra de Babilonia llevándose a los cautivos de los hijos de Israel; les ordenó reunir a todos los que había en Jerusalén, se reunió ante él todo pequeño y grande de los hijos de Israel, [[k:y escogió de entre ellos setenta mil muchachos]]. Cuando salió el botín de sus tropas y quiso repartirlo, le dijeron los reyes que estaban con él: «Oh rey, para ti todo nuestro botín, y reparte entre nosotros a estos muchachos que has escogido». Lo hizo, y a cada uno le tocaron cuatro muchachos; entre ellos estaban Daniel, Azarías, Misael y Ananías. Nabucodonosor los dividió en tres grupos: [[k:a un tercio lo dejó en Siria, a un tercio lo cautivó y a un tercio lo mató]]. Y se llevó los vasos de Jerusalén hasta Babilonia.",
     "Nos contó al-Hasan ibn Yahya: nos informó ʿAbd al-Razzaq: nos informó ʿAbd al-Samad ibn Maʿqil que oyó a Wahb ibn Munabbih decir, sobre Su palabra «¿Cómo devolverá Dios la vida a esta después de muerta?» (2:259): Que Jeremías, [[k:cuando Jerusalén fue arrasada y los libros fueron quemados]], se detuvo a un lado del monte y dijo: «¿Cómo devolverá Dios la vida a esta después de muerta?», y Dios lo hizo morir cien años. [[k:Luego Dios devolvió a los que devolvió de los hijos de Israel al cabo de setenta años]] desde que lo hizo morir, y la estuvieron reconstruyendo treinta años, hasta completar los cien."],
 prueba="El relato base de la destrucción de Jerusalén (587 a. C.) en la tradición islámica. Aquí aparece la idea de que «los libros fueron quemados», que luego usarán Ibn Hazm, al-Samawʾal, Ibn Taymiyya o al-Kairanawi.",
 ojo="Wahb (m. 110/114 H) era un yemení famoso por transmitir relatos de origen judío y cristiano (israʾiliyyat), y no cita fuente. El relato largo (n.º 5910) llega por Ibn Ishaq «de alguien de quien no se sospecha», es decir, con un eslabón anónimo (vol. 5, p. 447). Y mezcla personajes: identifica al hombre de Corán 2:259 con Jeremías; otros dicen que era ʿUzayr.")

again(1, "Wahb ibn Munabbih (m. 110/114 H), en al-Tabari, Tarikh", 'H11b', key="H11b",
 prueba="Continuación del relato de Wahb: al volver del exilio, la Torá «había sido quemada y se había perdido», y un ángel se la devuelve a Esdras (ʿUzayr), que se la vuelve a dictar a los israelitas. En el relato, la Torá restituida es la verdadera: la «reconocían».",
 ojo="No es opinión del propio al-Tabari: es el relato de Wahb que transmite vía Ibn Ishaq (empieza en la p. 548). La misma historia la cuenta al-Kalbi con otros detalles (#Kl#).")

add(1, "Wahb ibn Munabbih (m. 110/114 H / 728–732), en al-Tabari", key="Wb2", specs=["rWb2a", "rWb2b"],
 title="Dos versiones de Wahb: los diecisiete con la cara de Jesús… y un discípulo que lo vende por treinta dirhams",
 ref=f"{TAB}, sobre el Corán 4:157, n.º 10779 y 10780, vol. 9, pp. 368–369",
 ar_ref="تفسير الطبري ٩/٣٦٨–٣٦٩، رقم ١٠٧٧٩ و١٠٧٨٠", site=SH, url=S + "43/5049",
 es=["Nos contó Ibn Humayd: nos contó Yaʿqub al-Qummi, de Harun ibn ʿAntara, de Wahb ibn Munabbih, que dijo: Vinieron a por Jesús, que estaba con diecisiete de los discípulos en una casa, y los rodearon. Cuando entraron a por ellos, [[k:Dios les dio a todos la forma de Jesús]], y les dijeron: «¡Nos habéis hechizado! O nos sacáis a Jesús o os mataremos a todos». Dijo Jesús a sus compañeros: «[[k:¿Quién de vosotros vende hoy su alma a cambio del Paraíso?]]». Dijo un hombre de ellos: «Yo». Salió hacia ellos y dijo: «Yo soy Jesús» —y Dios le había dado la forma de Jesús—, [[k:y lo tomaron, lo mataron y lo crucificaron. Por eso se les hizo parecer]], y creyeron que habían matado a Jesús, [[k:y los cristianos creyeron lo mismo, que era Jesús]]; y Dios elevó a Jesús aquel mismo día.",
     "[Segunda versión de Wahb:] …Cuando amaneció, uno de los discípulos fue a los judíos y dijo: «¿Qué me dais si os llevo al Mesías?». [[k:Le dieron treinta dirhams, los tomó y los llevó hasta él]]. Ya antes se les había hecho parecer [a otro]. Lo tomaron, lo aseguraron y lo ataron con una cuerda, y lo llevaban diciéndole: «Tú resucitabas a los muertos, ahuyentabas al demonio y curabas al loco: ¿no te salvas a ti mismo de esta cuerda?»; y le escupían y le echaban espinas, hasta que lo llevaron al madero en el que querían crucificarlo; [[k:y Dios lo elevó hacia Sí, y crucificaron lo que se les hizo parecer]], y estuvo [allí] siete [días]. Luego su madre y la mujer a la que Jesús había tratado y Dios había curado de la locura vinieron llorando donde estaba el crucificado; vino a ellas Jesús y dijo: «¿Por qué lloráis?». Dijeron: «Por ti». Dijo: «Dios me ha elevado hacia Sí y no me ha pasado más que bien, [[k:y esto es algo que se les hizo parecer]]»."],
 prueba="Dos versiones del mismo Wahb, una detrás de otra en al-Tabari. En la primera, Dios da la cara de Jesús a los diecisiete y uno se ofrece. En la segunda, un discípulo lo vende por treinta dirhams y lo llevan atado hasta el madero; en el último momento Dios lo eleva y crucifican a «lo que se les hizo parecer». La segunda copia el relato de los Evangelios (la última cena, la negación de Pedro, Judas) y solo cambia el final.",
 ojo="Ni siquiera un mismo narrador da una sola versión. Y en la primera «los cristianos creyeron lo mismo»: los propios discípulos fueron engañados. Al-Tabari prefiere esta versión precisamente por eso (#TabV#). Wahb no da fuente.")

add(1, "Qatada (m. 117 H / 735) y al-Suddi (m. 127 H / 745), en al-Tabari", key="QS", specs=["rQt1", "rSd1"],
 title="El voluntario: «¿a quién de vosotros se le echará mi semejanza? Pues lo matarán»; para al-Suddi, «les faltaba un hombre»",
 ref=f"{TAB}, sobre el Corán 4:157, n.º 10781–10783, vol. 9, pp. 370–371",
 ar_ref="تفسير الطبري ٩/٣٧٠–٣٧١، رقم ١٠٧٨١–١٠٧٨٣", site=SH, url=S + "43/5051",
 es=["Nos contó Bishr ibn Muʿadh: nos contó Yazid: nos contó Saʿid, de Qatada, sobre Su palabra «Hemos matado al Mesías, Jesús hijo de María, mensajero de Dios. Pero no lo mataron ni lo crucificaron…» hasta «Dios es poderoso y sabio»: Esos son los enemigos de Dios, los judíos, que conspiraron para matar a Jesús hijo de María, mensajero de Dios, y pretendieron que lo mataron y lo crucificaron. [[a:Y se nos ha contado]] que el profeta de Dios Jesús hijo de María dijo a sus compañeros: «[[k:¿A quién de vosotros se le echará mi semejanza? Pues lo matarán]]». Dijo un hombre de sus compañeros: «Yo, profeta de Dios». [[k:Mataron a aquel hombre, y Dios protegió a Su profeta y lo elevó hacia Sí]].<br>Nos contó al-Hasan ibn Yahya: nos informó ʿAbd al-Razzaq: nos informó Maʿmar, de Qatada, sobre «No lo mataron ni lo crucificaron, sino que se les hizo parecer»: [[k:Se echó su semejanza sobre un hombre de los discípulos, y lo mataron]]. Jesús hijo de María se lo había ofrecido, diciendo: «¿A quién de vosotros se le echa mi semejanza, y tendrá el Paraíso?». Dijo un hombre: «A mí».",
     "Nos contó Muhammad ibn al-Husayn: nos contó Ahmad ibn al-Mufaddal: nos contó Asbat, de al-Suddi: Que los hijos de Israel cercaron a Jesús [[k:y a diecinueve hombres de los discípulos]] en una casa. Dijo Jesús a sus compañeros: «[[k:¿Quién toma mi forma, y lo matan, y tendrá el Paraíso?]]». La tomó un hombre de ellos, y Jesús fue subido al cielo. Cuando salieron los discípulos, vieron que eran diecinueve; les dijeron que Jesús —la paz sea con él— había sido subido al cielo, [[k:y se pusieron a contarlos y les faltaba un hombre del número]], y veían la forma de Jesús entre ellos, y dudaron de él. Y así mataron al hombre creyendo que era Jesús, y lo crucificaron."],
 prueba="Los dos comentaristas más citados de la generación de los Seguidores coinciden en el voluntario, pero no en los detalles: para Qatada se ofrece uno de los discípulos; para al-Suddi eran diecinueve; para Wahb, diecisiete (#Wb2#); para Ibn Abbas, doce, y el voluntario es un joven (#IA1#).",
 ojo="Qatada lo introduce con «se nos ha contado» (en azul): no dice de quién. Al-Suddi tampoco da fuente. Los dos escriben unos 700 años después de los hechos.")

add(1, "Qatada (m. 117 H / 735), en al-Tabari", key="Qt4", specs=["rFr2i", "rFr2"],
 title="Los cuatro doctores después de Jesús: jacobitas, nestorianos, «israelitas»… y los musulmanes, que pierden la guerra",
 ref=f"{TAB}, sobre el Corán 19:37, vol. 18, pp. 197–198",
 ar_ref="تفسير الطبري ١٨/١٩٧–١٩٨", site=SH, url=S + "43/10202",
 es=["Nos contó Bishr: nos contó Yazid: nos contó Saʿid, de Qatada, sobre Su palabra:",
     "«Y discreparon los partidos entre ellos» (19:37): [[a:Se nos ha contado]] que, cuando el hijo de María fue elevado, [[k:los hijos de Israel eligieron a cuatro de sus doctores]]. Dijeron al primero: «¿Qué dices de Jesús?». Dijo: «[[k:Es Dios, que bajó a la tierra]], creó lo que creó, dio vida a lo que dio vida y luego subió al cielo». Le siguieron algunas gentes, [[k:y esos fueron los jacobitas de los cristianos]]. Los otros tres dijeron: «Damos testimonio de que mientes». Dijeron al segundo: «¿Qué dices de Jesús?». Dijo: «Es el hijo de Dios». Le siguieron algunas gentes, [[k:y esos fueron los nestorianos de los cristianos]]. Los otros dos dijeron: «Damos testimonio de que mientes». Dijeron al tercero: «¿Qué dices de Jesús?». Dijo: «Él es dios, su madre es diosa y Dios es dios». Le siguieron algunas gentes, [[k:y esos fueron los «israelitas» de los cristianos]]. Dijo el cuarto: «Doy testimonio de que mientes; es el siervo de Dios y Su mensajero, Su palabra y Su espíritu». Discutieron, y el musulmán dijo: «Os conjuro por Dios: ¿no sabéis que Jesús comía y que Dios no come?». Dijeron: «Sí, por Dios». Dijo: «¿Sabéis que Jesús dormía?». Dijeron: «Sí, por Dios». Así el musulmán los venció en la discusión; y combatieron. [[k:Se nos ha contado que los jacobitas se impusieron aquel día y los musulmanes fueron abatidos]], y Dios reveló sobre ello el Corán: «A los que no creen en los signos de Dios, matan a los profetas sin derecho y matan a los que mandan la justicia entre la gente, anúnciales un castigo doloroso» (3:21)."],
 prueba="Otra versión de los «partidos» después de Jesús, ahora con cuatro grupos: jacobitas, nestorianos, «israelitas» (la trinidad de Dios, Jesús y María) y musulmanes. Los «musulmanes» ganan la discusión pero pierden la guerra.",
 ojo="No cuadra con Ibn Abbas (tres grupos, #IA1#) ni con Ibn Jurayj (#IJ#), que atribuye las doctrinas al revés: para Qatada «Dios bajó a la tierra» es lo que dicen los jacobitas; para Ibn Jurayj, los nestorianos. Y otra vez el anacronismo: ninguna de esas iglesias existía en el siglo I. Qatada dice dos veces «se nos ha contado» (en azul), sin fuente.")

again(1, "al-Suddi (m. 127 H / 745), en al-Tabari", 'H11c', key="H11c",
 prueba="La versión de al-Suddi: los amalecitas matan a los israelitas y se llevan la Torá; los sabios entierran copias en los montes; ʿUzayr la reescribe entera de memoria, con una pluma atada a cada dedo, y al cotejarla con las copias enterradas «la encontraron igual».",
 ojo="Es un relato de al-Suddi que recoge al-Tabari sin opinar. Aquí el enemigo no es Nabucodonosor sino los amalecitas, y la Torá no se quema. El editor de al-Tabari (Shakir, vol. 14, p. 204, n. 1) anota que un punto de este relato «necesita examen en cuanto a su autenticidad y su sentido».")

add(1, "al-Kalbi (m. 146 H / 763), en al-Baghawi (m. 516 H)", key="Kl", specs=["rKl1"],
 title="Nabucodonosor «mató a quien leía la Torá»; ʿUzayr la dicta de memoria y la copia enterrada coincide: «no le faltaba una letra»",
 ref="al-Baghawi, Maʿalim al-tanzil, sobre el Corán 9:30, vol. 4, p. 37 (Dar Tayba)",
 ar_ref="تفسير البغوي ٤/٣٧", site=SH, url=S + "41/1238",
 es=["Y dijo al-Kalbi: Nabucodonosor, cuando venció a los hijos de Israel [[k:y mató de ellos a quien leía la Torá]] —ʿUzayr era entonces pequeño, lo consideró demasiado joven y no lo mató—… Cuando los hijos de Israel volvieron a Jerusalén y no había entre ellos quien leyera la Torá, [[k:Dios envió a ʿUzayr para renovarles la Torá]] y que fuera para ellos un signo después de cien años. Se dice: le vino un ángel con un recipiente con agua, le dio de beber, y la Torá quedó presente en su pecho. Cuando llegó a ellos dijo: «Soy ʿUzayr», y lo desmintieron y dijeron: «Si eres como pretendes, [[k:díctanos la Torá]]», y se la escribió. Luego un hombre dijo: «Mi padre me contó, de mi abuelo, que la Torá fue puesta en una tinaja y enterrada en una viña». Fueron con él hasta sacarla, la cotejaron con lo que ʿUzayr les había escrito [[k:y no encontraron que le faltara una sola letra]], y dijeron: «Dios no ha echado la Torá en el corazón de un hombre sino porque es Su hijo». Entonces dijeron los judíos: «ʿUzayr es hijo de Dios»."],
 prueba="La versión de al-Kalbi, que repiten al-Farraʾ, al-Thaʿlabi y al-Baghawi: Nabucodonosor mata a todos los que sabían leer la Torá; ʿUzayr la dicta de memoria; aparece una copia enterrada y coincide letra por letra.",
 ojo="Al-Kalbi (m. 146 H) es de los transmisores más desacreditados para los críticos del hadiz (lo consideran «abandonado» y lo acusan de mentir), y aquí no da fuente. Y fíjate en la conclusión: en este relato la Torá restituida es idéntica a la antigua, lo contrario de lo que dirán Ibn Hazm (#Z14#) o al-Samawʾal (#Sam#).")

add(1, "Ibn Jurayj (m. 150 H / 767), en al-Tabari", key="IJ", specs=["rFr1"],
 title="«Diqyus, Nestorio y Mar Yaʿqub» discuten el día de la ascensión: nestorianos, «israelitas, los reyes de los cristianos», y musulmanes",
 ref=f"{TAB}, sobre el Corán 19:34–37, vol. 18, p. 195",
 ar_ref="تفسير الطبري ١٨/١٩٥", site=SH, url=S + "43/10199",
 es=["Nos contó al-Qasim: nos contó al-Husayn: me contó Hajjaj, de Ibn Jurayj, sobre Su palabra «sobre el que dudan» (19:34): Dijo: Discreparon. Un grupo dijo: «Es el siervo de Dios y Su profeta», y creyeron en él; otro grupo dijo: «No, es Dios»; y otro dijo: «Es hijo de Dios» —ensalzado sea Dios muy por encima de lo que dicen—. Dijo: Eso es Su palabra «Y discreparon los partidos entre ellos», y la de la sura al-Zujruf. [[k:Dijo: Diqyus, Nestorio y Mar Yaʿqub]]: uno de ellos dijo, cuando Dios elevó a Jesús: «Es Dios»; otro: «el hijo de Dios»; y otro: «la palabra de Dios y Su siervo». Los dos mentirosos dijeron: «Mi doctrina se parece más a la tuya, y la tuya a la mía, que la de este; vamos a combatirlos». Los combatieron y los aplastaron [el texto dice «les hicieron pisar Israel», frase oscura]. Y sacaron de ellos a cuatro hombres: cada pueblo sacó a su sabio, y discutieron sobre Jesús cuando fue elevado. Uno dijo: «[[k:Es Dios, que bajó a la tierra, dio vida a quien dio vida y muerte a quien dio muerte, y luego subió al cielo]]»; [[k:y estos son los nestorianos]]. Los otros dos dijeron: «Mientes». Luego uno de los dos dijo al otro: «Di tú lo que piensas». Dijo: «[[k:Es el tercero de tres: Dios es dios, él es dios y su madre es diosa]]»; [[k:y estos son los «israelitas», los reyes de los cristianos]]. Dijo el cuarto: «Mientes: [[k:es el siervo de Dios y Su mensajero, Su espíritu y Su palabra]]»; y estos son los musulmanes. Cada uno tuvo seguidores según lo que dijo; combatieron, [[k:y [los otros] vencieron a los musulmanes]]."],
 prueba="Ibn Jurayj (m. 150 H) pone nombre a los fundadores: Diqyus (¿Dióscoro?), Nestorio y Mar Yaʿqub (Jacobo), y los sitúa «cuando Dios elevó a Jesús». Los «israelitas», que creen en la trinidad de Dios, Jesús y su madre, son «los reyes de los cristianos».",
 ojo="Los nombres delatan el anacronismo: Nestorio fue patriarca de Constantinopla y lo condenaron en Éfeso (431); Dióscoro de Alejandría fue depuesto en Calcedonia (451); Jacobo Baradeo murió en 578. Ibn Jurayj los pone discutiendo el día de la ascensión. Además atribuye «Dios bajó a la tierra» a los nestorianos, justo lo contrario que Qatada (#Qt4#). No da fuente.")

add(1, "Ibn Ishaq (m. 150 H / 767), en al-Tabari", key="IS", specs=["rIs1a", "rIs1b"],
 title="El sustituto tiene nombre: «un hombre llamado Sergio», según «un hombre que era cristiano y se hizo musulmán»",
 ref=f"{TAB}, sobre el Corán 4:157, n.º 10785, vol. 9, pp. 372–373",
 ar_ref="تفسير الطبري ٩/٣٧٢–٣٧٣، رقم ١٠٧٨٥", site=SH, url=S + "43/5053",
 es=["Dijo Ibn Humayd: dijo Salama: dijo Ibn Ishaq: Y había entre ellos, según me han contado, [[k:un hombre llamado Sergio (Sarjis)]], de modo que eran trece hombres además de Jesús; [[k:los cristianos lo niegan, y es que él fue a quien se hizo parecer a los judíos en lugar de Jesús]]. Dijo: No sé quién es: si es uno de estos doce o era el decimotercero; lo negaron cuando reconocieron ante los judíos la crucifixión de Jesús…",
     "Nos contó Ibn Humayd: nos contó Salama, de Ibn Ishaq: [[k:me contó un hombre que era cristiano y se hizo musulmán]]: que Jesús, cuando le llegó de Dios «Voy a elevarte hacia Mí», dijo: «Discípulos, ¿quién de vosotros quiere ser mi compañero en el Paraíso, a condición de que se le dé mi forma ante esa gente y lo maten en mi lugar?». [[k:Dijo Sergio: «Yo, espíritu de Dios»]]. Dijo: «Siéntate en mi sitio».",
     "Se sentó en él, y Jesús —la bendición de Dios sea con él— fue elevado. Entraron a por él, lo tomaron y lo crucificaron; [[k:él fue al que crucificaron y con el que se les hizo parecer]]. El número de los que habían entrado con Jesús era conocido: los habían visto y contado. Cuando entraron a por él para tomarlo, encontraron a Jesús —según les parecía— y a sus compañeros, y echaron en falta a un hombre del número; ese es aquel sobre el que discreparon. No conocían a Jesús, [[k:hasta que dieron a Judas Iscariote (Yudas Zakariya Yuta) treinta dirhams]] para que se lo señalara. Les dijo: «Cuando entréis, yo lo besaré: el que yo bese es él, tomadlo». Cuando entraron, ya elevado Jesús, vio a Sergio con la forma de Jesús y no dudó de que era Jesús; se inclinó sobre él y lo besó, y lo tomaron y lo crucificaron. Luego Judas se arrepintió de lo que había hecho y se ahorcó con una cuerda hasta matarse; y es maldito entre los cristianos, y había sido uno de los contados entre sus compañeros. [[k:Y algunos cristianos pretenden que Judas Iscariote fue al que se hizo parecer]], y lo crucificaron mientras decía: «¡Yo no soy vuestro hombre! ¡Yo soy el que os lo señaló!». [[a:Y Dios sabe mejor cuál de esas cosas fue]]."],
 prueba="Ibn Ishaq (m. 150 H), el biógrafo del Profeta, pone nombre al sustituto: Sergio, un decimotercer discípulo «que los cristianos niegan». Su fuente, lo dice él mismo, es «un hombre que era cristiano y se hizo musulmán».",
 ojo="La fuente es un converso anónimo, más de 700 años después. Ibn Ishaq no sabe si Sergio era uno de los doce o un decimotercero, recoge que otros dicen que fue Judas y termina con «Dios sabe mejor cuál de esas cosas fue» (en azul). No hay ningún discípulo llamado Sergio en las listas de los Evangelios ni de Hechos.")

add(1, "Sayf ibn ʿUmar (m. c. 180 H / 796), atribuido a Ibn Abbas", key="Sy", specs=["rSy1"],
 title="La leyenda de Pablo: el rey perseguidor que finge convertirse, cambia la alquibla, permite todo alimento… y enseña la Trinidad a «Yaʿqub, Nastur y Malkun»",
 ref="Sayf ibn ʿUmar, Kitab al-ridda wa-l-futuh, n.º 133, pp. 136–139 (ed. Qasim al-Samarrai, Riad: Dar Umayya, 2.ª ed. 1997); texto OCR de archive.org",
 ar_ref="كتاب الردة والفتوح لسيف بن عمر، رقم ١٣٣", site="archive.org (texto OCR sin corregir de la edición impresa)",
 url="https://archive.org/stream/20220829_20220829_1712/ (…)_djvu.txt",
 es=["…de Ibn Abbas, que dijo: Que Jesús —la paz sea con él— llamó a los hijos de Israel y le respondieron los que Dios quiso. Cuando Dios —poderoso y majestuoso— lo elevó, a la gente le agradaron sus palabras y sus compañeros llegaron a setecientas familias. Dijo entonces Pablo —que tenía por sobrenombre Abu Shaʾul, [[k:y era el rey en aquel tiempo]]—: [«Matad a los cristianos»…]",
     "…Y dijo: «[[k:Me salió al encuentro Jesús cuando me volvía de vosotros y me tomó el oído, la vista]] y la razón, y no oí, ni vi, ni razoné; luego me lo destapó, y he dado a Dios, por Dios, el compromiso de entrar en vuestra causa, dedicarme a vosotros [[k:y enseñaros la Torá y sus normas]]». Le creyeron. Dijo: «Construidme una casa», y dijo: «Cubrid el suelo de ceniza». Lo hicieron, se retiró en ella a sus devociones y les enseñó lo que Dios quiso; luego la cerró. Rodearon la casa y dijeron: «Tememos que haya visto algo que le disgusta». La abrió al cabo de un día y dijeron: «¿Has visto algo que te disgusta?». Dijo: «No; pero he tenido una idea que os propongo: si es acertada, tomadla, y si es un error, apartadme de ella». Dijeron: «Dila». Dijo: «¿Habéis visto alguna vez un ganado que salga a pastar si no es desde donde está su dueño? Pues yo he visto que la noche, la mañana, el sol, la luna y las constelaciones vienen de aquí, y lo que viene de ese lado es el lado más digno de que se rece hacia él». Dijeron: «Tienes razón». [[k:Y les cambió la alquibla]]. Después se encerró dos días… y dijo: «Dios os ha sometido lo que hay en la tierra… ¿Por qué unas cosas son lícitas y otras ilícitas? [[k:Desde el mosquito hasta el elefante, todo es lícito]]». Dijeron: «Tienes razón». Y esa fue la segunda.",
     "Dijo: «Opino que no se haga daño a nadie ni se devuelva el golpe: a quien os haga mal, no le correspondáis; [[k:si le abofetean la mejilla, que ofrezca la otra]], y si le quitan parte de la ropa, que le dé el resto». Lo aceptaron [y abandonaron] la guerra santa. Luego se encerró más tiempo… Dijeron: «Dila». Dijo: «Sacad de la casa a la gente, [[k:que no queden más que Yaʿqub, Nastur]], Malkun y el Creyente». Lo hicieron, y dijo: «¿Sabéis de algún humano que haya creado del barro una figura, haya soplado en ella y se haya convertido en un ser vivo? ¿…que haya curado al ciego y al leproso y resucitado a los muertos? ¿…que informara a la gente de lo que comen y de lo que guardan en sus casas?». Dijeron: «No». Dijo: «Pues yo afirmo que Dios —ensalzado sea— se nos manifestó y luego se ocultó». Uno de ellos dijo: «Tienes razón». Otro dijo: «[[k:Él es Dios, y Jesús es Su hijo]]». Y el otro dijo: «No, [[k:sino que es el tercero de tres]]: Jesús el hijo, su padre y su madre». El Creyente se horrorizó y dijo: «¡Dios os maldiga! ¡Ay de vosotros! Por Dios, este no ha buscado otra cosa que vuestra perdición».",
     "…Y la huida de los creyentes de entre ellos fue a la península arábiga; y alcanzaron al Profeta treinta monjes de ellos, que creyeron en él. [[k:Y su ejemplo en esta comunidad es el ejemplo de Ibn Sabaʾ]]."],
 prueba="La versión más antigua y completa de la leyenda de Pablo, y viene atribuida a Ibn Abbas. Pablo es el rey que perseguía a los seguidores de Jesús; finge convertirse («Jesús me salió al encuentro», un eco de Damasco), se encierra y va soltando «revelaciones»: rezar hacia el oriente, todo alimento lícito, poner la otra mejilla y abandonar la guerra santa; y al final enseña a tres discípulos las tres doctrinas. Los creyentes huyen; treinta monjes llegan a conocer al Profeta.",
 ojo="Cuatro cautelas. (1) La cadena está rota en el único manuscrito: solo se lee «de Ibn Abbas, que dijo». (2) Sayf ibn ʿUmar es «débil» o «abandonado» para los críticos del hadiz. (3) La imagen es el texto OCR sin corregir de la edición impresa (archive.org), con letras persas y signos sueltos; para un vídeo conviene la página impresa. (4) Pablo no fue rey: era un fariseo de Tarso, según sus cartas y Hechos; «poner la otra mejilla» es enseñanza de Jesús (Mateo 5:39), no de Pablo; y las tres doctrinas son las de iglesias del siglo V.")
