# -*- coding: utf-8 -*-
# ---------- 5. Siglos IX–XIV H (XV–XX d. C.) ----------
IBR = "Ibn Jaldún, Kitab al-ʿIbar (Tarij Ibn Jaldun), ed. Jalil Shahada (Dar al-Fikr)"
MQK = "al-Maqrizi, al-Mawaʿiz wa-l-iʿtibar bi-dhikr al-jitat wa-l-athar (Dar al-Kutub al-ʿIlmiyya)"
IZ = "Rahmatullah al-Kairanawi, Izhar al-haqq, ed. Muhammad Malkawi (Riad, 1989)"
MN = "Muhammad Rashid Rida, Tafsir al-Manar"
MZ = "Muhammad Abu Zahra, Muhadarat fi l-Nasraniyya"
KHW = "Ibn Jaldún (m. 808 H / 1406)"
MQW = "al-Maqrizi (m. 845 H / 1442)"
KRW = "al-Kairanawi (m. 1308 H / 1891)"
RRW = "Rashid Rida (m. 1354 H / 1935)"
AZW = "Abu Zahra (m. 1394 H / 1974)"

add(5, KHW, key="KH1", specs=["rKH1a", "rKH1b"],
 title="El sustituto, Pedro y Pablo «enviados por Jesús» a Roma, la cruz hallada en tiempos de Claudio… y los Evangelios escritos por los apóstoles",
 ref=f"{IBR}, vol. 2, pp. 173–174", ar_ref="تاريخ ابن خلدون ٢/١٧٣–١٧٤", site=SH, url=S + "12320/991",
 es=["Jesús había avisado a los discípulos de que en su caso se haría parecer a los judíos, [[k:y aquella semejanza fue muerta y crucificada]], y estuvo [allí] siete [días]. Vino su madre llorando junto al madero, vino a ella Jesús y le dijo: «¿Por qué lloras?». Dijo: «Por ti». Dijo: «[[k:Dios me ha elevado y no me ha pasado más que bien; y esto es algo que se les hizo parecer]]».",
     "…Y entró Santiago, hermano de Juan, en Roma, y lo mató el césar Gayo, y encarceló a Simón; luego se libró, fue a Antioquía y volvió a Roma en tiempos del césar Claudio, después de Gayo; lo siguió mucha gente, [[k:y creyó en él una de las mujeres de los césares, y le contó la historia de la cruz]]; ella fue a Jerusalén, [[k:la sacó de debajo del estiércol y la basura, en el lugar de la crucifixión]], la cubrió de seda y oro y la llevó a Roma.",
     "Y en cuanto a Pedro, el mayor de los discípulos, y a Pablo, [[k:a los que Jesús —la bendición de Dios sea con él— envió a Roma]], se quedaron allí estableciendo la religión cristiana; [[k:luego Pedro escribió el Evangelio en la lengua de los romanos y lo atribuyó a su discípulo Marcos]]; y Mateo escribió su Evangelio en hebreo en Jerusalén…",
     "…y Lucas escribió su Evangelio en la lengua de los romanos y lo envió a uno de los grandes de los romanos, [[k:y Juan hijo de Zebedeo escribió su Evangelio en Roma]]. [[k:Luego los apóstoles discípulos se reunieron en Roma y pusieron los cánones legales de su religión]], y los dejaron en manos de Clemente, discípulo de Pedro."],
 prueba="Ibn Jaldún (m. 808 H), el gran historiador, combina el relato islámico del sustituto con la cronología cristiana: Pedro y Pablo «enviados por Jesús» a Roma; Pedro escribe el Evangelio y lo atribuye a Marcos; Mateo, en hebreo; Juan, en Roma; y los apóstoles fijan el canon en Roma.",
 ojo="Ibn Jaldún no acusa aquí a Pablo: lo pone junto a Pedro como enviado de Jesús. Y su relato de la cruz contradice a los demás: aquí la encuentra una mujer de los césares en tiempos de Claudio (siglo I), no Helena en tiempos de Constantino (siglo IV, #IK1#). Los «cánones de los apóstoles» atribuidos a Clemente son una obra del siglo IV.")

add(5, KHW, key="KH2", specs=["rKH2a", "rKH2b"],
 title="La Trinidad, un error de interpretación: «no supieron interpretar» el Evangelio; Nicea: 2.340 obispos, 318 de acuerdo, «la espada y el sello»",
 ref=f"{IBR}, vol. 2, pp. 176–177", ar_ref="تاريخ ابن خلدون ٢/١٧٦–١٧٧", site=SH, url=S + "12320/994",
 es=["…[[k:¡Lejos de Dios, del Mesías y de los discípulos defender eso!]], y es su creencia en la Trinidad. [[k:Les llevaron a ella expresiones literales de las palabras del Mesías en el Evangelio, que no supieron interpretar]] ni entender, como lo que dijo el Mesías cuando lo crucificaron, según pretenden: «Voy a mi Padre y a vuestro Padre»; y: «Haced tal y tal obra buena para que seáis hijos de vuestro Padre que está en el cielo y seáis perfectos, como vuestro Padre que está en el cielo es perfecto»; y se le dijo en el Evangelio: «Tú eres el Hijo único»; y le dijo Simón Pedro: «Tú eres verdaderamente el hijo de Dios». Al afirmar esta paternidad por lo literal de estas palabras, pretendieron que Jesús hijo de María viene de un Padre eterno, y que su unión con María fue la encarnación de una palabra de Él que se mezcló con el cuerpo del Mesías y se revistió de él; el conjunto de la palabra y el cuerpo fue un hijo; y María dio a luz a un Dios eterno, y la muerte y la crucifixión cayeron sobre el cuerpo y la palabra, a los que llaman lo humano y lo divino.",
     "…Y había en Alejandría un patriarca, Alejandro, y en su tiempo estaba Arrio, uno de los obispos, [[k:que sostenía que el Hijo fue creado]] y que creó a las criaturas porque el Padre le delegó la creación; Alejandro le prohibió entrar en la iglesia, declaró que su fe era corrupta y lo escribió a los demás obispos y patriarcas; e hizo lo mismo con otros dos obispos de la opinión de Arrio. Llevaron su caso ante Constantino, que los hizo venir a todos en el año diecinueve de su reinado, y discutieron. Cuando Arrio dijo que el Hijo es creado y que el Padre le delegó la creación, y Alejandro dijo que por la creación mereció la divinidad, a Constantino le gustó lo que decía este y le permitió proclamar la incredulidad de Arrio. Alejandro pidió que se reunieran los cristianos para fijar la creencia de la fe, [[k:y Constantino los reunió: eran dos mil trescientos cuarenta obispos]], en la ciudad de Nicea, y la reunión se llamó concilio de Nicea.",
     "…[[k:Y, tras mucha discrepancia, se pusieron de acuerdo trescientos dieciocho obispos en una sola opinión]]; [[k:Constantino se pasó a su doctrina y les dio su espada y su sello]]; lo bendijeron, [[k:le pusieron cánones de la religión y del reino]], desterraron a Arrio, proclamaron su incredulidad y escribieron la creencia en la que se pusieron de acuerdo los de aquel concilio."],
 prueba="Ibn Jaldún explica la Trinidad como un error de lectura: los cristianos tomaron al pie de la letra expresiones del Evangelio («vuestro Padre», «Hijo único»). Y cuenta Nicea según los cronistas cristianos: 2.340 obispos, 318 de acuerdo, Constantino les da la espada y el sello y ellos le dan «cánones de la religión y del reino».",
 ojo="Aquí no dice que el Evangelio esté alterado: dice que los cristianos no supieron interpretarlo. Sus cifras (2.340) no coinciden con las de al-Masʿudi e Ibn Taymiyya (2.048), y ninguna con las listas antiguas (unos 250). Arrio era presbítero, no obispo. Su fuente para el Credo es el cronista copto Ibn al-ʿAmid y al-Shahrastani, como él mismo dice.")

add(5, KHW, key="KH3", specs=["rKH3a", "rKH3b"],
 title="La doctrina, al vaivén de los emperadores: «una de las dos facciones se imponía cuando el rey era de su religión»",
 ref=f"{IBR}, vol. 2, pp. 178 y 180", ar_ref="تاريخ ابن خلدون ٢/١٧٨ و١٨٠", site=SH, url=S + "12320/996",
 es=["…Después se reunieron los partidarios de Arrio ante Constantino y le hicieron ver con buenos ojos esa doctrina: que los de Nicea habían sido injustos con Arrio y se habían apartado de la verdad al decir que el Padre es igual al Hijo en la sustancia; [[k:y el rey estuvo a punto de aceptárselo]]. Le escribió Cirilo, obispo de Jerusalén, advirtiéndole contra la doctrina de Arrio, y lo aceptó y se echó atrás. [[k:Y la situación de los césares después de Constantino cambió entre tomar el Credo o la doctrina de Arrio]], [[k:y una de las dos facciones se imponía cuando el rey era de su religión]].",
     "Dijo [Ibn al-ʿAmid]: [[k:Y desde el concilio de Calcedonia se dividieron las iglesias y los obispos en jacobitas, melquitas y nestorianos]]: los jacobitas, gente de la doctrina de Dióscoro que hemos explicado; los melquitas, gente del Credo que fijaron los de Nicea y luego los de Calcedonia, y que sigue la mayoría de los cristianos; y los nestorianos, gente del tercer concilio, la mayoría en Oriente. Y melquitas y jacobitas se fueron turnando en la jefatura de las sedes [[k:según a quién quisieran los césares y cuál de las dos doctrinas eligieran]]."],
 prueba="Ibn Jaldún describe cómo la doctrina oficial dependía del emperador de turno: Constantino casi se pasa a los arrianos; sus sucesores alternan entre el Credo y Arrio; y después de Calcedonia melquitas y jacobitas se turnan en las sedes «según a quién quisieran los césares».",
 ojo="El dato es real (Constancio II y Valente fueron arrianos; Teodosio impuso el Credo de Nicea en el 380), y sirve al argumento de que el poder político influyó en la doctrina. Pero también desmonta la idea de que Constantino «impuso» la Trinidad para siempre: la disputa siguió medio siglo. Y sitúa el origen de las tres iglesias en Calcedonia (451), no en el siglo I (#IA1#).")

add(5, MQW, key="MQ1", specs=["rMQ1"],
 title="La Pasión de los Evangelios aplicada «al que se les hizo parecer»; la resurrección, lo que «pretendieron los cristianos»; Mateo, nueve años después",
 ref=f"{MQK}, vol. 4, p. 393", ar_ref="المواعظ والاعتبار للمقريزي ٤/٣٩٣", site=SH, url=S + "11566/1724",
 es=["…[[k:y crucificaron al que se les hizo parecer]], y crucificaron con él a dos ladrones, los clavaron con clavos de hierro, y los soldados se repartieron la ropa del crucificado; la tierra quedó a oscuras tres horas, hasta que el día pareció noche y se vieron las estrellas, y hubo además temblor y terremoto. Luego bajaron al crucificado del madero la mañana del sábado y lo enterraron bajo una roca, en una tumba nueva, y pusieron guardias en la tumba para que sus compañeros no se llevaran al enterrado. [[k:Y pretendieron los cristianos que el enterrado se levantó de su tumba la noche del domingo, de madrugada]], que entró al atardecer de ese día con los discípulos, les habló y les hizo encargos, y que a los cuarenta días de su resurrección subió al cielo mientras los discípulos lo veían.",
     "Y Juan el evangelista fue a Asia y a Éfeso, [[k:y escribió su Evangelio en griego después de que Mateo, Marcos y Lucas escribieran los suyos, y vio que se habían quedado cortos en algunas cosas y habló de ellas]]; y eso fue treinta años después de la elevación del Mesías.",
     "Y Mateo el publicano fue a Palestina, Tiro, Sidón y Bosra, [[k:y escribió su Evangelio en hebreo nueve años después de la elevación del Mesías]], y Juan lo tradujo a la lengua de los romanos."],
 prueba="Al-Maqrizi (m. 845 H), el historiador de Egipto, cuenta la Pasión como la cuentan los Evangelios —los dos ladrones, la oscuridad, la tumba nueva, los guardias—, pero aplicada «al que se les hizo parecer», y da la resurrección como lo que «pretendieron los cristianos». Y fecha los Evangelios: Mateo, nueve años después; Juan, treinta.",
 ojo="Toma casi todo de fuentes cristianas coptas. Y su versión no resuelve nada: si todo lo que cuentan los Evangelios pasó, pero con otro en la cruz, el engaño incluye también el entierro, la tumba vacía y las apariciones. Sus fechas no coinciden con las de Ibn Hazm (#IH3#; Juan, «sesenta y tantos» años después) ni con las de al-Juwayni (#Jw#).")

add(5, MQW, key="MQ2", specs=["rMQ2a", "rMQ2b"],
 title="«Lleva este signo y vencerás»: «el comienzo de alzar la cruz… hasta adorarla»; Nicea: 2.340 obispos, y Constantino da «su espada y su sello» a los 318",
 ref=f"{MQK}, vol. 4, pp. 397–398", ar_ref="المواعظ والاعتبار للمقريزي ٤/٣٩٧–٣٩٨", site=SH, url=S + "11566/1728",
 es=["…[[k:y vio en sueños estrellas en el cielo en forma de cruz]], y una voz del cielo que le decía: «[[k:Lleva este signo y vencerás a tu enemigo]]». Contó su sueño a sus ayudantes, puso la forma de la cruz en sus banderas y estandartes y fue a combatir a Majencio en Roma; lo combatió, venció, se adueñó de Roma y luego puso su capital en Constantinopla. [[k:Y ese fue el comienzo de alzar la cruz y de que apareciera entre la gente: los cristianos la tomaron desde entonces y la veneraron hasta adorarla]]. Constantino honró a los cristianos, entró en su religión en la ciudad de Nicomedia en el duodécimo año de su reinado, y ordenó construir iglesias en todos sus reinos y romper los ídolos.",
     "Y se reunieron seis meses después en la ciudad de Nicea, [[k:y eran dos mil trescientos cuarenta obispos, en desacuerdo sobre el Mesías]].",
     "…[[k:Y entre ellos había quien decía que el Mesías es un hombre creado]], que el comienzo del Hijo es de María, que luego fue escogido y le acompañó la gracia divina por el amor y la voluntad, y que por eso se le llamó hijo de Dios —ensalzado sea por encima de eso—; y con todo, Dios es uno, subsistente; y estos negaban la Palabra y el Espíritu; y esta es la doctrina de Pablo de Samosata, patriarca de Antioquía, y de sus compañeros.",
     "Constantino quedó perplejo ante su discrepancia, se asombró mucho, mandó que los alojaran, les asignó sustento y les ordenó discutir hasta que se le aclarara quién acertaba. Los trescientos dieciocho se mantuvieron en su doctrina y los demás discreparon; [[k:y Constantino se inclinó por la opinión de los más]] y se apartó de las demás, se volvió hacia los trescientos, mandó que les pusieran sillas y los sentó en ellas, [[k:y les entregó su espada y su sello, y les dio poder en todo su reino]]; lo bendijeron [[k:y le compusieron el libro de los cánones de los reyes y de los cánones de la Iglesia]], con lo relativo a los juicios, los tratos y los matrimonios. El presidente de este concilio fue Alejandro, patriarca de Alejandría, con Eustacio, patriarca de Antioquía, y Macario, obispo de Jerusalén; Silvestre, patriarca de Roma, envió a dos sacerdotes, que estuvieron de acuerdo con ellos en excomulgar a Arrio; lo excomulgaron y lo desterraron, y los trescientos dieciocho pusieron el famoso Credo."],
 prueba="Al-Maqrizi da la versión más completa de Constantino y Nicea: la visión de la cruz («lleva este signo y vencerás»), que para él es «el comienzo» de la veneración de la cruz; 2.340 obispos en desacuerdo, entre ellos los que decían que el Mesías es un hombre creado; 318 se mantienen firmes y Constantino les entrega su espada y su sello.",
 ojo="El texto dice que Constantino se inclinó por «la opinión de los más», no por la de una minoría, lo que choca con la idea de que impuso la doctrina de 318 contra 2.000. Pablo de Samosata había sido condenado medio siglo antes (268) y no estuvo en Nicea. Y la cruz como símbolo cristiano es anterior a Constantino (Tertuliano, Minucio Félix).")

add(5, MQW, key="MQ3", specs=["rMQ3"],
 title="Calcedonia: los obispos dan la razón al emperador «por miedo», la emperatriz le arranca dos muelas a Dióscoro… y «quien no diga lo que él dice, que lo maten»",
 ref=f"{MQK}, vol. 4, p. 402", ar_ref="المواعظ والاعتبار للمقريزي ٤/٤٠٢", site=SH, url=S + "11566/1733",
 es=["Y el cuarto concilio de los cristianos fue en la ciudad de Calcedonia, y su causa fue que Dióscoro, patriarca de Alejandría, dijo que el Mesías es una sustancia de dos sustancias, una persona de dos personas, una naturaleza de dos naturalezas y una voluntad de dos voluntades; y la opinión de Marciano, rey de los romanos, y de la gente de su reino, era que son dos sustancias, dos naturalezas, dos voluntades y una sola persona. [[k:Cuando los obispos vieron que esa era la opinión del rey, le tuvieron miedo y le dieron la razón]], salvo Dióscoro y seis obispos…",
     "…Y dijo Pulqueria, esposa del rey Marciano, que estaba sentada frente a él: «Dióscoro, en tiempos de mi madre hubo un hombre de cabeza dura como tú, y lo excomulgaron y lo echaron de su sede» —se refería a Juan Crisóstomo, patriarca de Constantinopla—. Él le dijo: «Ya sabes lo que le pasó a tu madre, cómo la afligió la enfermedad que conoces, hasta que fue al cuerpo de Juan Crisóstomo, pidió perdón y se curó». Ella se enfureció [[k:y le dio un puñetazo que le arrancó dos muelas]], y los hombres se le echaron encima y le arrancaron la mayor parte de la barba; y el rey ordenó excomulgarlo y echarlo de su sede.",
     "[[k:Y desde este concilio los cristianos se dividieron en melquitas, según la doctrina del rey Marciano, y jacobitas, según la opinión de Dióscoro]]; y eso fue en el año 193 de Diocleciano. Y Marciano escribió a todo su reino [[k:que todo el que no dijera lo que él decía fuera muerto]]."],
 prueba="Al-Maqrizi narra Calcedonia (451) como un caso de doctrina impuesta por el poder: los obispos dan la razón al emperador «por miedo»; la emperatriz le arranca dos muelas de un puñetazo a Dióscoro; y el emperador manda matar a quien no piense como él. De ahí la división entre melquitas («los del rey») y jacobitas.",
 ojo="Es la versión copta (contraria a Calcedonia), escrita desde el lado de Dióscoro; la anécdota de las muelas viene de esa tradición polémica. Para el argumento importa otra cosa: sitúa el nacimiento de los jacobitas en el año 451, no el día de la ascensión (#IA1#).")

add(5, KRW, key="KR1", specs=["rKR1a", "rKR1b", "rKR1c"],
 title="Izhar al-haqq: después de Nabucodonosor «no les quedó más que el nombre»; Esdras los reescribió… y «esta Torá no es la que fue inspirada a Moisés»",
 ref=f"{IZ}, vol. 2, pp. 448–450", ar_ref="إظهار الحق للكيرانوي ٢/٤٤٨–٤٥٠", site=SH, url=S + "22721/433",
 es=["Sabe —Dios te guíe— que la mayoría de la gente del Libro dice que el primer y el segundo libro de las Crónicas los compuso Esdras —la paz sea con él— con la ayuda de los mensajeros Ageo y Zacarías; así que en esos dos libros estuvieron de acuerdo los tres profetas. [[k:Y los libros de historia atestiguan que el estado de los libros del Antiguo Testamento antes del suceso de Nabucodonosor era incompleto, y después de su suceso no les quedó más que el nombre]]; [[k:y si Esdras no hubiera vuelto a escribir estos libros, no habrían existido en su tiempo]], cuanto menos en tiempos posteriores. Y esto lo admite también la gente del Libro.",
     "…«[[k:Se quemó la Torá y nadie la conocía, y se dice que Esdras volvió a reunir lo que había en ella con la ayuda del Espíritu Santo]]». Y dijo Clemente de Alejandría: «[[k:Los libros celestiales se perdieron, y Esdras fue inspirado para volver a escribirlos]]». Y dijo Tertuliano: «Lo conocido es que Esdras escribió el conjunto de los libros después de que la gente de Babilonia atacara Jerusalén». Y dijo Teofilacto: «Los libros sagrados desaparecieron por completo y Esdras los volvió a hacer existir por inspiración». Y dijo John Milner, católico, en la página 115 de su libro impreso en Derby en 1842: «[[k:Los sabios están de acuerdo en que el ejemplar original de la Torá, y también los de los libros del Antiguo Testamento, se perdieron a manos del ejército de Nabucodonosor]]; y cuando aparecieron sus copias correctas por medio de Esdras, también esas copias se perdieron en el suceso de Antíoco».",
     "…[[k:que esta Torá que circula ahora no es la Torá que fue inspirada a Moisés]] —la paz sea con él— al principio, sino que, después de desaparecer, la escribió Esdras por inspiración otra vez; si no, Esdras habría recurrido a ella y no la habría contradicho, y no se habría apoyado en hojas incompletas en las que no podía distinguir lo erróneo de lo correcto. Y si dicen que es la misma, pero que también fue copiada de las copias incompletas que tenía, y que al redactarla no pudo distinguir entre ellas, digo: en ese supuesto, [[k:la Torá no es fiable, aunque quien la transmitió sea Esdras]]."],
 prueba="Al-Kairanawi (m. 1308 H / 1891), en Izhar al-haqq, su gran obra contra los misioneros protestantes en la India, renueva la tesis de Esdras con un método nuevo: cita a autores cristianos (Clemente de Alejandría, Tertuliano, Teofilacto, el católico John Milner) que repiten la tradición de que los libros se perdieron y Esdras los reescribió. Su conclusión: la Torá actual no es la que recibió Moisés.",
 ojo="La tradición de que Esdras reescribió la Biblia por inspiración procede de 4 Esdras 14, un apocalipsis judío de hacia el año 100 d. C.; los Padres que cita la toman de ahí. Y los manuscritos del mar Muerto, descubiertos en 1947 (después de al-Kairanawi), muestran que el texto hebreo de los siglos II–I a. C. es prácticamente el de las Biblias medievales.")

add(5, KRW, key="KR2", specs=["rKR2a", "rKR2b"],
 title="Nabucodonosor, Antíoco y Tito: tres destrucciones; en la de Antíoco «desaparecieron todas las copias que había escrito Esdras»",
 ref=f"{IZ}, vol. 2, pp. 607–608", ar_ref="إظهار الحق للكيرانوي ٢/٦٠٧–٦٠٨", site=SH, url=S + "22721/591",
 es=["…Y este es el segundo suceso de Nabucodonosor, [[k:y en este suceso desaparecieron la Torá y todos los libros del Antiguo Testamento]] compuestos antes de él, de la faz del mundo por completo; y esto lo admite también la gente del Libro, como has visto en el testimonio decimosexto del primer objetivo.<br>(Tercera cuestión) [[k:Cuando Esdras —la paz sea con él— volvió a escribir los libros del Antiguo Testamento, según pretenden]], ocurrió otro suceso que se menciona en el capítulo primero del primer libro de los Macabeos así: «Cuando Antíoco, rey de los reyes de los francos [sic], conquistó Jerusalén, [[k:quemó todos los ejemplares de los libros del Antiguo Testamento que consiguió]] de cualquier lugar, después de rasgarlos, y ordenó que quien tuviera un ejemplar de los libros del Antiguo Testamento o cumpliera un rito de la Ley fuera muerto; y se comprobaba cada mes, y se mataba a quien tuviera un ejemplar o cumpliera un rito de la Ley, y se destruía el ejemplar…».",
     "Este suceso fue ciento sesenta y un años antes del nacimiento del Mesías y duró tres años y medio, como se detalla en sus historias y en la de Josefo; [[k:y en este suceso desaparecieron todas las copias que había escrito Esdras]], como has visto en el testimonio decimosexto por las palabras de John Milner, católico: «cuando aparecieron sus copias correctas por medio de Esdras, también esas copias se perdieron en el suceso de Antíoco». Luego dijo John Milner: «No hubo testimonio de la veracidad de estos libros hasta que lo dieron el Mesías y los discípulos». (Digo:) ya has visto lo que vale ese testimonio en la respuesta al segundo sofisma.<br>(Cuarta cuestión) Después de ese suceso cayeron sobre los judíos otros sucesos a manos de los reyes de los francos, [[k:en los que desaparecieron las copias de Esdras y ejemplares sin número]]; entre ellos, el suceso de Tito el romano…"],
 prueba="Al-Kairanawi encadena las catástrofes: Nabucodonosor destruye todos los libros; Esdras los reescribe; Antíoco Epífanes (167 a. C.) quema todos los ejemplares que encuentra (1 Macabeos 1); y luego Tito (70 d. C.). Cada destrucción sería una oportunidad para alterar el texto.",
 ojo="El mismo 1 Macabeos dice que, pese a la persecución, el libro de la Ley siguió en manos de los fieles (1 Mac 1:56–57; 3:48), y los manuscritos del mar Muerto (siglos II–I a. C.) confirman que el texto sobrevivió. Además, cita a Milner diciendo que la garantía de estos libros es el testimonio del Mesías y los discípulos, que los citaban como Escritura; eso va contra su tesis.")

add(5, KRW, key="KR3", specs=["rKR3a", "rKR3b", "rKR3c"],
 title="Diocleciano manda quemar las Escrituras (303): «se abrió la puerta de la alteración»… y «no tienen una cadena continua para ningún libro»",
 ref=f"{IZ}, vol. 2, pp. 614–616", ar_ref="إظهار الحق للكيرانوي ٢/٦١٤–٦١٦", site=SH, url=S + "22721/598",
 es=["Estos hechos, si son ciertos como pretenden, no permiten imaginar que hubiera muchas copias ni que los libros se conservaran como es debido, ni que se corrigieran ni verificaran; [[k:y en tiempos así los alteradores tienen mucho margen para alterar]]; y ya has visto en la respuesta al primer sofisma que hubo muchas sectas innovadoras de cristianos en el primer siglo, y que alteraban.<br>(Octava cuestión) [[k:Diocleciano quiso borrar sus libros sagrados de la faz del mundo]] y se esforzó en ello, y ordenó en el año 303 [[k:destruir las iglesias, quemar los libros]] y que los cristianos no se reunieran para el culto; se destruyeron las iglesias y se quemó con gran empeño todo libro que conseguía, y a quien se negaba o se sospechaba que había escondido un libro se le torturaba.",
     "…[[a:Y no digo que todas las copias desaparecieran de la faz del mundo por su destrucción]], pero no cabe duda de que disminuyeron mucho y se perdieron muchísimas copias valiosas y correctas, porque los cristianos y sus libros eran en su reino más de diez veces lo que eran en otras partes; [[k:y se abrió la puerta de la alteración]], y no sería extraño que algunos libros desaparecieran del todo y que lo que existe con su nombre después sea falso e inventado.",
     "Así que no es improbable que algunos libros del Nuevo Testamento desaparecieran con el suceso de Diocleciano y con los de los demás soberanos mencionados, y que lo que existe con su nombre sea inventado, como has oído sobre el comentario de Tichen [?]; y el empeño en inventar algunos libros del Nuevo Testamento era para ellos más importante que inventar ese comentario, y el dicho aceptado entre ellos que se mencionó en la tercera guía aprobaba y recomendaba esa invención. Y por los sucesos de estas ocho cuestiones [[k:se perdieron las cadenas de transmisión continuas de sus libros]], [[k:y no tienen una cadena continua para ningún libro del Antiguo ni del Nuevo Testamento]], ni los judíos ni los cristianos."],
 prueba="El argumento final de al-Kairanawi: Diocleciano mandó en el año 303 quemar las Escrituras (lo cuenta Eusebio, que lo vio); «se abrió la puerta de la alteración»; y, con todas esas catástrofes, ni judíos ni cristianos tienen «una cadena de transmisión continua» (isnad) para ningún libro de la Biblia.",
 ojo="Él mismo reconoce que no desaparecieron todas las copias (en azul). Y hoy hay papiros del Nuevo Testamento anteriores al 303 —el P52 (hacia 125–150), el P66 y el P75 (hacia el 200)— que coinciden con los grandes códices posteriores (Sinaítico y Vaticano): la persecución no cambió el texto. El isnad es el criterio del hadiz; los manuscritos son otra forma, más directa, de comprobar la transmisión.")

add(5, RRW, key="RR1", specs=["rRR1a", "rRR1b"],
 title="Tafsir al-Manar: la cruz, «una fábula de los paganos» impuesta «por la influencia del rey Constantino»; y Pablo, «el peor enemigo del Mesías», fundador de la doctrina",
 ref=f"{MN}, vol. 6, pp. 26 y 45 (sobre el Corán 4:157)", ar_ref="تفسير المنار ٦/٢٦ و٦/٤٥", site=SH, url=S + "12304/1904",
 es=["¿No son mejores y más útiles [estas enseñanzas islámicas] que fiarse de [[k:esa historia de la cruz, de la que se transmite algo parecido en las fábulas de los paganos]], que no la cree una mente independiente ni la acepta un corazón sano, contraria a las leyes de la naturaleza y al orden de la creación, que corrompió las mentes y las costumbres en los reinos de la cruz [[k:desde que se extendió en ellos por la influencia del rey Constantino, el de la cruz]], hasta que Europa se liberó de la esclavitud de la Iglesia con la luz de la ciencia y la independencia que le llegaron de los países del islam?",
     "El resumen de estas investigaciones es que [[k:la historia de la crucifixión no tiene una cadena continua hasta las personas de las que se transmite]], y que esas personas no son conocidas con certeza, como se sabe por la Enciclopedia francesa y otros libros escritos por los sabios libres de Europa; y que lo que se saca del conjunto de esas narraciones sin cadena es que [[k:el primero que puso esta creencia cristiana hoy conocida fue Pablo el judío, que había sido el peor enemigo del Mesías]] —la paz sea con él— y el más feroz adversario de sus seguidores; luego vio que no podía dañarlos ni corromper su causa sino entrando entre ellos, y lo hizo."],
 prueba="Rashid Rida (m. 1354 H / 1935), discípulo de Muhammad ʿAbduh, en el Tafsir al-Manar: la cruz sería un mito de tipo pagano que se impuso «por la influencia del rey Constantino»; la crucifixión no tiene «cadena continua»; y Pablo, «el peor enemigo del Mesías», entró entre los cristianos para corromperlos. Se apoya en «la Enciclopedia francesa» y en «los sabios libres de Europa».",
 ojo="Cambia la fuente, no la tesis: donde antes había rumores de rabinos (#IH2#), ahora hay crítica europea del siglo XIX, en parte superada (la escuela que veía en Jesús un mito pagano). Y la crucifixión de Jesús es de los hechos mejor documentados de la Antigüedad, también fuera de los Evangelios (Tácito, Anales 15.44; Josefo, Antigüedades 18.63).")

add(5, RRW, key="RR2", specs=["rRR2a", "rRR2b"],
 title="«Estos cuatro evangelios no aparecieron hasta tres siglos después del Mesías», con Constantino; y el «Evangelio de Bernabé» contra Pablo",
 ref=f"{MN}, vol. 6, pp. 238 y 241 (sobre el Corán 5:14)", ar_ref="تفسير المنار ٦/٢٣٨ و٦/٢٤١", site=SH, url=S + "12304/2116",
 es=["Y la causa de ello es [[k:que el Mesías —la paz sea con él— no escribió lo que les recordó]] de exhortaciones, del monoteísmo, de la glorificación de Dios y de la guía para adorarlo; los que lo siguieron eran gente sencilla, y los mejores de ellos, sus discípulos, eran pescadores; los judíos los persiguieron con dureza, y no tuvieron una organización con fuerza y saber que pusiera por escrito y conservara lo que habían memorizado del Evangelio del Mesías. Por su historia y sus libros sagrados se ve que mucha gente difundía en su época enseñanzas falsas sobre el Mesías, y algunos escribieron sobre ello, hasta el punto de que los que escribieron libros llamados evangelios son muchísimos; [[k:y estos cuatro evangelios que hoy tienen por válidos no aparecieron hasta tres siglos después del Mesías]], cuando los cristianos tuvieron un Estado [[k:con la entrada del rey Constantino en el cristianismo, y cuando él lo hizo entrar en una nueva fase de paganismo]]. Estos evangelios son una historia incompleta del Mesías, contradictorios, de origen y fecha desconocidos; incluso discreparon sobre sus autores y las lenguas en que los escribieron. Ya explicamos al comienzo de la sura de la familia de ʿImran la realidad del Evangelio del Mesías, y que estos libros solo contienen un poco de él, como nuestra biografía del Profeta contiene un poco del Corán y del hadiz; y ese poco del Evangelio lo ha alcanzado la contradicción y la alteración.",
     "…[[k:Y Bernabé dice en la introducción de su evangelio que Pablo era de los que contradijeron al Mesías en su enseñanza]]. Y no hay duda de que Bernabé merece más crédito que Pablo, porque recibió directamente del Mesías, mientras que Pablo era enemigo del Mesías y de los cristianos, y si Bernabé no lo hubiera presentado a los apóstoles no se habrían fiado de su pretendido arrepentimiento; pero los cristianos rechazaron el evangelio de Bernabé, lleno de monoteísmo, de sabiduría y de virtud, y prefirieron las cartas de Pablo y los evangelios de sus discípulos Lucas y Marcos, y también el de Juan, como han demostrado algunos sabios de Europa; [[k:porque las enseñanzas de Pablo estaban más cerca de las creencias paganas de los romanos]], y fueron ellos quienes las prefirieron y rechazaron lo demás, pues tenían el poder en el cristianismo, y fueron ellos quienes le dieron esta forma."],
 prueba="Rashid Rida sitúa el origen de los Evangelios actuales en Constantino: «no aparecieron hasta tres siglos después del Mesías», con la conversión del emperador y «una nueva fase de paganismo». Y apoya la acusación contra Pablo en el «Evangelio de Bernabé», que él mismo publicó traducido al árabe en 1908.",
 ojo="Las dos afirmaciones son falsas. Los cuatro Evangelios están citados y nombrados mucho antes de Constantino (Ireneo, hacia el 180, habla ya de «cuatro Evangelios»), y hay papiros suyos del siglo II (P52, P66, P75). Y el «Evangelio de Bernabé» es una obra tardía: sus manuscritos más antiguos son de finales del siglo XVI, contiene errores medievales (el jubileo cada cien años, el vino en toneles) y no tiene nada que ver con el Bernabé de Hechos.")

add(5, AZW, key="AZ1", specs=["rAZ1"],
 title="«Pablo, el padre de lo asombroso»: de perseguidor a «mensajero»; y «el verdadero fundador del cristianismo actual es Pablo»",
 ref=f"{MZ}, p. 75", ar_ref="محاضرات في النصرانية لأبي زهرة ص ٧٥", site=SH, url=S + "2280/74",
 es=["…sino que [[k:lo asombroso del todo es que una persona pase de la incredulidad absoluta en una religión a ser mensajero en la religión en la que no creía]], a la que se oponía y combatía; eso no tiene precedente ni parecido, y nunca se ha conocido en profetas ni mensajeros. Esta es la Torá de los judíos y los libros del Antiguo Testamento, en los que creen los cristianos: ¿nos mencionan un mensajero enviado sin que en su vida anterior hubiera disposición a recibir la revelación…? Pero Pablo, el padre de lo asombroso, consiguió vencer ese asombro en su época, imponerse a los cristianos después de él y hacerles olvidar la razón cuando estudian sus palabras y enseñanzas. Pero la razón atraviesa con su luz los velos…, y por eso hubo en los siglos cristianos quienes discutieron con fuerza las palabras de Pablo, negándolas; y citamos las palabras del sacerdote ʿAbd al-Ahad: «Pablo venera y glorifica a un hombre llamado Jesús que fue muerto, murió y volvió a vivir, nada más; y quince cartas del Nuevo Testamento llevan el nombre de ese apóstol; así que no hay lugar a la duda si digo [[k:que el verdadero fundador del cristianismo actual es Pablo]]: Saulo, el joven de Tarso, de la tribu de Benjamín, de la escuela de los fariseos, discípulo de uno de los sabios de su tiempo, miembro del Sanedrín, llamado Gamaliel…, que se esforzaba en borrar el nombre de Jesús y de sus seguidores de la tierra, y que vio a su enemigo, el Nazareno, en el cielo, brillando entre las luces, al mediodía, ante Damasco; se convirtió y se llamó Pablo; [[k:y él es quien puso los cimientos del jesusismo]]»."],
 prueba="Muhammad Abu Zahra (m. 1394 H / 1974), profesor de al-Azhar, en sus Conferencias sobre el cristianismo: Pablo, «el padre de lo asombroso», pasó de perseguidor a «mensajero», algo sin precedentes; y cita a ʿAbd al-Ahad Dawud, un sacerdote caldeo convertido al islam: «el verdadero fundador del cristianismo actual es Pablo».",
 ojo="Abu Zahra ya no cuenta la leyenda medieval (soborno, suicidio, tres discípulos): toma los datos de Hechos y de la crítica moderna, y su argumento es de verosimilitud. Pero las conversiones súbitas de enemigos tienen paralelos en la propia historia islámica: ʿUmar ibn al-Jattab salió a matar al Profeta el día en que se convirtió.")

add(5, AZW, key="AZ2", specs=["rAZ2a", "rAZ2b", "rAZ2c", "rAZ2d"],
 title="Nicea según Abu Zahra: Constantino «se inclinó por la opinión de Pablo», 318 contra 1.700, la espada «y el temor a los gobernantes»… y ni siquiera estaba bautizado",
 ref=f"{MZ}, pp. 125–128", ar_ref="محاضرات في النصرانية لأبي زهرة ص ١٢٥–١٢٨", site=SH, url=S + "2280/124",
 es=["[Título:] La postura de Constantino ante los que discutían. Se reunieron aquellos que discrepaban, y Constantino oyó la explicación de cada grupo por sus representantes; se asombró mucho de lo que vio y oyó, les ordenó discutir para ver con quién estaba la religión verdadera y dejó una casa para la discusión; [[k:pero al final se inclinó por la opinión de Pablo]] y celebró una sesión especial para los obispos que representaban esa opinión, que eran trescientos dieciocho. [Título:] [[k:Su inclinación por la opinión de los que divinizaban al Mesías, aunque no eran la mayoría]]. Y dice sobre ello Ibn al-Bitriq: «El rey hizo para los trescientos dieciocho obispos una gran sesión especial, se sentó en medio de ellos, tomó su sello, su espada y su cetro, se los entregó y les dijo: Hoy os doy poder sobre mi reino…».",
     "Así que el concilio decidió la divinidad del Mesías: que es de la sustancia de Dios, eterno con Su eternidad, sin cambio ni transformación; [[k:y esa creencia se impuso a todos los cristianos, respaldada por el poder de Constantino]], maldiciendo a todo el que dijera otra cosa; los que la impusieron fueron 318 obispos, [[k:y les contradecían en ello unos mil setecientos obispos]], aunque no estuvieran de acuerdo entre ellos en una sola doctrina.",
     "…y porque los narradores dicen que Arrio, cuando se reunió con ellos y les expuso su doctrina, [[k:se sumaron a su opinión más de setecientos obispos]].",
     "[[k:Y parece que el bastón del poder y el temor al rey tuvieron parte en formar la opinión de los que sostuvieron la divinidad del Mesías]]: se cuenta que aquellos 318 no estaban todos de acuerdo en la divinidad del Mesías, pero bajo la tentación del poder que ejerció Constantino al darles las insignias de su reino, se pusieron de acuerdo; el amor al poder los llevó a seguir el deseo de Constantino, y firmaron aquella decisión bajo la presión del miedo o del deseo, o de ambos. Y así decidieron la divinidad del Mesías, [[k:y obligaron a la gente a ella con la fuerza de la espada y el temor a los gobernantes]].",
     "…Pero los sabios se impusieron sobre sus hermanos cristianos cuando Constantino les dio su sello, su espada y su cetro, [[k:y así contradijeron al Mesías —la paz sea con él— para obedecer a Constantino]].",
     "Dice el historiador Eusebio, cuyas palabras santifica la Iglesia y al que llama el príncipe de los historiadores: «[[k:Constantino fue bautizado cuando estaba postrado en el lecho]], y quien lo bautizó fue el propio historiador, que era amigo suyo». Y el bautismo es la declaración de entrar en el cristianismo; [[k:así que Constantino no era cristiano cuando se celebró ese concilio]], y no tenía derecho a juzgar a favor de unos; y podemos decir que tenía en ello un interés particular: acercarlo a su paganismo, o al menos, cuando prefirió la opinión de un grupo sobre otro, prefería la que estaba más cerca de su paganismo; sea lo uno o lo otro, [[k:prefirió lo que estaba más cerca del paganismo, por su paganismo]]."],
 prueba="Abu Zahra construye la versión moderna más influyente de Nicea, a partir de Ibn al-Bitriq: Constantino «se inclinó por la opinión de Pablo», que no era la de la mayoría; 318 contra unos 1.700; Arrio tenía «más de setecientos»; los 318 cedieron a la tentación del poder; y Constantino, que ni siquiera estaba bautizado, eligió la doctrina «más cercana a su paganismo».",
 ojo="Todas las cifras vienen de un cronista del siglo X (Ibn al-Bitriq, #IT3#), no de los historiadores del siglo IV, que hablan de unos 250–300 obispos de los que solo dos no firmaron. Abu Zahra confunde a los dos Eusebios: el historiador (Eusebio de Cesarea) no bautizó a Constantino; lo bautizó Eusebio de Nicomedia, filoarriano. Y si Constantino hubiera elegido lo «más cercano al paganismo», habría elegido a Arrio, como hicieron él al final de su vida y su hijo.")
