# -*- coding: utf-8 -*-
# ---------- 2. Siglos III–IV H (IX–X d. C.) ----------
KOS = "ketabonline.com (copia de la Maktaba Shamila; paginación automática, no coincide con la edición impresa)"
TT = "al-Tabari, Tarikh al-rusul wa-l-muluk, ed. Abu l-Fadl Ibrahim (Dar al-Maʿarif)"

add(2, "al-Farraʾ (m. 207 H / 822)", key="Fa", specs=["rFa1", "rFa2"],
 title="«Nabucodonosor mató a todo el que sabía leer la Torá»… y «un hombre malvado entró entre los cristianos»: «Él es Él», «es Su hijo», «es el tercero de tres»",
 ref="al-Farraʾ, Maʿani al-Qurʾan, sobre el Corán 9:30, vol. 1, pp. 432–433 (ed. al-Najati, al-Najjar y al-Shalabi)",
 ar_ref="معاني القرآن للفراء ١/٤٣٢–٤٣٣", site=SH, url=S + "23634/445",
 es=["Y la causa de que los judíos dijeran «ʿUzayr es hijo de Dios» fue [[k:que Nabucodonosor mató a todo el que sabía leer la Torá]]; le trajeron a ʿUzayr, lo consideró demasiado joven y lo dejó. Cuando Dios lo resucitó, fueron a él los judíos [[k:y les dictó la Torá de memoria]]. Luego un hombre de los judíos dijo: «Mi padre contó que la Torá está enterrada en un huerto suyo»; la sacaron y la cotejaron con lo que ʿUzayr había dictado, [[k:y no le faltaba una letra]]. Y dijeron los judíos: «Dios no ha reunido la Torá en el pecho de ʿUzayr, siendo un muchacho, sino porque es Su hijo» —ensalzado sea Dios muy por encima de lo que dicen—.",
     "Y Su palabra: «Y dijeron los cristianos: el Mesías es hijo de Dios» (9:30). [[a:Y se cuenta]] [[k:que un hombre entró entre los cristianos, y era malvado y perverso, y los confundió]]; [[k:y dijo: «Él es Él». Y dijo: «Es Su hijo». Y dijo: «Es el tercero de tres»]]."],
 prueba="Al-Farraʾ (m. 207 H), gramático de Kufa, en su comentario filológico del Corán: repite la versión de al-Kalbi sobre ʿUzayr y recoge el germen de la leyenda de Pablo, sin nombre: un hombre malvado que se mete entre los cristianos y enseña las tres doctrinas.",
 ojo="«Se cuenta» (en azul): sin fuente ni nombre. Comparada con la de Sayf (#Sy#), aquí no hay ni nombre ni detalles; al-Thaʿlabi (#Tl#) la contará entera con el nombre de Pablo.")

again(2, "al-Jahiz (m. 255 H / 869)", 'H10a', key="Jh",
 ojo="En el texto conservado no usa «tergiversar» ni «cambiar» referido a las Escrituras: de la Torá dice que es verdad y culpa a la mala interpretación y a la mala traducción. Para los Evangelios no cuenta ninguna historia de corrupción: le basta con que sean obra de cuatro hombres falibles. Página 3/334: https://shamela.ws/book/10428/1060")

add(2, "Ibn Qutayba (m. 276 H / 889)", key="Qu", specs=["rQu1a", "rQu1b"],
 title="Jeremías encarcelado, Nabucodonosor «mató, crucificó y quemó»… y ʿUzayr «restableció la Torá después de que fue quemada»",
 ref="Ibn Qutayba, al-Maʿarif, pp. 47 y 50 (ed. Tharwat ʿUkasha, El Cairo, 2.ª ed. 1992)",
 ar_ref="المعارف لابن قتيبة ص ٤٧ و٥٠", site=SH, url=S + "12129/169",
 es=["Luego volvieron a innovar, y Dios envió al profeta Jeremías para anunciarles la ira de Dios contra ellos; se levantó entre ellos con la revelación de Dios, [[k:y lo golpearon, lo encadenaron y lo encarcelaron]]. Entonces Dios envió a Nabucodonosor, y esa es la otra vez que Dios —poderoso y majestuoso— mencionó, diciendo: «Y cuando llegue la promesa de la segunda, para que os afrenten el rostro, entren en el Templo como entraron la primera vez y destruyan por completo lo que conquistaron» (17:7). [[k:Y mató de ellos, crucificó, quemó y mutiló, y vendió a sus hijos y a sus mujeres]], e hizo con ellos todo tipo de escarmiento.",
     "Y en cuanto a ʿUzayr, [[k:restableció para los hijos de Israel la Torá, después de que fue quemada]] —y la reconocían—, cuando volvió a Siria. [[k:Y un grupo de los judíos dijo: «Es hijo de Dios»]]. Y es el que más insistió en preguntar a Dios sobre el destino, [[k:y Dios borró su nombre de entre los profetas]], así que no se le menciona entre ellos; y es un mensajero."],
 prueba="Ibn Qutayba (m. 276 H), en su manual de historia, da por hecho que la Torá fue quemada y que ʿUzayr la restableció, y que los judíos «la reconocían».",
 ojo="No da fuente: es un resumen, sobre todo de Wahb. Y el pasaje clave tiene variantes en los manuscritos: en algunos se lee «no la reconocían» (nota [1] del editor), que invierte el sentido.")

add(2, "al-Yaʿqubi (m. c. 292 H / 905)", key="Yq1", specs=["rYq1"],
 title="Otra versión: Nabucodonosor enterró la Torá en un pozo y Zorobabel la sacó «tal como estaba, sin quemar»",
 ref="al-Yaʿqubi, Tarikh, vol. 1 (apartado «Roboam hijo de Salomón y los reyes posteriores»), p. 25 de ketabonline",
 ar_ref="تاريخ اليعقوبي ١، رحبعم بن سليمان والملوك بعده", site=KOS, url="https://ketabonline.com/ar/books/18614/read?part=1&page=25",
 es=["Los hijos de Israel siguieron cautivos en manos de Nabucodonosor hasta que se casó con una mujer de ellos llamada Malhat, hermana de Zorobabel, hija de Salatiel, y ella le pidió que devolviera a su pueblo a su país. Cuando los hijos de Israel volvieron a su país, pusieron como rey a Zorobabel, hijo de Salatiel, que construyó la ciudad de Jerusalén y el Templo, y estuvo construyéndolo cuarenta y seis años. En su tiempo Dios transformó a Nabucodonosor en una bestia hembra, y fue pasando por distintas especies de animales durante siete años; luego se dice que se arrepintió ante Dios —poderoso y majestuoso—, que lo devolvió a la forma humana, y luego murió.<br>[[k:Y Zorobabel fue quien sacó la Torá y los libros de los profetas del pozo en el que los había enterrado Nabucodonosor]], [[k:y los encontró tal como estaban, sin quemar]]; [[k:y volvió a copiar la Torá]] y los libros de los profetas, sus normas y sus leyes, y fue el primero que escribió estos libros."],
 prueba="Una versión muy distinta: la Torá ni se quemó ni se olvidó. Nabucodonosor la enterró en un pozo, y Zorobabel (no Esdras) la sacó «tal como estaba, sin quemar» y la volvió a copiar.",
 ojo="No da fuente. Contradice a Wahb, Ibn Qutayba e Ibn Hazm (la Torá quemada) y a Ibn Abbas (la Torá olvidada). El texto procede de ketabonline, con paginación automática que no coincide con la edición impresa.")

add(2, "al-Yaʿqubi (m. c. 292 H / 905)", key="Yq2", specs=["rYq2a", "rYq2b"],
 title="«Esto es lo que dicen los del Evangelio, y discrepan en todo»; y Pablo, el perseguidor convertido en Damasco, «la cabeza» de los discípulos",
 ref="al-Yaʿqubi, Tarikh, vol. 1, pp. 30–31 de ketabonline (resumen de los Evangelios y de Hechos)",
 ar_ref="تاريخ اليعقوبي ١، خبر المسيح والحواريين", site=KOS, url="https://ketabonline.com/ar/books/18614/read?part=1&page=30",
 es=["…Y le trajeron un trozo de pescado, y comió, y les dijo: «Si creéis en mí y hacéis lo que yo hago, no pondréis la mano sobre un enfermo sin que se cure, y la muerte no le dañará». Luego se elevó de ellos, y tenía treinta y tres años.<br>[[k:Esto es lo que dicen los del Evangelio, y discrepan en todos los sentidos]]. Dijo Dios —poderoso y majestuoso—: «[[k:No lo mataron ni lo crucificaron, sino que se les hizo parecer]]; y los que discrepan sobre él están en duda; no tienen conocimiento de ello, solo siguen conjeturas; y no lo mataron con certeza, sino que Dios lo elevó hacia Sí» (4:157–158).",
     "[[k:Y Pablo era el más duro de todos contra ellos]] y el que más los perseguía: mataba a los que podía y los buscaba por todas partes. Salió hacia Damasco para reunir a unos que había allí, y oyó una voz que lo llamaba: «[[k:Pablo, ¿cuánto me vas a perseguir?]]». Se asustó hasta perder la vista; luego vino Ananías, lo bendijo, se fue, y sanó su ojo; y empezó a levantarse en las iglesias recordando al Mesías y santificándolo. Los judíos quisieron matarlo y huyó de ellos, y se puso con los discípulos a llamar a la gente, hablando como ellos hablaban y mostrando desapego del mundo, [[k:hasta que todos los discípulos lo pusieron por delante de sí mismos y lo hicieron su cabeza]]. Y se levantaba a hablar, recordaba la historia de los hijos de Israel y de los profetas, y la del Mesías, y decía: «[[k:Vayámonos a las naciones]], como dijo Dios al Mesías: te he puesto como luz de las naciones…». Cada uno de ellos habló según su opinión, y dijeron: «Hay que guardar la Ley, y enviar a cada país a quien llame a esta religión, prohibiéndoles los sacrificios a los ídolos, la fornicación y comer sangre»."],
 prueba="Al-Yaʿqubi (m. c. 292 H) resume los Evangelios y Hechos con bastante fidelidad, sin hablar de corrupción. Su único juicio es que «discrepan en todos los sentidos», y lo zanja con el Corán 4:157. Y cuenta la conversión de Pablo en Damasco como la cuenta Hechos 9: ni rastro de la leyenda del Pablo traidor.",
 ojo="Exagera al decir que discrepan «en todos los sentidos»: los cuatro relatos de la Pasión coinciden en lo esencial (arresto, juicio, crucifixión, sepultura, tumba vacía). Y dice que Pablo pasó a ser «la cabeza» de todos los discípulos, cosa que Hechos no dice. Texto de ketabonline, paginación automática.")

add(2, "al-Yaʿqubi (m. c. 292 H / 905)", key="Yq3", specs=["rYq3"],
 title="Constantino, el sueño de las lanzas con cruces y Nicea: trece doctrinas sobre Jesús, una de ellas «un profeta entre los profetas»",
 ref="al-Yaʿqubi, Tarikh, vol. 1 (apartado «Los reyes cristianos de los romanos»), p. 60 de ketabonline",
 ar_ref="تاريخ اليعقوبي ١، ملوك الروم المتنصرة", site=KOS, url="https://ketabonline.com/ar/books/18614/read?part=1&page=60",
 es=["El primero de los reyes de los romanos que pasó de la doctrina griega al cristianismo fue Constantino. La causa fue que estaba en guerra con un pueblo, [[k:y vio en sueños como si bajaran del cielo lanzas con cruces encima]]; al amanecer puso cruces en sus lanzas, combatió y venció, y esa fue la causa de que se hiciera cristiano. Se dedicó a la religión cristiana, construyó iglesias y reunió a los obispos de cada país para establecer la religión cristiana; fue su primera reunión, [[k:y se reunieron en Nicea trescientos dieciocho obispos]] y cuatro patriarcas: el de Alejandría, el de Roma, el de Antioquía y el de Constantinopla.<br>La causa de que Constantino los reuniera fue que, cuando se hizo cristiano y el cristianismo entró en su corazón, quiso conocerlo a fondo; contó las doctrinas de sus fieles [[k:y encontró trece doctrinas]]: la de quien decía que el Mesías y su madre eran dos dioses; la de quien decía que procede del Padre como una llama que se separa de otra sin que la primera disminuya; la de quien afirmaba su divinidad; la de quien afirmaba que era siervo; la de quien decía que su cuerpo era una apariencia, «como Mateo y sus compañeros» [sic]; la de quien decía que es la Palabra; la de quien decía que es el Hijo; la de quien decía que es un espíritu eterno; la de quien decía que es hijo de José; [[k:la de quien decía que es un profeta entre los profetas]]; y la de quien decía que es divino y humano. Constantino reunió a trescientos dieciocho obispos y cuatro patriarcas, y en aquel tiempo no había otros.<br>El patriarca de Alejandría decía que el Mesías es divinizado y creado; cuando se reunieron discutieron con él, y la doctrina de todos coincidió en que el Mesías nació del Padre antes de la existencia de las criaturas y es de la naturaleza del Padre; [[k:y no mencionaron al Espíritu Santo, ni lo afirmaron creador ni criatura]]; pero acordaron que el Padre es Dios y el Hijo es Dios de Él."],
 prueba="El relato de Nicea de un historiador musulmán del siglo III H: Constantino se convierte por un sueño, encuentra trece doctrinas sobre Jesús —entre ellas, que era «un profeta entre los profetas»— y reúne a 318 obispos, que definen que el Hijo es «de la naturaleza del Padre».",
 ojo="Errores históricos: quien decía que el Mesías era «creado» no era el patriarca de Alejandría, sino Arrio, un presbítero de Alejandría (el patriarca, Alejandro, encabezó la condena); Constantinopla ni siquiera existía en 325 (se fundó en 330); y «como Mateo y sus compañeros» parece una errata del texto. Al-Yaʿqubi no dice que Nicea cambiara los Evangelios. Texto de ketabonline, paginación automática.")

add(2, "al-Tabari (m. 310 H / 923), relato de Ibn Ishaq", key="Tb1", specs=["rTb1a", "rTb1b"],
 title="Después de la elevación: los apóstoles por el mundo (Pablo, «de los seguidores, no de los discípulos»), y el rey de los romanos que baja a Sergio de la cruz",
 ref=f"{TT}, vol. 1, pp. 603–604 (relato de Ibn Ishaq)",
 ar_ref="تاريخ الطبري ١/٦٠٣–٦٠٤", site=SH, url=S + "9783/600",
 es=["…Luego Dios lo elevó hacia Sí, [[k:lo vistió de plumas, lo cubrió de luz]] y le quitó el placer de comer y beber; y voló con los ángeles, y está con ellos alrededor del Trono: fue humano y ángel, celeste y terrestre. Y los discípulos se dispersaron adonde él les mandó; y esa noche en que bajó es la noche en que los cristianos queman incienso. Entre los discípulos y los seguidores que quedaron en la tierra después de ellos, fueron enviados: [[k:Pedro el discípulo, y con él Pablo —que era de los seguidores, y no de los discípulos—, a Roma]]; Andrés y Mateo a la tierra cuyos habitantes comen gente —que, según creemos, es la de los negros—; Tomás a la tierra de Babilonia, en el oriente; Felipe a Cirene y Cartago, que es África; Juan a Éfeso, la aldea de los jóvenes de la cueva; Santiago a Jerusalén, que es Ilia, Bayt al-Maqdis; Bartolomé a Arabia, que es la tierra del Hiyaz; Simón a la tierra de los bereberes, más acá de África; y Judas —que no era de los discípulos— a Ariyubus, puesto en lugar de Judas Iscariote cuando hizo lo que hizo.",
     "Dijo: Luego atacaron al resto de los discípulos, los exponían al sol, los torturaban y los paseaban. [[k:Se enteró de ello el rey de los romanos]] —estaban bajo su mando, y era idólatra—, y le dijeron: «Había un hombre entre esa gente de los hijos de Israel que tienes bajo tu mando, al que atacaron y mataron; les decía que era el mensajero de Dios, les mostró maravillas, resucitó a sus muertos, curó sus enfermedades, les creó de barro algo con forma de pájaro, sopló en ello y fue pájaro con permiso de Dios, y les anunciaba lo oculto». Dijo: «¡Ay de vosotros! ¿Qué os impidió contarme esto? Por Dios, si lo hubiera sabido no los habría dejado hacer». Mandó a por los discípulos, se los arrancó de las manos, les preguntó por la religión de Jesús y su historia; se la contaron, [[k:y siguió su religión; e hizo bajar a Sergio [de la cruz] y lo escondió, y tomó el madero en el que fue crucificado]], lo honró y lo guardó por haberlo tocado; y atacó a los hijos de Israel y mató a muchos de ellos. [[k:Y de ahí vino el origen del cristianismo entre los romanos]]."],
 prueba="Ibn Ishaq, en la Historia de al-Tabari, cuenta lo que pasó después: Jesús, ya elevado, baja para enviar a los discípulos por el mundo (Pablo, «de los seguidores, no de los discípulos», va con Pedro a Roma); los judíos persiguen a los discípulos y el rey de los romanos se hace cristiano, baja de la cruz a Sergio —el sustituto— y venera el madero. Según esto, el cristianismo romano nace en el siglo I por la conversión de su rey.",
 ojo="Choca con todos los demás, incluida la propia Historia de al-Tabari (#Tb2#): el primer emperador cristiano fue Constantino, en el siglo IV. La primera parte (Jesús que vuelve a bajar, la noche del incienso) es, según Ibn Ishaq, lo que «pretenden los cristianos»; la lista de destinos de los apóstoles viene de tradiciones cristianas.")

add(2, "al-Tabari (m. 310 H / 923)", key="Tb2", specs=["rTb2a", "rTb2b"],
 title="Nerón «mató a Pedro y a Pablo»; Tito destruye Jerusalén; y Constantino, «el primero de los reyes de los romanos que se hizo cristiano»",
 ref=f"{TT}, vol. 1, p. 606 y p. 581 (esta, noticia de Hisham ibn al-Kalbi)",
 ar_ref="تاريخ الطبري ١/٦٠٦ و١/٥٨١", site=SH, url=S + "9783/603",
 es=["Dijo Abu Jaʿfar [al-Tabari]: [[a:Pretenden]] que el reino de Siria, de Palestina y de otros lugares pasó, después de Tiberio, a Gayo, hijo de Tiberio, y que reinó cuatro años. Luego reinó después de él otro hijo suyo, llamado Claudio, catorce años. [[k:Luego reinó después de él Nerón, que mató a Pedro y a Pablo, y lo crucificó cabeza abajo]], catorce años. Luego reinó después de él Vitelio, cuatro meses. Luego reinó después de él Vespasiano, padre de Tito, a quien envió a Jerusalén, diez años. Al cumplirse tres años de su reinado y cuarenta años desde la elevación de Jesús —la paz sea con él—, Vespasiano envió a su hijo Tito a Jerusalén, [[k:que la destruyó y mató a los hijos de Israel que mató, por cólera a causa del Mesías]].",
     "…Y el que se encargó de construirla fue el rey Constantino, [[k:que fue el primero de los reyes de los romanos que se hizo cristiano]]; y él expulsó de Palestina y del Jordán a los hijos de Israel que quedaban, [[k:por haber matado —según pretendía— a Jesús hijo de María]]; [[k:y tomó el madero en el que, según encontró que pretendían, habían crucificado al Mesías]]; los romanos lo veneraron y lo metieron en sus tesoros, y lo tienen hasta hoy."],
 prueba="La Historia de al-Tabari recoge la cronología de los cristianos: Nerón mata a Pedro y a Pablo; Tito destruye Jerusalén cuarenta años después; Constantino es «el primero de los reyes de los romanos que se hizo cristiano». Nada de un Pablo traidor: es un mártir más.",
 ojo="Contradice el relato de Ibn Ishaq que el mismo al-Tabari copia unas páginas antes (#Tb1#), según el cual el rey de los romanos ya se hizo cristiano en el siglo I. La noticia sobre Constantino es de Hisham ibn al-Kalbi (m. 204 H); la lista de emperadores la da con un «pretenden» (en azul).")

add(2, "al-Tabari (m. 310 H / 923), su propio juicio", key="TabV", specs=["rTbV1", "rTbV2"],
 title="Al-Tabari prefiere que los propios discípulos fueran engañados: «contaron lo que para ellos era verdad… y no merecen ser tenidos por mentirosos»",
 ref=f"{TAB}, sobre el Corán 4:157, vol. 9, pp. 374–375",
 ar_ref="تفسير الطبري ٩/٣٧٤–٣٧٥", site=SH, url=S + "43/5055",
 es=["Dijo Abu Jaʿfar: La más acertada de estas opiniones es una de las dos que hemos citado de Wahb ibn Munabbih: [[k:que la semejanza de Jesús fue echada sobre todos los que estaban en la casa con Jesús]] cuando lo rodearon a él y a ellos, sin que Jesús se lo pidiera, [[k:sino para que Dios humillara con ello a los judíos]], salvara a Su profeta de lo que querían hacerle, la muerte, y probara con ello a quien quisiera de Sus siervos en lo que dijeran de Jesús y en la verdad de la noticia sobre él. O bien la opinión que transmitió de él ʿAbd al-Samad. Y decimos que es la más acertada porque los discípulos que acompañaban a Jesús, si hubieran estado presentes cuando fue elevado y se echó su semejanza sobre aquel a quien se echó, habrían visto cómo era elevado de entre ellos, habrían identificado a quien se le echó su semejanza y lo habrían visto transformarse en su forma en su presencia; [[k:no se les habría ocultado nada de lo de Jesús ni de lo de aquel a quien se echó su semejanza]], habiéndolo visto todo, ni les habría resultado confuso, aunque sí lo fuera para otros, sus enemigos los judíos: que el muerto y crucificado era otro y que Jesús había sido elevado vivo de entre ellos.",
     "…O bien a los que estaban con Jesús en la casa de la que fue elevado, de sus discípulos, Dios los transformó a todos en la forma de Jesús cuando quiso elevarlo, y no pudieron distinguir a Jesús de los demás por la semejanza de todos ellos; y los judíos mataron a los que mataron de ellos viéndolos con la forma de Jesús y creyendo que era él, porque antes lo conocían. [[k:Y los que estaban en la casa con Jesús creyeron lo mismo que creyeron los judíos]], porque no distinguieron la persona de Jesús de la de los demás. [[k:Y por eso se pusieron todos de acuerdo]] —es decir, judíos y cristianos— en que el muerto era Jesús, y no era él, sino que se les hizo parecer.",
     "…[[k:Y contaron lo que para ellos era verdad, mientras que el asunto, ante Dios, era en realidad distinto de lo que contaron]]. [[k:Así que los discípulos que lo contaron no merecen ser tenidos por mentirosos]], ya que contaron lo que para ellos era verdad en lo aparente."],
 prueba="Es el juicio del propio al-Tabari, el gran comentarista. Rechaza la historia del voluntario porque, si uno se hubiera ofrecido delante de todos, los discípulos lo habrían sabido. Prefiere la versión en que Dios da la cara de Jesús a todos (o a uno cuando los demás ya se habían ido): los discípulos fueron engañados y contaron «de buena fe» lo que vieron.",
 ojo="Las consecuencias son fuertes: según al-Tabari, la fe de los apóstoles en la crucifixión no es una mentira ni una corrupción posterior, sino el resultado de un engaño de Dios a los testigos directos. Eso deja sin base la idea de que los apóstoles conocían la verdad y alguien la cambió después.")

add(2, "al-Masʿudi (m. 346 H / 957)", key="Md1", specs=["rMd1"],
 title="Jesús «siguió la religión de su pueblo leyendo la Torá»… y los cuatro que «compusieron la historia de Jesús»: Juan, Simón, Pablo y Lucas",
 ref="al-Masʿudi, Muruj al-dhahab, vol. 1, p. 76 (ed. Asʿad Daghir, Qom 1409 H), p. 61 de ketabonline",
 ar_ref="مروج الذهب ١/٧٦", site=KOS, url="https://ketabonline.com/ar/books/16498/read?part=1&page=61",
 es=["[[k:Y pretenden los cristianos que Jesús el Nazareno siguió la religión de los que le precedieron de su pueblo, leyendo la Torá]] y los libros anteriores en la ciudad de Tiberíades, en tierra del Jordán, en una iglesia llamada al-Midras, treinta años —o, se dice, veintinueve—; y que un día estaba leyendo el libro de Isaías cuando vio en el libro un escrito de luz que decía: «Tú eres mi profeta y mi elegido, te he escogido para Mí»; cerró el libro, se lo dio al servidor de la iglesia y salió diciendo: «Ahora se ha cumplido la voluntad de Dios en el hijo del hombre».",
     "Y se ha contado que [[k:Mar Yuhanna (Juan), Simón, Pablo y Lucas son los cuatro discípulos que recibieron el Evangelio y compusieron la historia de Jesús]] —la paz sea con él—."],
 prueba="Al-Masʿudi (m. 346 H) recoge lo que cuentan los cristianos (Jesús leía la Torá en la sinagoga, como en Lucas 4) y una noticia según la cual los cuatro que «recibieron el Evangelio y compusieron la historia de Jesús» fueron Juan, Simón, Pablo y Lucas.",
 ojo="La lista es errónea: los cuatro evangelistas son Mateo, Marcos, Lucas y Juan; Simón (Pedro) y Pablo no escribieron Evangelios. Y la escena de Isaías está en Nazaret, no en Tiberíades. Al-Masʿudi lo da con un «se ha contado». Texto de ketabonline, paginación automática.")

add(2, "al-Masʿudi (m. 346 H / 957)", key="Ms1", specs=["rMs1a", "rMs1b", "rMs1c"],
 title="Constantino se hace cristiano para no perder el trono (versión pagana); Nicea: «2.048 obispos de opiniones distintas», de los que se escogen 318",
 ref="al-Masʿudi, al-Tanbih wa-l-ishraf, pp. 119, 122 y 123 (ed. ʿAbd Allah al-Sawi, El Cairo)",
 ar_ref="التنبيه والإشراف للمسعودي ص ١١٩ و١٢٢–١٢٣", site=SH, url=S + "23718/125",
 es=["El primero de los reyes de esta dinastía es Constantino, hijo de Constancio, conocido por su madre Helena; reinó treinta y dos años y tres meses. [[k:Él fue quien hizo pública la religión cristiana y combatió por ella hasta que fue aceptada y se extendió por los países]] hasta hoy. Ya mencionamos en el libro al-Istidhkar la discusión sobre la causa de su conversión y de que dejara la religión de los paganos (hunafaʾ), y lo que dicen los paganos sobre ello: [[k:que le apareció una mancha blanca [de lepra] en el cuerpo y acordaron deponerlo]], porque en el fundamento de su religión estaba que quien la tuviera no podía reinar; y que se inclinó hacia aquellos entre quienes se había extendido el cristianismo, se apoyó en ellos y en sus allegados frente a quienes se le oponían, y profesó el cristianismo, pues en él no estaba prohibido que reinara quien tuviera eso. Y dicen algunos de ellos que lo ocultó y se lo reveló a uno de sus visires, que ocultaba su cristianismo; este envió varios ejércitos, una vez tras otra, contra los enemigos de alrededor, con los nombres de los siete ídolos que llevaban los nombres de los siete astros, a los que los sabeos ofrecían sacrificios, después de haberlos dejado muy débiles; y volvieron derrotados. Entonces mostró desprecio por ellos y por quienes los adoraban, [[k:y le aconsejó entonces pasarse al cristianismo, y lo hizo]].",
     "A los veinte años del reinado de Constantino fue el primer «sínodo», en la ciudad de Nicea, en tierra de los romanos —que significa «el concilio»—. [[k:Asistieron a este concilio dos mil cuarenta y ocho obispos de opiniones distintas]], [[k:y se eligió de entre ellos a trescientos dieciocho obispos de acuerdo entre sí, sin discrepancia]], y anatematizaron a Arrio de Alejandría…",
     "…a cuyo nombre se atribuyen los arrianos. [[k:Y establecieron en este concilio el Credo (al-amana)]] en el que están de acuerdo todos los cristianos —melquitas, jacobitas y los ʿIbad, que son los nestorianos—, y lo recitan cada día en la misa; [[k:y tienen cuarenta libros con las normas y las leyes]]. [[k:Y acordaron que la Pascua de los cristianos fuera el domingo siguiente a la Pascua de los judíos]], y que la Pascua de los judíos no coincidiera con la de los cristianos."],
 prueba="Al-Masʿudi da dos versiones de la conversión de Constantino: la de los paganos (se hizo cristiano para no perder el trono por una lepra) y la de los cristianos (la cruz luminosa). Y da las cifras que repetirán todos: 2.048 obispos «de opiniones distintas», de los que se escogen 318 que están de acuerdo; el Credo, cuarenta libros de normas y la fecha de la Pascua.",
 ojo="Las cifras no son históricas: las listas de Nicea tienen unos 220–250 obispos (la tradición los redondeó en 318, el número de Génesis 14:14), y el «2.048» viene de cronistas cristianos árabes del siglo X, como Saʿid ibn al-Bitriq. Y al-Masʿudi no dice que Nicea cambiara los Evangelios: dice que fijó el Credo, los cánones y la Pascua.")

add(2, "al-Masʿudi (m. 346 H / 957)", key="Md2", specs=["rMd2"],
 title="El sueño de Constantino y los 318 obispos: «y le establecieron como ley la religión cristiana»",
 ref="al-Masʿudi, Muruj al-dhahab, vol. 1, p. 352 (ed. Asʿad Daghir), p. 337 de ketabonline",
 ar_ref="مروج الذهب ١/٣٥٢", site=KOS, url="https://ketabonline.com/ar/books/16498/read?part=1&page=337",
 es=["…[[k:vio en sueños como si bajaran del cielo lanzas]] en las que había tormento, y estandartes con cruces de oro, plata, hierro, cobre, toda clase de piedras preciosas y madera en sus puntas, y se le dijo: «Toma estas lanzas y combate con ellas a tu enemigo y vencerás». Combatió con ellas en el sueño y vio a su enemigo derrotado y dándose a la fuga. Se despertó, mandó traer las lanzas, les puso lo que hemos dicho, las alzó en su ejército y avanzó contra su enemigo; huyeron y los alcanzó la espada. Volvió a la ciudad de Nicea y preguntó a los entendidos por aquellas cruces, si las conocían en alguna doctrina; le dijeron que Jerusalén, en tierra de Siria, era el centro de esa doctrina, y le contaron lo que habían hecho los reyes anteriores matando a los cristianos. Mandó a Siria y a Jerusalén, [[k:y le reunieron trescientos dieciocho obispos]]; fueron a él estando en Nicea, les contó su caso, [[k:y le establecieron como ley la religión cristiana]]. Este es el primer sínodo. Y se ha dicho que la madre de Constantino, Helena, se había hecho cristiana y se lo había ocultado antes de este sueño."],
 prueba="En Muruj al-dhahab la escena es aún más fuerte: Constantino vence gracias a un sueño, pregunta qué significan las cruces, manda traer a 318 obispos «y le establecieron como ley la religión cristiana». Es la frase que luego se usará para decir que el cristianismo de hoy se «hizo» para Constantino.",
 ojo="Leído en contexto, al-Masʿudi cuenta la conversión del emperador, no la invención del cristianismo: aquí mismo dice que los cristianos existían antes y eran perseguidos por «los reyes anteriores». Texto de ketabonline, paginación automática.")

add(2, "al-Masʿudi (m. 346 H / 957)", key="Ms2", specs=["rMs2"],
 title="El origen real de las sectas: los nestorianos se separan en Éfeso y los jacobitas en Calcedonia, cuatro siglos después de Jesús",
 ref="al-Masʿudi, al-Tanbih wa-l-ishraf, p. 129 (ed. ʿAbd Allah al-Sawi, El Cairo)",
 ar_ref="التنبيه والإشراف للمسعودي ص ١٢٩", site=SH, url=S + "23718/135",
 es=["Dijo al-Masʿudi: [[k:Y en este concilio los nestorianos se apartaron de los melquitas y se separaron de ellos]]. Del segundo concilio, el de los ciento cincuenta obispos que se reunieron en Constantinopla y maldijeron a Macedonio, a este concilio de los doscientos obispos que se reunieron en Éfeso, hay cincuenta y un años. En los días de este Teodosio hubo entre los cristianos sucesos en la religión y en el reino, entre ellos el destierro de Juan, conocido como Boca de Oro [Crisóstomo], patriarca de Constantinopla, por un juicio sobre una viña que disgustó a la esposa del rey, Eudoxia, y otras cosas. El undécimo, Marciano, reinó seis años; [[k:en el primer año de su reinado fue el cuarto sínodo, en la ciudad de Calcedonia]], contra Dióscoro, patriarca de Constantinopla [sic], y Eutiques; se reunieron en él seiscientos treinta obispos. Del tercer concilio, el de los doscientos obispos de Éfeso, a este concilio hay veintiún años. [[k:Y en este concilio los jacobitas discreparon del resto de los cristianos y se separaron de ellos]]. Ya contamos en el libro Ajbar al-zaman… la historia de Jacobo Baradeo de Antioquía —o de Harrán, se dice—, discípulo de Severo, y cómo se atribuyó la gente de la doctrina de Dióscoro a los jacobitas y se les dio el nombre de Jacobo."],
 prueba="Un historiador musulmán del siglo IV H sitúa el origen de nestorianos y jacobitas donde lo sitúa la historia: en los concilios de Éfeso (431) y Calcedonia (451), unos cuatrocientos años después de Jesús.",
 ojo="Esto desmiente, desde dentro de la propia tradición islámica, los relatos de Ibn Abbas, Qatada e Ibn Jurayj (#IA1#, #Qt4#, #IJ#), que ponen a jacobitas y nestorianos discutiendo el día de la ascensión. Error menor: Dióscoro era patriarca de Alejandría, no de Constantinopla.")
