# -*- coding: utf-8 -*-
# ---------- 3. Siglos V–VI H (XI–XII d. C.) ----------
AJ = "al-Qadi ʿAbd al-Jabbar, Tathbit dalaʾil al-nubuwwa, ed. ʿAbd al-Karim ʿUthman (Beirut: Dar al-ʿArabiyya, 1966)"
FS = "Ibn Hazm, al-Fisal fi l-milal wa-l-ahwaʾ wa-l-nihal"
SHF = "shamela.ws (Maktaba Shamila; paginación igual a la ed. de Maktabat al-Khanji, El Cairo)"
AJW = "ʿAbd al-Jabbar (m. 415 H / 1025)"
IHW = "Ibn Hazm (m. 456 H / 1064)"

add(3, AJW, key="AJ1", specs=["rAJ1a", "rAJ1b"],
 title="Jesús y sus compañeros cumplían la Torá; luego los cristianos «se fueron cambiando poco a poco» para ganarse a los romanos",
 ref=f"{AJ}, vol. 1, pp. 150 y 152", ar_ref="تثبيت دلائل النبوة للقاضي عبد الجبار ١/١٥٠ و١٥٢", site=SH, url=S + "9789/158",
 es=["…[dijo el Mesías: «He venido] para cumplir la Torá y los mandamientos de los profetas anteriores a mí; no he venido a abolir, sino a completar; y que caiga el cielo sobre la tierra es más fácil ante Dios que abolir algo de la ley de Moisés, y quien abola algo de ella será llamado pequeño en el reino de los cielos». Y así siguieron él y sus compañeros hasta que dejó este mundo, y dijo a sus compañeros: «Obrad como me habéis visto obrar, aconsejad a la gente lo que os he aconsejado, sed con ellos como yo he sido con vosotros». [[k:Y así siguieron sus compañeros después de él]], y luego los que vinieron tras la primera generación de sus compañeros, y los de después durante mucho tiempo. [[k:Luego empezaron a cambiar y alterar, a introducir innovaciones en la religión, a buscar el poder]], a congraciarse con la gente con lo que les gustaba, a hacer la contra a los judíos y desahogar su rencor contra ellos, aunque supusiera abandonar la religión. Esto está claro en los Evangelios que tienen y en su libro conocido como «Libro de los Hechos» (Afraksis): que unos cristianos salieron de Jerusalén, fueron a Antioquía y a otros lugares de Siria y llamaron a la gente a la norma de la Torá: a prohibir las víctimas de quienes no eran de ella, a la circuncisión, a guardar el sábado, a prohibir el cerdo y lo que la Torá prohíbe. Eso les resultó pesado a las naciones, y los cristianos se reunieron en Jerusalén y deliberaron cómo atraerse a las naciones para que les respondieran y obedecieran; [[k:y su decisión fue mezclarse con las naciones, hacerles concesiones]], rebajarse a sus deseos, no contrariarlas, comer de sus víctimas, adoptar sus costumbres y darles la razón en lo que hacían; y escribieron sobre ello un libro. Y dijo Pablo en el libro que llaman al-Salih [las cartas del Apóstol]: «Yo les dije: ¿hasta cuándo vais a judaizar a la gente?». Y dijo en las dos cartas: «[[k:Con el judío fui judío y con el romano, romano]]»…",
     "Y sabe que la religión del Mesías y las de los mensajeros —la paz sea con ellos— [[k:no cambiaron ni se alteraron de una vez, sino poco a poco]], en cada época y en cada momento, hasta que su cambio fue completo; los fieles a la verdad fueron disminuyendo y los del error aumentando, hasta que se impusieron y la verdad murió con ellos. Los compañeros del Mesías, después de él, estaban con los judíos y los hijos de Israel en sus sinagogas, haciendo su oración y sus fiestas en un mismo lugar, aunque discrepaban sobre el Mesías; [[k:y los romanos los gobernaban, y los cristianos se quejaban de los judíos a los reyes romanos]], les mostraban su debilidad y les pedían compasión, y ellos se compadecían. Esto se repitió, y los romanos les decían: «Tenemos con los judíos el pacto de no cambiar sus religiones; [[k:si salierais de sus religiones, os separarais de ellos y rezarais hacia el oriente como rezamos nosotros]], comierais lo que comemos y tuvierais por lícito lo que tenemos por lícito, os ayudaríamos y os honraríamos, y los judíos no podrían nada contra vosotros». Dijeron: «Lo haremos». Les dijeron: «Pues id, traed a vuestros compañeros y traed vuestro libro». Fueron a sus compañeros, les contaron lo que había entre ellos y los romanos, y les dijeron: «Traed el Evangelio y venid, para que vayamos a ellos». Pero aquellos les dijeron: «¡Qué mal habéis hecho! [[k:No nos es lícito dejar el Evangelio a los romanos impuros]]; vosotros habéis salido de la religión al responder a los romanos; no nos es lícito tratar con vosotros: hay que romper con vosotros e impediros el acceso al Evangelio»."],
 prueba="ʿAbd al-Jabbar (m. 415 H), cadí muʿtazilí de Rayy, escribe la historia de la corrupción más elaborada de toda la tradición: Jesús y sus compañeros cumplen la Torá; luego, «poco a poco», los cristianos se «romanizan» para ganarse el favor de Roma frente a los judíos (rezar al oriente, comer lo que comen los romanos). Los fieles se niegan a entregar el Evangelio «a los romanos impuros».",
 ojo="Usa textos cristianos como fuente: Mateo 5:17–19, el concilio de Jerusalén de Hechos 15 y 1 Corintios 9:20–22 («con los judíos me hice judío»), que cita adaptada. Pero el concilio de Hechos 15 no adopta costumbres romanas: pide a los gentiles abstenerse de lo sacrificado a los ídolos, de la sangre y de la fornicación. Ningún documento antiguo habla de un pacto de los cristianos con Roma para rezar al oriente.")

add(3, AJW, key="AJ2", specs=["rAJ2a", "rAJ2b"],
 title="El Evangelio verdadero se perdió con los fieles; los romanizados «decidieron componer un evangelio»: ochenta, reducidos a cuatro",
 ref=f"{AJ}, vol. 1, pp. 153 y 155", ar_ref="تثبيت دلائل النبوة ١/١٥٣ و١٥٥", site=SH, url=S + "9789/161",
 es=["Se produjo entre ellos una fuerte discrepancia. Aquellos volvieron a los romanos y les dijeron: «Ayudadnos contra estos compañeros nuestros antes que contra los judíos, y quitadles nuestro libro». Los otros se escondieron de los romanos y huyeron por los países. Los romanos escribieron sobre ellos a sus gobernadores en la región de Mosul y en la península arábiga; los buscaron, [[k:y cayeron algunos, que fueron quemados, y otros, que fueron muertos]]. Los que habían respondido a los romanos se reunieron y deliberaron qué poner en lugar del Evangelio, ya que lo habían perdido, [[k:y decidieron componer un evangelio]]. Dijeron: «La Torá no es más que nacimientos de profetas e historias de sus vidas; construyamos el Evangelio así, [[k:y que cada uno de nosotros recuerde lo que haya memorizado de las palabras del Evangelio]] y lo que los cristianos cuentan del Mesías». Un grupo escribió un evangelio; luego vino otro grupo y escribió otro, y escribieron varios evangelios, y se les cayó mucho de lo que había en el original. Había entre ellos, uno tras otro, quien sabía muchas cosas del Evangelio verdadero y se las calló para mantener su poder; [[k:y en aquel no había mención de la cruz ni de la crucifixión]]. [[k:Y pretenden que eran ochenta evangelios]], y no dejaron de disminuir y recortarse hasta que quedaron cuatro evangelios de cuatro hombres: cada uno hizo un evangelio en su época, y el que vino después lo vio deficiente e hizo otro que tenía por más correcto. [[k:Y no hay entre ellos ningún evangelio en la lengua del Mesías]], la que hablaban él y sus compañeros, el hebreo, lengua de Abraham y de los demás profetas: en ella hablaron, en ella bajaron los libros de Dios a los hijos de Israel, y en ella les habló Dios; y estos la abandonaron.",
     "Un evangelio lo hizo Juan, otro lo hizo Mateo; [[k:luego vino Marcos y no le satisficieron los evangelios de esos dos; luego vino Lucas y no le satisficieron esos evangelios, e hizo otro evangelio]]. Cada uno creía que su predecesor había fijado unas cosas y descuidado otras, y que él sabía y fijaba mejor.",
     "…[[k:Incluso Lucas dice en su evangelio que no vio al Mesías]]: dijo Lucas, dirigiéndose a aquel para quien hizo su evangelio —y es el último de los cuatro—: «Conocí tu deseo del bien, del saber y de la educación, e hice este evangelio por lo que sé y porque estuve cerca de los que sirvieron a la Palabra y la vieron». Así, antes que nada, declaró que no vio a la Palabra —quieren decir con la Palabra al Mesías—, y luego pretendió que vio a quien vio al Mesías."],
 prueba="La versión más radical de la historia de los Evangelios: el Evangelio verdadero se perdió con los fieles, perseguidos y quemados por los romanos; los romanizados «decidieron componer un evangelio» de memoria; hubo ochenta, que se fueron reduciendo a cuatro, cada uno escrito porque el anterior no convencía, y ninguno en hebreo, la lengua de Jesús.",
 ojo="El relato de la persecución y de los ochenta evangelios no cita ninguna fuente. La cita de Lucas sí es real (Lucas 1:1–4), y es honesta: Lucas reconoce que escribe a partir de testigos. La lengua cotidiana de Jesús era el arameo, no el hebreo. Y el orden Juan, Mateo, Marcos, Lucas no lo sostiene nadie.")

add(3, AJW, key="AJ3", specs=["rAJ3a", "rAJ3b", "rAJ3c"],
 title="Pablo, «un judío malvado», se declara romano, se va a Constantinopla y da a Roma una religión a su gusto: «la Torá es toda ella un mal»",
 ref=f"{AJ}, vol. 1, pp. 156–158", ar_ref="تثبيت دلائل النبوة ١/١٥٦–١٥٨", site=SH, url=S + "9789/164",
 es=["[[k:Y este Pablo era un judío malvado y perverso]], que se afanaba en el mal, ayudaba a los malos, agitaba las discordias, buscaba el poder y el mando y usaba para ello toda artimaña. [[k:Cuando era judío lo llamaban Saulo, y ayudaba contra los cristianos]]. Luego salió de Jerusalén, se ausentó mucho tiempo, volvió a Jerusalén y empezó a ayudar a los cristianos contra los judíos, diciéndoles: «Decid esto, haced esto, separaos de ellos y acercaos a las naciones enemigas de los judíos». Le dijeron los judíos: «¿Cómo te has hecho cristiano, y qué te ha traído aquí?». Dijo: «Dios —bendito y ensalzado— me llamó a ello. Mi historia es que salí de Jerusalén camino de Damasco; me alcanzó la noche con su oscuridad, sopló un viento enorme, perdí la vista, y el Señor me llamó y me dijo: “Saulo, ¿golpeas a los hermanos y dañas a los compañeros de mi hijo?”. Dije: “Señor, me arrepiento”. Me dijo: “Si es como dices, ve a Jaim el judío, el sacerdote, para que te devuelva la vista”. Fui a él y se lo conté; me pasó la mano por los ojos y cayó de ellos algo como cáscaras de huevo y escamas de pez, y vi como antes. Y Dios me llamó a Su lado, al cielo, [[k:y estuve con Él en el cielo catorce días]]».",
     "…Le dijo [Saulo al romano]: «¿Vas a azotar a un romano?». Dijo: «¿Eres romano?». Dijo: «Sí, [[k:sigo la religión del César, rey de los romanos, y renuncio al judaísmo]]». Dejó de golpearlo por haber entrado en la religión del rey, y le dijo: «Aquí hay un barco que va a Constantinopla; eres romano y de la religión de los romanos: vete allí si es como dices». Dijo: «Lo haré; envíame a la tierra de los romanos». [[k:Y fue a Constantinopla, frecuentó a los romanos, se pegó a la puerta del rey e incitó a los romanos contra los judíos]]: les recordó su enemistad, lo que les habían hecho los hijos de Israel y a cuántos habían matado, les hizo temer el mal de los judíos y les habló de sus muchas riquezas. Es costumbre de los romanos que sus mujeres no se oculten de los hombres, y la mujer del rey sale en el cortejo con la cara descubierta, habla a la gente, ordena y prohíbe; este Pablo se acercó a ella y le habló de los judíos. Y es costumbre de los romanos que el hombre no puede casarse con más de una mujer, y no los separa ni el divorcio, ni la vejez, ni defecto alguno, ni le está permitida otra hasta que ella muere. Las mujeres romanas detestan las religiones de los profetas de Israel porque permiten el divorcio y que el hombre se case con cuantas pueda mantener. Se le dijo a Saulo: «Eres de una nación que hace eso». Dijo: «No; [[k:al hombre no le está permitida más de una mujer, según las leyes de los romanos]]». Y así se ganó a las mujeres.",
     "…Los romanos detestan mucho la circuncisión, en hombres y mujeres, y odian a las naciones que la practican; se lo dijeron a Pablo, y dijo: «Sí, es como veis; [[k:no estáis obligados a circuncidaros: eso solo obliga a los hijos de Israel]], que son una nación con el prepucio en el corazón». Los romanos comen cerdo, y dijo: «No está prohibido; no se prohíbe al hombre nada que entre en su vientre, sino la mentira que sale de él». Los hijos de Israel no comen las víctimas de los idólatras y los romanos sí, y Pablo les dio la razón; se les hizo agradable en todo y en nada les contrarió. Las religiones de los romanos estaban entonces extendidas: la mayoría veneraba los astros y creía que dan la vida y la muerte, benefician y dañan, y tenían para ellos templos y sacrificios; otros seguían la religión de los griegos, para quienes los astros son vivos, racionales, proveedores y señores; y creían en la magia: en suma, todas sus religiones eran falsas, débiles y corruptas. Pablo les hablaba de la excelencia del Mesías, de su ascetismo, de que sus oraciones eran escuchadas y de que resucitaba a los muertos, y se reunían en torno a él; y era un tramposo y un malvado. Los romanos rezaban hacia la salida del sol y no veían obligatoria la ablución, ni el baño tras la impureza mayor o la menstruación, ni evitar la orina, las heces y la sangre; y se casaban con idólatras y con las demás naciones, y los hijos de Israel no. Se lo dijeron a Pablo, y dijo: «Que la creyente se case con el incrédulo, porque ella lo purifica y él no la mancha, y el hijo de ambos es puro». Y dijo: «Eso solo lo prohíbe la Torá, [[k:y la Torá es toda ella un mal]]; y cuando se quitan de encima de la gente las leyes de la Torá, se completa la bondad de Dios». [[k:Así Pablo se despojó de las religiones del Mesías]] y pasó a las religiones de los romanos. Si examinas el asunto, [[k:verás que los cristianos se romanizaron y volvieron a las religiones de los romanos, y no que los romanos se cristianizaran]]."],
 prueba="La leyenda de Pablo según ʿAbd al-Jabbar: un judío malvado que perseguía a los cristianos inventa la visión de Damasco, se declara romano para librarse de unos azotes, se va a Constantinopla y le da a Roma una religión a su gusto: sin circuncisión, con cerdo, con la monogamia romana y sin Torá. Su frase final resume la tesis: «los cristianos se romanizaron, no los romanos se cristianizaron».",
 ojo="Mezcla datos reales de Hechos y de las cartas (Saulo perseguidor, Damasco, Ananías —aquí «Jaim el sacerdote»—, las escamas de los ojos, la ciudadanía romana de Hechos 22:25, «nada de lo que entra en el hombre lo mancha» de Marcos 7, el cónyuge creyente de 1 Corintios 7:14) con disparates: Constantinopla no existía en tiempos de Pablo (se fundó en el 330), y «la Torá es toda ella un mal» no está en ninguna carta; Pablo llama a la ley «santa, justa y buena» (Romanos 7:12).")

add(3, AJW, key="AJ4", specs=["rAJ4a", "rAJ4b"],
 title="Helena de Harrán se casa con el rey «Pilato»; un rey descubre que Pablo es un fraude y lo crucifica; Constantino hereda… y contrae la lepra",
 ref=f"{AJ}, vol. 1, pp. 159–160", ar_ref="تثبيت دلائل النبوة ١/١٥٩–١٦٠", site=SH, url=S + "9789/167",
 es=["Los romanos tenían un rey llamado Pilato, que salió hacia Siria mucho tiempo después del Mesías —la paz sea con él— y de sus compañeros. Tenía una mujer en tierra de los romanos que murió, y quiso casarse con otra en su lugar. Es costumbre de los romanos que el hombre, cuando quiere casarse, examine a la mujer a fondo; si le conviene se casa con ella, y si no, la deja. [[k:Le describieron a Pilato una mujer de Harrán llamada Helena]], que estaba en una posada de Harrán —la posada es el jan—; la hizo venir, la examinó, le agradó y se casó con ella. Era cristiana, y ganó su favor; le pidió que honrara a los cristianos y les hiciera bien. Le dijo: «Los judíos pretenden que estos compañeros tuyos son unos tramposos que buscan el mundo y el poder». Dijo: «Mienten; te los traeré para que los veas». Le llevó un grupo de monjes y le dijo: «Mira su pobreza y su debilidad, para que sepas que los judíos mienten sobre ellos». Se compadeció de ellos y pensó bien de ellos, [[k:y los honró, los protegió y les dio poder en sus reinos de Siria y de la tierra de los romanos]]; se extendieron, se multiplicaron y se impusieron a los judíos. Este rey tenía hijos de la mujer anterior a Helena, [[k:y de esta Helena le nació un hijo llamado Constantino]].",
     "…[[k:Uno de sus reyes se dio cuenta de lo que era Pablo]], examinó su situación y supo que era un tramposo, un embaucador que buscaba el mundo y el poder. Lo hizo venir y le preguntó por la circuncisión, y él la censuró y censuró a quienes la practican. Le preguntó por el Mesías: ¿se circuncidó? ¿estaba circuncidado? ¿lo estaban sus discípulos? Dijo: «Sí». Luego lo destaparon, y estaba circuncidado. Vio que había ayudado a los romanos en sus religiones, que eran contrarias a las del Mesías y sus compañeros; además, los compañeros de Pablo tenían elefantiasis en las piernas y él pretendía que curaba. [[k:El rey ordenó que lo abofetearan, le afeitaran la barba y lo crucificaran]]. Les dijo: «[[k:No me crucifiquéis de pie, como fue crucificado nuestro Señor el Mesías; crucificadme atravesado]]». El rey que le hizo esto a Pablo se llamaba Bírun [¿Nerón?], y el cristianismo se debilitó en la tierra de los romanos. Después reinaron los hijos de Pilato, [[k:y el reino llegó a su hijo Constantino]], que en apariencia seguía las religiones de los romanos, pero su madre Helena lo había criado en el amor a la cruz y en las costumbres de los cristianos. [[k:Y le salió en el cuerpo la lepra]]…"],
 prueba="Aquí ʿAbd al-Jabbar lo junta todo: Helena, una cristiana de Harrán, se casa con un rey romano llamado «Pilato» y le hace proteger a los cristianos; un rey descubre que Pablo es un fraude y lo crucifica; y el hijo de Helena, Constantino, criado en el amor a la cruz, hereda el trono… y contrae la lepra.",
 ojo="Historia completamente confundida: Pilato fue gobernador de Judea en tiempos de Jesús, no un rey romano posterior ni el padre de Constantino (que fue Constancio Cloro); Helena no era de Harrán; y Pablo murió en Roma hacia el 64–67, dos siglos y medio antes de Constantino (según la tradición cristiana, decapitado; al que crucificaron cabeza abajo fue a Pedro). La lepra de Constantino es una leyenda tardía (la de su curación por el papa Silvestre).")

add(3, AJW, key="AJ5", specs=["rAJ5a", "rAJ5b"],
 title="Constantino cambia las medias lunas de los estandartes por cruces, mata a los filósofos y convierte los templos de los astros en iglesias",
 ref=f"{AJ}, vol. 1, pp. 161–162", ar_ref="تثبيت دلائل النبوة ١/١٦١–١٦٢", site=SH, url=S + "9789/169",
 es=["…Luego dijo: «Aquí hay una mujer que vio en sueños a alguien que le decía: [[k:pedid la victoria con esto]]», y sacó ante ellos una cruz. Coincidió que murió el jefe del ejército que los había atacado y se retiraron, y dijo él, y los de su opinión: «Esto es por la bendición de la cruz». Era costumbre de los romanos poner en sus estandartes medias lunas y figuras de media luna, buscando la bendición de la luna y las estrellas; [[k:las quitaron y pusieron en su lugar cruces]].",
     "[[k:Luego empezó a planear cómo trasladar a los romanos de la veneración de los astros a la veneración de las cruces]].",
     "…[[k:Y empezó a matarlos [a los filósofos] por categorías, a quemar sus libros y a anular sus templos]]; siguió así hasta que sus ciudades quedaron vacías de ellos —era la ciudad de los filósofos, y no quedaron en ella más que labradores, curtidores y tintoreros—; [[k:e hizo iglesias de los templos que eran de los astros]]…",
     "…Y él mostró veneración por el Mesías y por la cruz, [[k:y mantuvo las religiones de los romanos como estaban: la oración hacia el oriente]] y lo demás que hemos dicho; [[k:no quitó más que el culto a los astros, ni añadió más que la veneración del Mesías y la afirmación de su señorío]], y la veneración de la cruz."],
 prueba="Constantino, según ʿAbd al-Jabbar, se sirve de una visión ajena («una mujer vio en sueños…»), cambia las medias lunas de los estandartes por cruces, mata a los filósofos, quema sus libros y convierte los templos de los astros en iglesias. Y la frase clave: «no quitó más que el culto a los astros, ni añadió más que la veneración del Mesías». Es decir, el cristianismo de Constantino sería la religión romana con otro dios.",
 ojo="Las fuentes antiguas (Lactancio, Eusebio) dicen que el signo lo vio el propio Constantino antes de la batalla del Puente Milvio (312). No hay constancia de una matanza de filósofos ni de quema de sus libros por Constantino; los templos paganos se cerraron sobre todo a finales del siglo IV, con Teodosio. Y los cristianos ya rezaban hacia el oriente antes de Constantino (lo menciona Tertuliano hacia el año 200).")

add(3, AJW, key="AJ6", specs=["rAJ6a", "rAJ6b"],
 title="Nicea: 318 hombres fijan la fe, Constantino «la impuso a la gente: a quien no la aceptaba lo mataba»… con la cruz y el cerdo",
 ref=f"{AJ}, vol. 1, pp. 162–163", ar_ref="تثبيت دلائل النبوة ١/١٦٢–١٦٣", site=SH, url=S + "9789/170",
 es=["Y este Constantino fue a la Yazira y se dirigió a Harrán y su comarca, que veneraban los astros más que en Atenas y en la tierra de los romanos, [[k:y les pasó a cuchillo hasta exterminarlos]]; huyeron los que huyeron a los montes y los persiguió en persona —ellos reprochaban la lepra, y por eso tenía especial empeño en ellos—; le dijeron sus generales: «No mandes a buscarlos, que la nieve de estos montes acabará con ellos; y si queda alguno, lo haremos sangrador de los romanos». [Y convocó a] todos los cristianos, ermitaños y monjes para conocer por ellos la verdad del cristianismo y lo que debía fijarse para imponerlo a la gente sin que se apartaran de ello, y que a quien se apartara se le matara [el texto parece tener una laguna]. [[k:Y se reunieron ante él unos dos mil de sus jefes]], y fijaron cosas…",
     "…de la fórmula de la fe; y había entre ellos quienes se oponían a aquellos y decían que la Palabra de Dios es creada y que el Mesías es la Palabra de Dios: estaban allí Arrio, Macedonio, Eunomio [?], Valeriano [?] y sus compañeros, de los que dicen: [[k:la Palabra es creada]], y la palabra de Dios es una criatura de Sus criaturas; alborotaron contra ellos, el asunto se detuvo y aquella decisión quedó anulada.",
     "[[k:Luego se reunieron después trescientos dieciocho hombres en Nicea]], en tierra de los romanos, e hicieron la fórmula de su fe que ya se ha mencionado; [[k:se la llevaron a Constantino, la tomó, actuó según ella y la impuso a la gente: a quien no la aceptaba lo mataba]]. Aquellos tuvieron que mostrar que la aceptaban por miedo a la espada; anuló cualquier otra, y los que seguían la religión del Mesías sufrieron toda clase de males; [[k:y se impuso la veneración de la cruz, comer cerdo y las religiones de los romanos]], y al que no lo comía lo mataban.",
     "[[k:Y Constantino estuvo en el trono cincuenta años ocupado en matar a quien no veneraba la cruz ni afirmaba el señorío del Mesías]], hasta que eso quedó asentado y firme; se lo encomendó a los reyes después de él, se lo hizo jurar, y dijo: «Es mejor que venerar los astros y las opiniones de los filósofos»; afianzó este pacto con sus hijos, sus generales y sus partidarios, y dejó el reino a sus hijos."],
 prueba="El final de la historia según ʿAbd al-Jabbar: Constantino arrasa Harrán, reúne a unos 2.000 jefes sin acuerdo (allí están Arrio y Macedonio, que dicen que la Palabra es creada), y luego 318 en Nicea fijan la fe; Constantino la impone por la espada, junto con la cruz y el cerdo, y pasa «cincuenta años» matando a quien no venerase la cruz.",
 ojo="Errores: Constantino reinó 31 años (306–337), no cincuenta; Macedonio fue condenado en el 381, no en Nicea; y en Nicea no se trató de comer cerdo ni de venerar la cruz. Tampoco hay ninguna fuente de matanzas de Constantino para imponer el Credo: desterró a Arrio y a dos obispos que no firmaron, y años después rehabilitó a Arrio.")

add(3, AJW, key="AJ7", specs=["rAJ7"],
 title="El domingo, la Navidad (la fiesta romana del «nacimiento del tiempo») y la Cuaresma: añadidos romanos después de Constantino",
 ref=f"{AJ}, vol. 1, p. 164", ar_ref="تثبيت دلائل النبوة ١/١٦٤", site=SH, url=S + "9789/172",
 es=["Sus hijos reinaron después de él, confirmaron sus pactos y fueron fijando en cada momento algo más del cristianismo, hasta que llegó uno de sus reyes [[k:que decidió hacer del domingo una fiesta para ellos]], en la que se reunieran como los judíos el sábado; [[k:y esto fue mucho tiempo después de Constantino]]. Hicieron para ello un sínodo. [[k:Los romanos y los griegos tenían una fiesta que llamaban «el nacimiento del tiempo»]], cuando el sol vuelve en diciembre, [[k:e hicieron de ella el nacimiento del Mesías]], añadiendo y quitando; es una gran fiesta para ellos, la que los cristianos llaman la Natividad y la Nochebuena, y esa es su causa y su origen; los cristianos en tiempos del Mesías y de sus compañeros no conocían esta fiesta ni la celebraban. Los romanos y los sabeos tenían días que ayunaban para acercarse a los astros, absteniéndose de comer carne; cuando pasaron a decir que el Mesías era Dios, los mantuvieron, añadieron y quitaron, y hoy los ayunan cincuenta días hasta el mediodía; así ayunan en tierra de los romanos.<br>[[k:Y los romanos son el origen de estos tres grupos de cristianos]]; de ellos se ramificaron los jacobitas, seguidores de Jacobo, y después de los jacobitas los nestorianos, seguidores de Nestorio."],
 prueba="Según ʿAbd al-Jabbar, el domingo, la Navidad (tomada de la fiesta romana del solsticio, «el nacimiento del tiempo») y la Cuaresma (los ayunos de los astros) son añadidos romanos posteriores a Constantino. Y las tres iglesias vienen de los romanos.",
 ojo="Mezcla un acierto con un error grave. Es cierto que la fecha del 25 de diciembre se fijó en el siglo IV y coincide con la fiesta del Sol Invicto. Pero el domingo no lo introdujo un rey «mucho después de Constantino»: los cristianos se reunían «el primer día de la semana» desde el siglo I (Hechos 20:7; 1 Corintios 16:2; Didajé 14; Justino, Apología I 67), y fue Constantino quien lo hizo festivo civil en el 321. Y los nestorianos (431) son anteriores a los jacobitas (451), no al revés.")

add(3, "al-Thaʿlabi (m. 427 H / 1035)", key="Tl", specs=["rTl1a", "rTl1b", "rTl1c"],
 title="«Siguieron la religión del islam ochenta y un años… rezando hacia la alquibla y ayunando en Ramadán», hasta que llegó Pablo",
 ref="al-Thaʿlabi, al-Kashf wa-l-bayan, sobre el Corán 9:30, vol. 13, pp. 296–298",
 ar_ref="الكشف والبيان للثعلبي ١٣/٢٩٦–٢٩٨", site=SH, url=S + "18686/6952",
 es=["Y en cuanto a los cristianos, su idolatría fue que [[k:siguieron la religión del islam ochenta y un años después de que Jesús —la paz sea con él— fuera elevado]], [[k:rezando hacia la alquibla y ayunando en Ramadán]], hasta que hubo guerra entre ellos y los judíos; y había entre los judíos…",
     "…un hombre valiente llamado Pablo (Bulus), que mató a muchos de los compañeros de Jesús —la paz sea con él—. Luego dijo a los judíos: «Si la verdad está con Jesús y nosotros hemos sido incrédulos y lo hemos negado, y el Fuego es nuestro destino, salimos perdiendo si ellos entran en el Paraíso y nosotros en el Fuego; [[k:yo usaré una artimaña para extraviarlos y que entren en el Fuego]]». Tenía un caballo llamado al-ʿUqab con el que combatía; [[k:le cortó los tendones, fingió arrepentimiento y se echó tierra sobre la cabeza]]. Le dijeron los cristianos: «¿Quién eres?». Dijo: «Pablo, vuestro enemigo; me llamaron desde el cielo: no tienes arrepentimiento si no te haces cristiano; y me he arrepentido». Lo metieron en la iglesia, y entró en una casa un año, sin salir ni de noche ni de día, hasta que aprendió el Evangelio; luego salió y dijo: «Me han llamado: Dios ha aceptado tu arrepentimiento». Le creyeron y lo amaron. Luego se fue a Jerusalén [[k:y dejó como sucesor sobre ellos a Nestorio, y le enseñó que Jesús, María y el dios eran tres]]. Luego se dirigió a los romanos y les enseñó lo divino y lo humano, y dijo: «Jesús no era humano para hacerse humano, ni cuerpo para hacerse cuerpo, [[k:sino que es el hijo de Dios]]»; y se lo enseñó a un hombre llamado Jacobo. Luego llamó a un hombre llamado Malka y le dijo: «[[k:El dios no ha dejado ni deja de ser Jesús]]». Cuando se hubo asentado entre ellos, llamó a estos tres uno por uno y dijo a cada uno: «Tú eres mi elegido; he visto a Jesús en sueños y está satisfecho de mí»…",
     "…[y dijo a cada] uno de ellos: «Mañana me degollaré; llama tú a tu doctrina». [[k:Luego entró en el altar, se degolló y dijo: «Hago esto para complacer a Jesús»]]. Al tercer día, cada uno llamó a la gente a su doctrina; cada uno tuvo un grupo de seguidores, [[k:y combatieron y discreparon hasta hoy]]; y todos los cristianos son de los tres grupos."],
 prueba="La versión «clásica» de la leyenda de Pablo, la que repetirán al-Baghawi y otros comentaristas de 9:30: los seguidores de Jesús fueron «musulmanes» durante 81 años, rezando hacia la alquibla y ayunando en Ramadán; Pablo, un judío que había matado a muchos de ellos, finge convertirse y reparte tres doctrinas entre tres discípulos (Nestorio, Jacobo y Malka); luego se degüella en el altar para que cada uno predique la suya.",
 ojo="No da fuente. Y es imposible: el ayuno de Ramadán y la alquibla del islam no existían en el siglo I; Nestorio vivió en el siglo V y Jacobo Baradeo en el VI; Pablo murió hacia el 64–67, y no se suicidó. Comparada con la de Sayf (#Sy#), cambia casi todo: allí Pablo era rey, aquí un guerrero judío; allí los discípulos eran Yaʿqub, Nastur y Malkun, aquí Nestorio, Jacobo y Malka, y las doctrinas no coinciden.")

add(3, IHW, key="IH1", specs=["rIH1a", "rIH1b"],
 title="Las sectas: Arrio y Pablo de Samosata, «monoteísmo puro»; Constantino, «el primer rey que se hizo cristiano», era arriano; hoy, melquitas, nestorianos y jacobitas",
 ref=f"{FS}, vol. 1, pp. 47–48", ar_ref="الفصل في الملل والأهواء والنحل لابن حزم ١/٤٧–٤٨", site=SHF, url=S + "6521/39",
 es=["Y los cristianos son grupos. Entre ellos, los seguidores de Arrio, que era sacerdote en Alejandría; su doctrina era el monoteísmo puro, que Jesús —la paz sea con él— es un siervo creado y que es la palabra de Dios con la que creó los cielos y la tierra; vivió en tiempos de Constantino I, el que construyó Constantinopla [[k:y el primero de los reyes de los romanos que se hizo cristiano, que seguía la doctrina de este Arrio]]. Y entre ellos, los seguidores de Pablo de Samosata, que era patriarca en Antioquía antes de la aparición del cristianismo; [[k:su doctrina era el monoteísmo puro y verdadero, y que Jesús es el siervo de Dios y Su mensajero]], como uno de los profetas —la paz sea con ellos—, al que Dios creó en el vientre de María sin varón, y que es un hombre sin divinidad alguna; y decía: «No sé qué es la Palabra ni el Espíritu Santo».",
     "Y este grupo ya ha desaparecido. [[k:Su núcleo hoy son tres grupos; el mayor es el de los melquitas]], [[k:que es la doctrina de todos los reyes cristianos]] dondequiera que estén, salvo Abisinia y Nubia, y la de la mayoría de la gente de todo reino cristiano, y la de todos los cristianos de África, Sicilia y al-Ándalus y la mayoría de Siria. Dicen que Dios es lo que expresan con tres causas: Padre, Hijo y Espíritu Santo, todas eternas; que Jesús es Dios completo y hombre completo; que el hombre que hay en él fue el crucificado y muerto, y al Dios que hay en él no le alcanzó nada de eso; y que María dio a luz a Dios y al hombre, y ambos juntos son una sola cosa, hijo de Dios —ensalzado sea Dios por encima de su incredulidad—. Los nestorianos dicen lo mismo, salvo que María no dio a luz al Dios, sino solo al hombre, y que Dios no engendró al hombre, sino solo al Dios. Este grupo predomina en Mosul, Irak, Persia y Jorasán, [[k:y se les atribuye a Nestorio, patriarca de Constantinopla]]."],
 prueba="Ibn Hazm (m. 456 H) conoce la historia de las sectas: sabe que hubo cristianos unitarios (Arrio, Pablo de Samosata) y que las tres iglesias de su tiempo son melquitas, nestorianos y jacobitas, y atribuye los nestorianos a Nestorio, patriarca de Constantinopla. Y dice que Constantino, «el primero de los reyes de los romanos que se hizo cristiano», era arriano.",
 ojo="Pablo de Samosata fue obispo de Antioquía hacia el 260–268, no «antes de la aparición del cristianismo». Constantino no era arriano en Nicea (apoyó el Credo); al final de su vida se acercó a los arrianos y lo bautizó Eusebio de Nicomedia; el que sí fue arriano fue su hijo Constancio II. Y si los nestorianos vienen de Nestorio (siglo V), no pudieron existir el día después de la ascensión (#IA1#).")

again(3, IHW, 'Z14', key="Z14",
 prueba="La versión de Ibn Hazm del Antiguo Testamento: tras Salomón, reyes idólatras, uno de los cuales quemó la Torá; luego Nabucodonosor; y la Torá actual es la que «les dictó de memoria Esdras el escriba», que la encontró «con muchos defectos y la corrigió». De ahí concluye que es «un libro cambiado, mentiroso, inventado».",
 ojo="Para reconstruir esa historia usa los libros históricos de los judíos, que él mismo acaba de llamar «corruptos y falsos» (en azul). Y al-Tabari transmite la misma historia de Esdras con la conclusión contraria: la Torá restituida era la misma (#H11b#, #H11c#).")

again(3, IHW, 'Z22', key="Z22",
 prueba="Ibn Hazm concede algo importante: Jesús «sin duda tenía la Torá revelada tal como Dios la reveló, y el Evangelio revelado»; la pérdida total llega «con la elevación del Mesías», porque sus seguidores vivían ocultos y perseguidos.",
 ojo="Si Jesús tenía la Torá auténtica siglos después de Esdras, se debilita la tesis de que la Torá de Esdras era la única que circulaba. Ibn Hazm responde que Jesús la tenía porque Dios se la enseñó (3:48), no porque circulara entre los judíos. En 1/156 el texto dice «يقرأ» donde el sentido es «consentir». Página 157: https://shamela.ws/book/6521/149")

add(3, IHW, key="IH2", specs=["rIH2"],
 title="Pablo, sobornado por los rabinos: «nosotros cargamos con tu pecado»… como Ibn Sabaʾ con ʿAli",
 ref=f"{FS}, vol. 1, p. 164", ar_ref="الفصل لابن حزم ١/١٦٤", site=SHF, url=S + "6521/156",
 es=["Y entre lo que hemos oído que cuentan sus sabios, sin negarlo, está que sus doctores —de quienes tomaron su religión, la Torá y los libros de los profetas— [[k:se pusieron de acuerdo en sobornar a Pablo el benjaminita —Dios lo maldiga— y le ordenaron que mostrara la religión de Jesús]] —la paz sea con él—, que extraviara a sus seguidores y los llevara a decir que era Dios; [[k:y le dijeron: «Nosotros cargamos con tu pecado en esto»; y lo hizo]], y llegó en ello a donde se ve.",
     "…y eso fue con el islam [fingido] de ʿAbd Allah ibn Sabaʾ, conocido como Ibn al-Sawʾ, el judío himyarí —Dios lo maldiga—, para extraviar a los musulmanes que pudiera; y trazó a un grupo vil que tenía partido por ʿAli —Dios esté complacido con él— que dijeran que ʿAli era Dios, [[k:como trazó Pablo a los seguidores del Mesías —la paz sea con él— que dijeran que él era Dios]]."],
 prueba="La versión de Ibn Hazm sobre Pablo: los rabinos judíos lo sobornaron para que fingiera seguir a Jesús y llevara a sus seguidores a divinizarlo («nosotros cargamos con tu pecado»). Y lo compara con ʿAbd Allah ibn Sabaʾ, el judío al que se atribuye el origen del chiismo extremo.",
 ojo="Su fuente es «lo que hemos oído que cuentan sus sabios» (los de los judíos): un rumor, sin texto ni cadena. Y no cuadra con la leyenda de al-Thaʿlabi (#Tl#), donde Pablo actúa por su cuenta, ni con la de ʿAbd al-Jabbar (#AJ3#), donde busca el favor de Roma.")

add(3, IHW, key="IH3", specs=["rIH3a", "rIH3b"],
 title="Los Evangelios son «cuatro historias» de cuatro hombres: Mateo, «nueve años después»; Marcos, veintidós; Juan, «sesenta y tantos»",
 ref=f"{FS}, vol. 2, pp. 2–3", ar_ref="الفصل لابن حزم ٢/٢–٣", site=SHF, url=S + "6521/159",
 es=["En cuanto a los cristianos, nos han ahorrado todo este esfuerzo, [[k:porque no pretenden que los Evangelios hayan sido revelados por Dios al Mesías]], ni que el Mesías se los trajera; sino que todos ellos, del primero al último —arrianos [?], melquitas, nestorianos, jacobitas, maronitas y paulicianos—, [[k:no discrepan en que son cuatro historias]] compuestas por cuatro hombres conocidos en épocas distintas. La primera es la historia que compuso Mateo el levita…",
     "…discípulo del Mesías, [[k:nueve años después de la elevación del Mesías]] —la paz sea con él—, y la escribió en hebreo en la tierra de Judá, en Siria; tiene unas veintiocho hojas de letra mediana. La otra es la historia que compuso Marcos el aaronita, discípulo de Simón Pedro, veintidós años después de la elevación del Mesías, y la escribió en griego en Antioquía; [[k:y dicen que fue el propio Simón quien la compuso, y luego borró su nombre del principio y la atribuyó a su discípulo Marcos]]; tiene veinticuatro hojas; y ese Simón era discípulo del Mesías. La tercera es la historia que compuso Lucas el médico de Antioquía, también discípulo de Simón Pedro; la escribió en griego en Acaya, después de la de Marcos. La cuarta es la historia que compuso Juan, hijo de Zebedeo, discípulo del Mesías, [[k:unos sesenta y tantos años después de la elevación del Mesías]], y la escribió en griego en Asia; y ese mismo Juan es el que tradujo el Evangelio de su compañero Mateo del hebreo al griego."],
 prueba="La parte más sólida del argumento de Ibn Hazm: los cristianos no dicen que los Evangelios sean un libro dictado por Dios, sino cuatro «historias» escritas por cuatro hombres. Y da fechas y lugares: Mateo, nueve años después de Jesús, en hebreo; Marcos, veintidós; Lucas, después; Juan, más de sesenta.",
 ojo="Es una descripción correcta de cómo ven los cristianos los Evangelios (testimonios inspirados, no un libro dictado), pero no prueba que estén corrompidos. Las fechas que da (Mateo, 9 años; Marcos, 22) vienen de tradiciones medievales, no de los Evangelios; la crítica moderna fecha Marcos hacia el 65–70 y Juan hacia el 90–100.")

add(3, IHW, key="IH4", specs=["rIH4a", "rIH4b"],
 title="Trescientos años escondidos: «en ese tiempo se perdió el Evangelio revelado, salvo unos pocos pasajes»… pero los cuatro Evangelios están «en una sola versión»",
 ref=f"{FS}, vol. 2, pp. 4–5", ar_ref="الفصل لابن حزم ٢/٤–٥", site=SHF, url=S + "6521/161",
 es=["[[k:Toda la transmisión de los cristianos, de principio a fin, dondequiera que estén, se remonta a los tres que hemos nombrado: Pablo, Marcos y Lucas]]; y estos tres no transmiten más que de cinco: Pedro, Mateo, Juan, Santiago y Judas; y todos ellos son los más mentirosos y malvados de las criaturas, como explicaremos. Además, Pablo cuenta en Hechos y en una de sus cartas [[k:que no estuvo con Pedro más que quince días]]; luego se encontró con él otra vez y estuvo con él poco; luego se encontró con él la tercera vez, y los tomaron a los dos y los crucificaron. [[a:Pero los cuatro Evangelios y los libros que hemos dicho que son su base están, en todas las sectas cristianas de oriente y occidente, en una sola versión y un solo orden: nadie puede añadirles una palabra ni quitarles otra sin quedar en evidencia]] ante todos los cristianos, transmitidos tal cual hasta Marcos, Lucas y Juan —pues Juan es quien transmitió el Evangelio de Mateo—, y las cartas de Pablo igualmente hasta Pablo.",
     "Y sabed que el asunto de los cristianos es mucho más débil que el de los judíos, porque los judíos tuvieron un reino y una gran comunidad con Moisés y después de él, y muchos profetas visibles que mandaban y eran obedecidos, como Moisés, Josué, Samuel, David y Salomón; [[k:la corrupción entró en la Torá después de Salomón]], cuando apareció entre ellos la incredulidad, el culto a los ídolos, el asesinato de los profetas, la quema de la Torá y el saqueo del Templo una y otra vez, hasta que se perdió su reino. Pero en cuanto a los cristianos, nadie discrepa en que [[k:no creyeron en el Mesías en vida más que ciento veinte hombres]] —así está en Hechos— y algunas mujeres, entre ellas la mujer del administrador de Herodes, que lo mantenían con sus bienes —así está en su Evangelio—; y que todos los que creyeron en él [[k:estaban escondidos y atemorizados en vida de él y después, llamando a su religión en secreto]]…",
     "…sin mostrar su religión; y a todo el que atrapaban lo mataban: lapidado, como a Santiago, hijo de José el carpintero, y a Esteban, al que llaman el primer mártir; crucificado, como a Pedro, a su hermano Andrés, a Simón hermano de José el carpintero, a Felipe y a Pablo; a espada, como a Santiago hermano de Juan, a Tomás, a Bartolomé, a Judas hijo de José el carpintero y a Mateo; o con veneno, como a Juan hijo de Zebedeo. Y siguieron así, sin mostrarse nunca ni tener un lugar seguro, [[k:durante trescientos años después de la elevación del Mesías]]; [[k:y en ese tiempo se perdió el Evangelio revelado por Dios, salvo unos pocos pasajes]] que Dios conservó como prueba contra ellos y para su vergüenza. Y así estuvieron [[k:hasta que se hizo cristiano el rey Constantino]]; desde entonces los cristianos se mostraron, descubrieron su religión y se reunieron. La causa de su conversión fue que su madre Helena era hija de un cristiano; su padre se enamoró de ella y se casó con ella, y ella lo crio en secreto en el cristianismo; cuando reinó, mostró el cristianismo muchos años después, y aun así no pudo hasta que se fue de Roma, a un mes de camino, a Constantinopla y la construyó; y aun con eso, [[k:él y su hijo después de él fueron arrianos]] [«adyusíes» en el texto], que decían que el Mesías es un siervo creado, profeta de Dios y nada más."],
 prueba="El argumento histórico central de Ibn Hazm sobre el Evangelio: los cristianos fueron una minoría perseguida y escondida durante trescientos años, «y en ese tiempo se perdió el Evangelio revelado, salvo unos pocos pasajes», hasta Constantino. Toda su transmisión pasa por tres hombres: Pablo, Marcos y Lucas.",
 ojo="Ibn Hazm admite en el mismo pasaje (en azul) que los cuatro Evangelios están «en una sola versión» en todas las iglesias de oriente y occidente, y que nadie puede añadir ni quitar una palabra sin quedar en evidencia: sitúa la corrupción en el origen, no en la transmisión. Que una comunidad sea perseguida no hace que pierda su libro (el Corán se transmitió en La Meca en una comunidad perseguida). Y la persecución no fue continua durante tres siglos: hubo largos periodos de paz entre unas y otras.")

add(3, IHW, key="IH5", specs=["rIH5a", "rIH5b"],
 title="Constantino, trescientos años después: lo hizo cristiano su madre, impuso la religión «con la espada y con dinero»… y era arriano",
 ref=f"{FS}, vol. 2, pp. 71–72", ar_ref="الفصل لابن حزم ٢/٧١–٧٢", site=SHF, url=S + "6521/228",
 es=["…no lo que pretenden los cristianos con pura mentira: que los reyes entraron en su religión voluntariamente. Han mentido en eso, [[k:porque el primer rey que se hizo cristiano fue Constantino, el que construyó Constantinopla, unos trescientos años después de la elevación del Mesías]] —la paz sea con él—; ¿qué milagro le pudo constar después de tanto tiempo? [[k:Lo hizo cristiano su madre]], porque era cristiana, hija de un cristiano, y su padre se enamoró de ella y se casó con ella; esto no lo niega ningún cristiano.",
     "…de los reyes, Constantino, unos trescientos años después de la elevación del Mesías; [[k:y por Dios que no pudo mostrar el cristianismo hasta que se fue de Roma, a un mes de camino]], y construyó Bizancio, que es Constantinopla; [[k:luego obligó a la gente a hacerse cristiana con la espada y con dinero]], y una de sus disposiciones conocidas era no dar ningún cargo sino a quien se hiciera cristiano —y la gente corre hacia el mundo—; [[k:y con todo esto, seguía la doctrina de Arrio, no la Trinidad]]."],
 prueba="Ibn Hazm contra el argumento cristiano de que los reyes se convirtieron por la evidencia de los milagros: el primer rey cristiano llegó trescientos años después, lo hizo cristiano su madre, impuso la religión «con la espada y con dinero» y, encima, era arriano, no trinitario.",
 ojo="Que Constantino favoreció a los cristianos es cierto, pero no está documentado que obligara a nadie a convertirse con la espada: el paganismo siguió siendo legal en su reinado, y lo prohibió Teodosio (380–392). Y si Constantino era arriano, como dice Ibn Hazm, no pudo ser él quien impusiera la Trinidad, como dicen otros autores de este pack (#AJ6#, #IQ3#).")

again(3, IHW, 'Z27', key="Z27",
 prueba="Ibn Hazm recuerda que Jesús y sus discípulos vivieron según la Torá —circuncisión, sábado, Pascua y ayuno judío— y que los cristianos lo cambiaron todo: el domingo en lugar del sábado y un ayuno nuevo «más de cien años después de la elevación del Mesías».",
 ojo="Lo usa como argumento contra los cristianos a partir de los Evangelios, que considera poco fiables. Y aquí sitúa los cambios en el siglo II, no con Pablo ni con Constantino. Página 2/20: https://shamela.ws/book/6521/177")

add(3, "al-Juwayni (m. 478 H / 1085), atribuido", key="Jw", specs=["rJw1"],
 title="«La Torá que tienen los judíos es la que escribió Esdras… 545 años antes del Mesías»; y cada evangelista «declaró» cuántos años después escribió",
 ref="al-Juwayni (atrib.), Shifaʾ al-ghalil fi bayan ma waqaʿa fi l-Tawrat wa-l-Injil min al-tabdil, apartados «La Torá de Esdras el escriba» y «Los autores de los Evangelios»",
 ar_ref="شفاء الغليل فيما وقع في التوراة والإنجيل من التبديل", site="ar.wikisource.org (sin paginación impresa)", url="https://ar.wikisource.org/wiki/شفاء_الغليل_في_بيان_ما_وقع_في_التوراة_والإنجيل_من_التبديل",
 es=["Decimos: [[k:la Torá que tienen ahora los judíos es la Torá que escribió Esdras el escriba, después de su desgracia con Nabucodonosor]], de su matanza de sus multitudes —salvo unos pocos que dejó con vida y que no contaban—, de que hizo de sus bienes botín para sus tropas, [[k:y de que destruyó los libros que tenían]], porque no se sometía a las normas de su ley; puso en su templo un ídolo y pregonó prohibiendo mencionarla, hasta que pasó una generación así, de modo que quien encontraba alguna hoja suya iba a las cuevas a leerla a escondidas.<br>[[k:Y esta copia la escribió Esdras quinientos cuarenta y cinco años antes de la misión del Mesías]], cuando no había en la tierra ni un cristiano. Por tanto, el cambio era posible, porque no se conocía el número de copias de la Torá repartidas por el mundo, porque no dependía de que se sometieran todos los miembros de las dos comunidades, y porque sus copias no estaban en manos de judíos y cristianos, [[k:pues no llegaron a manos de los cristianos sino después de cambiada]]. [[k:Así que quien lo hizo fue uno solo: o Esdras]], o, si lo consideran por encima de eso, el que la copió de su copia. Que el cambio viniera de él es posible, por su afán de mantener su poder y porque no se le atribuye una infalibilidad que le impidiera cometer faltas.",
     "[[k:En cuanto a Mateo, declaró en su Evangelio que lo compuso nueve años después de que el Mesías fuera elevado]]. [[k:Juan también afirmó en su Evangelio que lo reunió treinta y tantos años después de la elevación del Mesías]]. Igualmente Marcos declaró en su Evangelio que lo reunió doce años después de la elevación del Mesías. E igualmente Lucas declaró en su Evangelio que lo compuso veintidós años después de que el Mesías fuera elevado; y se dice que veinte."],
 prueba="Shifaʾ al-ghalil, atribuido al gran teólogo asharí al-Juwayni (m. 478 H): la Torá actual es la de Esdras, escrita 545 años antes de Cristo tras la destrucción de los libros por Nabucodonosor; por tanto el cambio lo pudo hacer un solo hombre. Y de los Evangelios dice que cada evangelista «declaró en su Evangelio» que lo escribió años después de Jesús.",
 ojo="Ningún Evangelio dice en qué año se escribió: esas «declaraciones» no existen en los textos. Además, las cifras no coinciden con las de Ibn Hazm (#IH3#): para este, Marcos fue 22 años después y Juan más de 60. La atribución de la obra a al-Juwayni se discute, y la página (Wikisource) no tiene numeración impresa.")

add(3, "al-Shahrastani (m. 548 H / 1153)", key="Sh1", specs=["rSh1"],
 title="«Pablo le enredó el asunto [a Pedro]… y lo mezcló con palabras de los filósofos»; y cuatro discípulos reunieron cada uno «una colección que llamó Evangelio»",
 ref="al-Shahrastani, al-Milal wa-l-nihal, vol. 2, p. 26 (Muʾassasat al-Halabi)", ar_ref="الملل والنحل للشهرستاني ٢/٢٦", site=SH, url=S + "11812/263",
 es=["Y él, después de ser muerto y crucificado, bajó, y Simón Pedro vio su persona; le habló y le dejó su encargo; luego dejó el mundo y subió al cielo. [[k:Así su albacea fue Simón Pedro, el mejor de los discípulos en ciencia, ascetismo y educación]]. [[k:Pero Pablo (Fulus) le enredó el asunto, se hizo su socio, cambió el sentido de sus palabras y las mezcló con palabras de los filósofos y con las ocurrencias de su mente]].<br>[[k:Y he visto la carta de Pablo]] que escribió a los griegos: «Pensáis que el lugar de Jesús —la paz sea con él— es como el de los demás profetas, y no es así; su ejemplo es el de Melquisedec», que es el rey de paz al que Abraham daba los diezmos, y que bendecía a Abraham y le ungía la cabeza. Y lo sorprendente es que se transmite en los Evangelios que el Señor dijo: «Tú eres el hijo único»; ¿y cómo se compara al único con uno de los humanos?<br>[[k:Luego cuatro de los discípulos se reunieron y cada uno reunió una colección que llamó Evangelio]]: Mateo, Lucas, Marcos y Juan. Y el final del Evangelio de Mateo es que dijo: «Os envío a las naciones como mi Padre me envió a vosotros; id y llamad a las naciones en el nombre del Padre, del Hijo y del Espíritu Santo»."],
 prueba="Al-Shahrastani (m. 548 H), el gran historiador de las religiones, expone lo que creen los cristianos (Jesús murió, se apareció a Pedro y lo dejó como sucesor) y da su juicio: Pablo «enredó el asunto» y mezcló las palabras de Jesús con filosofía. Dice haber leído él mismo la carta sobre Melquisedec (Hebreos).",
 ojo="Es una exposición bastante fiel de la doctrina cristiana, sin historias de sobornos ni conspiraciones; la acusación contra Pablo es teológica, no un relato histórico. Dos errores: Lucas y Marcos no eran «de los discípulos», y la carta sobre Melquisedec (Hebreos) va dirigida a judíos cristianos, no «a los griegos»; su autoría paulina se discute desde la Antigüedad.")

add(3, "al-Shahrastani (m. 548 H / 1153)", key="Sh2", specs=["rSh2a", "rSh2b", "rSh2c", "rSh2d"],
 title="Setenta y dos sectas; los melquitas, «seguidores de Malka»; los 318 «en Constantinopla»; y Nestorio, «en tiempos de al-Maʾmun»",
 ref="al-Shahrastani, al-Milal wa-l-nihal, vol. 2, pp. 27–29 (Muʾassasat al-Halabi)", ar_ref="الملل والنحل للشهرستاني ٢/٢٧–٢٩", site=SH, url=S + "11812/264",
 es=["[[k:Luego los cristianos se dividieron en setenta y dos sectas]]; [[k:las mayores son tres: los melquitas, los nestorianos y los jacobitas]]; y de ellas se ramificaron los Iliyaniyya, Bilyarsiyya, Maqdanusiyya, Sabaliyya, Butanusiyya, Buliyya y las demás sectas.",
     "[[k:Los melquitas: seguidores de Malka, que apareció en tierra de los romanos y se apoderó de ella]]. La mayoría de los romanos son melquitas.",
     "Y cuando Arrio dijo: «El eterno es Dios, y el Mesías es creado», [[k:se reunieron los patriarcas, metropolitas y obispos en la ciudad de Constantinopla, en presencia de su rey]]; [[k:eran trescientos dieciocho hombres]], y acordaron esta palabra como creencia y predicación…",
     "[[k:Los nestorianos: seguidores de Nestorio el sabio, que apareció en tiempos de al-Maʾmun y dispuso de los Evangelios según su opinión]]; y su relación con ellos es como la de los muʿtazilíes con esta ley [el islam]."],
 prueba="Al-Shahrastani da la versión «de manual» de las sectas: setenta y dos, con tres principales; los melquitas, por un tal «Malka» que dominó la tierra de los romanos; el Credo de los 318; y Nestorio, que «dispuso de los Evangelios según su opinión».",
 ojo="Tres errores de bulto en tres páginas. «Melquita» viene del siríaco malka, «rey»: los partidarios del emperador, no de un hombre llamado Malka. Los 318 se reunieron en Nicea (325), no en Constantinopla. Y Nestorio vivió en el siglo V, no en tiempos del califa al-Maʾmun (siglo IX), cuatrocientos años después. Con esos datos cuesta fiarse de su relato de cómo se «cambió» el Evangelio.")

add(3, "al-Samawʾal al-Maghribi (m. c. 570 H / 1175)", key="Sam", specs=["rSam0", "rSam1", "rSam2", "rSam3", "rSam4"],
 title="Un judío converso: Moisés solo dio la Torá a los sacerdotes; Nabucodonosor los mató; Esdras la «compuso»: «es el libro de Esdras, y no el libro de Dios»",
 ref="al-Samawʾal al-Maghribi, Ifham al-Yahud, pp. 135–140 (ed. al-Sharqawi, Dar al-Jil, 1990)", ar_ref="إفحام اليهود للسموأل المغربي ص ١٣٥–١٤٠", site=SH, url=S + "6529/79",
 es=["Y no creemos que estas blasfemias estuvieran en la Torá revelada a Moisés —la bendición de Dios sea con él—, ni decimos que los judíos se propusieran cambiarla y estropearla; la verdad es lo más digno de seguirse, [[k:y ahora vamos a explicar la verdadera causa del cambio de la Torá]]. [Capítulo:] La causa del cambio de la Torá. Sus sabios y sus doctores saben que de esta Torá que tienen [[k:ninguno de sus sabios ni de sus doctores cree que sea la revelada a Moisés]] en absoluto…",
     "…[Moisés] guardó la Torá lejos de los hijos de Israel y no la difundió entre ellos, [[k:sino que la entregó a su clan, los hijos de Leví]]; y la prueba es lo que dice la Torá: «Va-yijtov Moshé et ha-Torá ha-zot va-yitnah el ha-kohanim bnei Leví», cuya traducción es: «Moisés escribió esta Torá y la dio a los sacerdotes, hijos de Leví» [Deuteronomio 31:9]. Los hijos de Aarón eran los jueces y gobernantes de los judíos, porque el sacerdocio, el servicio de los sacrificios y el Templo les estaban reservados. [[k:Y Moisés no dio de la Torá a los hijos de Israel más que media sura llamada Haazinu]]…",
     "…[[k:Y a estos sacerdotes aaronitas, que conocían la Torá y sabían de memoria la mayor parte, los mató Nabucodonosor a todos de una vez el día que conquistó Jerusalén]].",
     "Y aprender la Torá de memoria no era obligatorio ni recomendado, [[k:sino que cada uno de los aaronitas se sabía un pasaje de la Torá]]. Cuando Esdras vio que a la gente le habían quemado el Templo, se había perdido su reino, se había dispersado su comunidad y se les había quitado su libro, [[k:reunió de lo que él sabía de memoria y de los pasajes que sabían los sacerdotes con lo que compuso esta Torá que tienen ahora]].",
     "Por eso exageraron en venerar a este Esdras al máximo, y pretenden que hasta hoy aparece la luz sobre su tumba, junto a los pantanos de Irak, [[k:porque les hizo un libro que conserva su religión]]. [[k:Así que esta Torá que tienen es, en realidad, el libro de Esdras, y no el libro de Dios]]."],
 prueba="Al-Samawʾal (m. c. 570 H), un judío del Magreb convertido al islam, da la explicación más elaborada: Moisés solo confió la Torá a los sacerdotes de Leví; Nabucodonosor los mató a todos de una vez; y Esdras «compuso» la Torá actual con lo que él recordaba y los pasajes sueltos que sabían otros sacerdotes. Conclusión: «es el libro de Esdras, y no el libro de Dios».",
 ojo="Es la tesis que copiará Ibn al-Qayyim (#IQ1#). Pero el mismo capítulo que cita, Deuteronomio 31, manda leer la Torá «ante todo Israel» cada siete años (31:10–13): no era un secreto de los sacerdotes. Y es falso que ningún sabio judío crea que es la Torá revelada a Moisés: es justo lo que afirma el judaísmo rabínico (Maimónides, octavo principio de la fe).")
