# -*- coding: utf-8 -*-
# Mini-pack W: la conversión de Pablo en Damasco (al-Yaʿqubi; Wahb ibn Munabbih en Ibn ʿAsakir e Ibn Manzur; Ibn Kathir).
SH = "shamela.ws (Maktaba Shamila; paginación igual a la edición impresa)"
S = "https://shamela.ws/book/"
USO = "Mini-pack «Pablo en Damasco» · verificación de las fuentes"
WCARDS = [
 dict(id="W01", key="Yq", tag="Siglo III H · al-Yaʿqubi (m. c. 292 H / 905)", specs=["W-yq"],
  title="al-Yaʿqubi: «oyó una voz que lo llamaba: Pablo, ¿cuánto me vas a perseguir?»… y Ḥananiyā le cura los ojos. No hay ángel",
  ref="al-Yaʿqubi, Tarij, ed. Dar Sadir (2 vols.), vol. 1, pp. 79–80, según la digitalización de OpenITI «conforme al impreso» (Zaydiyya0000057)",
  ar_ref="تاريخ اليعقوبي، دار صادر ١/٧٩–٨٠", site="GitHub, corpus abierto OpenITI (texto plano)",
  url="https://raw.githubusercontent.com/OpenITI/0300AH/master/data/0292Yacqubi/0292Yacqubi.Tarikh/0292Yacqubi.Tarikh.Zaydiyya0000057-ara1",
  es=["Libro: Historia de al-Yaʿqubi ¶ Autor: Ahmad ibn Abi Yaʿqub ibn Yaʿfar ibn Wahb ibn Wadih al-Katib al-ʿAbbasi, conocido como al-Yaʿqubi ¶ Editor: ¶ [[k:Editorial: (Dar Sadir)]] ¶ Edición: ¶ Número de volúmenes: 2 ¶ Fuente del libro: sitio Yaʿsub ¶ [[k:[La numeración del libro es conforme a la impresa]]]",
      "Y Pablo era el más duro de todos contra ellos y el que más los dañaba; mataba a los que [[a:[fin de la p. 79; empieza la p. 80]]] podía de ellos y los buscaba por todas partes. Salió con intención de ir a Damasco para reunir a unos que había allí, [[k:y oyó una voz que lo llamaba: «Pablo, ¿cuánto me vas a perseguir?»]]. [[k:Se asustó hasta no ver; luego vino a él]] [[k:Ḥananiyā [Ananías], lo bendijo hasta que se fue, y su ojo sanó]]. Y empezó a levantarse en las iglesias recordando al Mesías y santificándolo. Los judíos quisieron matarlo y huyó de ellos, y se unió a los discípulos llamando a la gente, hablando como ellos hablaban y mostrando desapego del mundo, [[k:hasta que todos los discípulos lo pusieron por delante de sí mismos y lo hicieron su cabeza]]."],
  prueba="Confirmado. El texto es idéntico en las tres digitalizaciones del Tarij que hay en OpenITI (JK001493, Shia003468 y Zaydiyya0000057). Es el resumen de Hechos 9: una voz que llama a Pablo, la ceguera y Ḥananiyā (Ananías), que lo cura. No hay ningún ángel, y Pablo no conoce en persona a Jesús.",
  ojo="La voz no se identifica: dice «¿cuánto me vas a perseguir?», lo que implica que habla el perseguido, pero no lo nombra. Las páginas 79–80 salen de los marcadores digitales de una copia «conforme al impreso», no de un ejemplar físico. La «p. 31» del foro es la paginación automática de ketabonline, que ese sitio declara que no coincide con el libro impreso (es la captura R18 del pack histórico).", uso=USO),

 dict(id="W02", key="IA", tag="Siglo VI H · Ibn ʿAsakir (m. 571 H / 1176), citando a Wahb ibn Munabbih (m. 110/114 H)", specs=["W-ia1", "W-ia2"],
  title="Ibn ʿAsakir, entrada «Ḥanīnā, uno de los amigos del Mesías»: Wahb cuenta que un ángel ciega a Pablo en Kawkaba y Jesús lo manda a Ḥanīnā",
  ref="Ibn ʿAsakir, Tarij madinat Dimashq (Dar al-Fikr, 1415/1995, 80 vols.), vol. 15, pp. 333–334, entrada n.º 1825",
  ar_ref="تاريخ دمشق لابن عساكر ١٥/٣٣٣–٣٣٤، رقم ١٨٢٥", site=SH, url=S + "71/6817 · 71/6818",
  es=["1825 — Ḥanīnā, uno de los amigos del Mesías. [[a:Se dice en algunas noticias que estuvo en Damasco]]. [[k:Leí, de puño y letra de Abu Muhammad ibn Sabir]], según lo que dijo que copió de puño y letra de Abu l-Husayn Muhammad ibn ʿAbd Allah al-Hafiz: nos informó Abu ʿAbd Allah Muhammad ibn Salih ibn Muhammad al-Jawlani al-Misri: nos contó ʿUmara ibn Wathima ibn Musa ibn al-Furat: nos contó mi padre, Wathima, de ʿAmr ibn al-Azhari, [[k:de Abu Ilyas Idris, hijo de la hija de Wahb ibn Munabbih, de Wahb ibn Munabbih, que dijo]]: Pablo era de los jefes de los judíos, el más fiero y el de mayor peso en rechazar lo que trajo el Mesías —la paz sea con él— y en apartar de él a la gente. Reunió tropas y marchó hacia el Mesías para matarlo e impedirle entrar en Damasco. [[k:Lo encontró en Kawkaba, y un ángel lo golpeó con su ala y lo dejó ciego]]; y vio tales señales de su asunto, y tales circunstancias que le impidieron hacerle el mal que quería, que se vio obligado a creer en él y a dar por verdadero lo que trajo. Fue al Mesías en ese estado y le pidió que le abriera los ojos, [[k:y el Mesías le dijo: «¿Cuánto te esfuerzas en dañarme a mí y a los que están conmigo]], y haces y deshaces?». Luego le dijo el Mesías: «Ve hasta entrar en Damasco; toma el mercado largo que se extiende por el centro de la ciudad —es decir, Damasco— hasta llegar a su final, [[k:y llega a Ḥanīnā]]» —y Ḥanīnā se había escondido de él, por miedo, en una cueva hacia la Puerta Oriental— «para que te abra los ojos». [[k:Fue a él junto a la Iglesia Muṣallaba, que es la iglesia que hoy se le atribuye]]. [[k:Y Pablo había cogido a su sobrino, que había creído en el Mesías; le rapó el centro de la cabeza, lo pregonó y lo apedreó [la edición imprime «ورحمه», «tuvo piedad de él»] hasta que murió]]. Y desde…",
      "…[[k:entonces los cristianos adoptaron raparse el centro de la cabeza, para imitar el castigo que él sufrió]], y es como señal de humildad, no de deshonra, para quien cree en el Mesías —la paz sea con él—."],
  prueba="Confirmado. El núcleo del relato que cuenta Ibn Kathir (W04) ya está en Ibn ʿAsakir y se atribuye expresamente a Wahb ibn Munabbih, con cadena. Coinciden: Pablo, jefe de los judíos; Kawkaba; el ángel que lo ciega con el ala; el mercado largo; Ḥanīnā escondido en una cueva junto a la Puerta Oriental; la Iglesia Muṣallaba; y el sobrino rapado y matado.",
  ojo="El análisis que te pasaron se equivoca en un punto: el sobrino sí está en Ibn ʿAsakir (rapado, pregonado y apedreado). Lo que no está es «ظالما غاشما» («injusto, opresor») ni «lo paseó por la ciudad». Las páginas son las 333–334, no 332–333. La cadena es de transmisión escrita: Ibn ʿAsakir no la oyó, «la leyó de puño y letra» de otro, que a su vez «dijo» haberla copiado; no hemos comprobado la fiabilidad de esos transmisores. Además, en el relato Jesús sigue vivo y camina hacia Damasco cuando Pablo se convierte, algo que no cuadra ni con Hechos ni con la idea islámica de que Jesús ya había sido elevado.", uso=USO),

 dict(id="W03", key="IM", tag="Siglo VIII H · Ibn Manzur (m. 711 H / 1311), resumiendo a Ibn ʿAsakir", specs=["W-im1", "W-im2"],
  title="El resumen de Ibn Manzur: «Dijo Wahb ibn Munabbih…»: el mismo relato, sin la cadena",
  ref="Ibn Manzur, Mujtasar Tarij Dimashq li-Ibn ʿAsakir, ed. Ruhiyya al-Nahhas, Riyad Murad y Muhammad Mutiʿ (Dar al-Fikr, 1402/1984), vol. 7, pp. 283–284",
  ar_ref="مختصر تاريخ دمشق لابن منظور ٧/٢٨٣–٢٨٤", site=SH, url=S + "3118/2478 · 3118/2479",
  es=["[Ḥanīnā, uno de los amigos del Mesías]. [[a:Se dijo que estuvo en Damasco]]. [[k:Dijo Wahb ibn Munabbih]]: Pablo era de los jefes de los judíos, el más fiero y el de mayor peso en rechazar lo que trajo el Mesías —la paz sea con él— y en apartar de él a la gente. Reunió tropas y marchó hacia el Mesías para matarlo e impedirle entrar en Damasco; lo encontró en Kawkaba [[k:y un ángel lo golpeó con su ala y lo dejó ciego]]; y vio tales señales […] que se vio obligado a creer en él […]. Fue al Mesías en ese estado y le pidió que le abriera los ojos, y el Mesías le dijo: [[k:«¿Cuánto te esfuerzas en dañarme a mí y a los que están conmigo]], y haces y deshaces?». Luego le dijo el Mesías: «Ve hasta entrar en Damasco y toma el mercado largo que se extiende por el centro…",
      "…de la ciudad —es decir, Damasco— hasta llegar a su final, [[k:y llega a Ḥanīnā]]» —y Ḥanīnā se había escondido de él, por miedo, en una cueva hacia la Puerta Oriental— «para que te abra los ojos». [[k:Fue a él junto a la Iglesia Muṣallaba, que es la iglesia que hoy se le atribuye]]. Y Pablo había cogido a su sobrino, que había creído en el Mesías, [[k:le rapó el centro de la cabeza, lo pregonó y lo apedreó [impreso: «tuvo piedad de él»] hasta que murió]]; [[k:y desde entonces los cristianos adoptaron raparse el centro de la cabeza]], para imitar el castigo que él sufrió, como señal de humildad, no de deshonra, para quien cree en el Mesías —la paz sea con él—."],
  prueba="Confirmado. El resumen de Ibn Manzur reproduce el texto de Ibn ʿAsakir casi palabra por palabra, pero quita la cadena y deja solo «dijo Wahb ibn Munabbih». Vol. 7, pp. 283–284, como decía el análisis.",
  ojo="No es una fuente independiente: es un resumen de Ibn ʿAsakir (W02). Tampoco trae la frase de la «buena fe» de Pablo ni la «iglesia de Pablo».", uso=USO),

 dict(id="W04", key="IK", tag="Siglo VIII H · Ibn Kathir (m. 774 H / 1373)", specs=["W-ik"],
  title="Ibn Kathir cuenta lo mismo sin nombrar a Wahb, y añade: «la fe de Pablo en el Mesías se volvió buena… y se le construyó una iglesia: la famosa iglesia de Pablo en Damasco»",
  ref="Ibn Kathir, al-Bidaya wa-l-nihaya (ed. ʿAli Shiri, Dar Ihyaʾ al-Turath), vol. 2, p. 119; = paginación de Saʿada (Dar al-Fikr), vol. 2, pp. 100–101; = ed. crítica Dar Hayar (al-Turki), vol. 2, pp. 529–530",
  ar_ref="البداية والنهاية ٢/١١٩ (ت. شيري)", site=SH, url=S + "8376/509",
  es=["Y entre los de Damasco que creyeron en el Mesías y le dieron crédito [[k:había un hombre llamado Ḍīnā]], que se escondía en una cueva dentro de la Puerta Oriental, cerca de la Iglesia Muṣallaba, por miedo a Pablo el judío, [[k:que era injusto, opresor y odiaba al Mesías]] y lo que trajo. Había rapado la cabeza a su sobrino cuando creyó en el Mesías, [[k:lo paseó por la ciudad y luego lo apedreó hasta que murió]] —Dios tenga misericordia de él—. Y cuando Pablo oyó que el Mesías —la paz sea con él— [[a:se había dirigido hacia Damasco]], preparó sus mulas y salió a matarlo; lo encontró en Kawkaba, y cuando se enfrentó a los compañeros del Mesías, [[k:vino a él un ángel, le golpeó la cara con la punta de su ala y lo dejó ciego]]. Al ver eso, le entró en el alma creer en el Mesías; fue a él, se disculpó por lo que había hecho y creyó en él, y él lo aceptó; le pidió que le pasara la mano por los ojos para que Dios le devolviera la vista, y le dijo: «Ve a Ḍīnā, que está cerca de ti en Damasco, al extremo oriental del mercado largo, y él rezará por ti». Fue a él, rezó, y le devolvió la vista; [[k:y la fe de Pablo en el Mesías —la paz sea con él— se volvió buena]]: [[k:que es siervo de Dios y Su mensajero; y se le construyó una iglesia con su nombre, que es la famosa iglesia de Pablo en Damasco]], desde el tiempo en que la conquistaron los Compañeros —Dios esté complacido con ellos— hasta que fue destruida."],
  prueba="Ibn Kathir sigue el relato de Wahb (W02), pero no lo atribuye a nadie. Cambia «Ḥanīnā» por «Ḍīnā» y añade cosas: «injusto, opresor», «lo paseó por la ciudad» y, sobre todo, el final: la fe de Pablo «se volvió buena» —que Jesús es siervo de Dios y Su mensajero— y la «famosa iglesia de Pablo en Damasco».",
  ojo="El final sobre la fe de Pablo y su iglesia no está en Ibn ʿAsakir ni en Ibn Manzur. Sí está en todas las ediciones de al-Bidaya que hemos mirado: Shiri, la paginación de Saʿada (Dar al-Fikr), Maktabat al-Maʿarif y la edición crítica de Dar Hayar, esta sin variantes anotadas. No sabemos de dónde lo saca: puede ser de otra fuente o suyo, y él era de Damasco. En la p. 100 de la paginación de Saʿada hay, en efecto, una nota [1], pero va en «los compañeros de sus compañeros» (Marcos y Lucas), no en Pablo, y su texto no está en la digitalización: sigue sin verificar. Los nombres Ḥanīnā y Ḍīnā parecen deformaciones de Ḥananiyā (Ananías), el nombre que da correctamente al-Yaʿqubi (W01).", uso=USO),
]
